delete from course_level
/
commit
/
DROP SEQUENCE course_id_seq
/

--
-- course_id_seq  (Sequence) 
--
CREATE SEQUENCE course_id_seq
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/


CREATE OR REPLACE TRIGGER trig_course_level_seq BEFORE INSERT ON COURSE_LEVEL
FOR EACH ROW
BEGIN
SELECT course_id_seq.NEXTVAL into :new.course_id FROM dual;
END;


INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('ADVANCED DIPLOMA (ADVDIP)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('CERTIFICATE IN HIGHER EDUCATION (CERTHE)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('DEGREE');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('DIPLOMA IN HIGHER EDUCATION (DIPHE)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('GRADUATE CERTIFICATE (GRADCERT)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('GRADUATE DIPLOMA (GRADDIP)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('HIGHER NATIONAL CERTIFICATE (HNC)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('HIGHER NATIONAL DIPLOMA (HND)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('PROFESSIONAL GRADUATE DIPLOMA IN EDUCATION (PGDE)');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('SCQF Level 7');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('SCQF Level 8');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('SCQF Level 9');

INSERT INTO COURSE_LEVEL (COURSE_LEVEL_DESC) 
VALUES 
('SCQF Level 10');

COMMIT;