-- Reference data
-- Table: LEARNER 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
--          22.07.08    A.Bowman (SAAS)         Initial Version.
--
-- Configuration Management:
-- $HeadURL: 
-- $Author: 
-- $Date: 
-- $Revision: 

INSERT INTO LEARNER ( LEARNER_ID, TITLE_ID, OTHER_TITLE, FORENAME, SURNAME, HOUSENAME_NO,
ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, POSTCODE, DOB, GENDER, TELEPHONE_NO,
EMAIL_ADDRESS, LIVES_SCOTLAND_FLAG, LIVES_AWAY_FLAG, DECEASED_FLAG, MAIL_RETURNED_DATE,
HOLD_PAYMENTS, HOLD_LETTERS, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'555555', 1, NULL, 'JAMES', 'SMITH', '1', 'MAIN ROAD', 'EDINBURGH', NULL, NULL, 'EH1 1AA',  TO_Date( '01/01/1980 12:00:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, '0131 111 1111', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UIGUYS',  SYSDATE); 
COMMIT;

INSERT INTO LEARNER ( LEARNER_ID, TITLE_ID, OTHER_TITLE, FORENAME, SURNAME, HOUSENAME_NO,
ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, POSTCODE, DOB, GENDER, TELEPHONE_NO,
EMAIL_ADDRESS, LIVES_SCOTLAND_FLAG, LIVES_AWAY_FLAG, DECEASED_FLAG, MAIL_RETURNED_DATE,
HOLD_PAYMENTS, HOLD_LETTERS, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'666666', 1, NULL, 'JOHN', 'BROWN', '1', 'HIGH ROAD', 'EDINBURGH', NULL, NULL, 'EH1 1AB',  TO_Date( '01/01/1981 12:00:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, '0131 222 2222', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UIGUYS',  SYSDATE); 
COMMIT;

INSERT INTO LEARNER ( LEARNER_ID, TITLE_ID, OTHER_TITLE, FORENAME, SURNAME, HOUSENAME_NO,
ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, POSTCODE, DOB, GENDER, TELEPHONE_NO,
EMAIL_ADDRESS, LIVES_SCOTLAND_FLAG, LIVES_AWAY_FLAG, DECEASED_FLAG, MAIL_RETURNED_DATE,
HOLD_PAYMENTS, HOLD_LETTERS, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'777777', 1, NULL, 'JACK', 'JONES', '1', 'PRINCES STREET', 'EDINBURGH', NULL, NULL, 'EH1 1AC',  TO_Date( '01/01/1982 12:00:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, '0131 333 3333', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UIGUYS',  SYSDATE); 
COMMIT;

INSERT INTO LEARNER ( LEARNER_ID, TITLE_ID, OTHER_TITLE, FORENAME, SURNAME, HOUSENAME_NO,
ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, POSTCODE, DOB, GENDER, TELEPHONE_NO,
EMAIL_ADDRESS, LIVES_SCOTLAND_FLAG, LIVES_AWAY_FLAG, DECEASED_FLAG, MAIL_RETURNED_DATE,
HOLD_PAYMENTS, HOLD_LETTERS, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'888888', 1, NULL, 'JOE', 'MURPHY', '1', 'HILL END', 'EDINBURGH', NULL, NULL, 'EH1 1AD',  TO_Date( '01/01/1983 12:00:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, '0131 444 4444', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UIGUYS',  SYSDATE); 
COMMIT;

INSERT INTO LEARNER ( LEARNER_ID, TITLE_ID, OTHER_TITLE, FORENAME, SURNAME, HOUSENAME_NO,
ADDRESS_LINE1, ADDRESS_LINE2, ADDRESS_LINE3, ADDRESS_LINE4, POSTCODE, DOB, GENDER, TELEPHONE_NO,
EMAIL_ADDRESS, LIVES_SCOTLAND_FLAG, LIVES_AWAY_FLAG, DECEASED_FLAG, MAIL_RETURNED_DATE,
HOLD_PAYMENTS, HOLD_LETTERS, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'999999', 1, NULL, 'JASON', 'EVANS', '1', 'BROOMHOUSE ROAD', 'EDINBURGH', NULL, NULL, 'EH1 1AE',  TO_Date( '01/01/1984 12:00:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, '0131 555 5555', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'UIGUYS',  SYSDATE); 
COMMIT;


 
