CREATE OR REPLACE VIEW SGAS.DE_PM_BATCHES
(DPB_BATCH_REF, DPB_COUNT, DPB_AC_YEAR, DPB_AC_PERIOD, DPB_TOTAL_PAYMENT, 
 DPB_TOTAL_VOLUME, DPB_TOTAL_VAT, DPB_BATCH_CREATION_DATE, DPB_ALLOW_SUSPENSE, DPB_VALIDATE_ONLY)
AS 
select DPB_BATCH_REF,
			 DPB_COUNT,
			 DPB_AC_YEAR,
			 DPB_AC_PERIOD,
			 DPB_TOTAL_PAYMENT,
			 DPB_TOTAL_VOLUME,
			 DPB_TOTAL_VAT,
			 DPB_BATCH_CREATION_DATE,
			 DPB_ALLOW_SUSPENSE,
			 DPB_VALIDATE_ONLY
	from scoap_batches
	where DPB_STATUS = 'A'
/


CREATE PUBLIC SYNONYM DE_PM_BATCHES FOR SGAS.DE_PM_BATCHES
/


GRANT SELECT ON  SGAS.DE_PM_BATCHES TO SCOAP_QUERY
/