-- ILA500.ILA_SDS_2009.sql
-- Description: Materialized view of VU_SDS2009
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      13.08.10    A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $
-- $Author: $
-- $Date: $
-- $Revision: $

DROP MATERIALIZED VIEW ILA500.ILA_SDS_2009;

CREATE MATERIALIZED VIEW ILA500.ILA_SDS_2009
TABLESPACE USERS
STORAGE (INITIAL 50K NEXT 50K PCTINCREASE 50)
REFRESH COMPLETE
WITH ROWID
AS SELECT
ILA_REF_NO, TITLE, TITLE_CHANGE_DATE, LAST_NAME, SURNAME_CHANGE_DATE, 
 FIRST_NAME, FORENAME_CHANGE_DATE, DATE_OF_BIRTH, DOB_CHANGE_DATE, GENDER, 
 GENDER_CHANGE_DATE, HOUSE_NAME_NO, HOUSENAME_NO_CHANGE_DATE, ADDRESS_LINE_1, ADDR1_CHANGE_DATE, 
 ADDRESS_LINE_2, ADDR2_CHANGE_DATE, ADDRESS_LINE_3, ADDR3_CHANGE_DATE, ADDRESS_LINE_4, 
 ADDR4_CHANGE_DATE, POSTCODE, POSTCODE_CHANGE_DATE, PHONE_NUMBER, PHONE_CHANGE_DATE, 
 EMAIL_ADDRESS, EMAIL_CHANGE_DATE, CHANGED_STATUS, STATUS_CHANGED_DATE, DATE_OF_WITHDRAWAL, 
 LEARNER_IS_DECEASED, DATE_NOTIFIED_DECEASED, DATE_LEARNER_MAIL_RETURNED, DATE_CHANGED_MAIL_RETURNED
 from VU_SDS2009
/
    --------------------------------------------------------
    -- Indexes for ILA_SDS_2009
    --------------------------------------------------------
    CREATE INDEX ILA_SDS_2009_IND1
    ON ILA500.ILA_SDS_2009 (ila_ref_no)
    TABLESPACE USERS
    STORAGE (INITIAL 20M NEXT 20M PCTINCREASE 0);