--DROP TABLE LATEST_COLLEGE;

CREATE TABLE LATEST_COLLEGE
(
  HEI_INST_CODE  VARCHAR2(4 ),
  INST_CODE      VARCHAR2(5 ),
  HEI_INST_NAME  VARCHAR2(50 ),
  SESSION_CODE   VARCHAR2(50 ),
  MAX_FEE        NUMBER(10)
)
TABLESPACE SLC_DATA;