/* Formatted on 12/09/2018 11:27:12 (QP5 v5.256.13226.35538) */
--DROP TABLE EXT_COURSE_2018;


CREATE TABLE EXT_COURSE_2018 (
      HEI_INST_CODE      VARCHAR2(4),
      INST_CODE      VARCHAR2(5),
      CAMPUS VARCHAR2(100),
      HEI_CRSE_CODE VARCHAR2(6),
      CRSE_CODE  VARCHAR2(5),
      SCOTTISH  VARCHAR2(100),
      HEI_CRSE_NAME  VARCHAR2(50),
      DUMMY1  VARCHAR2(50),
      SESSION_CODE  VARCHAR2(50),
      DURATION  NUMBER(1)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'EXT_COURSE_2018.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_INST_CODE      CHAR(4),
      INST_CODE      CHAR(5),
      CAMPUS CHAR(100),
      HEI_CRSE_CODE CHAR(6),
      CRSE_CODE  CHAR(5),
      SCOTTISH  CHAR(100),
      HEI_CRSE_NAME  CHAR(50),
      DUMMY1  CHAR(50) ,
      DURATION  CHAR(1)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2018')
  )
  LOCATION ('f_course.2018.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

--DROP TABLE EXT_COURSE_2017;


CREATE TABLE EXT_COURSE_2017 (
      HEI_INST_CODE      VARCHAR2(4),
      INST_CODE      VARCHAR2(5),
      CAMPUS VARCHAR2(100),
      HEI_CRSE_CODE VARCHAR2(6),
      CRSE_CODE  VARCHAR2(5),
      SCOTTISH  VARCHAR2(100),
      HEI_CRSE_NAME  VARCHAR2(50),
      DUMMY1  VARCHAR2(50),
      SESSION_CODE  VARCHAR2(50),
      DURATION  NUMBER(1)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'EXT_COURSE_2017.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_INST_CODE      CHAR(4),
      INST_CODE      CHAR(5),
      CAMPUS CHAR(100),
      HEI_CRSE_CODE CHAR(6),
      CRSE_CODE  CHAR(5),
      SCOTTISH  CHAR(100),
      HEI_CRSE_NAME  CHAR(50),
      DUMMY1  CHAR(50) ,
      DURATION  CHAR(1)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2017')
  )
  LOCATION ('f_course.2017.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE VIEW EXT_COURSE
AS
   SELECT HEI_INST_CODE, INST_CODE, CAMPUS, HEI_CRSE_CODE, CRSE_CODE, SCOTTISH, HEI_CRSE_NAME, DUMMY1, SESSION_CODE, DURATION FROM EXT_COURSE_2018 ec1
   UNION ALL
   SELECT HEI_INST_CODE, INST_CODE, CAMPUS, HEI_CRSE_CODE, CRSE_CODE, SCOTTISH, HEI_CRSE_NAME, DUMMY1, SESSION_CODE, DURATION FROM EXT_COURSE_2017 ec2;
