--DROP TABLE EXT_COLLEGE_2018;

CREATE TABLE EXT_COLLEGE_2018 (
      HEI_INST_CODE      VARCHAR2(4),
      INST_CODE      VARCHAR2(5),
      HEI_INST_NAME VARCHAR2(50),
      SESSION_CODE  VARCHAR2(50),
      MAX_FEE  NUMBER(10)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'SLC_TERM_DATE_DIR:EXT_COLLEGE_2018.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_INST_CODE      CHAR(4),
      INST_CODE      CHAR(5),
      HEI_INST_NAME  CHAR(50),
      DUMMY4  CHAR(500),
      DUMMY5  CHAR(500),
      DUMMY6  CHAR(500),
      DUMMY7  CHAR(500),
      DUMMY8  CHAR(500),
      DUMMY9  CHAR(500),
      DUMMY10  CHAR(500),
      DUMMY11  CHAR(500),
      DUMMY12  CHAR(500),
      DUMMY13  CHAR(500),
      DUMMY14  CHAR(500),
      DUMMY15  CHAR(500),
      DUMMY16  CHAR(500),
      DUMMY17  CHAR(500),
      DUMMY18  CHAR(500),
      DUMMY19  CHAR(500),
      DUMMY20  CHAR(500),
      DUMMY21  CHAR(500),
      DUMMY22  CHAR(500),
      MAX_FEE  CHAR(100)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2018')
  )
  LOCATION ('f_coll.2018.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

--DROP TABLE EXT_COLLEGE_2017;

CREATE TABLE EXT_COLLEGE_2017 (
      HEI_INST_CODE      VARCHAR2(4),
      INST_CODE      VARCHAR2(5),
      HEI_INST_NAME VARCHAR2(50),
      SESSION_CODE  VARCHAR2(50),
      MAX_FEE  NUMBER(10)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'SLC_TERM_DATE_DIR:EXT_COLLEGE_2017.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_INST_CODE      CHAR(4),
      INST_CODE      CHAR(5),
      HEI_INST_NAME  CHAR(50),
      DUMMY4  CHAR(500),
      DUMMY5  CHAR(500),
      DUMMY6  CHAR(500),
      DUMMY7  CHAR(500),
      DUMMY8  CHAR(500),
      DUMMY9  CHAR(500),
      DUMMY10  CHAR(500),
      DUMMY11  CHAR(500),
      DUMMY12  CHAR(500),
      DUMMY13  CHAR(500),
      DUMMY14  CHAR(500),
      DUMMY15  CHAR(500),
      DUMMY16  CHAR(500),
      DUMMY17  CHAR(500),
      DUMMY18  CHAR(500),
      DUMMY19  CHAR(500),
      DUMMY20  CHAR(500),
      DUMMY21  CHAR(500),
      DUMMY22  CHAR(500),
      MAX_FEE  CHAR(100)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2017')
  )
  LOCATION ('f_coll.2017.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE VIEW EXT_COLLEGE
AS
   SELECT HEI_INST_CODE, INST_CODE, HEI_INST_NAME, SESSION_CODE, MAX_FEE FROM EXT_COLLEGE_2018 ec1
   UNION ALL
   SELECT HEI_INST_CODE, INST_CODE, HEI_INST_NAME, SESSION_CODE, MAX_FEE FROM EXT_COLLEGE_2017 ec2;
