--DROP TABLE TERM_CHANGE;

CREATE TABLE TERM_CHANGE
(
  HEI_CRSE_CODE  VARCHAR2(6 ),
  ACADEMIC_YEAR  NUMBER(3),
  TERM           NUMBER(1),
  NEW_TERM_START     DATE,
  NEW_TERM_END       DATE,
  NEW_FEES           VARCHAR2(100 ),
  OLD_TERM_START     DATE,
  OLD_TERM_END       DATE,
  OLD_FEES           VARCHAR2(100 ),
  CHANGE_TYPE        VARCHAR2(1 ),
  CREATED_DATE       DATE,
  CREATED_BY         VARCHAR2(50 ),
  STATUS             VARCHAR2(20 ),
  STATUS_BY          VARCHAR2(50 ),  
  SESSION_CODE   VARCHAR2(50 )
)
TABLESPACE SLC_DATA;