/* Formatted on 12/09/2018 11:27:12 (QP5 v5.256.13226.35538) */
--DROP TABLE EXT_TERM_2018;


CREATE TABLE EXT_TERM_2018 (
      HEI_CRSE_CODE VARCHAR2(6),
      ACADEMIC_YEAR  NUMBER(3),
      TERM  NUMBER(1),
      TERM_START  DATE,
      TERM_END  DATE,
      SESSION_CODE  VARCHAR2(50),
      FEES  VARCHAR2(100)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'EXT_TERM_2018.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_CRSE_CODE CHAR(6),
      ACADEMIC_YEAR  CHAR(3),
      TERM  CHAR(1),
      TERM_START  DATE 'DDMMYYYY' ,
      TERM_END  DATE 'DDMMYYYY' ,
      FEES  CHAR(100)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2018')
  )
  LOCATION ('f_term.2018.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

/* Formatted on 12/09/2018 11:27:12 (QP5 v5.256.13226.35538) */
--DROP TABLE EXT_TERM_2017;


CREATE TABLE EXT_TERM_2017 (
      HEI_CRSE_CODE VARCHAR2(6),
      ACADEMIC_YEAR  NUMBER(3),
      TERM  NUMBER(1),
      TERM_START  DATE,
      TERM_END  DATE,
      SESSION_CODE  VARCHAR2(50),
      FEES  VARCHAR2(100)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY SLC_TERM_DATE_DIR
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    BADFILE 'EXT_TERM_2017.BADFILE'
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
    (
      HEI_CRSE_CODE CHAR(6),
      ACADEMIC_YEAR  CHAR(3),
      TERM  CHAR(1),
      TERM_START  DATE 'DDMMYYYY' ,
      TERM_END  DATE 'DDMMYYYY' ,
      FEES  CHAR(100)
    )
    COLUMN TRANSFORMS
    ( SESSION_CODE FROM CONSTANT '2017')
  )
  LOCATION ('f_term.2017.txt')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;

CREATE OR REPLACE VIEW EXT_TERM
AS
   SELECT HEI_CRSE_CODE, ACADEMIC_YEAR, TERM, TERM_START, TERM_END, SESSION_CODE, FEES FROM EXT_TERM_2018 ec1
   UNION ALL
   SELECT HEI_CRSE_CODE, ACADEMIC_YEAR, TERM, TERM_START, TERM_END, SESSION_CODE, FEES FROM EXT_TERM_2017 ec2;