--DROP TABLE CURRENT_COURSE;

CREATE TABLE CURRENT_COURSE
(
  HEI_INST_CODE  VARCHAR2(4 BYTE),
  INST_CODE      VARCHAR2(5 BYTE),
  CAMPUS         VARCHAR2(100 BYTE),
  HEI_CRSE_CODE  VARCHAR2(6 BYTE),
  CRSE_CODE      VARCHAR2(5 BYTE),
  SCOTTISH       VARCHAR2(100 BYTE),
  HEI_CRSE_NAME  VARCHAR2(50 BYTE),
  DUMMY1         VARCHAR2(50 BYTE),
  SESSION_CODE   VARCHAR2(50 BYTE),
  DURATION       NUMBER(1)
)
TABLESPACE SLC_DATA;
