--DROP TABLE LATEST_TERM;

CREATE TABLE LATEST_TERM
(
  HEI_CRSE_CODE  VARCHAR2(6 BYTE),
  ACADEMIC_YEAR  NUMBER(3),
  TERM           NUMBER(1),
  TERM_START     DATE,
  TERM_END       DATE,
  SESSION_CODE   VARCHAR2(50 BYTE),
  FEES           VARCHAR2(100 BYTE)
)
TABLESPACE SLC_DATA;
