--DROP TABLE COURSE_CHANGE;

CREATE TABLE COURSE_CHANGE
(
  HEI_INST_CODE      VARCHAR2(4 ),
  NEW_INST_CODE      VARCHAR2(5 ),
  NEW_CAMPUS         VARCHAR2(100 ),
  NEW_HEI_CRSE_CODE  VARCHAR2(6 ),
  NEW_CRSE_CODE      VARCHAR2(5 ),
  NEW_SCOTTISH       VARCHAR2(100 ),
  NEW_HEI_CRSE_NAME  VARCHAR2(50 ),
  DUMMY1             VARCHAR2(50 ),
  NEW_DURATION       NUMBER(1),
  OLD_INST_CODE      VARCHAR2(5 ),
  OLD_CAMPUS         VARCHAR2(100 ),
  OLD_HEI_CRSE_CODE  VARCHAR2(6 ),
  OLD_CRSE_CODE      VARCHAR2(5 ),
  OLD_SCOTTISH       VARCHAR2(100 ),
  OLD_HEI_CRSE_NAME  VARCHAR2(50 ),
  OLD_DURATION       NUMBER(1),
  CHANGE_TYPE        VARCHAR2(1),
  CREATED_DATE       DATE,
  CREATED_BY         VARCHAR2(50),
  STATUS             VARCHAR2(20),
  STATUS_BY          VARCHAR2(50),  
  SESSION_CODE   VARCHAR2(50 )  
)
TABLESPACE SLC_DATA;
