--DROP TABLE COLLEGE_CHANGE;

CREATE TABLE COLLEGE_CHANGE
(
  HEI_INST_CODE  VARCHAR2(4 ),
  NEW_INST_CODE      VARCHAR2(5 ),
  NEW_HEI_INST_NAME  VARCHAR2(50 ),
  NEW_MAX_FEE        NUMBER(10),
  OLD_INST_CODE      VARCHAR2(5 ),
  OLD_HEI_INST_NAME  VARCHAR2(50 ),
  OLD_MAX_FEE        NUMBER(10),
  CHANGE_TYPE        VARCHAR2(1),
  CREATED_DATE       DATE,
  CREATED_BY         VARCHAR2(50),
  STATUS             VARCHAR2(50),
  STATUS_BY          VARCHAR2(50), 
  SESSION_CODE   VARCHAR2(50 )
  
)
TABLESPACE SLC_DATA;
