ALTER TABLE SGAS.ATTENDANCE_DATA_AUD
 DROP PRIMARY KEY CASCADE;
DROP TABLE SGAS.ATTENDANCE_DATA_AUD CASCADE CONSTRAINTS;

CREATE TABLE SGAS.ATTENDANCE_DATA_AUD
(
  AUD_ID        NUMBER(10),
  AUD_DATE      DATE,
  COLUMN_NAME   VARCHAR2(32 BYTE),
  TABLE_PKEY1   VARCHAR2(32 BYTE),
  USERNAME      VARCHAR2(15 BYTE),
  OLD           VARCHAR2(400 BYTE),
  NEW           VARCHAR2(400 BYTE),
  ACTION        VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.ATTENDANCE_DATA_AUD IS 'Table holding audit data for the ATTENDANCE_DATA table';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.AUD_ID IS 'Unique identifier for each row on the table';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.AUD_DATE IS 'Date the row on the audit table is created';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.COLUMN_NAME IS 'Name of the column that is being audited';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.TABLE_PKEY1 IS 'The unique identifier of the row on the table that is being audited';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.USERNAME IS 'The unique identifier of the user making the change';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.OLD IS 'The old value';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.NEW IS 'The new value';

COMMENT ON COLUMN SGAS.ATTENDANCE_DATA_AUD.ACTION IS 'The action carried out by the user, ie update, insert or delete';


CREATE UNIQUE INDEX SGAS.ATTENDANCE_DATA_AUD_PK ON SGAS.ATTENDANCE_DATA_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM ATTENDANCE_DATA_AUD;

CREATE PUBLIC SYNONYM ATTENDANCE_DATA_AUD FOR SGAS.ATTENDANCE_DATA_AUD;


ALTER TABLE SGAS.ATTENDANCE_DATA_AUD ADD (
  CONSTRAINT ATTENDANCE_DATA_AUD_PK
 PRIMARY KEY
 (AUD_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));



--#ATTENDANCE_DATA_AUD.ATT_DATA_AUD_ID SEQUENCE###############################
DROP SEQUENCE SGAS.ATT_DATA_AUD_ID_SEQ;

CREATE SEQUENCE SGAS.ATT_DATA_AUD_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT SELECT ON  SGAS.ATT_DATA_AUD_ID_SEQ TO PUBLIC;