ALTER TABLE SGAS.COMPLETED_SHWAP
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SGAS.COMPLETED_SHWAP CASCADE CONSTRAINTS
/

--
-- COMPLETED_SHWAP  (Table) 
--
--   Row count:0
CREATE TABLE SGAS.COMPLETED_SHWAP
(
  STUD_REF_NO         VARCHAR2(10 BYTE)         NOT NULL,
  FORENAMES           VARCHAR2(25 BYTE)             NULL,
  SURNAME             VARCHAR2(25 BYTE)         NOT NULL,
  SESSION_CODE        VARCHAR2(4 BYTE)              NULL,
  OBJECT_ID           VARCHAR2(44 BYTE)         NOT NULL,
  WEB_USER_ID         VARCHAR2(25 BYTE)             NULL,
  WEB_SUBMITTED_DATE  DATE                          NULL,
  STATUS              VARCHAR2(1 BYTE)              NULL,
  ERROR_MESSAGE       VARCHAR2(1024 BYTE)           NULL,
  CONSTRAINT P_CSHWAP_PK
 PRIMARY KEY
 (OBJECT_ID)
)
/
