--DROP TABLE SGAS.CORRESPONDENCE_TASKS_ALL CASCADE CONSTRAINTS;

CREATE TABLE SGAS.CORRESPONDENCE_TASKS_ALL
(
  CUSTOM_TASK_ID  VARCHAR2(255 BYTE),
  TASK_ID         NUMBER(10)                    NOT NULL,
  TASK_NAME       VARCHAR2(765 BYTE),
  CREATION_DATE   DATE,
  WORKQUEUE       VARCHAR2(10 BYTE),
  LAST_ACTIONED   VARCHAR2(12 BYTE),
  ACCEPTED_BY     VARCHAR2(255 BYTE),
  INST_NAME       VARCHAR2(50 BYTE)
)
TABLESPACE STEPS_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
