-- Country table. Reference data. 
--
-- MODIFICATION HISTORY:
-- Ref      Date       Author                      Desc.
--          28.02.08   S Durkin (Sopra UK)         Initial Version.
-- 001      11.03.08   A.Bowman (SAAS)             Added last_updated_by and last_updated_on columns as this table has audit requirements
-- 002      22.06.09   A.Bowman (SAAS)             Added audit triggers
-- 003      17.11.09   A.Bowman (SAAS)             Added reference data
-- 004      28.01.10   A.Bowman (SAAS)             Amended audit triggers
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/tables/COUNTRY.sql $
-- $Author: $
-- $Date: 2010-12-21 14:42:40 +0000 (Tue, 21 Dec 2010) $
-- $Revision: 6206 $
--

ALTER TABLE SGAS.COUNTRY
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SGAS.COUNTRY CASCADE CONSTRAINTS PURGE
/

--
-- COUNTRY  (Table) 
--
--   Row count:542
CREATE TABLE SGAS.COUNTRY
( COUNTRY_CODE        NUMBER(3) CONSTRAINT NN_CN_COUNTRY_CODE NOT NULL,
  SHORT_NAME          VARCHAR2(12 BYTE)             NULL,
  CATEGORY            NUMBER(1)                     NULL,
  NATIONALITY_NAME    VARCHAR2(25 BYTE)             NULL,
  LONG_NAME           VARCHAR2(73 BYTE) CONSTRAINT NN_CN_LONG_NAME NOT NULL,
  SKELETON            VARCHAR2(1 BYTE)          DEFAULT 'Y' CONSTRAINT NN_CN_SKELETON NOT NULL,
  EUROPEAN_COMMUNITY  VARCHAR2(1 BYTE)          DEFAULT 'Y' CONSTRAINT NN_CN_EUROPEAN_COMMUNITY NOT NULL,
  NEW_CATEGORY        VARCHAR2(1 BYTE)              NULL,
--- 001 columns added for audit purposes
  LAST_UPDATED_BY    VARCHAR2(15 BYTE) DEFAULT User CONSTRAINT NN_CN_LAST_UPDATED_BY NOT NULL,
  LAST_UPDATED_ON    DATE DEFAULT Sysdate CONSTRAINT NN_CN_LAST_UPDATED_ON NOT NULL)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          100K
            NEXT             100K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- P_CN  (Index) 
--
--  Dependencies: 
--   COUNTRY (Table)
--
CREATE UNIQUE INDEX P_CN ON SGAS.COUNTRY
(COUNTRY_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          100K
            NEXT             100K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

CREATE OR REPLACE TRIGGER SGAS.cn_iud
   AFTER INSERT OR DELETE OR UPDATE OF CATEGORY, LAST_UPDATED_BY
   ON SGAS.COUNTRY    FOR EACH ROW
DECLARE
   p_aud_date       DATE                            := SYSDATE;
   p_column_name    country_aud.column_name%TYPE    := NULL;
   p_table_pkey1    country_aud.table_pkey1%TYPE    := :OLD.country_code;
   p_table_pkey2    country_aud.table_pkey2%TYPE    := NULL;
   p_table_pkey3    country_aud.table_pkey3%TYPE    := NULL;
   p_table_pkey4    country_aud.table_pkey4%TYPE    := NULL;
   p_table_pkey5    country_aud.table_pkey5%TYPE    := NULL;
   p_old            country_aud.OLD%TYPE            := NULL;
   p_new            country_aud.NEW%TYPE            := NULL;
   p_action         country_aud.action%TYPE         := NULL;
   p_username       country_aud.username%TYPE       := :NEW.LAST_UPDATED_BY;
   p_stud_ref_no    country_aud.stud_ref_no%TYPE    := NULL;
   p_inst_code      country_aud.inst_code%TYPE      := NULL;
   p_session_code   country_aud.session_code%TYPE   := NULL;
BEGIN
   IF INSERTING
   THEN
      p_action := 'I';
      p_table_pkey1 := :NEW.country_code;
   ELSIF UPDATING
   THEN
      p_action := 'U';
   ELSIF DELETING
   THEN
      p_action := 'D';
      p_table_pkey1 := :OLD.country_code;
      p_username := :OLD.last_updated_by;
   END IF;

   p_column_name := 'CATEGORY';
   p_old := TO_CHAR (:OLD.CATEGORY);
   p_new := TO_CHAR (:NEW.CATEGORY);
   pk_steps_aud.ins_cn_aud (p_aud_date,
                            p_column_name,
                            p_table_pkey1,
                            p_table_pkey2,
                            p_table_pkey3,
                            p_table_pkey4,
                            p_table_pkey5,
                            p_old,
                            p_new,
                            p_action,
                            p_username,
                            p_stud_ref_no,
                            p_inst_code,
                            p_session_code
                           );
   p_column_name := 'LAST_UPDATED_BY';
   p_old := :OLD.LAST_UPDATED_BY;
   p_new := :NEW.LAST_UPDATED_BY;
   pk_steps_aud.ins_cn_aud (p_aud_date,
                            p_column_name,
                            p_table_pkey1,
                            p_table_pkey2,
                            p_table_pkey3,
                            p_table_pkey4,
                            p_table_pkey5,
                            p_old,
                            p_new,
                            p_action,
                            p_username,
                            p_stud_ref_no,
                            p_inst_code,
                            p_session_code
                           );
END cn_iud;

SHOW ERRORS;

DROP PUBLIC SYNONYM COUNTRY
/

--
-- COUNTRY  (Synonym) 
--
--  Dependencies: 
--   COUNTRY (Table)
--
CREATE PUBLIC SYNONYM COUNTRY FOR SGAS.COUNTRY
/


-- 
-- Non Foreign Key Constraints for Table COUNTRY 
-- 
ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT CN_CATEGORY
 CHECK ( CATEGORY IN('1','2','3','4')))
/

ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT CN_SKELETON
 CHECK ( SKELETON IN('Y','N')))
/

ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT CN_EUROPEAN_COMMUNITY
 CHECK ( EUROPEAN_COMMUNITY IN('Y','N')))
/

ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT CN_NEW_CATEGORY
 CHECK (NEW_CATEGORY IN (1,2,3)))
/

ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT P_CN
 PRIMARY KEY
 (COUNTRY_CODE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          100K
                NEXT             100K
                MINEXTENTS       1
                MAXEXTENTS       99
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
               ))
/

--
-- Insert Reference Data
--
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
1, 'ENG', NULL, 'ENGLISH', 'ENGLAND', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
2, 'USA', 3, 'AMERICAN', 'UNITED STATES', 'N', 'N', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
4, 'IRE', NULL, 'IRISH', 'IRELAND', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
9, 'CAROLINA', 3, 'AMERICAN', 'NORTH CAROLINA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
10, 'UK', 1, 'BRITISH', 'UNITED KINGDOM', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
99, 'N.IRE', NULL, 'BRITISH', 'N IRELAND', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
100, 'NOR', NULL, 'NORWEGIAN', 'NORWAY 2000', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
299, 'SCOTLAND', NULL, 'SCOTTISH', 'SCOTLAND', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
420, 'SCIL', 4, 'SCILLIAN', 'SCILLY', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
427, 'ILEA', 4, 'ILEASE', 'ILEA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
579, 'WAL', NULL, 'WELSH', 'WALES', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
601, 'YEM PDR', 4, 'YEMENI', 'YEMEN PDR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
602, 'AFGN', 4, 'AFGHAN', 'AFGHANISTAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
603, 'ALBN', 4, 'ALBANIAN', 'ALBANIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
604, 'ALG', 4, 'ALGERIAN', 'ALGERIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
605, 'AND', 4, 'ANDORRAN', 'ANDORRA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:49 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
606, 'ANGO', 4, 'ANGOLAN', 'ANGOLA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
607, 'ANTG', 4, 'ANTIGUAN', 'ANTIGUA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
608, 'ARG', 4, 'ARGENTINIAN', 'ARGENTINA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
609, 'AUSL', 3, 'AUSTRALIAN', 'AUSTRALIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
610, 'AUST', 2, 'AUSTRIAN', 'AUSTRIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
611, 'BAHM', 4, 'BAHAMIAN', 'BAHAMAS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
612, 'BAHR', 4, 'BAHRANIAN', 'BAHRAIN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
613, 'BARB', 4, 'BARBADIAN', 'BARBADOS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
614, 'BELG', 2, 'BELGIAN', 'BELGIUM', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:50 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
615, 'BERM', 4, 'BERMUDAN', 'BERMUDA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
616, 'BHUT', 4, 'BHUTAN', 'BHUTAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
617, 'BOLV', 4, 'BOLIVIAN', 'BOLIVIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
618, 'BOTS', 4, 'BOTSWANIAN', 'BOTSWANA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
619, 'BRAZ', 4, 'BRAZILIAN', 'BRAZIL', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
620, 'BRUN', 4, 'BRUNEI', 'BRUNEI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
621, 'BULG', 4, 'BULGARIAN', 'BULGARIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
622, 'BURM', 4, 'BURMESE', 'BURMA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
623, 'BURU', 4, 'BURUNDI', 'BURUNDI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
624, 'KAMP', 4, 'KAMPUCHEAN', 'KAMPUCHEA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
625, 'CAMR', 4, 'CAMEROON', 'CAMEROON', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
626, 'CANA', 3, 'CANADIAN', 'CANADA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
627, 'C.A.R.', 4, 'C.A.R.', 'CENTRAL AFRICAN REPUBLIC', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
628, 'S LAN', 4, 'SRI LANKAN', 'SRI LANKA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
629, 'CHAD', 4, 'CHAD', 'CHAD', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
630, 'CHIL', 4, 'CHILIAN', 'CHILE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
631, 'CHNA', 4, 'CHINESE', 'CHINA (COMMUNIST)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
632, 'COLM', 4, 'COLOMBIAN', 'COLOMBIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
633, 'ZAI', 4, 'ZAIRIAN', 'ZAIRE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
634, 'CONG', 4, 'CONGOLESE', 'CONGO (PEOPLES REPUBLIC)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
635, 'COST', 4, 'COSTA RICAN', 'COSTA RICA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
636, 'CUBA', 4, 'CUBAN', 'CUBA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
637, 'ANTL', 2, 'DUTCH', 'ANTILLES (NETHERLANDS)', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
638, 'CYPR', 4, 'CYPRIOT', 'CYPRUS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
640, 'BENI', 4, 'BENIN', 'BENIN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
641, 'DENM', 1, 'DANISH', 'DENMARK', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
642, 'DOMI', 4, 'DOMINICAN', 'DOMINICA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
643, 'DOMR', 4, 'DOMINICAN', 'DOMINICAN REPUBLIC', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
644, 'DENM', 1, 'DANISH', 'DENMARK 2002', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:48 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
645, 'ECUA', 4, 'ECUADORIAN', 'ECUADOR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
646, 'EL SAL', 4, 'EL SALVADORIAN', 'EL SALVADOR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
647, 'TUVU', 4, 'TUVULA', 'TUVALU', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
648, 'ETHI', 4, 'ETHIOPIAN', 'ETHIOPIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
649, 'FALK', 4, 'BRITISH', 'FALKLAND ISLANDS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
650, 'FIJI', 4, 'FIJIAN', 'FIJI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
651, 'FIN', 1, 'FINNISH', 'FINLAND', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
652, 'TAI', 1, 'TAIWANESE', 'TAIWAN', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
653, 'FRAN', 2, 'FRENCH', 'FRANCE', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
654, 'GAB', 4, 'GABON', 'GABON', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
655, 'GAMB', 4, 'GAMBIAN', 'GAMBIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
656, 'GERM', 2, 'GERMAN', 'GERMANY', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
658, 'GHAN', 4, 'GHANAIAN', 'GHANA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
659, 'GIBR', 4, 'BRITISH', 'GIBRALTAR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
660, 'KIRI', 4, 'KIRIBATI', 'KIRIBATI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
661, 'GREE', 3, 'GREEK', 'GREECE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
662, 'GREN', 4, 'GRENADAN', 'GRENADA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
663, 'GUAT', 4, 'GUATAMALIAN', 'GUATEMALA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
664, 'GUIN', 4, 'GUINEAN', 'GUINEA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
665, 'GUYA', 4, 'GUYANAN', 'GUYANA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
666, 'HAIT', 4, 'HAITIAN', 'HAITI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
667, 'HOND', 4, 'HONDURAN', 'HONDURAS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:56 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
668, 'BELZ', 4, 'BELIZE', 'BELIZE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
669, 'HONG', 2, 'HONG KONG', 'HONG KONG', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
670, 'HUNG', 4, 'HUNGARIAN', 'HUNGARY', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
671, 'ICEL', 1, 'ICELANDIC', 'ICELAND', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
672, 'INDI', 4, 'INDIAN', 'INDIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
673, 'INDO', 3, 'INDONESIAN', 'INDONESIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
674, 'IRAN', 4, 'IRANIAN', 'IRAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
675, 'IRAQ', 4, 'IRAQI', 'IRAQ', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:57 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
676, 'EIRE', 3, 'IRISH', 'IRELAND (REPUBLIC)', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:58 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
677, 'ISRA', 2, 'ISRAELI', 'ISRAEL', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:58 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
678, 'ITAL', 3, 'ITALIAN', 'ITALY', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:58 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
679, 'IV CST', 4, 'IVORY COAST', 'IVORY COAST', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:58 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
680, 'JAM', 4, 'JAMAICAN', 'JAMAICA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:58 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
681, 'JAP', 1, 'JAPANESE', 'JAPAN', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
682, 'JORD', 4, 'JORDANIAN', 'JORDAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
683, 'KENY', 4, 'KENYAN', 'KENYA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
684, 'KOR REP', 2, 'KOREAN', 'KOREA (REPUBLIC)', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
685, 'KOR DPR', 2, 'KOREAN', 'KOREA DPR', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
686, 'KUW', 4, 'KUWAITI', 'KUWAIT', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
687, 'LAO PDR', 4, 'LAO PDR', 'LAO PDR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
688, 'LEB', 4, 'LEBANESE', 'LEBANON', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
689, 'LEE ISL', 4, 'LEEWARD ISLANDS', 'LEEWARD ISLANDS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:06 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
690, 'LESO', 4, 'LESOTHAN', 'LESOTHO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
691, 'LIBE', NULL, 'LIBERIAN', 'LIBERIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
693, 'LUX', 2, 'LUXEMBOURG', 'LUXEMBOURG', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
694, 'MAC', 4, 'MACAO', 'MACAO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
695, 'MALA', 4, 'MALAGASY REP', 'MALAGASY REP', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
696, 'MALA', 4, 'MALAWIAN', 'MALAWI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
697, 'MALY', 4, 'MALAYAN', 'MALAYA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
698, 'MALS', 4, 'MALAYSIAN', 'MALAYSIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:07 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
699, 'MALI', 4, 'MALI', 'MALI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
700, 'MALT', 4, 'MALTESE', 'MALTA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
701, 'MAUN', 4, 'MAURITANIAN', 'MAURITANIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
702, 'MAUR', 4, 'MAURITIAN', 'MAURITIUS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
703, 'MEX', 4, 'MEXICAN', 'MEXICO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
704, 'MONG', 4, 'MONGOLIAN', 'MONGOLIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
705, 'MONT', 4, 'MONTSERRAT', 'MONTSERRAT', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
706, 'MORO', 4, 'MOROCCAN', 'MOROCCO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:08 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
707, 'MOZ', 4, 'MOZAMBIQUE', 'MOZAMBIQUE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
708, 'OMAN', 4, 'OMANI', 'OMAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
709, 'NEP', 4, 'NEPALI', 'NEPAL', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
710, 'NETH', 2, 'DUTCH', 'NETHERLANDS', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
711, 'N CAL', 4, 'NEW CALEDONIAN', 'NEW CALEDONIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
712, 'N GUI', 4, 'NEW GUINEAN', 'NEW GUINEA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
713, 'VANU', 4, 'VANUATU', 'VANUATU', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
714, 'N ZEA', 3, 'NEW ZEALAND', 'NEW ZEALAND', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:09 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
715, 'NIC', 4, 'NICARAGUAN', 'NICARAGUA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
716, 'NIGR', 4, 'NIGER', 'NIGER', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
717, 'NIGE', 4, 'NIGERIAN', 'NIGERIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
718, 'NORW', 1, 'NORWEGIAN', 'NORWAY', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
721, 'PAKI', 4, 'PAKISTANI', 'PAKISTAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
722, 'PANA', 4, 'PANAMANIAN', 'PANAMA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
723, 'PAP', 4, 'PAPUA', 'PAPUA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
724, 'PARA', 4, 'PARAGUAYAN', 'PARAGUAY', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
725, 'PERU', 4, 'PERUVIAN', 'PERU', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:10 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
726, 'PHIL', 4, 'FILIPINO', 'PHILIPPINES', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
727, 'POL', 4, 'POLISH', 'POLAND', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
728, 'PORT', 4, 'PORTUGUESE', 'PORTUGAL', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
730, 'P RICO', 4, 'PUERTO RICAN', 'PUERTO RICO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
731, 'QATA', 4, 'QATARI', 'QATAR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
732, 'ZIM', 4, 'ZIMBABWEAN', 'ZIMBABWE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
733, 'RUM', 4, 'ROMANIAN', 'ROMANIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
734, 'RWAN', 4, 'RWANDAN', 'RWANDA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:11 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
735, 'ST HEL', 4, 'ST HELENA', 'ST.HELENA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
737, 'ST LUC', 4, 'ST LUCIAN', 'ST.LUCIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
739, 'SABA', 4, 'SABAH', 'SABAH', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
741, 'W SAM', 4, 'WESTERN SAMOAN', 'WEST SAMOA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
742, 'SARA', 4, 'SARAWAKI', 'SARAWAK', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
743, 'SAUD', 4, 'SAUDI', 'SAUDI ARABIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
744, 'SEY', 4, 'SEYCHELLOIS', 'SEYCHELLES', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
745, 'S LEON', 4, 'SIERRA LEONE', 'SIERRA LEONE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
746, 'SING', 4, 'SINGAPORE', 'SINGAPORE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:12 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
747, 'SOL ISL', 4, 'SOLOMAN ISLANDS', 'SOLOMON ISLANDS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
748, 'SOM REP', 4, 'SOMALI', 'SOMALI REPUBLIC', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
749, 'DJIB', 4, 'DJIBOUTI', 'DJIBOUTI', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
750, 'S AFR', 4, 'SOUTH AFRICAN', 'SOUTH AFRICA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
751, 'SPN', 3, 'SPANISH', 'SPAIN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
752, 'SUD', 4, 'SUDANESE', 'SUDAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
753, 'SUR', 4, 'SURINAM', 'SURINAM', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
754, 'SWAZ', NULL, 'SWAZI', 'SWAZILAND', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:13 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
755, 'SWE', 1, 'SWEDISH', 'SWEDEN', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
756, 'SWI', 1, 'SWISS', 'SWITZERLAND', 'N', 'Y', '1', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
757, 'SYR AR', 4, 'SYRIAN', 'SYRIAN AR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
759, 'TANZ', 4, 'TANZANIAN', 'TANZANIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
760, 'THAI', 4, 'THAI', 'THAILAND', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
761, 'TIB', 4, 'TIBETAN', 'TIBET', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
762, 'TOGO', 4, 'TOGOAN', 'TOGO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
763, 'TRIN AND TOB', 4, 'TRINIDAD AND TOBAGAN', 'TRINIDAD AND TOBAGO', 'N', 'Y', '3', 'SGAS'
,  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
764, 'UAE', 4, 'UAE', 'UNITED ARAB EMIRATES', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
765, 'TUN', 4, 'TUNISIAN', 'TUNISIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
766, 'TURK', 4, 'TURKISH', 'TURKEY', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
767, 'UGAN', 4, 'UGANDAN', 'UGANDA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
768, 'UAR', 4, 'UAR', 'UNITED ARAB REPUBLIC', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:51 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
769, 'UP VOL', 4, 'UPPER VOLTA', 'UPPER VOLTA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
770, 'URUG', 4, 'URUGUYAN', 'URUGUAY', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
771, 'USA', 3, 'AMERICAN', 'USA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
772, 'USSR/CIS', 3, 'USSR/CIS', 'USSR/CIS', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
773, 'VEN', 4, 'VENEZUELAN', 'VENEZUELA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
774, 'S VIET', 4, 'SOUTH VIETNAMESE', 'VIETNAM (SOUTH)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
775, 'N VIET', 4, 'NORTH VIETNAMESE', 'VIETNAM (NORTH)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
776, 'VIRG UK', 4, 'BRITISH', 'VIRGIN ISLANDS (BRITISH)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
777, 'W IND', 4, 'WEST INDIAN', 'WEST INDIES', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:52 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
779, 'YEM AR', 4, 'YEMENI', 'YEMEN AR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
780, 'YUGO', 4, 'YUGOSLAVIAN', 'YUGOSLAVIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
781, 'ZAM', 4, 'ZAMBIAN', 'ZAMBIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
782, 'NOT KNOWN', 4, 'NOT KNOWN', 'NOT KNOWN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
784, 'TONG', 4, 'TONGAN', 'TONGA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
785, 'SENE', 4, 'SENEGALI', 'SENEGAL', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
786, 'P TIMOR', 4, 'PORTUGUESE TIMOR', 'PORTUGUESE TIMOR', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:53 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
787, 'BANG', 4, 'BANGLADESHI', 'BANGLADESH', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
788, 'CPVR', 4, 'CAPE VERDE', 'CAPE VERDE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
789, 'CAYM', 4, 'CAYMAN', 'CAYMAN ISLANDS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
790, 'EQUA GUIN', 4, 'GUINEAN', 'EQUATORIAL GUINEA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
791, 'FR GUIN', NULL, 'FRENCH', 'FRENCH GUIANA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
792, 'F.W.I.', NULL, 'FRENCH', 'FRENCH WEST INDIES', 'N', 'Y', NULL, 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
793, 'MALD', 4, 'MALDIVE ISLANDS', 'MALDIVE ISLANDS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
794, 'P.W.A.', 4, 'PORTUGUESE WEST AFRICAN', 'PORTUGUESE WEST AFRICA', 'N', 'Y', '3'
, 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
796, 'SAMO US', 4, 'SAMOAN', 'SAMOA (US)', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:33:54 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
797, 'SIKK', 4, 'SIKKIMI', 'SIKKIM', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
798, 'NAMB', 4, 'NAMIBIAN', 'NAMIBIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:33:55 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
799, 'TUR AND CAI', 4, 'TURKA AND CAICOS ISLANDS', 'TURKS AND CAICOS ISLANDS', 'N', 'Y'
, '3', 'SGAS',  TO_Date( '05/01/2008 05:34:22 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
800, 'VIRG US', NULL, 'AMERICAN', 'VIRGIN I (US)', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:22 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
801, 'ANTA', 4, 'BRITISH', 'ANTARCTICA (BRITISH)', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:22 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
802, 'GUIN BIS', 4, 'GUINEA BISSAUN', 'GUINEA BISSAU', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:22 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
803, 'S.T AND P', 4, 'SAO TOME AND PRINCIPE', 'SAO TOME AND PRINCIPE', 'N', 'Y', '3', 'SGAS'
,  TO_Date( '05/01/2008 05:34:37 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
804, 'COM', 4, 'COMOROS', 'COMOROS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
805, 'NAUR', 4, 'NAURAN', 'NAURU', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
821, 'MAYO', 4, 'MAYOTTIAN', 'MAYOTTE', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
822, 'F.O.T.', NULL, 'FRENCH', 'FRENCH O/SEAS TERRITORIES (NEC)', 'N', 'Y', NULL, 'SGAS'
,  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
824, 'ANGL', 4, 'ANGUILLAN', 'ANGUILLA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
825, 'MON', 4, 'MONACAN', 'MONACO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
826, 'SAN MAR', 4, 'SAN MARINO', 'SAN MARINO', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:38 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
828, 'GREE AND FAR', 4, 'GREENLANDER/FAROE', 'GREENLAND AND FAROE', 'N', 'Y', '3', 'SGAS'
,  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
831, 'ESTO', 3, 'ESTONIAN', 'ESTONIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
832, 'LATV', 3, 'LATVIAN', 'LATVIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
833, 'LITH', 3, 'LITHUANIAN', 'LITHUANIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
834, 'CROA', 4, 'CROATIAN', 'CROATIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
835, 'SLO', 4, 'SLOVENIAN', 'SLOVENIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:45 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
836, 'ARMN', 3, 'ARMENIAN', 'ARMENIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
837, 'AZER', 3, 'AZERBAIJANI', 'THE AZERBAIJANI REPUBLIC', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
838, 'BELR', 3, 'BELARUSSIAN', 'BELARUS', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
839, 'KAZA', 4, 'KAZAKH', 'KAZAKHSTAN', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
840, 'KYRG', 4, 'KYRGYZSTANI', 'KYRGYZSTAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
841, 'MOLD', 3, 'MOLDOVAN', 'MOLDOVA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
842, 'RUSS', 3, 'RUSSIAN', 'RUSSIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
843, 'TAJI', 4, 'TAJIK', 'TAJIKISTAN', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
844, 'TURM', 4, 'TURKMAN', 'TURKMENISTAN', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
845, 'UKR', 3, 'UKRANIAN', 'UKRAINE', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
846, 'UZBE', 4, 'UZBEKISTAN', 'UZBEKISTAN', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
847, 'GEOR', 3, 'GEORGIAN', 'GEORGIA', 'N', 'Y', '2', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
848, 'BOSN', 4, 'BOSNIAN', 'BOSNIA AND HERZEGOVINA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
849, 'CZEC', 4, 'CZECH', 'CZECH REPUBLIC', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
850, 'SLOV', 4, 'SLOVAKIAN', 'SLOVAKIA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
851, 'ST OF ERIT', 4, 'ERITREAN', 'THE STATE OF ERITREA', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO COUNTRY ( COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, SKELETON,
EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
900, 'EGY', 4, 'EGYPTIAN', 'EGYPT', 'N', 'Y', '3', 'SGAS',  TO_Date( '05/01/2008 05:34:47 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
COMMIT;
