ALTER TABLE SGAS.COURSE_CHANGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE SGAS.COURSE_CHANGE CASCADE CONSTRAINTS;

CREATE TABLE SGAS.COURSE_CHANGE
(
  COURSE_CHANGE_ID  NUMBER(10),
  STUD_REF_NO       NUMBER(10),
  CHANGE_DATE       DATE,
  INST_CODE         VARCHAR2(15 BYTE),
  CRSE_ID           NUMBER(9),
  CRSE_NAME         VARCHAR2(150 BYTE),
  SCHEME_TYPE       VARCHAR2(3 BYTE),
  CRSE_YEAR_NO      NUMBER(2),
  OTHER_CRSE        VARCHAR2(150 BYTE),
  OLD_INST_CODE     VARCHAR2(15 BYTE),
  OLD_CRSE_ID       NUMBER(9),
  OLD_CRSE_NAME     VARCHAR2(150 BYTE),
  OLD_SCHEME_TYPE   VARCHAR2(1 BYTE),
  OLD_CRSE_YEAR_NO  NUMBER(2),
  WITHDRAW          VARCHAR2(1 BYTE),
  WITHDRAW_DATE     DATE,
  WITHDRAW_REASON   VARCHAR2(1024 BYTE),
  CREATED_DATE      DATE                        DEFAULT SYSDATE,
  SESSION_CODE      NUMBER(4),
  OBJECT_ID         VARCHAR2(44),
  PROCESS_ID        VARCHAR2(64 BYTE),
  WORK_QUEUE        VARCHAR2(100 BYTE)
)
TABLESPACE STEPS_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SGAS.COURSE_CHANGE_IND1 ON SGAS.COURSE_CHANGE
(STUD_REF_NO)
LOGGING
TABLESPACE STEPS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SGAS.COURSE_CHANGE_PK ON SGAS.COURSE_CHANGE
(COURSE_CHANGE_ID)
LOGGING
TABLESPACE STEPS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER SGAS.COURSE_CHANGE_SET_SESSION_CODE
BEFORE INSERT
ON SGAS.COURSE_CHANGE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
sessionCode NUMBER;
coursechangeid NUMBER;

BEGIN    
  sessionCode := 0;
  SELECT CVAL INTO sessionCode FROM CONFIG_DATA WHERE ITEM_NAME = 'CURRENT_SESSION';
  select  COURSE_CHANGE_ID_SEQ.NEXTVAL into coursechangeid from dual;
  :NEW.SESSION_CODE := sessionCode;
  :NEW.COURSE_CHANGE_ID := coursechangeid;
  :NEW.WORK_QUEUE := PK_STEPS_COURSE_CHANGE.GET_WORK_QUEUE (:NEW.STUD_REF_NO,
                                                :NEW.SESSION_CODE);
                                                    
  EXCEPTION
  WHEN OTHERS THEN
  RAISE;
END COURSE_CHANGE_SET_SESSION_CODE;
/


CREATE OR REPLACE TRIGGER SGAS.COURSE_CHANGE_EDM_INSERTS
AFTER INSERT
ON SGAS.COURSE_CHANGE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
DECLARE
  documentTypeCode varchar(100);
BEGIN
  
  documentTypeCode := 
    CASE NVL(:NEW.WITHDRAW,'N')
      WHEN 'N' THEN 'COURSE_CHANGE'
      ELSE 'WITHDRAW_COURSE'
    END;
  
  Insert into EDM.EDM_COMPLETE (OBJECT_ID, BATCH_TYPE_CODE, STUD_REF_NO, SCAN_DATE, PROC_ERROR, URGENT)
  Values (concat(CONCAT('CC',:NEW.STUD_REF_NO),:NEW.COURSE_CHANGE_ID), 98, :NEW.STUD_REF_NO, :NEW.CREATED_DATE, 'N', 'N');
    
  Insert into EDM.EDM_TEMP (OBJECT_ID, SESSION_CODE, DOCUMENT_TYPE_CODE, DOCUMENT_NAME, DOCUMENT_TYPE_COUNT, ATTACHMENT_TYPE_CODE)
  Values (concat(CONCAT('CC',:NEW.STUD_REF_NO),:NEW.COURSE_CHANGE_ID), :NEW.SESSION_CODE, documentTypeCode, CONCAT(:NEW.STUD_REF_NO,'-COURSE_CHANGE_MSG'), 1, 'PDF');

  EXCEPTION
  WHEN OTHERS THEN
    -- Consider logging the error and then re-raise
    RAISE;
END COURSE_CHANGE_EDM_INSERTS;
/


ALTER TABLE SGAS.COURSE_CHANGE ADD (
  CHECK ( (CHANGE_DATE IS NULL AND WITHDRAW_DATE IS NOT NULL) OR
          (CHANGE_DATE IS NOT NULL AND WITHDRAW_DATE IS  NULL))
  ENABLE VALIDATE,
  CONSTRAINT COURSE_CHANGE_PK
  PRIMARY KEY
  (COURSE_CHANGE_ID)
  USING INDEX SGAS.COURSE_CHANGE_PK
  ENABLE VALIDATE);