CREATE TABLE SGAS.COURSE_CHANGE_REPORT
(
  STUD_REF_NO        NUMBER(10),
  TASK_ID            NUMBER(10),
  TASK_CREATED_DATE  DATE,
  LAST_UPDATED_DATE  DATE,
  WORK_QUEUE         VARCHAR2(100 BYTE),
  ACCEPTED_BY        VARCHAR2(40 BYTE),
  LAST_ACCEPTED_BY   VARCHAR2(40 BYTE),
  PDF_VIEWED         VARCHAR2(1 BYTE),
  TYPE               VARCHAR2(15 BYTE),
  SCHEME_TYPE        VARCHAR2(3 BYTE),
  NEW_INST_CODE      VARCHAR2(15 BYTE),
  NEW_CRSE_ID        NUMBER(9),
  NEW_CRSE_NAME      VARCHAR2(150 BYTE),
  NEW_CRSE_YEAR_NO   NUMBER(2),
  OLD_INST_CODE      VARCHAR2(15 BYTE),
  OLD_CRSE_ID        NUMBER(9),
  OLD_CRSE_NAME      VARCHAR2(150 BYTE),
  OLD_CRSE_YEAR_NO   NUMBER(2),
  WITHDRAW_DATE      DATE,
  WITHDRAW_REASON    VARCHAR2(1024 BYTE),
  TIMESTAMP			 VARCHAR2(100)
)
TABLESPACE STEPS_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;