-- ED8_RUN_LOG.sql
-- Description: Table holding all ED8 Run Info
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      05.07.12    A Bowman (SAAS)         Initial Version.
-- 1.1      19.07.12    A Bowman (SAAS)         Amended size of error_msg column  
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

ALTER TABLE sgas.ED8_RUN_LOG
 DROP PRIMARY KEY CASCADE
/
DROP TABLE sgas.ED8_RUN_LOG CASCADE CONSTRAINTS PURGE;
--
-- ED8_RUN_LOG  (Table) 
--
CREATE TABLE SGAS.ED8_RUN_LOG
(
  ED8_RUN_LOG_ID  NUMBER(4)                     NOT NULL,
  FILENAME        VARCHAR2(100)                 NOT NULL,
  SESSION_CODE    NUMBER(4)                     NOT NULL,
  MODE_TYPE       VARCHAR2(1)                   NOT NULL,
  SCHEME_TYPE     VARCHAR2(1),
  SUCCESS         VARCHAR2(100)                 NOT NULL,
  START_TIME      DATE                          NOT NULL,
  FINISH_TIME     DATE                          NOT NULL,
  ERROR_MSG       VARCHAR2(1024),
  NO_OF_RECORDS   NUMBER(10)                    NOT NULL
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE SGAS.ED8_RUN_LOG ADD (
  CONSTRAINT ED8_RUN_LOG_PK
 PRIMARY KEY
 (ED8_RUN_LOG_ID)
    USING INDEX 
    TABLESPACE STEPS_INDEX);


CREATE INDEX SGAS.ED8_FILENAME ON SGAS.ED8_RUN_LOG
(FILENAME)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;


DROP SEQUENCE SGAS.ED8_RUN_LOG_ID_SEQ;

CREATE SEQUENCE SGAS.ED8_RUN_LOG_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER SGAS.TRIG_ED8_RUN_LOG_ID_SEQ
   BEFORE INSERT
   ON SGAS.ED8_RUN_LOG    FOR EACH ROW
BEGIN
   SELECT ED8_RUN_LOG_ID_SEQ.NEXTVAL
     INTO :NEW.ED8_RUN_LOG_ID
     FROM DUAL;
END;
SHOW ERRORS;
