-- EMAIL_MPHONE_CHANGE_EXC.sql
-- Description: This table is used to store any email_mphone exceptions and the data
-- 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      02.06.11    A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

DROP TABLE SGAS.EMAIL_MPHONE_CHANGE_EXC CASCADE CONSTRAINTS;

CREATE TABLE SGAS.EMAIL_MPHONE_CHANGE_EXC
(
  STUD_REF_NO  NUMBER(10)                       NOT NULL,
  CHANGE_DATE  DATE                             NOT NULL,
  NEW_EMAIL    VARCHAR2(80 BYTE),
  NEW_PHONE    VARCHAR2(14 BYTE),
  SQLCODE      VARCHAR2(25 BYTE),
  SQLERRM      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX SGAS.EMAIL_MPHONE_CHANGE_EXC_IDX1 ON SGAS.EMAIL_MPHONE_CHANGE_EXC
(STUD_REF_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          16K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


DROP PUBLIC SYNONYM EMAIL_MPHONE_CHANGE_EXC;

CREATE PUBLIC SYNONYM EMAIL_MPHONE_CHANGE_EXC FOR SGAS.EMAIL_MPHONE_CHANGE_EXC;

