--ALTER TABLE SGAS.INST_GROUPING DROP PRIMARY KEY CASCADE;

--DROP TABLE SGAS.INST_GROUPING CASCADE CONSTRAINTS;

CREATE TABLE SGAS.INST_GROUPING
(
  INST_CODE                 VARCHAR2(5 BYTE)    NOT NULL,
  PARENT_INST_CODE          VARCHAR2(5 BYTE)    NOT NULL,
  PARENT_INST_DISPLAY_NAME  VARCHAR2(100 BYTE)  NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SGAS.INST_GROUPING_PK ON SGAS.INST_GROUPING
(INST_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SGAS.INST_GROUPING ADD (
  CONSTRAINT INST_GROUPING_PK
  PRIMARY KEY
  (INST_CODE)
  USING INDEX SGAS.INST_GROUPING_PK
  ENABLE VALIDATE);

ALTER TABLE SGAS.INST_GROUPING ADD (
  CONSTRAINT INST_GROUPING_R01 
  FOREIGN KEY (INST_CODE) 
  REFERENCES SGAS.INST (INST_CODE)
  ENABLE VALIDATE,
  CONSTRAINT INST_GROUPING_R02 
  FOREIGN KEY (PARENT_INST_CODE) 
  REFERENCES SGAS.INST (INST_CODE)
  ENABLE VALIDATE);
