-- PAYMENT_RETURNS.sql
-- Description: This table is used to hold details of returned payments
-- 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      23.09.11    P.Hughes (SAAS)         Initial Version.
-- 1.1      26.09.11    A.Bowman (SAAS)         Added bells and whistles to script
-- 
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $


DROP TABLE SGAS.PAYMENT_RETURNS CASCADE CONSTRAINTS PURGE;

--
-- PAYMENT_RETURNS  (Table) 
--

CREATE TABLE SGAS.PAYMENT_RETURNS
(
  PAYMENT_INSTALMENT_ID          NUMBER(10) NOT NULL,
  PAYMENT_RETURNS_LOAD_ID        NUMBER(10) NOT NULL,
  PAYEE_PAYMENT_ID               NUMBER(10) NOT NULL,
  RETURNS_BATCH_REF              VARCHAR2(7 BYTE) NOT NULL,
  RETURNS_DATE                   DATE NOT NULL,
  RETURNS_AMOUNT                 NUMBER(9,2) NOT NULL,
  RECEIPT_TYPE_ID                VARCHAR2(1 BYTE) NOT NULL,
  RETURNS_STATUS                 VARCHAR2(1 BYTE) NOT NULL,
  PROCESS_DATE                   DATE NOT NULL,
  ENTITY                         VARCHAR2(3 BYTE) DEFAULT '600' NOT NULL,
  COST_CENTRE                    VARCHAR2(6 BYTE) NOT NULL,
  ACCOUNT                        VARCHAR2(8 BYTE) NOT NULL,
  PROGRAMME                      VARCHAR2(3 BYTE) NOT NULL,
  SUB_TYPE                       VARCHAR2(2 BYTE) NOT NULL,
  PAYMENT_METHOD                 VARCHAR2(1 BYTE) NOT NULL,
  NOTES                          VARCHAR2(100),
  LAST_UPDATED_BY                VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON                DATE               DEFAULT Sysdate NOT NULL)


TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3400K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURNS IS 'table is used to hold details of returned payments';

CREATE UNIQUE INDEX PAYMENT_RETURNS_PK ON sgas.PAYMENT_RETURNS
(PAYMENT_INSTALMENT_ID)
LOGGING
TABLESPACE users
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64 k
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE sgas.PAYMENT_RETURNS ADD (
  CONSTRAINT PAYMENT_RETURNS_PK
 PRIMARY KEY
 (PAYMENT_INSTALMENT_ID)
    USING INDEX
    TABLESPACE users
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64 k
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F1_PAYRTN 
 FOREIGN KEY (PAYMENT_INSTALMENT_ID) 
 REFERENCES SGAS.PAYMENT_INSTALMENT (PAYMENT_INSTALMENT_ID));

ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F2_PAYRTN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES SGAS.PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));

ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F3_PAYRTN 
 FOREIGN KEY (RETURNS_BATCH_REF) 
 REFERENCES SGAS.RETURN_BATCHES (RETURNS_BATCH_REF));

ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F4_PAYRTN 
 FOREIGN KEY (RECEIPT_TYPE_ID) 
 REFERENCES PAYMENT_RETURN_TYPE (PAYMENT_RETURN_TYPE_ID));

-- 
-- Create public synonym 
-- 

DROP PUBLIC SYNONYM PAYMENT_RETURNS
/
CREATE PUBLIC SYNONYM PAYMENT_RETURNS FOR sgas.PAYMENT_RETURNS
/

