-- PAYMENT_RETURNS_UNIDENTIFIED.sql
-- Description: This table is used to hold any unidentified returned payments
-- 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      23.09.11    P.Hughes (SAAS)         Initial Version.
-- 1.1      26.09.11    A.Bowman (SAAS)         Added bells and whistles to script
-- 1.2      17.07.12    A.Bowman (SAAS)         Amended table to create new pk and fk
-- 
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $


DROP TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED CASCADE CONSTRAINTS PURGE
/

--
-- PAYMENT_RETURNS_UNIDENTIFIED  (Table) 
--

CREATE TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED
(
  PAY_RETNS_UNIDENTIFIED_ID NUMBER(10) NOT NULL,
  PAYMENT_RETURNS_LOAD_ID        NUMBER(10) NOT NULL, 
  RETURNS_DATE                   DATE NOT NULL,
  RETURNS_AMOUNT                 NUMBER(9,2) NOT NULL,
  RECEIPT_TYPE_ID                VARCHAR2(1 BYTE) NOT NULL,
  RETURNS_STATUS                 VARCHAR2(1 BYTE) NOT NULL,
  PROCESS_DATE                   DATE NOT NULL,
  PAYEE_PAYMENT_ID               NUMBER(10),
  PAYEE_ID                       NUMBER(10),
  PAYEE_REF_ID                   NUMBER(10),
  IDENTIFIED_RETURN              VARCHAR2(1 BYTE) NOT NULL,
  NOTES                          VARCHAR2(100),
  LAST_UPDATED_BY                VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON                DATE               DEFAULT Sysdate NOT NULL  


)
TABLESPACE STEPS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3400K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED IS 'table is used to hold any unidentified returned payments';

CREATE UNIQUE INDEX PAYMENT_RTNS_UN_PK ON SGAS.PAYMENT_RETURNS_UNIDENTIFIED
(PAY_RETNS_UNIDENTIFIED_ID)
LOGGING
TABLESPACE STEPS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED ADD (
  CONSTRAINT PAYMENT_RTNS_UN_PK
 PRIMARY KEY
 (PAY_RETNS_UNIDENTIFIED_ID)
    USING INDEX 
    TABLESPACE STEPS_INDEX
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED ADD (
  CONSTRAINT F1_PAYRTNUN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES SGAS.PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));

-- 
-- Create public synonym 
-- 

DROP PUBLIC SYNONYM PAYMENT_RETURNS_UNIDENTIFIED
/
CREATE PUBLIC SYNONYM PAYMENT_RETURNS_UNIDENTIFIED FOR sgas.PAYMENT_RETURNS_UNIDENTIFIED
/

DROP SEQUENCE SGAS.PAY_RETNS_UNI_ID_SEQ;              
               
CREATE SEQUENCE SGAS.PAY_RETNS_UNI_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER SGAS.TRIG_PAY_RETNS_UNI_SEQ 
   BEFORE INSERT
   ON SGAS.PAYMENT_RETURNS_UNIDENTIFIED
   FOR EACH ROW
BEGIN
   SELECT PAY_RETNS_UNI_ID_SEQ.NEXTVAL
     INTO :NEW.PAY_RETNS_UNIDENTIFIED_ID
     FROM DUAL;
END;