CREATE TABLE SGAS.PG_ED_PSYCH
(
  INST_CODE           VARCHAR2(5 BYTE)          NOT NULL,
  CRSE_CODE           VARCHAR2(4 BYTE)          NOT NULL,
  IS_LOCAL_AUTHORITY  VARCHAR2(1 BYTE)          DEFAULT 'N'                   NOT NULL
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SGAS.PG_ED_PSYCH_PK ON SGAS.PG_ED_PSYCH
(INST_CODE, CRSE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE SGAS.PG_ED_PSYCH ADD (
  CHECK (IS_LOCAL_AUTHORITY IN ('N','Y'))
  ENABLE VALIDATE,
  CONSTRAINT PG_ED_PSYCH_PK
  PRIMARY KEY
  (INST_CODE, CRSE_CODE)
  USING INDEX SGAS.PG_ED_PSYCH_PK
  ENABLE VALIDATE);
