/******************************************************************************
TABLE NAME: RESIDENCE_CATEGORY        
DESCRIPTION: Table holding details of a students residence status

MODIFICATION HISTORY:
Ver        Date        Author           Description
---------  ----------  ---------------  ------------------------------------
1.0        21.02.2011  A.Bowman         Initial Version

CONFIGURATION MANAGEMENT:
-------------------------
$HeadURL:  $ 
$Author:  $ 
$Date:  $ 
$Revision:  $ 
 
*******************************************************************************/
 
DROP TABLE SGAS.RESIDENCE_CATEGORY CASCADE CONSTRAINTS PURGE
/

--
-- RESIDENCE_CATEGORY  (Table) 
--

CREATE TABLE SGAS.RESIDENCE_CATEGORY
( RESIDENCE_CATEGORY_ID               VARCHAR2(1) NOT NULL,
  RESIDENCE_STATUS           VARCHAR2(20)
)

TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RESIDENCE_CATEGORY_PK ON SGAS.RESIDENCE_CATEGORY
(RESIDENCE_CATEGORY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SGAS.RESIDENCE_CATEGORY ADD (
  CONSTRAINT RESIDENCE_CATEGORY_PK
 PRIMARY KEY
 (RESIDENCE_CATEGORY_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

-- 
-- Create public synonym: 
-- 

DROP PUBLIC SYNONYM RESIDENCE_CATEGORY
/

CREATE PUBLIC SYNONYM RESIDENCE_CATEGORY FOR SGAS.RESIDENCE_CATEGORY
/

DELETE FROM RESIDENCE_CATEGORY;

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('1','MIGRANT WORKER');

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('2','ASYLUM SEEKER');

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('3','REFUGEE');

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('4','BIDAR');

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('5','GHURKA');

INSERT INTO SGAS.RESIDENCE_CATEGORY (
   RESIDENCE_CATEGORY_ID, RESIDENCE_STATUS) 
VALUES ('6','IRAQI DIRECT ENTRY');

COMMIT;