--DROP TABLE SGAS.REWORK_TASKS CASCADE CONSTRAINTS;

CREATE TABLE SGAS.REWORK_TASKS
(
  CUSTOM_TASK_ID  VARCHAR2(255 BYTE),
  TASK_ID         NUMBER(10)                    NOT NULL,
  EMAIL           VARCHAR2(255 BYTE),
  CREATION_DATE   DATE,
  PROCESS_BPM     VARCHAR2(25 BYTE)             NOT NULL
)
TABLESPACE STEPS_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
