DROP TABLE SGAS.SHORT_APP_STUD_INFO CASCADE CONSTRAINTS PURGE;

CREATE TABLE SGAS.SHORT_APP_STUD_INFO
(
  STUD_REF_NO            NUMBER(10),
  SESSION_CODE           NUMBER(4),
  AWARD                  VARCHAR2(1 BYTE),
  LOAN_GIVEN             VARCHAR2(1 BYTE),
  DEARING                VARCHAR2(1 BYTE),
  INST_CODE              VARCHAR2(5 BYTE),
  CRSE_CODE              VARCHAR2(4 BYTE),
  CRSE_YEAR_NO           NUMBER(2),
  LOAN_ELIGIBILITY_ONLY  VARCHAR2(1 BYTE),
  LOAN_REQUEST           NUMBER(7,2),
  MAX_LOAN_REQUESTED     VARCHAR2(1 BYTE),
  FEES_CALCULATED        VARCHAR2(1 BYTE)       DEFAULT 'N'
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SGAS.P_SASI_PK ON SGAS.SHORT_APP_STUD_INFO
(STUD_REF_NO, SESSION_CODE)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;


DROP PUBLIC SYNONYM SHORT_APP_STUD_INFO;

CREATE PUBLIC SYNONYM SHORT_APP_STUD_INFO FOR SGAS.SHORT_APP_STUD_INFO;


GRANT DELETE, INSERT, SELECT, UPDATE ON  SGAS.SHORT_APP_STUD_INFO TO PUBLIC;