DROP TABLE SGAS.SHORT_APP_INST_CRSE CASCADE CONSTRAINTS PURGE;

CREATE TABLE SGAS.SHORT_APP_INST_CRSE
(
  INST_CODE     VARCHAR2(5 BYTE),
  CRSE_CODE     VARCHAR2(4 BYTE),
  SESSION_CODE  NUMBER(4)
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SGAS.P_SAIC ON SGAS.SHORT_APP_INST_CRSE
(INST_CODE, CRSE_CODE, SESSION_CODE)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;


GRANT DELETE, INSERT, SELECT, UPDATE ON  SGAS.SHORT_APP_INST_CRSE TO PUBLIC;