DROP TABLE SGAS.SHWAP CASCADE CONSTRAINTS PURGE;

CREATE TABLE SGAS.SHWAP
(
  TYPE_OF_SUPPORT_IND           VARCHAR2(1 BYTE),
  STUD_REF_NO                   VARCHAR2(10 BYTE),
  STUD_SLC_REF_NO               VARCHAR2(10 BYTE),
  STUD_TITLE                    VARCHAR2(8 BYTE),
  STUD_FORENAMES                VARCHAR2(25 BYTE),
  STUD_SURNAME                  VARCHAR2(25 BYTE),
  STUD_HOUSE_NO_NAME            VARCHAR2(32 BYTE),
  STUD_ADDR_L1                  VARCHAR2(65 BYTE),
  STUD_ADDR_L2                  VARCHAR2(65 BYTE),
  STUD_ADDR_L3                  VARCHAR2(32 BYTE),
  STUD_ADDR_L4                  VARCHAR2(32 BYTE),
  STUD_POST_CODE                VARCHAR2(8 BYTE),
  STUD_TEL_NO                   VARCHAR2(15 BYTE),
  STUD_ADDR_CORR_FLAG           VARCHAR2(1 BYTE),
  STUD_NINO                     VARCHAR2(10 BYTE),
  STUD_INST_NAME                VARCHAR2(50 BYTE),
  STUD_CRSE_NAME                VARCHAR2(50 BYTE),
  STUD_CRSE_YEAR_NO             VARCHAR2(2 BYTE),
  STUD_SORT_CODE                VARCHAR2(6 BYTE),
  STUD_ACCOUNT_NO               VARCHAR2(18 BYTE),
  STUD_LOCATION_INDICATOR       VARCHAR2(20 BYTE),
  STUD_CONT1_RELATION           VARCHAR2(15 BYTE),
  STUD_CONT1_NAME               VARCHAR2(60 BYTE),
  STUD_CONT1_ADDR_L1            VARCHAR2(60 BYTE),
  STUD_CONT1_ADDR_L2            VARCHAR2(60 BYTE),
  STUD_CONT1_ADDR_L3            VARCHAR2(60 BYTE),
  STUD_CONT1_POSTCODE           VARCHAR2(8 BYTE),
  STUD_CONT1_TEL_NO             VARCHAR2(14 BYTE),
  STUD_CONT2_NAME               VARCHAR2(60 BYTE),
  STUD_CONT2_ADDR_L1            VARCHAR2(60 BYTE),
  STUD_CONT2_ADDR_L2            VARCHAR2(60 BYTE),
  STUD_CONT2_ADDR_L3            VARCHAR2(60 BYTE),
  STUD_CONT2_POSTCODE           VARCHAR2(8 BYTE),
  STUD_CONT2_TEL_NO             VARCHAR2(14 BYTE),
  AWARD                         VARCHAR2(1 BYTE),
  LOAN_GIVEN                    VARCHAR2(1 BYTE),
  DEARING                       VARCHAR2(1 BYTE),
  CRSE_YEAR_NO                  NUMBER(2),
  LOAN_ELIGIBILITY_ONLY         VARCHAR2(1 BYTE),
  LOAN_REQUEST                  NUMBER(7,2),
  MAX_LOAN_REQUESTED            VARCHAR2(1 BYTE),
  FEES_CALCULATED               VARCHAR2(1 BYTE),
  INST_CODE                     VARCHAR2(5 BYTE),
  CRSE_CODE                     VARCHAR2(4 BYTE),
  STUD_CONT1_RELATION_DESCRIPT  VARCHAR2(51 BYTE),
  STUD_WEB_USER_ID              VARCHAR2(25 BYTE),
  STUD_EMAIL_ADDR               VARCHAR2(80 BYTE),
  INVALID_EMAIL_DATE            DATE,
  COMPLETED_SHWAP_APP           VARCHAR2(5 BYTE) DEFAULT '0',
  STUD_CRSE_YEAR_ID             NUMBER(9),
  STUD_SESSION_ID               NUMBER(9)
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SGAS.P_SHAP_PK ON SGAS.SHWAP
(STUD_REF_NO)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;