/* Formatted on 10/10/2013 09:18:07 (QP5 v5.215.12089.38647) */
-- SLC_CUSTOMER_RECORD_STATUSES.sql
-- Description:
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      25.09.13    A.Bowman (SAAS)         Initial Version.
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

ALTER TABLE SGAS.SLC_CUSTOMER_RECORD_STATUSES DROP PRIMARY KEY CASCADE;

DROP TABLE SGAS.SLC_CUSTOMER_RECORD_STATUSES CASCADE CONSTRAINTS;

CREATE TABLE SGAS.SLC_CUSTOMER_RECORD_STATUSES
(
   CUSTOMER_RECORD_STATUS_CODE      NUMBER (2) NOT NULL,
   CUSTOMER_RECORD_STATUS_LABEL     VARCHAR2 (15 BYTE),
   CUSTOMER_RECORD_STATUS_DESCRIP   VARCHAR2 (100 BYTE)
)
TABLESPACE USERS
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.SLC_CUSTOMER_RECORD_STATUSES IS
	'Reference table describing the various statuses related to the SLC Customer Record File functionality';

COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD_STATUSES.CUSTOMER_RECORD_STATUS_CODE IS
   'Status code for a customer record';

COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD_STATUSES.CUSTOMER_RECORD_STATUS_LABEL IS
   'Status label';

COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD_STATUSES.CUSTOMER_RECORD_STATUS_DESCRIP IS
   'Status code description';


CREATE UNIQUE INDEX SGAS.SLC_CUSTOMER_RECORD_STATUSESPK
   ON SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE)
   LOGGING
   TABLESPACE USERS
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT)
   NOPARALLEL;


ALTER TABLE SGAS.SLC_CUSTOMER_RECORD_STATUSES ADD (
  CONSTRAINT SLC_CUSTOMER_RECORD_STATUSESPK
 PRIMARY KEY
 (CUSTOMER_RECORD_STATUS_CODE)
    USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

INSERT
  INTO SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE,
                                          CUSTOMER_RECORD_STATUS_LABEL,
                                          CUSTOMER_RECORD_STATUS_DESCRIP)
VALUES (
          0,
          'SENT',
          'Status code indicating that the Customer Record has passed all SAAS validation checks to send to SLC');

INSERT
  INTO SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE,
                                          CUSTOMER_RECORD_STATUS_LABEL,
                                          CUSTOMER_RECORD_STATUS_DESCRIP)
VALUES (
          1,
          'SUCCESSFUL',
          'Status code indicating that the Customer Record was successfully sent / loaded at SLC');

INSERT
  INTO SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE,
                                          CUSTOMER_RECORD_STATUS_LABEL,
                                          CUSTOMER_RECORD_STATUS_DESCRIP)
VALUES (
          2,
          'SAAS FAILED',
          'Status code indicating that the Customer Record has failed SAAS validation');

INSERT
  INTO SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE,
                                          CUSTOMER_RECORD_STATUS_LABEL,
                                          CUSTOMER_RECORD_STATUS_DESCRIP)
VALUES (
          3,
          'SLC FAILED',
          'Status code indicating that the Customer Record has failed SLC validation checks');

INSERT
  INTO SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE,
                                          CUSTOMER_RECORD_STATUS_LABEL,
                                          CUSTOMER_RECORD_STATUS_DESCRIP)
VALUES (
          4,
          'CORRECTED',
          'Status code indicating that the Customer Record has been corrected, ready for sending to SLC');

COMMIT;

ALTER TABLE SGAS.SLC_CR_BATCHES ADD (
  CONSTRAINT F1_SLCRB
 FOREIGN KEY (SLC_FILE_STATUS)
 REFERENCES SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE));
 
ALTER TABLE SGAS.SLC_CR_DATA ADD (
  CONSTRAINT F3_SLCRD
 FOREIGN KEY (SLC_CR_STATUS)
 REFERENCES SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE));

ALTER TABLE SGAS.SLC_CUSTOMER_RECORD ADD (
  CONSTRAINT F2_SLCCR
 FOREIGN KEY (SLC_CR_STATUS)
 REFERENCES SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE));
 
ALTER TABLE SGAS.SLC_CR_ERRORS ADD (
  CONSTRAINT F2_SLCE
 FOREIGN KEY (RECORD_ERROR_TYPE)
 REFERENCES SGAS.SLC_CUSTOMER_RECORD_STATUSES (CUSTOMER_RECORD_STATUS_CODE));