/* Formatted on 10/10/2013 09:17:40 (QP5 v5.215.12089.38647) */
-- SLC_CUST_REC.sql
-- Description:
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      25.09.13    A.Bowman (SAAS)         Initial Version.
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

ALTER TABLE SGAS.SLC_CUSTOMER_RECORD DROP PRIMARY KEY CASCADE;

DROP TABLE SGAS.SLC_CUSTOMER_RECORD CASCADE CONSTRAINTS;

CREATE TABLE SGAS.SLC_CUSTOMER_RECORD (
   STUD_CRSE_YEAR_ID NUMBER (9) NOT NULL,
   SLC_SSN VARCHAR2 (13) NOT NULL,
   SLC_CR_STATUS NUMBER (2),
   SLC_CR_SENT VARCHAR2 (1) DEFAULT NULL,
   SLC_CR_SENT_DATE DATE,
   SLC_CR_TYPE VARCHAR2 (1) DEFAULT 'S' CHECK (SLC_CR_TYPE IN ('S', 'H')),
   HANDOVER_DATE DATE DEFAULT NULL,
   REQUEST_ARREARS VARCHAR2 (1),
   ARREARS_REQ_DATE DATE,
   ARREARS_REQ_SENT VARCHAR2 (1),
   ARREARS_REQ_SENT_DATE DATE)
TABLESPACE users
PCTUSED 0
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
NOMONITORING;

COMMENT ON TABLE SGAS.SLC_CUSTOMER_RECORD IS
	'Record the status of individual customer records sent to SLC from the StEPS database';
	
COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD.SLC_CR_SENT_DATE IS
   'The date the Customer Record was last sent to SLC';

COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD.ARREARS_REQ_DATE IS
   'Set when arrears request selected by the Case Worker';

COMMENT ON COLUMN SGAS.SLC_CUSTOMER_RECORD.ARREARS_REQ_SENT_DATE IS
   'Date arrears request sent to SLC';


ALTER TABLE SGAS.SLC_CUSTOMER_RECORD ADD (
  CONSTRAINT SLC_CUSTOMER_RECORD_PK
 PRIMARY KEY
 (STUD_CRSE_YEAR_ID));

ALTER TABLE SGAS.SLC_CUSTOMER_RECORD ADD (
  CONSTRAINT F1_SLCCR
 FOREIGN KEY (STUD_CRSE_YEAR_ID)
 REFERENCES SGAS.STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));
