-- STUD_INCOME_TYPE.sql
-- Description: Table holding the different Stud Income Types used in StEPS
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      09.11.12    A Bowman (SAAS)         Initial Version. 
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

ALTER TABLE sgas.STUD_INCOME_TYPE
 DROP PRIMARY KEY CASCADE
/
DROP TABLE sgas.STUD_INCOME_TYPE CASCADE CONSTRAINTS PURGE;
--
-- STUD_INCOME_TYPE  (Table) 
--
CREATE TABLE SGAS.STUD_INCOME_TYPE
(
  INCOME_TYPE_ID   NUMBER(10)                     NOT NULL,
  DESCRIPTION     VARCHAR2(50)                  NOT NULL,
  LAST_UPDATED_BY            VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON            DATE               DEFAULT Sysdate NOT NULL
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE STUD_INCOME_TYPE IS 'Table holding all the different stud income types used in StEPS';

ALTER TABLE SGAS.STUD_INCOME_TYPE ADD (
  CONSTRAINT STUD_INCOME_TYPE_PK
 PRIMARY KEY
 (INCOME_TYPE_ID)
    USING INDEX 
    TABLESPACE STEPS_INDEX);


--
-- INSERT DATA
--

INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
0, 'NONE', 'SGAS', sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
1, 'BENEFITS', 'SGAS',  sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
2, 'WORKING TAX CREDITS', 'SGAS',  sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
3, 'TRUST INCOME', 'SGAS',  sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
4, 'PENSION INCOME', 'SGAS',  sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
5, 'PROPERTY INCOME', 'SGAS',  sysdate); 
INSERT INTO STUD_INCOME_TYPE ( INCOME_TYPE_ID, DESCRIPTION, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
6, 'OTHER INCOME', 'SGAS',  sysdate); 

COMMIT;


