
-- View on GRASS Reference Data
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                                  Desc.
--            28.02.08   S Durkin (Sopra UK)         Initial Version.
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/views/STUD_RATES.sql $
-- $Author: $
-- $Date: 2009-07-02 10:37:39 +0100 (Thu, 02 Jul 2009) $
-- $Revision: 3342 $


DROP VIEW SGAS.stud_rates
/

--
-- STUD_RATES  (View) 
--
CREATE VIEW SGAS.stud_rates
(
    STUD_AWARD_TYPE, START_DATE, DESCRIPT, COND_STMTS_DESCRIPT, STUD_INCOME_ALLOW, SPONS_INCOME_ALLOW, DPND_CHILD_ALLOW, DPND_1STCHILD, DPND_ADULT, DPND_CHILD_11_TO_15, DPND_CHILD_16_TO_17, DPND_CHILD_18_PLUS, DPND_CHILD_LESS_11, DPND_DEDUCT_AMOUNT, DISAB_BASIC_MAX, DISAB_NON_MED_MAX, DISAB_EQUIP_MAX, DOMEST_ASSIST, END_DATE, MSA_AGED_26, MSA_AGED_27, MSA_AGED_28, MSA_AGED_29_PLUS, MAINT_HOME, MAINT_ELSE, MAINT_LONDON, NLB_MAINT_HOME, NLB_MAINT_ELSE, NLB_MAINT_LONDON, WK_MAINT_LOND, WK_MAINT_ELSE, WK_MAINT_HOME, MAX_OX_MAINT_ELSE, MAX_OX_MAINT_HOME, MAX_MAINT_ELSE, MAX_MAINT_HOME, MAX_MAINT_LOND, STD_CRSE_LEN, STD_OX_CRSE_LEN, MAX_CRSE_LEN, OPTIONAL_ALLOWANCE, CAT1, CAT2, CAT3, CAT4, WK_CAT1, WK_CAT2, WK_CAT3, WK_CAT4, MAX_CAT1, MAX_CAT2, MAX_CAT3, MAX_CAT4, TWO_HOMES_ALLOW, SNB_INIT_EXP, MAX_YEARS, ADVANCE_CODE, JOINT_APPL_ALLOW, PARENTCHILD_ALLOW, TRUST_INCOME, STUD_PENSION_ALLOW, TRAV_ELEMENT, MIN_TERM_AWARD, SNB_UNDER_26, SNB_GRAD, SNB_26_PLUS, SNB_SING_PAR, GROSS_BANK_INTEREST, GROSS_DIVIDEND_INC, GROSS_OTHER_INC, GROSS_LIFE_DEDUCT, MAX_SUPERANN_PC, MAX_ANNUITY_PC, MAX_LIFE_INS, DPND_ADULT_ALLOW, YDA_1STCHILD, YDA_2NDCHILD, PT_LOAN_AMOUNT, PT_INCOME_THRESHOLD, PT_SPOUSE_DISREGARD, PT_FIRST_CHILD_DISREGARD, PT_OTHER_CHILD_DISREGARD, SMG_AGE3_LESS_THAN_11, SMG_AGE_11, X_LOAN, YSB, LONE_CHILDCARE_GRANT, DSA_FEE_MAX, NMSB_LONE_CHILDCARE_GRANT, SOSB, SNB_SINGLE_RATE
)
AS
(
 SELECT
    STUD_AWARD_TYPE, START_DATE, DESCRIPT, COND_STMTS_DESCRIPT, STUD_INCOME_ALLOW, SPONS_INCOME_ALLOW, DPND_CHILD_ALLOW, DPND_1STCHILD, DPND_ADULT, DPND_CHILD_11_TO_15, DPND_CHILD_16_TO_17, DPND_CHILD_18_PLUS, DPND_CHILD_LESS_11, DPND_DEDUCT_AMOUNT, DISAB_BASIC_MAX, DISAB_NON_MED_MAX, DISAB_EQUIP_MAX, DOMEST_ASSIST, END_DATE, MSA_AGED_26, MSA_AGED_27, MSA_AGED_28, MSA_AGED_29_PLUS, MAINT_HOME, MAINT_ELSE, MAINT_LONDON, NLB_MAINT_HOME, NLB_MAINT_ELSE, NLB_MAINT_LONDON, WK_MAINT_LOND, WK_MAINT_ELSE, WK_MAINT_HOME, MAX_OX_MAINT_ELSE, MAX_OX_MAINT_HOME, MAX_MAINT_ELSE, MAX_MAINT_HOME, MAX_MAINT_LOND, STD_CRSE_LEN, STD_OX_CRSE_LEN, MAX_CRSE_LEN, OPTIONAL_ALLOWANCE, CAT1, CAT2, CAT3, CAT4, WK_CAT1, WK_CAT2, WK_CAT3, WK_CAT4, MAX_CAT1, MAX_CAT2, MAX_CAT3, MAX_CAT4, TWO_HOMES_ALLOW, SNB_INIT_EXP, MAX_YEARS, ADVANCE_CODE, JOINT_APPL_ALLOW, PARENTCHILD_ALLOW, TRUST_INCOME, STUD_PENSION_ALLOW, TRAV_ELEMENT, MIN_TERM_AWARD, SNB_UNDER_26, SNB_GRAD, SNB_26_PLUS, SNB_SING_PAR, GROSS_BANK_INTEREST, GROSS_DIVIDEND_INC, GROSS_OTHER_INC, GROSS_LIFE_DEDUCT, MAX_SUPERANN_PC, MAX_ANNUITY_PC, MAX_LIFE_INS, DPND_ADULT_ALLOW, YDA_1STCHILD, YDA_2NDCHILD, PT_LOAN_AMOUNT, PT_INCOME_THRESHOLD, PT_SPOUSE_DISREGARD, PT_FIRST_CHILD_DISREGARD, PT_OTHER_CHILD_DISREGARD, SMG_AGE3_LESS_THAN_11, SMG_AGE_11, X_LOAN, YSB, LONE_CHILDCARE_GRANT, DSA_FEE_MAX, NMSB_LONE_CHILDCARE_GRANT, SOSB, SNB_SINGLE_RATE
 FROM stud_rates@GRASS
)
/
