CREATE OR REPLACE VIEW SGAS.TEMP_STUD
(S_STUD_REF_NO, G_STUD_REF_NO, S_ABROAD, G_ABROAD, S_DOB, 
 G_DOB, S_TITLE, G_TITLE, S_INITIALS, G_INITIALS, 
 S_FORENAMES, G_FORENAMES, S_SURNAME, G_SURNAME, S_SEX, 
 G_SEX, S_BIRTH_COUNTRY_CODE, G_BIRTH_COUNTRY_CODE, S_RESIDENCE_COUNTRY_CODE, G_RESIDENCE_COUNTRY_CODE, 
 S_NATION_COUNTRY_CODE, G_NATION_COUNTRY_CODE, S_UCAS_NO, G_UCAS_NO, S_MARITAL_STATUS, 
 G_MARITAL_STATUS, S_MARRIAGE_DATE, G_MARRIAGE_DATE, S_SUSPEND_PAYMENT, G_SUSPEND_PAYMENT, 
 S_BIRTH_FORENAMES, G_BIRTH_FORENAMES, S_BIRTH_SURNAME, G_BIRTH_SURNAME, S_DISTRICT_BIRTH_CERT_ISSUED, 
 G_DISTRICT_BIRTH_CERT_ISSUED, S_ADDR_CORR_FLAG, G_ADDR_CORR_FLAG, S_BANKRUPT_FLAG, G_BANKRUPT_FLAG, 
 S_TRAVEL_METHOD, G_TRAVEL_METHOD, S_BANK_VALIDATE, G_BANK_VALIDATE, S_MOBILE_TEL_NO, 
 G_MOBILE_TEL_NO, S_EMAIL_ADDR, G_EMAIL_ADDR, S_PAYMENT_METHOD, G_PAYMENT_METHOD, 
 S_NI_NO, G_NI_NO, S_ACCOUNT_NO, G_ACCOUNT_NO, S_SORT_CODE, 
 G_SORT_CODE)
AS 
select st.stud_ref_no as s_stud_ref_no,
       stg.stud_ref_no as g_stud_ref_no, 
       nvl(st.abroad,0) as s_abroad, 
       stg.abroad as g_abroad,
       st.dob as s_dob,
       stg.dob as g_dob,
       st.title as s_title,
       stg.title as g_title,
       st.initials as s_initials,
       stg.initials as g_initials,
       st.forenames as s_forenames,
       stg.forenames as g_forenames,
       st.surname as s_surname,
       stg.surname as g_surname,
       st.sex as s_sex,
       stg.sex as g_sex,
       st.birth_country_code as s_birth_country_code, 
       stg.birth_country_code as g_birth_country_code,
       st.residence_country_code as s_residence_country_code,
       stg.residence_country_code as g_residence_country_code,
       st.nation_country_code as s_nation_country_code,
       stg.nation_country_code as g_nation_country_code,
       st.ucas_no as s_ucas_no,
       stg.ucas_no as g_ucas_no,
       st.marital_status as s_marital_status,
       stg.marital_status as g_marital_status,
       st.marriage_date as s_marriage_date,
       stg.marriage_date as g_marriage_date,
       st.suspend_payment as s_suspend_payment,
       stg.suspend_payment as g_suspend_payment,
       st.birth_forenames as s_birth_forenames,
       stg.birth_forenames as g_birth_forenames,
       st.birth_surname as s_birth_surname,
       stg.birth_surname as g_birth_surname,
       st.district_birth_cert_issued as s_district_birth_cert_issued,
       stg.district_birth_cert_issued as g_district_birth_cert_issued,
       st.addr_corr_flag as s_addr_corr_flag,
       stg.addr_corr_flag as g_addr_corr_flag,
       st.bankrupt_flag as s_bankrupt_flag,
       stg.bankrupt_flag as g_bankrupt_flag,
       st.travel_method as s_travel_method,
       stg.travel_method as g_travel_method,
       st.bank_validate as s_bank_validate,
       stg.bank_validate as g_bank_validate,
       st.mobile_tel_no as s_mobile_tel_no,
       stg.mobile_tel_no as g_mobile_tel_no,
       st.email_addr as s_email_addr,
       stg.email_addr as g_email_addr,
       st.payment_method as s_payment_method, 
       stg.payment_method as g_payment_method,
       st.ni_no as s_ni_no,
       stg.ni_no as g_ni_no,
       st.account_no as s_account_no,
       stg.account_no as g_account_no,
       st.sort_code as s_sort_code,
       stg.sort_code as g_sort_code 
from stud st, stud@grass stg
where st.stud_ref_no = stg.stud_ref_no
/


GRANT SELECT ON  SGAS.TEMP_STUD TO SGAS_EUL
/
