BEGIN 
  SYS.DBMS_JOB.REMOVE(517);
COMMIT;
END;
/

DECLARE
  X NUMBER;
BEGIN
  SYS.DBMS_JOB.SUBMIT
  ( job       => X 
   ,what      => 'EXECUTE IMMEDIATE ''TRUNCATE TABLE CORRESPONDENCE_TASKS_ALL''; 
    INSERT INTO CORRESPONDENCE_TASKS_ALL
   (SELECT DISTINCT
       TT.CUSTOM_TASK_ID,
       TT.TASK_ID,
       TT.TASK_NAME,
       TRUNC (PID.CREATION_DATE) CREATION_DATE,
       THINGS.ITEMNAME AS WORKQUEUE, 
       TO_CHAR ( TIMESTAMP ''1970-01-01 00:00:00'' + NUMTODSINTERVAL (TT.LAST_UPDATED_DATE / 1000, ''second''), ''DD/MM/YYYY'') AS LAST_ACTIONED,
       TU.EMAIL,
       SCY.INST_NAME
  FROM T_TASK@WMSTEPS.WORLD TT,
       PROCESS_INSTANCE_DATA PID,
       WMPROCESSSTEP@WMSTEPS.WORLD PRO,
       TBLUSER@WMSTEPS.WORLD TU,
       STUD_CRSE_YEAR SCY,
       TBLTHINGNAME@WMSTEPS.WORLD THINGS
 WHERE TT.STATUS = 1
       AND THINGS.IDTHING = TT.ASSIGNED_TO
       AND TT.PRT_PROCESS_MODEL_ID = ''StEPSProcessCorrespondenceBPM/Correspondence''
       AND TT.ACCEPTED_BY = TU.IDTHING(+)
       AND TT.PRT_PROCESS_INSTANCE_ID = PID.PROCESS_ID
       AND PID.PROCESS_BPM = ''CorrespondenceBPM''
       AND PID.PROCESS_ID = PRO.INSTANCEID
       AND PID.STUD_REF_NO = SCY.STUD_REF_NO
       AND SCY.LATEST_CRSE_IND = ''Y''
       AND SCY.SESSION_CODE = (SELECT MAX (SCY1.SESSION_CODE)
                                 FROM STUD_CRSE_YEAR SCY1
                                WHERE SCY1.STUD_REF_NO = SCY.STUD_REF_NO)          
       AND PRO.AUDITTIMESTAMP = (SELECT MAX (PRO1.AUDITTIMESTAMP)
                                   FROM WMPROCESSSTEP@WMSTEPS.WORLD PRO1
                                  WHERE PRO1.INSTANCEID = PRO.INSTANCEID))
   ORDER BY CREATION_DATE; 
   COMMIT; '
   ,next_date => to_date('03/05/2017 12:15:00','dd/mm/yyyy hh24:mi:ss')
   ,interval  => 'TRUNC(SYSDATE)+ 1 + 12/24 + 15/1440 '
   ,no_parse  => FALSE
  );
  SYS.DBMS_OUTPUT.PUT_LINE('Job Number is: ' || to_char(x));
COMMIT;
END;
/
