DROP VIEW SGAS.V_ESTRANGED_STUD_REPORT;

DROP VIEW SGAS.V_AWARDS_REPORT;

BEGIN 
  SYS.DBMS_JOB.REMOVE(367);
COMMIT;
END;

DROP PACKAGE SGAS.PK_STEPS_ESTRANGED_STUD_REPORT;

DROP TABLE SGAS.ESTRANGED_STUD_REPORT CASCADE CONSTRAINTS;



