ALTER TABLE EDM.RAW_DATA 
    ADD (BEN1_EMAIL_ADDR VARCHAR2(80),
        BEN2_EMAIL_ADDR VARCHAR2(80)
        );
        
ALTER TABLE EDM.RAW_DATA$TEST_DATA
    ADD (BEN1_EMAIL_ADDR VARCHAR2(80),
        BEN2_EMAIL_ADDR VARCHAR2(80)
        );        