DROP INDEX ADI_PAYMENT_AUD_PK
/

--
-- ADI_PAYMENT_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX ADI_PAYMENT_AUD_PK ON ADI_PAYMENT_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ADI_PAYMENT_PK
/

--
-- ADI_PAYMENT_PK  (Index) 
--
CREATE UNIQUE INDEX ADI_PAYMENT_PK ON ADI_PAYMENT
(ADI_PAYMENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_EVIDENCEPK
/

--
-- APPLICATION_EVIDENCEPK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_EVIDENCEPK ON APPLICATION_EVIDENCE
(EVID_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_EVIDENCE_AUD_PK
/

--
-- APPLICATION_EVIDENCE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_EVIDENCE_AUD_PK ON APPLICATION_EVIDENCE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_REJECTION_AUD_PK
/

--
-- APPLICATION_REJECTION_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_REJECTION_AUD_PK ON APPLICATION_REJECTION_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_REJECTION_PK
/

--
-- APPLICATION_REJECTION_PK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_REJECTION_PK ON APPLICATION_REJECTION
(APPLICATION_REJECTION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_STATUS_AUD_PK
/

--
-- APPLICATION_STATUS_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_STATUS_AUD_PK ON APPLICATION_STATUS_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX APPLICATION_STATUS_PK
/

--
-- APPLICATION_STATUS_PK  (Index) 
--
CREATE UNIQUE INDEX APPLICATION_STATUS_PK ON APPLICATION_STATUS
(APPLICATION_STATUS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX BACS_RUN_AUD_PK
/

--
-- BACS_RUN_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX BACS_RUN_AUD_PK ON BACS_RUN_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX BACS_RUN_PK
/

--
-- BACS_RUN_PK  (Index) 
--
CREATE UNIQUE INDEX BACS_RUN_PK ON BACS_RUN
(BACS_RUN_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX CASEWORKER_NOTE_AUD_PK
/

--
-- CASEWORKER_NOTE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX CASEWORKER_NOTE_AUD_PK ON CASEWORKER_NOTE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX CASEWORKER_NOTE_PK
/

--
-- CASEWORKER_NOTE_PK  (Index) 
--
CREATE UNIQUE INDEX CASEWORKER_NOTE_PK ON CASEWORKER_NOTE
(CW_NOTE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX COURSE_LEVEL_AUD_PK
/

--
-- COURSE_LEVEL_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX COURSE_LEVEL_AUD_PK ON COURSE_LEVEL_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX COURSE_LEVEL_PK
/

--
-- COURSE_LEVEL_PK  (Index) 
--
CREATE UNIQUE INDEX COURSE_LEVEL_PK ON COURSE_LEVEL
(COURSE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX COURSE_TYPE_AUD_PK
/

--
-- COURSE_TYPE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX COURSE_TYPE_AUD_PK ON COURSE_TYPE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX COURSE_TYPE_PK
/

--
-- COURSE_TYPE_PK  (Index) 
--
CREATE UNIQUE INDEX COURSE_TYPE_PK ON COURSE_TYPE
(COURSE_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX DOCUMENT_REGISTER_AUD_PK
/

--
-- DOCUMENT_REGISTER_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX DOCUMENT_REGISTER_AUD_PK ON DOCUMENT_REGISTER_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_CONFIG_DATA_AUD_PK
/

--
-- ILA500_CONFIG_DATA_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX ILA500_CONFIG_DATA_AUD_PK ON ILA500_CONFIG_DATA_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_EDM_IMAGES_AUD_PK
/

--
-- ILA500_EDM_IMAGES_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX ILA500_EDM_IMAGES_AUD_PK ON ILA500_EDM_IMAGES_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_EDM_IMAGES_IDX01
/

--
-- ILA500_EDM_IMAGES_IDX01  (Index) 
--
CREATE INDEX ILA500_EDM_IMAGES_IDX01 ON ILA500_EDM_IMAGES
(LEARNER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          504K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_EDM_IMAGES_UK01
/

--
-- ILA500_EDM_IMAGES_UK01  (Index) 
--
CREATE UNIQUE INDEX ILA500_EDM_IMAGES_UK01 ON ILA500_EDM_IMAGES
(RESCAN_REQUEST_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          504K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_QA_DATA_AUD_PK
/

--
-- ILA500_QA_DATA_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX ILA500_QA_DATA_AUD_PK ON ILA500_QA_DATA_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_RULE_AUD_PK
/

--
-- ILA500_RULE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX ILA500_RULE_AUD_PK ON ILA500_RULE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX ILA500_RULE_PK
/

--
-- ILA500_RULE_PK  (Index) 
--
CREATE UNIQUE INDEX ILA500_RULE_PK ON ILA500_RULE
(RULE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_APPLICATION_AUD_PK
/

--
-- LEARNER_APPLICATION_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_APPLICATION_AUD_PK ON LEARNER_APPLICATION_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_APPLICATION_PK
/

--
-- LEARNER_APPLICATION_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_APPLICATION_PK ON LEARNER_APPLICATION
(LEARNER_APPLICATION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_AUD_PK
/

--
-- LEARNER_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_AUD_PK ON LEARNER_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_DUPLICATE_AUD_PK
/

--
-- LEARNER_DUPLICATE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_DUPLICATE_AUD_PK ON LEARNER_DUPLICATE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_DUPLICATE_PK
/

--
-- LEARNER_DUPLICATE_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_DUPLICATE_PK ON LEARNER_DUPLICATE
(LEARNER_DUPLICATE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_PAYMENT_AUD_PK
/

--
-- LEARNER_PAYMENT_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_PAYMENT_AUD_PK ON LEARNER_PAYMENT_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_PAYMENT_PK
/

--
-- LEARNER_PAYMENT_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_PAYMENT_PK ON LEARNER_PAYMENT
(LEARNER_PAYMENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX LEARNER_PK
/

--
-- LEARNER_PK  (Index) 
--
CREATE UNIQUE INDEX LEARNER_PK ON LEARNER
(LEARNER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX NOTE_TYPE_AUD_PK
/

--
-- NOTE_TYPE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX NOTE_TYPE_AUD_PK ON NOTE_TYPE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX NOTE_TYPE_PK
/

--
-- NOTE_TYPE_PK  (Index) 
--
CREATE UNIQUE INDEX NOTE_TYPE_PK ON NOTE_TYPE
(NOTE_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PAYMENT_STATUS_AUD_PK
/

--
-- PAYMENT_STATUS_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX PAYMENT_STATUS_AUD_PK ON PAYMENT_STATUS_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PAYMENT_STATUS_PK
/

--
-- PAYMENT_STATUS_PK  (Index) 
--
CREATE UNIQUE INDEX PAYMENT_STATUS_PK ON PAYMENT_STATUS
(PAYMENT_STATUS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_AUD_PK
/

--
-- PROVIDER_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_AUD_PK ON PROVIDER_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_PAYMENT_AUD_PK
/

--
-- PROVIDER_PAYMENT_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_PAYMENT_AUD_PK ON PROVIDER_PAYMENT_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_PAYMENT_PK
/

--
-- PROVIDER_PAYMENT_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_PAYMENT_PK ON PROVIDER_PAYMENT
(PROVIDER_PAYMENT_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_PK
/

--
-- PROVIDER_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_PK ON PROVIDER
(PROVIDER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_STATUS_AUD_PK
/

--
-- PROVIDER_STATUS_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_STATUS_AUD_PK ON PROVIDER_STATUS_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_STATUS_PK
/

--
-- PROVIDER_STATUS_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_STATUS_PK ON PROVIDER_STATUS
(PROV_STATUS_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_TYPE_AUD_PK
/

--
-- PROVIDER_TYPE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_TYPE_AUD_PK ON PROVIDER_TYPE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX PROVIDER_TYPE_PK
/

--
-- PROVIDER_TYPE_PK  (Index) 
--
CREATE UNIQUE INDEX PROVIDER_TYPE_PK ON PROVIDER_TYPE
(PROV_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX P_CL
/

--
-- P_CL  (Index) 
--
CREATE UNIQUE INDEX P_CL ON ILA500_CASEWORKER_LOCKS
(LEARNER_ID, CASEWORKER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX P_COD
/

--
-- P_COD  (Index) 
--
CREATE UNIQUE INDEX P_COD ON ILA500_CONFIG_DATA
(ITEM_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX P_DOCUMENT_REGISTER
/

--
-- P_DOCUMENT_REGISTER  (Index) 
--
CREATE UNIQUE INDEX P_DOCUMENT_REGISTER ON DOCUMENT_REGISTER
(DOC_REG_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX P_SHELL_LETTER
/

--
-- P_SHELL_LETTER  (Index) 
--
CREATE UNIQUE INDEX P_SHELL_LETTER ON SHELL_LETTER
(DOC_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX P_SQD
/

--
-- P_SQD  (Index) 
--
CREATE UNIQUE INDEX P_SQD ON ILA500_QA_DATA
(USERNAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX REPORT_HISTORY_AUD_PK
/

--
-- REPORT_HISTORY_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX REPORT_HISTORY_AUD_PK ON REPORT_HISTORY_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX REPORT_HISTORY_PK
/

--
-- REPORT_HISTORY_PK  (Index) 
--
CREATE UNIQUE INDEX REPORT_HISTORY_PK ON REPORT_HISTORY
(REP_HIST_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX S1_APR
/

--
-- S1_APR  (Index) 
--
CREATE INDEX S1_APR ON DOCUMENT_REGISTER
(PRIMARY_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX S2_APR
/

--
-- S2_APR  (Index) 
--
CREATE INDEX S2_APR ON DOCUMENT_REGISTER
(DOCUMENT_TYPE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX SHELL_LETTER_AUD_PK
/

--
-- SHELL_LETTER_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX SHELL_LETTER_AUD_PK ON SHELL_LETTER_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX TITLE_AUD_PK
/

--
-- TITLE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX TITLE_AUD_PK ON TITLE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX TITLE_PK
/

--
-- TITLE_PK  (Index) 
--
CREATE UNIQUE INDEX TITLE_PK ON TITLE
(TITLE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX TRANSACTION_TYPE_AUD_PK
/

--
-- TRANSACTION_TYPE_AUD_PK  (Index) 
--
CREATE UNIQUE INDEX TRANSACTION_TYPE_AUD_PK ON TRANSACTION_TYPE_AUD
(AUD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


DROP INDEX TRANSACTION_TYPE_PK
/

--
-- TRANSACTION_TYPE_PK  (Index) 
--
CREATE UNIQUE INDEX TRANSACTION_TYPE_PK ON TRANSACTION_TYPE
(TRANSACTION_TYPE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/

