-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- CR-OLS-203
-- Materialized View for the Student Enquiry Task Report
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

DROP MATERIALIZED VIEW SGAS.STUD_ENQUIRY_TASK_REPORT;

CREATE MATERIALIZED VIEW SGAS.STUD_ENQUIRY_TASK_REPORT 
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH COMPLETE
AS 
SELECT TT.TASK_ID,
       SE.ENQUIRY_ID,
       SE.STUD_REF_NO,
       TO_DATE( TO_CHAR( ( (FROM_TZ ( CAST ( ( TO_DATE ('19700101000000', 'YYYYMMDDHH24MISS') + NUMTODSINTERVAL (TT.CREATED_DATE / 1000, 'SECOND')) AS TIMESTAMP), 'GMT') AT TIME ZONE 'Europe/London')), 'DD/MM/YYYY HH24:mi:ss'), 'DD/MM/YYYY HH24:mi:ss') AS TASK_CREATED_DATE,
       TO_DATE( TO_CHAR( ( (FROM_TZ ( CAST ( ( TO_DATE ('19700101000000', 'YYYYMMDDHH24MISS') + NUMTODSINTERVAL (TT.LAST_UPDATED_DATE / 1000, 'SECOND')) AS TIMESTAMP), 'GMT') AT TIME ZONE 'Europe/London')), 'DD/MM/YYYY HH24:mi:ss'), 'DD/MM/YYYY HH24:mi:ss') AS LAST_UPDATED_DATE,       
       REF_TABLE_ASSIGNED_TO.ITEMNAME AS ASSIGNED_TO,
       REF_TABLE_ACCEPTED_BY.ITEMNAME AS ACCEPTED_BY,
       REF_TABLE_LAST_ACCEPTED_BY.ITEMNAME AS LAST_ACCEPTED_BY,
       SE.IS_VIEWED,
       SCY.INST_NAME,
       EO.DESCRIPTION AS SUBJECT,
       EO.DESCRIPTION AS SUBJECT_FILTER,
       REF_TABLE_ASSIGNED_TO.ITEMNAME AS ASSIGNED_TO_FILTER
  FROM ( SELECT TASK_ID, STATUS, CREATED_DATE, LAST_UPDATED_DATE, ASSIGNED_TO, ACCEPTED_BY, LAST_ACCEPTED_BY
           FROM T_TASK@WMSTEPS.WORLD ) TT
      LEFT JOIN TBLTHINGNAME@WMSTEPS.WORLD REF_TABLE_ASSIGNED_TO ON TT.ASSIGNED_TO = REF_TABLE_ASSIGNED_TO.IDTHING
      LEFT JOIN TBLTHINGNAME@WMSTEPS.WORLD REF_TABLE_ACCEPTED_BY ON TT.ACCEPTED_BY = REF_TABLE_ACCEPTED_BY.IDTHING
      LEFT JOIN TBLTHINGNAME@WMSTEPS.WORLD REF_TABLE_LAST_ACCEPTED_BY ON TT.LAST_ACCEPTED_BY = REF_TABLE_LAST_ACCEPTED_BY.IDTHING
     INNER JOIN STUD_ENQUIRY_TASK_MAP SETM ON TT.TASK_ID = SETM.TASK_ID
     INNER JOIN STUD_ENQUIRY SE ON SE.ENQUIRY_ID = SETM.ENQUIRY_ID
     INNER JOIN STUD_CRSE_YEAR SCY ON SE.STUD_REF_NO = SCY.STUD_REF_NO
     INNER JOIN ENQUIRY_OPTION EO ON SE.ENQUIRY_OPTION_ID = EO.ENQUIRY_OPTION_ID
 WHERE SCY.LATEST_CRSE_IND = 'Y'
   AND TT.STATUS <> 3
   AND SCY.SESSION_CODE = (SELECT MAX (SCY1.SESSION_CODE)
                                 FROM STUD_CRSE_YEAR SCY1
                                WHERE SCY1.STUD_REF_NO = SCY.STUD_REF_NO)   
 ORDER BY TASK_CREATED_DATE ASC, TASK_ID ASC
/