
CREATE INDEX SGAS.CESB_FLAGS_AUD_IND1 ON SGAS.CESB_FLAGS_AUD
(TABLE_PKEY1, COLUMN_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
COMPUTE STATISTICS;
COMMIT;