-- DROP COLUMNS

ALTER TABLE CAMPUS_AUD DROP (STUD_REF_NO, INST_CODE, SESSION_CODE);

ALTER TABLE CRSE_AUD DROP (STUD_REF_NO, INST_CODE, SESSION_CODE);

ALTER TABLE INST_AUD DROP (STUD_REF_NO, INST_CODE, SESSION_CODE);

ALTER TABLE INST_TERM_AUD DROP (STUD_REF_NO, INST_CODE, SESSION_CODE);

ALTER TABLE CRSE_SESSION_AUD DROP (STUD_REF_NO, INST_CODE);

ALTER TABLE CRSE_TERM_AUD DROP (STUD_REF_NO, INST_CODE);

ALTER TABLE CRSE_YEAR_AUD DROP (STUD_REF_NO, INST_CODE);


-- ADD COLUMNS

ALTER TABLE CRSE_SESSION_AUD ADD CRSE_ID NUMBER(9);

ALTER TABLE CRSE_TERM_AUD ADD CRSE_ID NUMBER(9);
ALTER TABLE CRSE_TERM_AUD ADD CRSE_YEAR_NO NUMBER(2);

ALTER TABLE CRSE_YEAR_AUD ADD CRSE_ID NUMBER(9);
ALTER TABLE CRSE_YEAR_AUD ADD CRSE_YEAR_NO NUMBER(2);

