--CAMPUS AUD

CREATE INDEX SGAS.CAMPUS_AUD_IND2 ON SGAS.CAMPUS_AUD (AUD_DATE);

CREATE INDEX SGAS.CAMPUS_AUD_IND3 ON SGAS.CAMPUS_AUD (USERNAME);


--CRSE_AUD

CREATE INDEX SGAS.CRSE_AUD_IND2 ON SGAS.CRSE_AUD (AUD_DATE);

CREATE INDEX SGAS.CRSE_AUD_IND3 ON SGAS.CRSE_AUD (USERNAME);


--CRSE_SESSION_AUD 

CREATE INDEX SGAS.CRSE_SESSION_AUD_IND2 ON SGAS.CRSE_SESSION_AUD (AUD_DATE);

CREATE INDEX SGAS.CRSE_SESSION_AUD_IND3 ON SGAS.CRSE_SESSION_AUD (USERNAME);

CREATE INDEX SGAS.CRSE_SESSION_AUD_IND4 ON SGAS.CRSE_SESSION_AUD (CRSE_ID, SESSION_CODE);


--CRSE_TERM_AUD 

CREATE INDEX SGAS.CRSE_TERM_AUD_IND2 ON SGAS.CRSE_TERM_AUD (AUD_DATE);

CREATE INDEX SGAS.CRSE_TERM_AUD_IND3 ON SGAS.CRSE_TERM_AUD (USERNAME);

CREATE INDEX SGAS.CRSE_TERM_AUD_IND4 ON SGAS.CRSE_TERM_AUD (CRSE_ID, SESSION_CODE, CRSE_YEAR_NO);


--CRSE_YEAR_AUD 

CREATE INDEX SGAS.CRSE_YEAR_AUD_IND2 ON SGAS.CRSE_YEAR_AUD (AUD_DATE);

CREATE INDEX SGAS.CRSE_YEAR_AUD_IND3 ON SGAS.CRSE_YEAR_AUD (USERNAME);

CREATE INDEX SGAS.CRSE_YEAR_AUD_IND4 ON SGAS.CRSE_YEAR_AUD (CRSE_ID, SESSION_CODE, CRSE_YEAR_NO);


--INST_AUD 

CREATE INDEX SGAS.INST_AUD_IND2 ON SGAS.INST_AUD (AUD_DATE);

CREATE INDEX SGAS.INST_AUD_IND3 ON SGAS.INST_AUD (USERNAME);


--INST_TERM_AUD 

DROP INDEX SGAS.INST_TERM_AUD_IND1;

CREATE INDEX SGAS.INST_TERM_AUD_IND1 ON SGAS.INST_TERM_AUD (TABLE_PKEY1, TABLE_PKEY2, TABLE_PKEY3, COLUMN_NAME);
	
CREATE INDEX SGAS.INST_TERM_AUD_IND2 ON SGAS.INST_TERM_AUD (AUD_DATE);

CREATE INDEX SGAS.INST_TERM_AUD_IND3 ON SGAS.INST_TERM_AUD (USERNAME);



