CREATE OR REPLACE VIEW DE_PM_JOURNAL_LINES
(DPJ_BATCH_REF, DPJ_COST_CENTRE, DPJ_ACCOUNT, DPJ_ACTIVITY, DPJ_JOB, 
 DPJ_ANALYSIS_1_ID, DPJ_ANALYSIS_2_ID, DPJ_ANALYSIS_3_ID, DPJ_ANALYSIS_4_ID, DPJ_ANALYSIS_5_ID, 
 DPJ_ANALYSIS_6_ID, DPJ_SIGN, DPJ_AMOUNT, DPJ_VOLUME, DPJ_UOM, 
 DPJ_DESCRIPTION, DPJ_VAT_AMOUNT, DPJ_VAT_CODE, DPJ_PROGRAMME, DPJ_CURRENCY, 
 DPJ_ENTITY)
AS 
SELECT "DPJ_BATCH_REF","DPJ_COST_CENTRE","DPJ_ACCOUNT","DPJ_ACTIVITY","DPJ_JOB","DPJ_ANALYSIS_1_ID","DPJ_ANALYSIS_2_ID","DPJ_ANALYSIS_3_ID","DPJ_ANALYSIS_4_ID","DPJ_ANALYSIS_5_ID","DPJ_ANALYSIS_6_ID","DPJ_SIGN","DPJ_AMOUNT","DPJ_VOLUME","DPJ_UOM","DPJ_DESCRIPTION","DPJ_VAT_AMOUNT","DPJ_VAT_CODE","DPJ_PROGRAMME","DPJ_CURRENCY","DPJ_ENTITY" FROM SCOAP_JOURNAL_LINES
WHERE dpj_batch_ref IN
(SELECT dpb_batch_ref FROM SCOAP_BATCHES
 WHERE dpb_batch_creation_date > (SYSDATE - 1)
 AND dpb_payment_type = 'C')
UNION
SELECT "DPJ_BATCH_REF","DPJ_COST_CENTRE","DPJ_ACCOUNT","DPJ_ACTIVITY","DPJ_JOB","DPJ_ANALYSIS_1_ID","DPJ_ANALYSIS_2_ID","DPJ_ANALYSIS_3_ID","DPJ_ANALYSIS_4_ID","DPJ_ANALYSIS_5_ID","DPJ_ANALYSIS_6_ID","DPJ_SIGN","DPJ_AMOUNT","DPJ_VOLUME","DPJ_UOM","DPJ_DESCRIPTION","DPJ_VAT_AMOUNT","DPJ_VAT_CODE","DPJ_PROGRAMME","DPJ_CURRENCY","DPJ_ENTITY" FROM SCOAP_JOURNAL_LINES@STEPSSIT.WORLD
WHERE dpj_batch_ref IN
(SELECT dpb_batch_ref FROM SCOAP_BATCHES@STEPSSIT.WORLD
 WHERE dpb_batch_creation_date > (SYSDATE - 1)
 AND dpb_payment_type = 'C');



CREATE PUBLIC SYNONYM DE_PM_JOURNAL_LINES FOR SGAS.DE_PM_JOURNAL_LINES
/


GRANT SELECT ON  SGAS.DE_PM_JOURNAL_LINES TO SCOAP_QUERY
/