DROP TABLE SGAS.ZZ_MASK_TABLE CASCADE CONSTRAINTS;

CREATE TABLE SGAS.ZZ_MASK_TABLE
(
  ORDER_NUMBER  NUMBER,
  SCHEMA_NAME   VARCHAR2(100 BYTE),
  TABLE_NAME    VARCHAR2(100 BYTE),
  STATUS        VARCHAR2(100 BYTE)              DEFAULT 'REQUIRED'
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
