DROP TABLE SGAS.ZZ_MASK_COLUMN CASCADE CONSTRAINTS;

CREATE TABLE SGAS.ZZ_MASK_COLUMN
(
  SCHEMA_NAME          VARCHAR2(100 BYTE),
  TABLE_NAME           VARCHAR2(100 BYTE),
  COLUMN_NAME          VARCHAR2(100 BYTE),
  MASK_NAME            VARCHAR2(100 BYTE),
  ORDER_NUMBER         NUMBER,
  NEW_KEY_TABLE_NAME   VARCHAR2(100 BYTE),
  NEW_KEY_COLUMN_NAME  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
