DROP TABLE SGAS.ZZ_MASK_KEY CASCADE CONSTRAINTS;

CREATE TABLE SGAS.ZZ_MASK_KEY
(
  SCHEMA_NAME   VARCHAR2(100 BYTE),
  TABLE_NAME    VARCHAR2(100 BYTE),
  COLUMN_NAME   VARCHAR2(100 BYTE),
  KEY_VALUE     VARCHAR2(1000 BYTE),
  ORDER_NUMBER  NUMBER,
  STATUS        VARCHAR2(100 BYTE),
  KEY_TYPE      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


Insert into SGAS.ZZ_MASK_KEY
   (SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, KEY_VALUE, ORDER_NUMBER, 
    STATUS, KEY_TYPE)
 Values
   ('SGAS', 'EMPLOYEE', 'USERNAME', 'SGAS.EMPLOYEE_SEQ.NEXTVAL', 1, 
    'REQUIRED', 'SEQUENCE');

COMMIT;
