/* Formatted on 24/10/2017 11:56:07 (QP5 v5.256.13226.35538) */

CREATE MATERIALIZED VIEW GRASS_STUD
   (
   STUD_REF_NO,
   DOB,
   FORENAMES,
   SURNAME,
   NI_NO
   )
   TABLESPACE SAAS_DATA
   LOGGING
   BUILD IMMEDIATE
   REFRESH COMPLETE
AS
   SELECT S.STUD_REF_NO,
          S.DOB,
          S.FORENAMES,
          S.SURNAME,
          S.NI_NO
     FROM STUD@GRASS.WORLD S;


COMMENT ON MATERIALIZED VIEW GRASS_STUD IS
   'snapshot table for snapshot SGAS.GRASS_STUD';

-- Note: Index I_SNAP$_GRASS_STUD will be created automatically
--       by Oracle with the associated materialized view.




CREATE INDEX GRASS_STUD_IND2 ON GRASS_STUD
(DOB)
LOGGING
NOPARALLEL
COMPUTE STATISTICS;

CREATE INDEX GRASS_STUD_IND3 ON GRASS_STUD
(NI_NO)
LOGGING
NOPARALLEL
COMPUTE STATISTICS;

CREATE INDEX GRASS_STUD_IND4 ON GRASS_STUD
(SURNAME, FORENAMES)
LOGGING
NOPARALLEL
COMPUTE STATISTICS;

BEGIN
DBMS_REFRESH.ADD(
name => 'GRASS_REFERENCE_GROUP',
 list => 'GRASS_STUD',
lax => TRUE);
END;
 