CREATE OR REPLACE VIEW SGAS.DE_PM_BATCHES
(DPB_BATCH_REF, DPB_COUNT, DPB_AC_YEAR, DPB_AC_PERIOD, DPB_TOTAL_PAYMENT, 
 DPB_TOTAL_VOLUME, DPB_TOTAL_VAT, DPB_BATCH_CREATION_DATE, DPB_ALLOW_SUSPENSE, DPB_VALIDATE_ONLY, 
 DPB_STATUS, ARC_ID, ARC_RESTORE_DATE, INSTAL_NUMBER, DPB_TYPE)
AS 
SELECT "DPB_BATCH_REF","DPB_COUNT","DPB_AC_YEAR","DPB_AC_PERIOD","DPB_TOTAL_PAYMENT","DPB_TOTAL_VOLUME","DPB_TOTAL_VAT","DPB_BATCH_CREATION_DATE","DPB_ALLOW_SUSPENSE","DPB_VALIDATE_ONLY","DPB_STATUS","ARC_ID","ARC_RESTORE_DATE","INSTAL_NUMBER","DPB_TYPE" FROM SCOAP_BATCHES
WHERE dpb_batch_creation_date > (SYSDATE - 1)
and dpb_payment_type = 'C'
UNION
SELECT "DPB_BATCH_REF","DPB_COUNT","DPB_AC_YEAR","DPB_AC_PERIOD","DPB_TOTAL_PAYMENT","DPB_TOTAL_VOLUME","DPB_TOTAL_VAT","DPB_BATCH_CREATION_DATE","DPB_ALLOW_SUSPENSE","DPB_VALIDATE_ONLY","DPB_STATUS","ARC_ID","ARC_RESTORE_DATE","INSTAL_NUMBER","DPB_TYPE" FROM SCOAP_BATCHES@STEPS.WORLD
WHERE dpb_batch_creation_date > (SYSDATE - 1)
and dpb_payment_type = 'C'
/


CREATE PUBLIC SYNONYM DE_PM_BATCHES FOR SGAS.DE_PM_BATCHES
/


GRANT SELECT ON  SGAS.DE_PM_BATCHES TO SCOAP_QUERY
/
