ALTER TABLE ILA500_CASEWORKER_LOCKS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ILA500_CASEWORKER_LOCKS CASCADE CONSTRAINTS PURGE
/

--
-- ILA500_CASEWORKER_LOCKS  (Table) 
--
CREATE TABLE ILA500_CASEWORKER_LOCKS
(
  REFERENCE_ID   VARCHAR2(10 BYTE) CONSTRAINT NN_ICL_REFERENCE_ID NOT NULL,
  CASEWORKER_ID  VARCHAR2(30 BYTE) CONSTRAINT NN_ICL_CASEWORKER_ID NOT NULL,
  TTL            DATE CONSTRAINT NN_ICL_TTL      NOT NULL,
  REFERENCE_ID_TYPE  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN ILA500_CASEWORKER_LOCKS.REFERENCE_ID IS 'Learner unique identifier'
/

COMMENT ON COLUMN ILA500_CASEWORKER_LOCKS.CASEWORKER_ID IS 'Authenticated user id of the caseworker - must be supplied by application.'
/

COMMENT ON COLUMN ILA500_CASEWORKER_LOCKS.TTL IS 'Time To Live - date and time by which the lock will expire.'
/


--
-- P_CL  (Index) 
--
CREATE UNIQUE INDEX P_ICL ON ILA500_CASEWORKER_LOCKS
(REFERENCE_ID, CASEWORKER_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          104K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table ILA500_CASEWORKER_LOCKS 
-- 
ALTER TABLE ILA500_CASEWORKER_LOCKS ADD (
  CONSTRAINT P_ICL
 PRIMARY KEY
 (REFERENCE_ID, CASEWORKER_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          104K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

