-- Script to bring build into line with the sit environment. Generated from TOAD and modified 
-- on 08/09/2008.
--
-- Notes on the results of running these scripts are included at the bottom of this file as comments. (SD 08/09/08)
--
-- Modification History
-- Date       Author      Ref    Desc
-- 08/09/08 SD                    Initial version. Commented out the webmethods objects. (TODO: Allow these to be generated from webmethods?)
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/synch-build-with-sit.sql $
-- $Author: $
-- $Date: 2008-10-01 14:26:20 +0100 (Wed, 01 Oct 2008) $
-- $Revision: 1237 $
--

Prompt Synonym EDM_COMPLETE_COPY;
CREATE PUBLIC SYNONYM EDM_COMPLETE_COPY FOR EDM.EDM_COMPLETE_COPY;

-- SD > WM code commented out
-- Prompt Trigger WMTBD2KSZH;
-- CREATE OR REPLACE TRIGGER EDM.WMTbd2kszh AFTER INSERT ON EDM.EDM_COMPLETE FOR EACH ROW
-- BEGIN INSERT INTO WMBbd2kszh (OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT, wm_rowid) VALUES (:new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT, WMSbd2kszh.NEXTVAL); END;
-- /
-- SHOW ERRORS;


Prompt Table EDM_TEMP$TEST_DATA;
CREATE TABLE EDM.EDM_TEMP$TEST_DATA
(
  OBJECT_ID             VARCHAR2(44 BYTE),
  SESSION_CODE          NUMBER(4),
  DOCUMENT_TYPE_CODE    VARCHAR2(16 BYTE),
  DOCUMENT_NAME         VARCHAR2(40 BYTE),
  DOCUMENT_TYPE_COUNT   NUMBER(3),
  ATTACHMENT_TYPE_CODE  VARCHAR2(10 BYTE),
  RESCAN_REQUEST_ID     NUMBER(10),
  AUD_ACTION            VARCHAR2(30 BYTE),
  AUD_TIMESTAMP         DATE,
  AUD_USER              VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt Trigger RAW_DATA$AUDIT_TRIG;
CREATE OR REPLACE TRIGGER EDM.RAW_DATA$AUDIT_TRIG
 AFTER INSERT OR UPDATE ON EDM.RAW_DATA FOR EACH ROW
DECLARE 
v_operation VARCHAR2(10) := NULL;
BEGIN
IF INSERTING THEN
   v_operation := 'INS';
ELSIF UPDATING THEN
   v_operation := 'UPD';
END IF;
IF INSERTING OR UPDATING THEN
  INSERT INTO RAW_DATA$TEST_DATA (
    OBJECT_ID, RAW_DATA_ID, BATCH_ID, ENVELOPE_ID, SUPPLEMENTARY_GRANTS, STUD_REF_NO, SCOTTISH_CAND, NI_NO, NI_NO_F, TITLE, SURNAME, FORENAMES, BIRTH_SURNAME, BIRTH_FORENAMES, DOB, DOB_F, DISTRICT_BIRTH_CERT_ISSUED, SEX, MARITAL_STATUS, MARRIAGE_DATE, HOME_HOUSE_NO_NAME, HOME_POST_CODE, HOME_ADDR_L1, HOME_ADDR_L2, HOME_ADDR_L3, HOME_ADDR_L4, HOME_TELE_NO, SORT_CODE, SORT_CODE_F, ACCOUNT_NO, ACCOUNT_NO_F, BIRTH_COUNTRY_CODE, BIRTH_COUNTRY_CODE_F, NATION_COUNTRY_CODE, NATION_COUNTRY_CODE_F, RESIDENCE_COUNTRY_CODE, RESIDENCE_COUNTRY_CODE_F, INST_NAME, INST_NAME_F, INST_CODE, CRSE_NAME, CRSE_NAME_F, CRSE_CODE, CRSE_YEAR_NO, FIRST_DEP_SURNAME, FIRST_DEP_FORENAMES, FIRST_DEP_DOB, FIRST_DEP_DOB_F, FIRST_DEP_REL_TYPE, FIRST_DEP_INCOME_CODE_1, FIRST_DEP_INCOME_CODE_1_F, FIRST_DEP_INCOME_AMOUNT_1, FIRST_DEP_INCOME_AMOUNT_1_F, FIRST_DEP_INCOME_CODE_2, FIRST_DEP_INCOME_CODE_2_F, FIRST_DEP_INCOME_AMOUNT_2, FIRST_DEP_INCOME_AMOUNT_2_F, FIRST_DEP_INCOME_CODE_3, FIRST_DEP_INCOME_CODE_3_F, FIRST_DEP_INCOME_AMOUNT_3, FIRST_DEP_INCOME_AMOUNT_3_F, SEC_DEP_SURNAME, SEC_DEP_FORENAMES, SEC_DEP_DOB, SEC_DEP_DOB_F, SEC_DEP_REL_TYPE, SEC_DEP_INCOME_CODE_1, SEC_DEP_INCOME_CODE_1_F, SEC_DEP_INCOME_AMOUNT_1, SEC_DEP_INCOME_AMOUNT_1_F, SEC_DEP_INCOME_CODE_2, SEC_DEP_INCOME_CODE_2_F, SEC_DEP_INCOME_AMOUNT_2, SEC_DEP_INCOME_AMOUNT_2_F, SEC_DEP_INCOME_CODE_3, SEC_DEP_INCOME_CODE_3_F, SEC_DEP_INCOME_AMOUNT_3, SEC_DEP_INCOME_AMOUNT_3_F, THIRD_DEP_SURNAME, THIRD_DEP_FORENAMES, THIRD_DEP_DOB, THIRD_DEP_DOB_F, THIRD_DEP_REL_TYPE, THIRD_DEP_INCOME_CODE_1, THIRD_DEP_INCOME_CODE_1_F, THIRD_DEP_INCOME_AMOUNT_1, THIRD_DEP_INCOME_AMOUNT_1_F, THIRD_DEP_INCOME_CODE_2, THIRD_DEP_INCOME_CODE_2_F, THIRD_DEP_INCOME_AMOUNT_2, THIRD_DEP_INCOME_AMOUNT_2_F, THIRD_DEP_INCOME_CODE_3, THIRD_DEP_INCOME_CODE_3_F, THIRD_DEP_INCOME_AMOUNT_3, THIRD_DEP_INCOME_AMOUNT_3_F, ADD_DEP_DETAILS, LPCG, TWO_HOMES_ALLOW, VAC_GRANT, NET_INCOME, NET_INCOME_F, PENSION_INCOME, PENSION_INCOME_F, TRUST_INCOME, TRUST_INCOME_F, AWARD_ORG, ANNUAL_VALUE, MAINTENANCE, FEES, LENGTH_OF_SUPPORT, SUPPORT_START_DATE, APP_FORM_SIG, MAX_LOAN_REQUESTED, LOAN_REQUEST, LOAN_REQUEST_F, CONT1_FORENAME, CONT1_SURNAME, CONT1_NAME, CONT1_REL_CODE, CONT1_HOUSE_NO_NM, CONT1_POSTCODE, CONT1_ADDR1, CONT1_ADDR2, CONT1_ADDR3, CONT1_ADDR4, CONT1_TEL_NO, CONT2_FORENAME, CONT2_SURNAME, CONT2_NAME, CONT2_HOUSE_NO_NM, CONT2_POSTCODE, CONT2_ADDR1, CONT2_ADDR2, CONT2_ADDR3, CONT2_ADDR4, CONT2_TEL_NO, BANKRUPT_FLAG, TERM_HOUSE_NO_NAME, TERM_POST_CODE, TERM_ADDR_L1, TERM_ADDR_L2, TERM_ADDR_L3, TERM_ADDR_L4, SLC_CORRES_DEST, LOAN_SIGNATURE, LOAN_DECLARATION_DATE, LOAN_DECLARATION_DATE_F, BEN1_NI_NO, BEN1_NI_NO_F, BEN1_TITLE, BEN1_SURNAME, BEN1_FORENAMES, BEN1_REL_TYPE, BEN1_HOUSE_NO_NAME, BEN1_POSTCODE, BEN1_ADDR1, BEN1_ADDR2, BEN1_ADDR3, BEN1_ADDR4, BEN1_EMP_STATUS, BEN2_NI_NO, BEN2_NI_NO_F, BEN2_TITLE, BEN2_SURNAME, BEN2_FORENAMES, BEN2_REL_TYPE, BEN2_HOUSE_NO_NAME, BEN2_POSTCODE, BEN2_ADDR1, BEN2_ADDR2, BEN2_ADDR3, BEN2_ADDR4, BEN2_EMP_STATUS, JA_CASE, BEN1_PAYE, BEN1_PAYE_F, BEN2_PAYE, BEN2_PAYE_F, BEN1_SELF_EMPLOYMENT, BEN1_SELF_EMPLOYMENT_F, BEN2_SELF_EMPLOYMENT, BEN2_SELF_EMPLOYMENT_F, BEN1_PROPERTY, BEN1_PROPERTY_F, BEN2_PROPERTY, BEN2_PROPERTY_F, BEN1_PENSIONS, BEN1_PENSIONS_F, BEN2_PENSIONS, BEN2_PENSIONS_F, BEN1_BENEFITS, BEN1_BENEFITS_F, BEN2_BENEFITS, BEN2_BENEFITS_F, BEN1_NAT_SAVINGS, BEN1_NAT_SAVINGS_F, BEN2_NAT_SAVINGS, BEN2_NAT_SAVINGS_F, BEN1_INTEREST, BEN1_INTEREST_F, BEN2_INTEREST, BEN2_INTEREST_F, BEN1_DIVIDEND, BEN1_DIVIDEND_F, BEN2_DIVIDEND, BEN2_DIVIDEND_F, BEN1_OTHER_INC, BEN1_OTHER_INC_F, BEN2_OTHER_INC, BEN2_OTHER_INC_F, BEN1_SUPERANN, BEN1_SUPERANN_F, BEN2_SUPERANN, BEN2_SUPERANN_F, BEN1_RAP, BEN1_RAP_F, BEN2_RAP, BEN2_RAP_F, BEN1_OTHER_DED, BEN1_OTHER_DED_F, BEN2_OTHER_DED, BEN2_OTHER_DED_F, BEN1_FIRST_DEP_DOB, BEN1_FIRST_DEP_DOB_F, BEN1_SEC_DEP_DOB, BEN1_SEC_DEP_DOB_F, BEN1_THIRD_DEP_DOB, BEN1_THIRD_DEP_DOB_F, DOMESTIC_HELP, BEN_DEC_SIG, EXTRA_NOTES, OUT_UK, FAST_TRACK, RES_QUERY, ARA_SENT, BIRTH_CERT_FLAG, OFFER_FLAG, REPEAT_YEAR, DATE_APPLIC_RECEIVED, EMP_LOGIN, APP_FORM_SIG_DATE, PGCE, DSA, TOT_TRAV_AMOUNT_CLAIMED, TOT_TRAV_AMOUNT_CLAIMED_F, MOBILE_TEL_NO, HOME_ADDR_MAIL_SORT, BEN1_MAIL_SORT, BEN2_MAIL_SORT, EMAIL_ADDR, WEB_USER_ID, BANK_VALIDATE, EMAIL_ADDR_F, TERM_TIME_RESIDENCE, TERM_TIME_RESIDENCE_F, RELEVANT_DATE, RELEVANT_DATE_F, ORDIN_RES_UK_3_YEARS, ORDIN_RES_UK_3_YEARS_F, ORDIN_RES_SCOT_REL_DATE, ORDIN_RES_SCOT_REL_DATE_F, IN_EDUC_SINCE_LEAVE_SCHOOL, IN_EDUC_SINCE_LEAVE_SCHOOL_F, EU_GRADUATE, EU_GRADUATE_F, STUDY_ABROAD, STUDY_ABROAD_F, PLACEMENT_YEAR, PLACEMENT_YEAR_F, SECONDARY_OR_PRIMARY_ED, SECONDARY_OR_PRIMARY_ED_F, SECONDARY_SUBJECT, SECONDARY_SUBJECT_F, EXEMPT_FROM_PARENT_CONTRIB, EXEMPT_FROM_PARENT_CONTRIB_F, PLAN_TO_WORK_OUTSIDE_UK, PLAN_TO_WORK_OUTSIDE_UK_F, BEN1_FIRST_DEP_LAST_NAME, BEN1_FIRST_DEP_LAST_NAME_F, BEN1_FIRST_DEP_FIRST_NAME, BEN1_FIRST_DEP_FIRST_NAME_F, BEN1_FIRST_DEP_LEAVE_SCHOOL, BEN1_FIRST_DEP_LEAVE_SCHOOL_F, BEN1_SEC_DEP_LAST_NAME, BEN1_SEC_DEP_LAST_NAME_F, BEN1_SEC_DEP_FIRST_NAME, BEN1_SEC_DEP_FIRST_NAME_F, BEN1_SEC_DEP_LEAVE_SCHOOL, BEN1_SEC_DEP_LEAVE_SCHOOL_F, BEN1_THIRD_DEP_LAST_NAME, BEN1_THIRD_DEP_LAST_NAME_F, BEN1_THIRD_DEP_FIRST_NAME, BEN1_THIRD_DEP_FIRST_NAME_F, BEN1_THIRD_DEP_LEAVE_SCHOOL, BEN1_THIRD_DEP_LEAVE_SCHOOL_F, EU_STUDENT, NOS_YEARS_COURSE_TAKES, ORD_RES_SCOTLAND_WEB, ORD_RES_UK_WEB, MAX_FEE_LOAN, FEE_LOAN_AMOUNT, FEE_LOAN_CHARGED_AMOUNT, DEP_GRANT, LPG, MORE_THAN_3_BEN_DEPS
    ,aud_action,aud_timestamp,aud_user)  
  VALUES (
    :new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SUPPLEMENTARY_GRANTS, :new.STUD_REF_NO, :new.SCOTTISH_CAND, :new.NI_NO, :new.NI_NO_F, :new.TITLE, :new.SURNAME, :new.FORENAMES, :new.BIRTH_SURNAME, :new.BIRTH_FORENAMES, :new.DOB, :new.DOB_F, :new.DISTRICT_BIRTH_CERT_ISSUED, :new.SEX, :new.MARITAL_STATUS, :new.MARRIAGE_DATE, :new.HOME_HOUSE_NO_NAME, :new.HOME_POST_CODE, :new.HOME_ADDR_L1, :new.HOME_ADDR_L2, :new.HOME_ADDR_L3, :new.HOME_ADDR_L4, :new.HOME_TELE_NO, :new.SORT_CODE, :new.SORT_CODE_F, :new.ACCOUNT_NO, :new.ACCOUNT_NO_F, :new.BIRTH_COUNTRY_CODE, :new.BIRTH_COUNTRY_CODE_F, :new.NATION_COUNTRY_CODE, :new.NATION_COUNTRY_CODE_F, :new.RESIDENCE_COUNTRY_CODE, :new.RESIDENCE_COUNTRY_CODE_F, :new.INST_NAME, :new.INST_NAME_F, :new.INST_CODE, :new.CRSE_NAME, :new.CRSE_NAME_F, :new.CRSE_CODE, :new.CRSE_YEAR_NO, :new.FIRST_DEP_SURNAME, :new.FIRST_DEP_FORENAMES, :new.FIRST_DEP_DOB, :new.FIRST_DEP_DOB_F, :new.FIRST_DEP_REL_TYPE, :new.FIRST_DEP_INCOME_CODE_1, :new.FIRST_DEP_INCOME_CODE_1_F, :new.FIRST_DEP_INCOME_AMOUNT_1, :new.FIRST_DEP_INCOME_AMOUNT_1_F, :new.FIRST_DEP_INCOME_CODE_2, :new.FIRST_DEP_INCOME_CODE_2_F, :new.FIRST_DEP_INCOME_AMOUNT_2, :new.FIRST_DEP_INCOME_AMOUNT_2_F, :new.FIRST_DEP_INCOME_CODE_3, :new.FIRST_DEP_INCOME_CODE_3_F, :new.FIRST_DEP_INCOME_AMOUNT_3, :new.FIRST_DEP_INCOME_AMOUNT_3_F, :new.SEC_DEP_SURNAME, :new.SEC_DEP_FORENAMES, :new.SEC_DEP_DOB, :new.SEC_DEP_DOB_F, :new.SEC_DEP_REL_TYPE, :new.SEC_DEP_INCOME_CODE_1, :new.SEC_DEP_INCOME_CODE_1_F, :new.SEC_DEP_INCOME_AMOUNT_1, :new.SEC_DEP_INCOME_AMOUNT_1_F, :new.SEC_DEP_INCOME_CODE_2, :new.SEC_DEP_INCOME_CODE_2_F, :new.SEC_DEP_INCOME_AMOUNT_2, :new.SEC_DEP_INCOME_AMOUNT_2_F, :new.SEC_DEP_INCOME_CODE_3, :new.SEC_DEP_INCOME_CODE_3_F, :new.SEC_DEP_INCOME_AMOUNT_3, :new.SEC_DEP_INCOME_AMOUNT_3_F, :new.THIRD_DEP_SURNAME, :new.THIRD_DEP_FORENAMES, :new.THIRD_DEP_DOB, :new.THIRD_DEP_DOB_F, :new.THIRD_DEP_REL_TYPE, :new.THIRD_DEP_INCOME_CODE_1, :new.THIRD_DEP_INCOME_CODE_1_F, :new.THIRD_DEP_INCOME_AMOUNT_1, :new.THIRD_DEP_INCOME_AMOUNT_1_F, :new.THIRD_DEP_INCOME_CODE_2, :new.THIRD_DEP_INCOME_CODE_2_F, :new.THIRD_DEP_INCOME_AMOUNT_2, :new.THIRD_DEP_INCOME_AMOUNT_2_F, :new.THIRD_DEP_INCOME_CODE_3, :new.THIRD_DEP_INCOME_CODE_3_F, :new.THIRD_DEP_INCOME_AMOUNT_3, :new.THIRD_DEP_INCOME_AMOUNT_3_F, :new.ADD_DEP_DETAILS, :new.LPCG, :new.TWO_HOMES_ALLOW, :new.VAC_GRANT, :new.NET_INCOME, :new.NET_INCOME_F, :new.PENSION_INCOME, :new.PENSION_INCOME_F, :new.TRUST_INCOME, :new.TRUST_INCOME_F, :new.AWARD_ORG, :new.ANNUAL_VALUE, :new.MAINTENANCE, :new.FEES, :new.LENGTH_OF_SUPPORT, :new.SUPPORT_START_DATE, :new.APP_FORM_SIG, :new.MAX_LOAN_REQUESTED, :new.LOAN_REQUEST, :new.LOAN_REQUEST_F, :new.CONT1_FORENAME, :new.CONT1_SURNAME, :new.CONT1_NAME, :new.CONT1_REL_CODE, :new.CONT1_HOUSE_NO_NM, :new.CONT1_POSTCODE, :new.CONT1_ADDR1, :new.CONT1_ADDR2, :new.CONT1_ADDR3, :new.CONT1_ADDR4, :new.CONT1_TEL_NO, :new.CONT2_FORENAME, :new.CONT2_SURNAME, :new.CONT2_NAME, :new.CONT2_HOUSE_NO_NM, :new.CONT2_POSTCODE, :new.CONT2_ADDR1, :new.CONT2_ADDR2, :new.CONT2_ADDR3, :new.CONT2_ADDR4, :new.CONT2_TEL_NO, :new.BANKRUPT_FLAG, :new.TERM_HOUSE_NO_NAME, :new.TERM_POST_CODE, :new.TERM_ADDR_L1, :new.TERM_ADDR_L2, :new.TERM_ADDR_L3, :new.TERM_ADDR_L4, :new.SLC_CORRES_DEST, :new.LOAN_SIGNATURE, :new.LOAN_DECLARATION_DATE, :new.LOAN_DECLARATION_DATE_F, :new.BEN1_NI_NO, :new.BEN1_NI_NO_F, :new.BEN1_TITLE, :new.BEN1_SURNAME, :new.BEN1_FORENAMES, :new.BEN1_REL_TYPE, :new.BEN1_HOUSE_NO_NAME, :new.BEN1_POSTCODE, :new.BEN1_ADDR1, :new.BEN1_ADDR2, :new.BEN1_ADDR3, :new.BEN1_ADDR4, :new.BEN1_EMP_STATUS, :new.BEN2_NI_NO, :new.BEN2_NI_NO_F, :new.BEN2_TITLE, :new.BEN2_SURNAME, :new.BEN2_FORENAMES, :new.BEN2_REL_TYPE, :new.BEN2_HOUSE_NO_NAME, :new.BEN2_POSTCODE, :new.BEN2_ADDR1, :new.BEN2_ADDR2, :new.BEN2_ADDR3, :new.BEN2_ADDR4, :new.BEN2_EMP_STATUS, :new.JA_CASE, :new.BEN1_PAYE, :new.BEN1_PAYE_F, :new.BEN2_PAYE, :new.BEN2_PAYE_F, :new.BEN1_SELF_EMPLOYMENT, :new.BEN1_SELF_EMPLOYMENT_F, :new.BEN2_SELF_EMPLOYMENT, :new.BEN2_SELF_EMPLOYMENT_F, :new.BEN1_PROPERTY, :new.BEN1_PROPERTY_F, :new.BEN2_PROPERTY, :new.BEN2_PROPERTY_F, :new.BEN1_PENSIONS, :new.BEN1_PENSIONS_F, :new.BEN2_PENSIONS, :new.BEN2_PENSIONS_F, :new.BEN1_BENEFITS, :new.BEN1_BENEFITS_F, :new.BEN2_BENEFITS, :new.BEN2_BENEFITS_F, :new.BEN1_NAT_SAVINGS, :new.BEN1_NAT_SAVINGS_F, :new.BEN2_NAT_SAVINGS, :new.BEN2_NAT_SAVINGS_F, :new.BEN1_INTEREST, :new.BEN1_INTEREST_F, :new.BEN2_INTEREST, :new.BEN2_INTEREST_F, :new.BEN1_DIVIDEND, :new.BEN1_DIVIDEND_F, :new.BEN2_DIVIDEND, :new.BEN2_DIVIDEND_F, :new.BEN1_OTHER_INC, :new.BEN1_OTHER_INC_F, :new.BEN2_OTHER_INC, :new.BEN2_OTHER_INC_F, :new.BEN1_SUPERANN, :new.BEN1_SUPERANN_F, :new.BEN2_SUPERANN, :new.BEN2_SUPERANN_F, :new.BEN1_RAP, :new.BEN1_RAP_F, :new.BEN2_RAP, :new.BEN2_RAP_F, :new.BEN1_OTHER_DED, :new.BEN1_OTHER_DED_F, :new.BEN2_OTHER_DED, :new.BEN2_OTHER_DED_F, :new.BEN1_FIRST_DEP_DOB, :new.BEN1_FIRST_DEP_DOB_F, :new.BEN1_SEC_DEP_DOB, :new.BEN1_SEC_DEP_DOB_F, :new.BEN1_THIRD_DEP_DOB, :new.BEN1_THIRD_DEP_DOB_F, :new.DOMESTIC_HELP, :new.BEN_DEC_SIG, :new.EXTRA_NOTES, :new.OUT_UK, :new.FAST_TRACK, :new.RES_QUERY, :new.ARA_SENT, :new.BIRTH_CERT_FLAG, :new.OFFER_FLAG, :new.REPEAT_YEAR, :new.DATE_APPLIC_RECEIVED, :new.EMP_LOGIN, :new.APP_FORM_SIG_DATE, :new.PGCE, :new.DSA, :new.TOT_TRAV_AMOUNT_CLAIMED, :new.TOT_TRAV_AMOUNT_CLAIMED_F, :new.MOBILE_TEL_NO, :new.HOME_ADDR_MAIL_SORT, :new.BEN1_MAIL_SORT, :new.BEN2_MAIL_SORT, :new.EMAIL_ADDR, :new.WEB_USER_ID, :new.BANK_VALIDATE, :new.EMAIL_ADDR_F, :new.TERM_TIME_RESIDENCE, :new.TERM_TIME_RESIDENCE_F, :new.RELEVANT_DATE, :new.RELEVANT_DATE_F, :new.ORDIN_RES_UK_3_YEARS, :new.ORDIN_RES_UK_3_YEARS_F, :new.ORDIN_RES_SCOT_REL_DATE, :new.ORDIN_RES_SCOT_REL_DATE_F, :new.IN_EDUC_SINCE_LEAVE_SCHOOL, :new.IN_EDUC_SINCE_LEAVE_SCHOOL_F, :new.EU_GRADUATE, :new.EU_GRADUATE_F, :new.STUDY_ABROAD, :new.STUDY_ABROAD_F, :new.PLACEMENT_YEAR, :new.PLACEMENT_YEAR_F, :new.SECONDARY_OR_PRIMARY_ED, :new.SECONDARY_OR_PRIMARY_ED_F, :new.SECONDARY_SUBJECT, :new.SECONDARY_SUBJECT_F, :new.EXEMPT_FROM_PARENT_CONTRIB, :new.EXEMPT_FROM_PARENT_CONTRIB_F, :new.PLAN_TO_WORK_OUTSIDE_UK, :new.PLAN_TO_WORK_OUTSIDE_UK_F, :new.BEN1_FIRST_DEP_LAST_NAME, :new.BEN1_FIRST_DEP_LAST_NAME_F, :new.BEN1_FIRST_DEP_FIRST_NAME, :new.BEN1_FIRST_DEP_FIRST_NAME_F, :new.BEN1_FIRST_DEP_LEAVE_SCHOOL, :new.BEN1_FIRST_DEP_LEAVE_SCHOOL_F, :new.BEN1_SEC_DEP_LAST_NAME, :new.BEN1_SEC_DEP_LAST_NAME_F, :new.BEN1_SEC_DEP_FIRST_NAME, :new.BEN1_SEC_DEP_FIRST_NAME_F, :new.BEN1_SEC_DEP_LEAVE_SCHOOL, :new.BEN1_SEC_DEP_LEAVE_SCHOOL_F, :new.BEN1_THIRD_DEP_LAST_NAME, :new.BEN1_THIRD_DEP_LAST_NAME_F, :new.BEN1_THIRD_DEP_FIRST_NAME, :new.BEN1_THIRD_DEP_FIRST_NAME_F, :new.BEN1_THIRD_DEP_LEAVE_SCHOOL, :new.BEN1_THIRD_DEP_LEAVE_SCHOOL_F, :new.EU_STUDENT, :new.NOS_YEARS_COURSE_TAKES, :new.ORD_RES_SCOTLAND_WEB, :new.ORD_RES_UK_WEB, :new.MAX_FEE_LOAN, :new.FEE_LOAN_AMOUNT, :new.FEE_LOAN_CHARGED_AMOUNT, :new.DEP_GRANT, :new.LPG, :new.MORE_THAN_3_BEN_DEPS
    ,v_operation,SYSDATE,USER);
END IF; 
END;
/
SHOW ERRORS;

-- SD > WM code commented out
-- Prompt Sequence WMSBD2KSZH;
-- CREATE SEQUENCE EDM.WMSBD2KSZH
  -- START WITH 1361
  -- MAXVALUE 999999999999999999999999999
  -- MINVALUE 1
  -- NOCYCLE
  -- CACHE 20
  -- ORDER;

Prompt Privs on SEQUENCE RAW_DATA_ID_SEQ TO SGAS;
GRANT SELECT ON  EDM.RAW_DATA_ID_SEQ TO SGAS;

Prompt Synonym EDM_TEMP$TEST_DATA;
CREATE PUBLIC SYNONYM EDM_TEMP$TEST_DATA FOR EDM.EDM_TEMP$TEST_DATA;

Prompt Synonym RAW_DATA_COPY;
CREATE PUBLIC SYNONYM RAW_DATA_COPY FOR EDM.RAW_DATA_COPY;

-- SD > WM code commented out
-- Prompt Trigger WMTBEII1KS;
-- CREATE OR REPLACE TRIGGER EDM.WMTbeii1ks AFTER INSERT ON EDM.EDM_COMPLETE FOR EACH ROW
-- BEGIN INSERT INTO WMBbeii1ks (OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT, wm_rowid) VALUES (:new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT, WMSbeii1ks.NEXTVAL); END;
-- /
-- SHOW ERRORS;


Prompt Synonym EDM_TEMP_COPY;
CREATE PUBLIC SYNONYM EDM_TEMP_COPY FOR EDM.EDM_TEMP_COPY;

Prompt Trigger EDM_COMPLETE$AUDIT_TRIG;
CREATE OR REPLACE TRIGGER EDM.EDM_COMPLETE$AUDIT_TRIG
 AFTER INSERT OR UPDATE ON EDM.EDM_COMPLETE FOR EACH ROW
DECLARE 
v_operation VARCHAR2(10) := NULL;
BEGIN
IF INSERTING THEN
   v_operation := 'INS';
ELSIF UPDATING THEN
   v_operation := 'UPD';
END IF;
IF INSERTING OR UPDATING THEN
  INSERT INTO EDM_COMPLETE$TEST_DATA (
    OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT
    ,aud_action,aud_timestamp,aud_user)  
  VALUES (
    :new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT
    ,v_operation,SYSDATE,USER);
END IF; 
END;
/
SHOW ERRORS;


Prompt Trigger EDM_TEMP$AUDIT_TRIG;
CREATE OR REPLACE TRIGGER EDM.EDM_TEMP$AUDIT_TRIG
 AFTER INSERT OR UPDATE ON EDM.EDM_TEMP FOR EACH ROW
DECLARE 
v_operation VARCHAR2(10) := NULL;
BEGIN
IF INSERTING THEN
   v_operation := 'INS';
ELSIF UPDATING THEN
   v_operation := 'UPD';
END IF;
IF INSERTING OR UPDATING THEN
  INSERT INTO EDM_TEMP$TEST_DATA (
    OBJECT_ID, SESSION_CODE, DOCUMENT_TYPE_CODE, DOCUMENT_NAME, DOCUMENT_TYPE_COUNT, ATTACHMENT_TYPE_CODE, RESCAN_REQUEST_ID
    ,aud_action,aud_timestamp,aud_user)  
  VALUES (
    :new.OBJECT_ID, :new.SESSION_CODE, :new.DOCUMENT_TYPE_CODE, :new.DOCUMENT_NAME, :new.DOCUMENT_TYPE_COUNT, :new.ATTACHMENT_TYPE_CODE, :new.RESCAN_REQUEST_ID
    ,v_operation,SYSDATE,USER);
END IF; 
END;
/
SHOW ERRORS;


-- SD > WM code commented out
-- Prompt Table WMBBD2KSZH;
-- CREATE TABLE EDM.WMBBD2KSZH
-- (
  -- OBJECT_ID        VARCHAR2(44 BYTE),
  -- RAW_DATA_ID      NUMBER(10),
  -- BATCH_TYPE_CODE  NUMBER(2),
  -- STUD_REF_NO      NUMBER(10),
  -- BATCH_ID         NUMBER(16),
  -- ENVELOPE_ID      NUMBER(4),
  -- SCAN_DATE        DATE,
  -- PROC_ERROR       VARCHAR2(1 BYTE),
  -- URGENT           VARCHAR2(1 BYTE),
  -- WM_ROWID         NUMBER(9),
  -- WM_SENDTIME      NUMBER(14)
-- )
-- LOGGING 
-- NOCOMPRESS 
-- NOCACHE
-- NOPARALLEL
-- MONITORING;


-- Prompt Table WMBBEII1KS;
-- CREATE TABLE EDM.WMBBEII1KS
-- (
  -- OBJECT_ID        VARCHAR2(44 BYTE),
  -- RAW_DATA_ID      NUMBER(10),
  -- BATCH_TYPE_CODE  NUMBER(2),
  -- STUD_REF_NO      NUMBER(10),
  -- PROVIDER_ID      NUMBER(10),
  -- LEARNER_ID       VARCHAR2(10 BYTE),
  -- BATCH_ID         NUMBER(16),
  -- ENVELOPE_ID      NUMBER(4),
  -- SCAN_DATE        DATE,
  -- PROC_ERROR       VARCHAR2(1 BYTE),
  -- URGENT           VARCHAR2(1 BYTE),
  -- WM_ROWID         NUMBER(9),
  -- WM_SENDTIME      NUMBER(14)
-- )
-- LOGGING 
-- NOCOMPRESS 
-- NOCACHE
-- NOPARALLEL
-- MONITORING;


Prompt Privs on TABLE EDM_TEMP$TEST_DATA TO PUBLIC;
GRANT SELECT ON  EDM.EDM_TEMP$TEST_DATA TO PUBLIC;

Prompt Table RAW_DATA$TEST_DATA;
CREATE TABLE EDM.RAW_DATA$TEST_DATA
(
  OBJECT_ID                      VARCHAR2(44 BYTE),
  RAW_DATA_ID                    VARCHAR2(10 BYTE),
  BATCH_ID                       NUMBER(16),
  ENVELOPE_ID                    NUMBER(4),
  SUPPLEMENTARY_GRANTS           VARCHAR2(1 BYTE),
  STUD_REF_NO                    VARCHAR2(10 BYTE),
  SCOTTISH_CAND                  VARCHAR2(10 BYTE),
  NI_NO                          VARCHAR2(9 BYTE),
  NI_NO_F                        VARCHAR2(1 BYTE),
  TITLE                          VARCHAR2(8 BYTE),
  SURNAME                        VARCHAR2(25 BYTE),
  FORENAMES                      VARCHAR2(25 BYTE),
  BIRTH_SURNAME                  VARCHAR2(30 BYTE),
  BIRTH_FORENAMES                VARCHAR2(30 BYTE),
  DOB                            VARCHAR2(10 BYTE),
  DOB_F                          VARCHAR2(1 BYTE),
  DISTRICT_BIRTH_CERT_ISSUED     VARCHAR2(25 BYTE),
  SEX                            VARCHAR2(1 BYTE),
  MARITAL_STATUS                 VARCHAR2(1 BYTE),
  MARRIAGE_DATE                  VARCHAR2(10 BYTE),
  HOME_HOUSE_NO_NAME             VARCHAR2(32 BYTE),
  HOME_POST_CODE                 VARCHAR2(8 BYTE),
  HOME_ADDR_L1                   VARCHAR2(65 BYTE),
  HOME_ADDR_L2                   VARCHAR2(65 BYTE),
  HOME_ADDR_L3                   VARCHAR2(32 BYTE),
  HOME_ADDR_L4                   VARCHAR2(32 BYTE),
  HOME_TELE_NO                   VARCHAR2(15 BYTE),
  SORT_CODE                      VARCHAR2(6 BYTE),
  SORT_CODE_F                    VARCHAR2(1 BYTE),
  ACCOUNT_NO                     VARCHAR2(10 BYTE),
  ACCOUNT_NO_F                   VARCHAR2(1 BYTE),
  BIRTH_COUNTRY_CODE             VARCHAR2(3 BYTE),
  BIRTH_COUNTRY_CODE_F           VARCHAR2(1 BYTE),
  NATION_COUNTRY_CODE            VARCHAR2(3 BYTE),
  NATION_COUNTRY_CODE_F          VARCHAR2(1 BYTE),
  RESIDENCE_COUNTRY_CODE         VARCHAR2(3 BYTE),
  RESIDENCE_COUNTRY_CODE_F       VARCHAR2(1 BYTE),
  INST_NAME                      VARCHAR2(50 BYTE),
  INST_NAME_F                    VARCHAR2(1 BYTE),
  INST_CODE                      VARCHAR2(5 BYTE),
  CRSE_NAME                      VARCHAR2(50 BYTE),
  CRSE_NAME_F                    VARCHAR2(1 BYTE),
  CRSE_CODE                      VARCHAR2(4 BYTE),
  CRSE_YEAR_NO                   VARCHAR2(2 BYTE),
  FIRST_DEP_SURNAME              VARCHAR2(25 BYTE),
  FIRST_DEP_FORENAMES            VARCHAR2(25 BYTE),
  FIRST_DEP_DOB                  VARCHAR2(10 BYTE),
  FIRST_DEP_DOB_F                VARCHAR2(1 BYTE),
  FIRST_DEP_REL_TYPE             VARCHAR2(4 BYTE),
  FIRST_DEP_INCOME_CODE_1        VARCHAR2(2 BYTE),
  FIRST_DEP_INCOME_CODE_1_F      VARCHAR2(1 BYTE),
  FIRST_DEP_INCOME_AMOUNT_1      VARCHAR2(11 BYTE),
  FIRST_DEP_INCOME_AMOUNT_1_F    VARCHAR2(1 BYTE),
  FIRST_DEP_INCOME_CODE_2        VARCHAR2(2 BYTE),
  FIRST_DEP_INCOME_CODE_2_F      VARCHAR2(1 BYTE),
  FIRST_DEP_INCOME_AMOUNT_2      VARCHAR2(11 BYTE),
  FIRST_DEP_INCOME_AMOUNT_2_F    VARCHAR2(1 BYTE),
  FIRST_DEP_INCOME_CODE_3        VARCHAR2(2 BYTE),
  FIRST_DEP_INCOME_CODE_3_F      VARCHAR2(1 BYTE),
  FIRST_DEP_INCOME_AMOUNT_3      VARCHAR2(11 BYTE),
  FIRST_DEP_INCOME_AMOUNT_3_F    VARCHAR2(1 BYTE),
  SEC_DEP_SURNAME                VARCHAR2(25 BYTE),
  SEC_DEP_FORENAMES              VARCHAR2(25 BYTE),
  SEC_DEP_DOB                    VARCHAR2(10 BYTE),
  SEC_DEP_DOB_F                  VARCHAR2(1 BYTE),
  SEC_DEP_REL_TYPE               VARCHAR2(4 BYTE),
  SEC_DEP_INCOME_CODE_1          VARCHAR2(2 BYTE),
  SEC_DEP_INCOME_CODE_1_F        VARCHAR2(1 BYTE),
  SEC_DEP_INCOME_AMOUNT_1        VARCHAR2(11 BYTE),
  SEC_DEP_INCOME_AMOUNT_1_F      VARCHAR2(1 BYTE),
  SEC_DEP_INCOME_CODE_2          VARCHAR2(2 BYTE),
  SEC_DEP_INCOME_CODE_2_F        VARCHAR2(1 BYTE),
  SEC_DEP_INCOME_AMOUNT_2        VARCHAR2(11 BYTE),
  SEC_DEP_INCOME_AMOUNT_2_F      VARCHAR2(1 BYTE),
  SEC_DEP_INCOME_CODE_3          VARCHAR2(2 BYTE),
  SEC_DEP_INCOME_CODE_3_F        VARCHAR2(1 BYTE),
  SEC_DEP_INCOME_AMOUNT_3        VARCHAR2(11 BYTE),
  SEC_DEP_INCOME_AMOUNT_3_F      VARCHAR2(1 BYTE),
  THIRD_DEP_SURNAME              VARCHAR2(25 BYTE),
  THIRD_DEP_FORENAMES            VARCHAR2(25 BYTE),
  THIRD_DEP_DOB                  VARCHAR2(10 BYTE),
  THIRD_DEP_DOB_F                VARCHAR2(1 BYTE),
  THIRD_DEP_REL_TYPE             VARCHAR2(4 BYTE),
  THIRD_DEP_INCOME_CODE_1        VARCHAR2(2 BYTE),
  THIRD_DEP_INCOME_CODE_1_F      VARCHAR2(1 BYTE),
  THIRD_DEP_INCOME_AMOUNT_1      VARCHAR2(11 BYTE),
  THIRD_DEP_INCOME_AMOUNT_1_F    VARCHAR2(1 BYTE),
  THIRD_DEP_INCOME_CODE_2        VARCHAR2(2 BYTE),
  THIRD_DEP_INCOME_CODE_2_F      VARCHAR2(1 BYTE),
  THIRD_DEP_INCOME_AMOUNT_2      VARCHAR2(11 BYTE),
  THIRD_DEP_INCOME_AMOUNT_2_F    VARCHAR2(1 BYTE),
  THIRD_DEP_INCOME_CODE_3        VARCHAR2(2 BYTE),
  THIRD_DEP_INCOME_CODE_3_F      VARCHAR2(1 BYTE),
  THIRD_DEP_INCOME_AMOUNT_3      VARCHAR2(11 BYTE),
  THIRD_DEP_INCOME_AMOUNT_3_F    VARCHAR2(1 BYTE),
  ADD_DEP_DETAILS                VARCHAR2(1 BYTE),
  LPCG                           VARCHAR2(1 BYTE),
  TWO_HOMES_ALLOW                VARCHAR2(1 BYTE),
  VAC_GRANT                      VARCHAR2(1 BYTE),
  NET_INCOME                     VARCHAR2(10 BYTE),
  NET_INCOME_F                   VARCHAR2(1 BYTE),
  PENSION_INCOME                 VARCHAR2(10 BYTE),
  PENSION_INCOME_F               VARCHAR2(1 BYTE),
  TRUST_INCOME                   VARCHAR2(10 BYTE),
  TRUST_INCOME_F                 VARCHAR2(1 BYTE),
  AWARD_ORG                      VARCHAR2(25 BYTE),
  ANNUAL_VALUE                   VARCHAR2(10 BYTE),
  MAINTENANCE                    VARCHAR2(10 BYTE),
  FEES                           VARCHAR2(10 BYTE),
  LENGTH_OF_SUPPORT              VARCHAR2(2 BYTE),
  SUPPORT_START_DATE             VARCHAR2(10 BYTE),
  APP_FORM_SIG                   VARCHAR2(1 BYTE),
  MAX_LOAN_REQUESTED             VARCHAR2(1 BYTE),
  LOAN_REQUEST                   VARCHAR2(8 BYTE),
  LOAN_REQUEST_F                 VARCHAR2(1 BYTE),
  CONT1_FORENAME                 VARCHAR2(25 BYTE),
  CONT1_SURNAME                  VARCHAR2(25 BYTE),
  CONT1_NAME                     VARCHAR2(60 BYTE),
  CONT1_REL_CODE                 VARCHAR2(1 BYTE),
  CONT1_HOUSE_NO_NM              VARCHAR2(32 BYTE),
  CONT1_POSTCODE                 VARCHAR2(8 BYTE),
  CONT1_ADDR1                    VARCHAR2(60 BYTE),
  CONT1_ADDR2                    VARCHAR2(60 BYTE),
  CONT1_ADDR3                    VARCHAR2(30 BYTE),
  CONT1_ADDR4                    VARCHAR2(30 BYTE),
  CONT1_TEL_NO                   VARCHAR2(14 BYTE),
  CONT2_FORENAME                 VARCHAR2(25 BYTE),
  CONT2_SURNAME                  VARCHAR2(25 BYTE),
  CONT2_NAME                     VARCHAR2(60 BYTE),
  CONT2_HOUSE_NO_NM              VARCHAR2(32 BYTE),
  CONT2_POSTCODE                 VARCHAR2(8 BYTE),
  CONT2_ADDR1                    VARCHAR2(60 BYTE),
  CONT2_ADDR2                    VARCHAR2(60 BYTE),
  CONT2_ADDR3                    VARCHAR2(30 BYTE),
  CONT2_ADDR4                    VARCHAR2(30 BYTE),
  CONT2_TEL_NO                   VARCHAR2(14 BYTE),
  BANKRUPT_FLAG                  VARCHAR2(1 BYTE),
  TERM_HOUSE_NO_NAME             VARCHAR2(32 BYTE),
  TERM_POST_CODE                 VARCHAR2(8 BYTE),
  TERM_ADDR_L1                   VARCHAR2(65 BYTE),
  TERM_ADDR_L2                   VARCHAR2(65 BYTE),
  TERM_ADDR_L3                   VARCHAR2(32 BYTE),
  TERM_ADDR_L4                   VARCHAR2(32 BYTE),
  SLC_CORRES_DEST                VARCHAR2(1 BYTE),
  LOAN_SIGNATURE                 VARCHAR2(1 BYTE),
  LOAN_DECLARATION_DATE          VARCHAR2(10 BYTE),
  LOAN_DECLARATION_DATE_F        VARCHAR2(1 BYTE),
  BEN1_NI_NO                     VARCHAR2(9 BYTE),
  BEN1_NI_NO_F                   VARCHAR2(1 BYTE),
  BEN1_TITLE                     VARCHAR2(8 BYTE),
  BEN1_SURNAME                   VARCHAR2(25 BYTE),
  BEN1_FORENAMES                 VARCHAR2(25 BYTE),
  BEN1_REL_TYPE                  VARCHAR2(4 BYTE),
  BEN1_HOUSE_NO_NAME             VARCHAR2(32 BYTE),
  BEN1_POSTCODE                  VARCHAR2(8 BYTE),
  BEN1_ADDR1                     VARCHAR2(65 BYTE),
  BEN1_ADDR2                     VARCHAR2(65 BYTE),
  BEN1_ADDR3                     VARCHAR2(32 BYTE),
  BEN1_ADDR4                     VARCHAR2(32 BYTE),
  BEN1_EMP_STATUS                VARCHAR2(1 BYTE),
  BEN2_NI_NO                     VARCHAR2(9 BYTE),
  BEN2_NI_NO_F                   VARCHAR2(1 BYTE),
  BEN2_TITLE                     VARCHAR2(8 BYTE),
  BEN2_SURNAME                   VARCHAR2(25 BYTE),
  BEN2_FORENAMES                 VARCHAR2(25 BYTE),
  BEN2_REL_TYPE                  VARCHAR2(4 BYTE),
  BEN2_HOUSE_NO_NAME             VARCHAR2(32 BYTE),
  BEN2_POSTCODE                  VARCHAR2(8 BYTE),
  BEN2_ADDR1                     VARCHAR2(65 BYTE),
  BEN2_ADDR2                     VARCHAR2(65 BYTE),
  BEN2_ADDR3                     VARCHAR2(32 BYTE),
  BEN2_ADDR4                     VARCHAR2(32 BYTE),
  BEN2_EMP_STATUS                VARCHAR2(1 BYTE),
  JA_CASE                        VARCHAR2(1 BYTE),
  BEN1_PAYE                      VARCHAR2(11 BYTE),
  BEN1_PAYE_F                    VARCHAR2(1 BYTE),
  BEN2_PAYE                      VARCHAR2(11 BYTE),
  BEN2_PAYE_F                    VARCHAR2(1 BYTE),
  BEN1_SELF_EMPLOYMENT           VARCHAR2(11 BYTE),
  BEN1_SELF_EMPLOYMENT_F         VARCHAR2(1 BYTE),
  BEN2_SELF_EMPLOYMENT           VARCHAR2(11 BYTE),
  BEN2_SELF_EMPLOYMENT_F         VARCHAR2(1 BYTE),
  BEN1_PROPERTY                  VARCHAR2(11 BYTE),
  BEN1_PROPERTY_F                VARCHAR2(1 BYTE),
  BEN2_PROPERTY                  VARCHAR2(11 BYTE),
  BEN2_PROPERTY_F                VARCHAR2(1 BYTE),
  BEN1_PENSIONS                  VARCHAR2(11 BYTE),
  BEN1_PENSIONS_F                VARCHAR2(1 BYTE),
  BEN2_PENSIONS                  VARCHAR2(11 BYTE),
  BEN2_PENSIONS_F                VARCHAR2(1 BYTE),
  BEN1_BENEFITS                  VARCHAR2(11 BYTE),
  BEN1_BENEFITS_F                VARCHAR2(1 BYTE),
  BEN2_BENEFITS                  VARCHAR2(11 BYTE),
  BEN2_BENEFITS_F                VARCHAR2(1 BYTE),
  BEN1_NAT_SAVINGS               VARCHAR2(11 BYTE),
  BEN1_NAT_SAVINGS_F             VARCHAR2(1 BYTE),
  BEN2_NAT_SAVINGS               VARCHAR2(11 BYTE),
  BEN2_NAT_SAVINGS_F             VARCHAR2(1 BYTE),
  BEN1_INTEREST                  VARCHAR2(11 BYTE),
  BEN1_INTEREST_F                VARCHAR2(1 BYTE),
  BEN2_INTEREST                  VARCHAR2(11 BYTE),
  BEN2_INTEREST_F                VARCHAR2(1 BYTE),
  BEN1_DIVIDEND                  VARCHAR2(11 BYTE),
  BEN1_DIVIDEND_F                VARCHAR2(1 BYTE),
  BEN2_DIVIDEND                  VARCHAR2(11 BYTE),
  BEN2_DIVIDEND_F                VARCHAR2(1 BYTE),
  BEN1_OTHER_INC                 VARCHAR2(11 BYTE),
  BEN1_OTHER_INC_F               VARCHAR2(1 BYTE),
  BEN2_OTHER_INC                 VARCHAR2(11 BYTE),
  BEN2_OTHER_INC_F               VARCHAR2(1 BYTE),
  BEN1_SUPERANN                  VARCHAR2(11 BYTE),
  BEN1_SUPERANN_F                VARCHAR2(1 BYTE),
  BEN2_SUPERANN                  VARCHAR2(11 BYTE),
  BEN2_SUPERANN_F                VARCHAR2(1 BYTE),
  BEN1_RAP                       VARCHAR2(11 BYTE),
  BEN1_RAP_F                     VARCHAR2(1 BYTE),
  BEN2_RAP                       VARCHAR2(11 BYTE),
  BEN2_RAP_F                     VARCHAR2(1 BYTE),
  BEN1_OTHER_DED                 VARCHAR2(11 BYTE),
  BEN1_OTHER_DED_F               VARCHAR2(1 BYTE),
  BEN2_OTHER_DED                 VARCHAR2(11 BYTE),
  BEN2_OTHER_DED_F               VARCHAR2(1 BYTE),
  BEN1_FIRST_DEP_DOB             VARCHAR2(10 BYTE),
  BEN1_FIRST_DEP_DOB_F           VARCHAR2(1 BYTE),
  BEN1_SEC_DEP_DOB               VARCHAR2(10 BYTE),
  BEN1_SEC_DEP_DOB_F             VARCHAR2(1 BYTE),
  BEN1_THIRD_DEP_DOB             VARCHAR2(10 BYTE),
  BEN1_THIRD_DEP_DOB_F           VARCHAR2(1 BYTE),
  DOMESTIC_HELP                  VARCHAR2(1 BYTE),
  BEN_DEC_SIG                    VARCHAR2(1 BYTE),
  EXTRA_NOTES                    VARCHAR2(1 BYTE),
  OUT_UK                         VARCHAR2(1 BYTE),
  FAST_TRACK                     VARCHAR2(1 BYTE),
  RES_QUERY                      VARCHAR2(1 BYTE),
  ARA_SENT                       VARCHAR2(1 BYTE),
  BIRTH_CERT_FLAG                VARCHAR2(1 BYTE),
  OFFER_FLAG                     VARCHAR2(1 BYTE),
  REPEAT_YEAR                    VARCHAR2(1 BYTE),
  DATE_APPLIC_RECEIVED           VARCHAR2(10 BYTE),
  EMP_LOGIN                      VARCHAR2(30 BYTE),
  APP_FORM_SIG_DATE              VARCHAR2(10 BYTE),
  PGCE                           VARCHAR2(1 BYTE),
  DSA                            VARCHAR2(1 BYTE),
  TOT_TRAV_AMOUNT_CLAIMED        VARCHAR2(7 BYTE),
  TOT_TRAV_AMOUNT_CLAIMED_F      VARCHAR2(1 BYTE),
  MOBILE_TEL_NO                  VARCHAR2(14 BYTE),
  HOME_ADDR_MAIL_SORT            VARCHAR2(5 BYTE),
  BEN1_MAIL_SORT                 VARCHAR2(5 BYTE),
  BEN2_MAIL_SORT                 VARCHAR2(5 BYTE),
  EMAIL_ADDR                     VARCHAR2(80 BYTE),
  WEB_USER_ID                    VARCHAR2(25 BYTE),
  BANK_VALIDATE                  VARCHAR2(1 BYTE),
  EMAIL_ADDR_F                   VARCHAR2(1 BYTE),
  TERM_TIME_RESIDENCE            VARCHAR2(1 BYTE),
  TERM_TIME_RESIDENCE_F          VARCHAR2(1 BYTE),
  RELEVANT_DATE                  VARCHAR2(5 BYTE),
  RELEVANT_DATE_F                VARCHAR2(1 BYTE),
  ORDIN_RES_UK_3_YEARS           VARCHAR2(1 BYTE),
  ORDIN_RES_UK_3_YEARS_F         VARCHAR2(1 BYTE),
  ORDIN_RES_SCOT_REL_DATE        VARCHAR2(1 BYTE),
  ORDIN_RES_SCOT_REL_DATE_F      VARCHAR2(1 BYTE),
  IN_EDUC_SINCE_LEAVE_SCHOOL     VARCHAR2(1 BYTE),
  IN_EDUC_SINCE_LEAVE_SCHOOL_F   VARCHAR2(1 BYTE),
  EU_GRADUATE                    VARCHAR2(1 BYTE),
  EU_GRADUATE_F                  VARCHAR2(1 BYTE),
  STUDY_ABROAD                   VARCHAR2(1 BYTE),
  STUDY_ABROAD_F                 VARCHAR2(1 BYTE),
  PLACEMENT_YEAR                 VARCHAR2(1 BYTE),
  PLACEMENT_YEAR_F               VARCHAR2(1 BYTE),
  SECONDARY_OR_PRIMARY_ED        VARCHAR2(1 BYTE),
  SECONDARY_OR_PRIMARY_ED_F      VARCHAR2(1 BYTE),
  SECONDARY_SUBJECT              VARCHAR2(25 BYTE),
  SECONDARY_SUBJECT_F            VARCHAR2(1 BYTE),
  EXEMPT_FROM_PARENT_CONTRIB     VARCHAR2(1 BYTE),
  EXEMPT_FROM_PARENT_CONTRIB_F   VARCHAR2(1 BYTE),
  PLAN_TO_WORK_OUTSIDE_UK        VARCHAR2(1 BYTE),
  PLAN_TO_WORK_OUTSIDE_UK_F      VARCHAR2(1 BYTE),
  BEN1_FIRST_DEP_LAST_NAME       VARCHAR2(25 BYTE),
  BEN1_FIRST_DEP_LAST_NAME_F     VARCHAR2(1 BYTE),
  BEN1_FIRST_DEP_FIRST_NAME      VARCHAR2(25 BYTE),
  BEN1_FIRST_DEP_FIRST_NAME_F    VARCHAR2(1 BYTE),
  BEN1_FIRST_DEP_LEAVE_SCHOOL    VARCHAR2(1 BYTE),
  BEN1_FIRST_DEP_LEAVE_SCHOOL_F  VARCHAR2(1 BYTE),
  BEN1_SEC_DEP_LAST_NAME         VARCHAR2(25 BYTE),
  BEN1_SEC_DEP_LAST_NAME_F       VARCHAR2(1 BYTE),
  BEN1_SEC_DEP_FIRST_NAME        VARCHAR2(25 BYTE),
  BEN1_SEC_DEP_FIRST_NAME_F      VARCHAR2(1 BYTE),
  BEN1_SEC_DEP_LEAVE_SCHOOL      VARCHAR2(1 BYTE),
  BEN1_SEC_DEP_LEAVE_SCHOOL_F    VARCHAR2(1 BYTE),
  BEN1_THIRD_DEP_LAST_NAME       VARCHAR2(25 BYTE),
  BEN1_THIRD_DEP_LAST_NAME_F     VARCHAR2(1 BYTE),
  BEN1_THIRD_DEP_FIRST_NAME      VARCHAR2(25 BYTE),
  BEN1_THIRD_DEP_FIRST_NAME_F    VARCHAR2(1 BYTE),
  BEN1_THIRD_DEP_LEAVE_SCHOOL    VARCHAR2(1 BYTE),
  BEN1_THIRD_DEP_LEAVE_SCHOOL_F  VARCHAR2(1 BYTE),
  EU_STUDENT                     VARCHAR2(1 BYTE),
  NOS_YEARS_COURSE_TAKES         VARCHAR2(1 BYTE),
  ORD_RES_SCOTLAND_WEB           VARCHAR2(1 BYTE),
  ORD_RES_UK_WEB                 VARCHAR2(11 BYTE),
  MAX_FEE_LOAN                   VARCHAR2(1 BYTE),
  FEE_LOAN_AMOUNT                VARCHAR2(11 BYTE),
  FEE_LOAN_CHARGED_AMOUNT        VARCHAR2(11 BYTE),
  DEP_GRANT                      VARCHAR2(1 BYTE),
  LPG                            VARCHAR2(1 BYTE),
  MORE_THAN_3_BEN_DEPS           VARCHAR2(1 BYTE),
  AUD_ACTION                     VARCHAR2(30 BYTE),
  AUD_TIMESTAMP                  DATE,
  AUD_USER                       VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt Synonym RAW_DATA$TEST_DATA;
CREATE PUBLIC SYNONYM RAW_DATA$TEST_DATA FOR EDM.RAW_DATA$TEST_DATA;

Prompt Privs on TABLE RAW_DATA$TEST_DATA TO PUBLIC;
GRANT SELECT ON  EDM.RAW_DATA$TEST_DATA TO PUBLIC;

Prompt Table EDM_COMPLETE$TEST_DATA;
CREATE TABLE EDM.EDM_COMPLETE$TEST_DATA
(
  OBJECT_ID        VARCHAR2(44 BYTE),
  RAW_DATA_ID      NUMBER(10),
  BATCH_TYPE_CODE  NUMBER(2),
  STUD_REF_NO      NUMBER(10),
  BATCH_ID         NUMBER(16),
  ENVELOPE_ID      NUMBER(4),
  SCAN_DATE        DATE,
  PROC_ERROR       VARCHAR2(1 BYTE)             DEFAULT 'N',
  URGENT           VARCHAR2(1 BYTE)             DEFAULT 'N',
  AUD_ACTION       VARCHAR2(30 BYTE),
  AUD_TIMESTAMP    DATE,
  AUD_USER         VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

Prompt Privs on TABLE EDM_COMPLETE$TEST_DATA TO PUBLIC;
GRANT SELECT ON  EDM.EDM_COMPLETE$TEST_DATA TO PUBLIC;

Prompt Synonym EDM_COMPLETE$TEST_DATA;
CREATE PUBLIC SYNONYM EDM_COMPLETE$TEST_DATA FOR EDM.EDM_COMPLETE$TEST_DATA;

Prompt Trigger EAT_INS;
CREATE OR REPLACE TRIGGER EDM.EAT_INS
BEFORE INSERT
ON EDM.EDM_AUD_TEMP 
FOR EACH ROW
DECLARE
  v_oldval	EDM_AUD_TEMP.OLD%TYPE;
  v_newval	EDM_AUD_TEMP.NEW%TYPE;
  v_date	DATE;
BEGIN
--
  v_oldval := null;
  v_newval := null;
--
-- Get the NEW value from the last audit record for the same field
--
  IF :NEW.action IN ('A', 'B') THEN
    SELECT e1.new
    INTO   v_oldval
    FROM edm_aud_temp e1
    WHERE  e1.raw_data_id = :NEW.raw_data_id
    AND	   e1.field_name = :NEW.field_name
    AND	   e1.aud_date = (SELECT max(e2.aud_date)
                          FROM   edm_aud_temp e2
                          WHERE	 e2.field_name = e1.field_name
                          AND	 e2.raw_Data_id = e1.raw_Data_id);
--
-- Use the value found to populate the OLD value of the new record
--
  :NEW.old := nvl(v_oldval, 'Null');
  v_newval := :NEW.new;
  :NEW.new := nvl(v_newval, 'Null');
--
  END IF;
--
EXCEPTION
  WHEN others THEN
    :NEW.old := 'Null';
  	v_newval := :NEW.new;
    :NEW.new := nvl(v_newval, 'Null');
END wi_ud;
/
SHOW ERRORS;

-- SD > WM code commented out
-- Prompt Sequence WMSBEII1KS;
-- CREATE SEQUENCE EDM.WMSBEII1KS
  -- START WITH 561
  -- MAXVALUE 999999999999999999999999999
  -- MINVALUE 1
  -- NOCYCLE
  -- CACHE 20
  -- ORDER;

/**
 * Schema comparion results post-run.
 * The schemas are not identical. Differences fall into two groups - "intended" or "We're not caring".
 *
========================================================================================
= 2 Objects in EDM@192.168.186.2:1521/stepsbui but not EDM@192.168.186.2:1521/stepssit =
========================================================================================
** Recycle bin objects: Don't care
    Object Name                      Object Type      Parent Table (if any)            Differs by
    ---------------------------------------------------------------------------------------------
    "BIN$VhI776WcJM3gRAADugdqDQ==$0" TO PUBLICGrant            "BIN$VhI776WcJM3gRAADugdqDQ==$0" 
    "BIN$VhI776WYJM3gRAADugdqDQ==$0" TO PUBLICGrant            "BIN$VhI776WYJM3gRAADugdqDQ==$0" 

==========================
= 7 Objects Which Differ =
==========================
** Non-functional differences - don't care
    Object Name                      Object Type      Parent Table (if any)            Differs by
    ---------------------------------------------------------------------------------------------
    DUP_ENVELOPE_SEQ                 Sequence                                          maximum value
    EAT_INS                          Trigger          EDM_AUD_TEMP                     description
    EDM_COMPLETE$AUDIT_TRIG          Trigger          EDM_COMPLETE                     description
    EDM_PICK_LIST_ID_SEQ             Sequence                                          maximum value
    EDM_TEMP$AUDIT_TRIG              Trigger          EDM_TEMP                         description
    RAW_DATA$AUDIT_TRIG              Trigger          RAW_DATA                         description
    RAW_DATA_ID_SEQ                  Sequence                                          maximum value

========================================================================================
= 8 Objects in EDM@192.168.186.2:1521/stepssit but not EDM@192.168.186.2:1521/stepsbui =
========================================================================================
** WM objects - these are functional differences that will be addressed later either through 
** the WM interface or by a subsequent script like this one, depending on what looks most sensible
** 
    Object Name                      Object Type      Parent Table (if any)            Differs by
    ---------------------------------------------------------------------------------------------
    SYS_C0010237                     Index            WMBBEII1KS                       
    SYS_C006664                      Index            WMBBD2KSZH                       
    WMBBD2KSZH                       Table                                             
    WMBBEII1KS                       Table                                             
    WMSBD2KSZH                       Sequence                                          
    WMSBEII1KS                       Sequence                                          
    WMTBD2KSZH                       Trigger          EDM_COMPLETE                     
    WMTBEII1KS                       Trigger          EDM_COMPLETE                     

**/