DELETE FROM SHELL_LETTER WHERE DOC_NAME = 'NO_SIGNATURE';
DELETE FROM SHELL_LETTER WHERE DOC_NAME = 'NO INCOME';

ALTER TABLE SHELL_LETTER MODIFY (DOC_NAME VARCHAR2(15));

INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(18, 'NO_SIGNATURES', 'APPLICATION HAS NOT BEEN SIGNED');
INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(12, 'NO_INCOME', 'LETTER REQUESTING PROOF OF NO INCOME');

COMMIT;