-- Name:Adhoc 15 Add/Modify ILA500_CONFIG_DATA
-- Description: This script is created to add values to existing ILA500_CONFIG_DATA table and make amendments based on 2010 year changes.
--
-- MODIFICATION HISTORY:
-- Ref      Date          Author                  Desc.
-- 001      15.04.2010    P.Hughes (SAAS)         Initial Version.
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_AGE_LIMIT', '16', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_INCOME_LIMIT', '22000', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_APPLICATIONS_DUE_DAYS', '7', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_APPLICATIONS_QA_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_LCORRESPONDENCE_DUE_DAYS', '7', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_LCORRESP_QA_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_PCORRESP_DUE_DAYS', '7', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_PCORRESP_QA_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_LAD_HOC_QA_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_LAD_HOCQA_REWORK_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_PAD_HOC_QA_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_PAD_HOCQA_REWORK_DUE_DAYS', '1', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_AWARD_LETTER_PATH', '/projects/app/webmethods/letters/award', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_REJECT_LETTER_PATH', '/projects/app/webmethods/letters/rejected', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_EVID_REQUEST_LETTER_PATH', '/projects/app/webmethods/letters', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_BACS_SAVE_LOCATION', '/projects/app/webmethods/reports/ILA500/BACS_files', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_ADI_SAVE_LOCATION', '/projects/app/webmethods/reports/ILA500/ADI_Journals', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_SDS_REPORT_PATH', '/projects/app/webmethods/reports/ILA500/SDS_Reports', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_SDS_DAYS_BACK', '7', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_PAYMENT_REPORT_PATH', '/projects/app/webmethods/reports/ILA500/Payment_Reports', NULL, 'ILA500');

INSERT INTO ILA500_CONFIG_DATA ( ITEM_NAME, CVAL, NVAL, LAST_UPDATED_BY ) VALUES ( 
'ILA500_RELEASE_YEAR', '2009', NULL, 'ILA500');

update ila500_config_data
set cval = 2010
where item_name = 'CURRENT_SESSION';





