--ADHOC SCRIPT TO REMOVE OLD UNUSED ROWS FROM ILA500_CONFIG_DATA
DELETE from ila500_config_data
where item_name IN('JANUARY_LAST_WDAY','FEBRUARY_LAST_WDAY','MARCH_LAT_WDAY','MARCH_LAST_WDAY','APRIL_LAST_WDAY','MAY_LAST_WDAY','JUNE_LAST_WDAY','JULY_LAST_WDAY','AUGUST_LAST_WDAY',
                    'SEPTEMBER_LAST_WDAY','OCTOBER_LAST_WDAY','NOVEMBER_LAST_WDAY','DECEMBER_LAST_WDAY','PROVIDER_PAYMENT_REPORT_PATH')
                    
                    
                    SELECT * FROM ILA500_CONFIG_DATA
