INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(16, 'ADD_DETAILS', 'RETURN LETTER AS ADDITIONAL DETS NOT COMPLETE');

INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(17, 'NO_RESIDENCY', 'RETURN LETTER AS RESIDENCY NOT COMPLETE');

INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(18, 'NO_SIGNATURE', 'aPPLICATION HAS NOT BEEN SIGNED');

INSERT INTO SHELL_LETTER (DOC_ID,DOC_NAME,DOC_DESC) 
VALUES 
(19, 'PAYSLIPS', 'RETURN LETTER AS PAYSLIP HANDWRITTEN');

COMMIT;