SET DEFINE OFF;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (18, 51, '0', 'Learning Difficulty', 'SGAS', SYSDATE, 'Y');
COMMIT;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (19, 53, '0', 'Social or communication impairment', 'SGAS', SYSDATE, 'Y');
COMMIT;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (20, 54, '0', 'Long standing illness or health condition', 'SGAS', SYSDATE, 'Y');
COMMIT;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (21, 55, '0', 'Mental health condition', 'SGAS', SYSDATE, 'Y');
COMMIT;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (22, 56, '0', 'Physical impairment or mobility issues', 'SGAS', SYSDATE, 'Y');
COMMIT;

Insert into SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID, LEGACY_ID, LEGACY_CODE, DESCRIPT, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE) Values
   (25, 96, '0', 'Disability not listed', 'SGAS', SYSDATE, 'Y');
COMMIT;
