SET DEFINE OFF;

Insert into EDM_BATCH_WF (BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR, FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD) Values (95, 'DSA Online', 'S', NULL, 'C', 'N');

COMMIT;
