SET DEFINE OFF;
Insert into CONFIG_EDM
   (DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED, 
    REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('DSA_ONLINE_APP', 'DSA Online Application', 'E', 'Y', 'Y', 
    'Y', 'PDF', 'SGAS', SYSDATE);
COMMIT;