/* COMFIG_EDM.sql
 *
 * Generated from SGAS schema in gv36eda.test2 database using TOAD.
 *
 * All objects into USERS tablespace.
 * Init storage now 100K
 *
 * Modification history: 
 * 30.11.2007 Initial Version   Robert Hunter
 * 09/01/2008 Add synonyms and grants. Steve Durkin
 * 28/07/2010 Added data..........A.Bowman
 * 
 * Configuration Management: 
 * $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/tables/CONFIG_EDM.sql $ 
 * $Author: $ 
 * $Date: 2010-11-26 10:25:14 +0000 (Fri, 26 Nov 2010) $ 
 * $Revision: 6094 $ 
 */

ALTER TABLE SGAS.CONFIG_EDM
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SGAS.CONFIG_EDM CASCADE CONSTRAINTS
/

--
-- CONFIG_EDM  (Table) 
--
CREATE TABLE SGAS.CONFIG_EDM
(
  DOCUMENT_TYPE_CODE    VARCHAR2(16 BYTE)       NOT NULL,
  DOCUMENT_TYPE_NAME    VARCHAR2(50 BYTE)       NOT NULL,
  TYPE                  VARCHAR2(1 BYTE)        NOT NULL,
  MULTIPAGE             VARCHAR2(1 BYTE),
  RESCAN_ALLOWED        VARCHAR2(1 BYTE),
  REQ_ORIGINAL_ALLOWED  VARCHAR2(1 BYTE),
  FILE_EXT              VARCHAR2(6 BYTE),
  last_updated_by  VARCHAR2(15 BYTE) DEFAULT User CONSTRAINT NN_CE_LAST_UPDATED_BY NOT NULL,
  last_updated_on  DATE DEFAULT Sysdate CONSTRAINT NN_CE_LAST_UPDATED_ON NOT NULL
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- CONFIG_EDM_PK  (Index) 
--
CREATE UNIQUE INDEX CONFIG_EDM_PK ON SGAS.CONFIG_EDM
(DOCUMENT_TYPE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table CONFIG_EDM 
-- 
ALTER TABLE SGAS.CONFIG_EDM ADD (
  CONSTRAINT CONFIG_EDM_CC01
 CHECK (type in ('E', 'O', 'X')))
/

ALTER TABLE SGAS.CONFIG_EDM ADD (
  CONSTRAINT CONFIG_EDM_PK
 PRIMARY KEY
 (DOCUMENT_TYPE_CODE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          500K
                NEXT             500K
                MINEXTENTS       1
                MAXEXTENTS       99
                PCTINCREASE      1
                FREELISTS        1
                FREELIST GROUPS  1
               ))
/

-- 
-- Create public synonym: 
-- 
DROP PUBLIC SYNONYM CONFIG_EDM
/

CREATE PUBLIC SYNONYM CONFIG_EDM FOR SGAS.CONFIG_EDM
/

-- 
-- Grants
--
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE
ON SGAS.CONFIG_EDM
TO EDM_USER
/

GRANT SELECT ON SGAS.CONFIG_EDM TO ILA500;
GRANT SELECT ON  SGAS.CONFIG_EDM TO PUBLIC;

--- insert data

INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'NMSB1', 'NMSB1 (auto recognised)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'PLACEMENT_EXP', 'Placement Expense Claims (AB24)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS'
,  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'NMSB_MAN', 'NMSB (Manual)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'NMSB_PDF', 'NMSB_ONLINE_PDF', 'E', 'Y', 'N', 'N', 'PDF', 'SGAS',  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3_PDF', 'SAS3_ONLINE_PDF', 'E', 'Y', 'N', 'N', 'PDF', 'SGAS',  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS7_PDF', 'SAS7_ONLINE_PDF', 'E', 'Y', 'N', 'N', 'PDF', 'SGAS',  TO_Date( '11/25/2008 03:39:14 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3', 'SAS3 (auto recognised)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS7', 'SAS7 (auto recognised)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'AB4_EDM_APP', 'AB4 (auto recognised)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SHORT_APP', 'Shortened Application', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'WEB_SHORT_APP', 'Web Shortened Application', 'E', 'Y', 'N', 'N', 'PDF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'GEN_CORR', 'General correspondence', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DSA_CORR', 'DSA correspondence', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DSA_APP', 'DSA form', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_DOC', 'Income documentation', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'CERT', 'Certificates', 'E', 'N', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DUP_APP', 'Duplicate Application', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'FEE_LOAN_APP', 'Fee Loan Application', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OP_CORR', 'Overpayment Correspondence', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'TOP_UP_LOAN', 'Top Up Student Loan Application', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS'
,  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'TOP_UP_FEE_LOAN', 'Top Up Fee Loan', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OFFER', 'Offer letters', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'PT_MAN', 'Part Time (Manual)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3_MAN', 'SAS3 (Manual)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS7_MAN', 'SAS7 (Manual)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3_APPEND', 'Appending SAS3 page', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'URGENT', 'Urgent Mail', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'XML', 'XML File', 'X', NULL, NULL, NULL, NULL, 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'AWARD_REP', 'Award Report', 'O', NULL, NULL, NULL, 'PDF', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_EMAIL', 'Incoming E-mail', 'O', NULL, NULL, NULL, 'MSG', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_EMAIL', 'Outgoing E-mail', 'O', NULL, NULL, NULL, 'MSG', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_WORD', 'Incoming Document', 'O', NULL, NULL, NULL, 'DOC', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_WORD', 'Outgoing Document', 'O', NULL, NULL, NULL, 'DOC', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_EXCEL', 'Incoming Excel', 'O', NULL, NULL, NULL, 'XLS', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_EXCEL', 'Outgoing Excel', 'O', NULL, NULL, NULL, 'XLS', 'SGAS',  TO_Date( '09/25/2008 05:30:28 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'STEPSILA500APP', 'StEPS ILA500 Learner Application', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS'
,  TO_Date( '10/08/2008 02:39:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'STEPSILA500LCORR', 'StEPS ILA500 Learner Correspondence', 'E', 'N', 'Y', 'Y', 'TIFF'
, 'SGAS',  TO_Date( '10/08/2008 02:39:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'STEPSILA500PCORR', 'StEPS ILA500 Learning Provider Correspondence', 'E', 'N', 'Y'
, 'Y', 'TIFF', 'SGAS',  TO_Date( '10/08/2008 02:39:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'NMSB1_PDF', 'NMSB1 (auto recognised)', 'E', 'Y', 'Y', 'Y', 'TIFF', 'SGAS',  TO_Date( '09/10/2009 06:32:46 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
COMMIT;

