-- DDL generated from TOAD and modified by hand
-- for purposes of building the STEPS development
-- schema.
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                                  Desc.
--            28.02.08   S Durkin (Sopra UK)         Initial Version.
-- 001      03.09.10    A.Bowman (SAAS)              Added foreign key constraint
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/tables/SCOAP_PAYMENTS.sql $
-- $Author: $
-- $Date: 2010-09-03 10:58:37 +0100 (Fri, 03 Sep 2010) $
-- $Revision: 5627 $


DROP TABLE SGAS.SCOAP_PAYMENTS CASCADE CONSTRAINTS
/

--
-- SCOAP_PAYMENTS  (Table) 
--
CREATE TABLE SGAS.SCOAP_PAYMENTS
(
  DPP_BATCH_REF              VARCHAR2(7 BYTE) CONSTRAINT NN_SP_DPP_BATCH_REF NOT NULL,
  DPP_SEQUENCE_NO            NUMBER(7),
  DPP_OUR_REF1               VARCHAR2(10 BYTE) CONSTRAINT NN_SP_DPP_OUR_REF1 NOT NULL,
  DPP_OUR_REF2               VARCHAR2(10 BYTE) CONSTRAINT NN_SP_DPP_OUR_REF2 NOT NULL,
  DPP_OUR_REF3               VARCHAR2(10 BYTE)  DEFAULT '          ' CONSTRAINT NN_SP_DPP_OUR_REF3 NOT NULL,
  DPP_SOURCE_REF             VARCHAR2(10 BYTE)  DEFAULT '          ' CONSTRAINT NN_SP_DPP_SOURCE_REF NOT NULL,
  DPP_PAYEE                  VARCHAR2(30 BYTE) CONSTRAINT NN_SP_DPP_PAYEE NOT NULL,
  DPP_PAYEE_ADDRESS1         VARCHAR2(30 BYTE),
  DPP_PAYEE_ADDRESS2         VARCHAR2(30 BYTE),
  DPP_PAYEE_ADDRESS3         VARCHAR2(30 BYTE),
  DPP_PAYEE_POSTCODE         VARCHAR2(10 BYTE),
  DPP_PAYEE_BANK_ACCOUNT     CHAR(10 BYTE),
  DPP_PAYEE_BANK_SORT_CODE   CHAR(6 BYTE),
  DPP_BANK_ACCOUNT_TYPE      VARCHAR2(1 BYTE),
  DPP_BUILD_SOC_ROLL_NO      VARCHAR2(18 BYTE),
  DPP_PAYMENT_AMOUNT         NUMBER(15,2) CONSTRAINT NN_SP_DPP_PAYMENT_AMOUNT NOT NULL,
  DPP_PAYMENT_METHOD         CHAR(2 BYTE) CONSTRAINT NN_SP_DPP_PAYMENT_METHOD NOT NULL,
  DPP_PAY_SUB_TYPE           CHAR(2 BYTE),
  DPP_PAYMENT_DATE           DATE CONSTRAINT NN_SP_DPP_PAYMENT_DATE NOT NULL,
  DPP_REFER_TO_OR_ENCLOSURE  VARCHAR2(40 BYTE),
  DPP_REMITTER_ADDRESS_CODE  VARCHAR2(8 BYTE),
  DPP_RADV_ADDRESSEE         VARCHAR2(45 BYTE) CONSTRAINT NN_SP_DPP_RADV_ADDRESSEE NOT NULL,
  DPP_RADV_ADDRESS1          VARCHAR2(45 BYTE),
  DPP_RADV_ADDRESS2          VARCHAR2(45 BYTE),
  DPP_RADV_ADDRESS3          VARCHAR2(45 BYTE),
  DPP_RADV_ADDRESS4          VARCHAR2(45 BYTE),
  DPP_RADV_POSTCODE          VARCHAR2(10 BYTE),
  DPP_BANK_ID                CHAR(4 BYTE),
  DPP_REMITTANCE_TEXT_01     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_02     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_03     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_04     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_05     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_06     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_07     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_08     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_09     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_10     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_11     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_12     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_13     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_14     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_15     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_16     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_17     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_18     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_19     VARCHAR2(60 BYTE),
  DPP_REMITTANCE_TEXT_20     VARCHAR2(60 BYTE),
  DPP_PAYMENT_ID             NUMBER(5),
  DPP_PO_NUM                 NUMBER(9),
  DPP_REISSUE                VARCHAR2(1 BYTE)   DEFAULT 'N',
  DPP_RETURNED               VARCHAR2(1 BYTE),
  DPP_CURRENCY               VARCHAR2(15 BYTE),
  DPP_OUR_REF4               VARCHAR2(10 BYTE),
  LAST_UPDATED_BY  VARCHAR2(15 BYTE) DEFAULT User CONSTRAINT NN_DPP_LAST_UPDATED_BY NOT NULL,
  LAST_UPDATED_ON  DATE DEFAULT Sysdate CONSTRAINT NN_DPP_LAST_UPDATED_ON NOT NULL
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3400K
            NEXT             100K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- S2_SP  (Index) 
--
CREATE INDEX S2_SP ON SGAS.SCOAP_PAYMENTS
(DPP_OUR_REF2)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             200K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- S1_SP  (Index) 
--
CREATE INDEX S1_SP ON SGAS.SCOAP_PAYMENTS
(DPP_BATCH_REF)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             100K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table SCOAP_PAYMENTS 
-- 
ALTER TABLE SGAS.SCOAP_PAYMENTS ADD (
  CONSTRAINT SP_DPP_BANK_ACCOUNT_TYPE
 CHECK ( DPP_BANK_ACCOUNT_TYPE IN(0,1)))
/

ALTER TABLE SGAS.SCOAP_PAYMENTS ADD (
  CONSTRAINT F1_SP 
 FOREIGN KEY (DPP_BATCH_REF) 
 REFERENCES SGAS.SCOAP_BATCHES (DPB_BATCH_REF));