--
-- Add foreign key constraints. (Done separately to permit bulk load of data)
--
-- Modification History
-- Date        Author       Ref    Desc
-- 09.09.08   Remove foreign key on AWARD table FOREIGN KEY (TUITION_FEE_TYPE_CODE) refers to a view.
-- 15.02.08   Steve Durkin  001    Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/tables/TAB_FKS.sql $
-- $Author: $
-- $Date: 2008-10-01 14:24:02 +0100 (Wed, 01 Oct 2008) $
-- $Revision: 1232 $

PROMPT APPLIC_REG
PROMPT ====================
ALTER TABLE APPLIC_REG ADD (
 CONSTRAINT F1_APR
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
 ON DELETE CASCADE
);

PROMPT APPLIC_REG
PROMPT ====================
ALTER TABLE APPLIC_REG ADD (
 CONSTRAINT F2_APR
 FOREIGN KEY (DOC_TYPE_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT AWARD
PROMPT ====================
ALTER TABLE AWARD ADD (
 CONSTRAINT F1_AW
 FOREIGN KEY (STUD_CRSE_YEAR_ID)
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID)
);

-- SD> This refers to a view of GRASS data.
-- PROMPT AWARD
-- PROMPT ====================
-- ALTER TABLE AWARD ADD (
 -- CONSTRAINT F3_AW
 -- FOREIGN KEY (TUITION_FEE_TYPE_CODE)
 -- REFERENCES TUITION_FEE_TYPE (TUITION_FEE_TYPE_CODE)
-- );

PROMPT AWARD_INSTALMENT
PROMPT ====================
ALTER TABLE AWARD_INSTALMENT ADD (
 CONSTRAINT F1_AWI
 FOREIGN KEY (AWARD_ID)
 REFERENCES AWARD (AWARD_ID)
);

-- PROMPT AWARD_INSTALMENT
-- PROMPT ====================
-- ALTER TABLE AWARD_INSTALMENT ADD (
 -- CONSTRAINT F2_AWI
 -- FOREIGN KEY (CAMPUS_ID)
 -- REFERENCES CAMPUS (CAMPUS_ID)
-- );

PROMPT AWARDS_RECALC
PROMPT ====================
ALTER TABLE awards_recalc ADD (
 CONSTRAINT F1_AWR
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT BENEFACTOR_DEPENDANT
PROMPT ====================
ALTER TABLE BENEFACTOR_DEPENDANT ADD (
 CONSTRAINT F1_BED
 FOREIGN KEY (BEN_ID)
 REFERENCES BENEFACTOR (BEN_ID)

);

PROMPT BENEFACTOR_DEPENDANT
PROMPT ====================
ALTER TABLE BENEFACTOR_DEPENDANT ADD (
 CONSTRAINT F2_BED
 FOREIGN KEY (RELATION_TYPE_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT BENEFACTOR_INCOME
PROMPT ====================
ALTER TABLE BENEFACTOR_INCOME ADD (
 CONSTRAINT F1_BEI
 FOREIGN KEY (BEN_ID)
 REFERENCES BENEFACTOR (BEN_ID)
);

PROMPT CORRES
PROMPT ====================
ALTER TABLE CORRES ADD (
 CONSTRAINT F1_CO
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT CORRES_ATTACH
PROMPT ====================
ALTER TABLE CORRES_ATTACH ADD (
 CONSTRAINT F1_COA
 FOREIGN KEY (CORRES_ID)
 REFERENCES CORRES (CORRES_ID)
);

-- PROMPT EDM_AUD
-- PROMPT ====================
-- ALTER TABLE EDM_AUD ADD (
 -- CONSTRAINT EDM_AUD_STUD_FK
 -- FOREIGN KEY (STUD_REF_NO)
 -- REFERENCES STUD (STUD_REF_NO)
-- );

PROMPT EDM_EVENT_AUD_ACTION
PROMPT ====================
ALTER TABLE EDM_EVENT_AUD_ACTION ADD (
 CONSTRAINT EDM_EVENT_AA_EDM_EVENT_A_FK
 FOREIGN KEY (EVENT_AUD_ID)
 REFERENCES EDM_EVENT_AUD (EVENT_AUD_ID)
);

PROMPT EDM_IMAGES
PROMPT ====================
ALTER TABLE EDM_IMAGES ADD (
 CONSTRAINT EDM_IMAGES_CONFIG_EDM_FK
 FOREIGN KEY (DOCUMENT_TYPE_CODE)
 REFERENCES CONFIG_EDM (DOCUMENT_TYPE_CODE)
);

-- PROMPT EDM_IMAGES
-- PROMPT ====================
-- ALTER TABLE EDM_IMAGES ADD (
 -- CONSTRAINT EDM_IMAGES_STUD_FK
 -- FOREIGN KEY (STUD_REF_NO)
 -- REFERENCES STUD (STUD_REF_NO)
-- );

PROMPT EDM_NOTES
PROMPT ====================
ALTER TABLE EDM_NOTES ADD (
 CONSTRAINT EDM_NOTES_STUD_FK
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT LABEL_PRINT
PROMPT ====================
ALTER TABLE LABEL_PRINT ADD (
 CONSTRAINT F1_LP
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT PT_STUD_DEPENDANT
PROMPT ====================
ALTER TABLE PT_STUD_DEPENDANT ADD (
 CONSTRAINT F1_PTSD
 FOREIGN KEY (STUD_SESSION_ID)
 REFERENCES STUD_SESSION (STUD_SESSION_ID)
);

PROMPT PT_STUD_DEPENDANT
PROMPT ====================
ALTER TABLE PT_STUD_DEPENDANT ADD (
 CONSTRAINT F2_PTSD
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT PT_STUD_DEPENDANT
PROMPT ====================
ALTER TABLE PT_STUD_DEPENDANT ADD (
 CONSTRAINT F3_PTSD
 FOREIGN KEY (RELATION_TYPE_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT PT_STUD_INCOME
PROMPT ====================
ALTER TABLE PT_STUD_INCOME ADD (
 CONSTRAINT F1_PTSI
 FOREIGN KEY (STUD_SESSION_ID)
 REFERENCES STUD_SESSION (STUD_SESSION_ID)
);

PROMPT PT_STUD_INCOME
PROMPT ====================
ALTER TABLE PT_STUD_INCOME ADD (
 CONSTRAINT F2_PTSI
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT SCOAP_JOURNAL_LINES
PROMPT ====================
ALTER TABLE SCOAP_JOURNAL_LINES ADD (
 CONSTRAINT F1_SJ
 FOREIGN KEY (DPJ_BATCH_REF)
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF)
);

PROMPT SCOAP_PAYMENTS
PROMPT ====================
ALTER TABLE SCOAP_PAYMENTS ADD (
 CONSTRAINT F1_SP
 FOREIGN KEY (DPP_BATCH_REF)
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF)
);

PROMPT STUD
PROMPT ====================
ALTER TABLE STUD ADD (
 CONSTRAINT F1_ST
 FOREIGN KEY (RESIDENCE_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT STUD
PROMPT ====================
ALTER TABLE STUD ADD (
 CONSTRAINT F2_ST
 FOREIGN KEY (BIRTH_COUNTRY_CODE)
 REFERENCES COUNTRY (COUNTRY_CODE)
);

PROMPT STUD
PROMPT ====================
ALTER TABLE STUD ADD (
 CONSTRAINT F3_ST
 FOREIGN KEY (RESIDENCE_COUNTRY_CODE)
 REFERENCES COUNTRY (COUNTRY_CODE)
);

PROMPT STUD
PROMPT ====================
ALTER TABLE STUD ADD (
 CONSTRAINT F4_ST
 FOREIGN KEY (NATION_COUNTRY_CODE)
 REFERENCES COUNTRY (COUNTRY_CODE)
);

-- PROMPT STUD
-- PROMPT ====================
-- ALTER TABLE STUD ADD (
 -- CONSTRAINT FE_ST
 -- FOREIGN KEY (PREV_INST_CODE)
 -- REFERENCES INST (INST_CODE)
-- );

-- PROMPT STUD
-- PROMPT ====================
-- ALTER TABLE STUD ADD (
 -- CONSTRAINT FF_ST
 -- FOREIGN KEY (PROP_INST_CODE)
 -- REFERENCES INST (INST_CODE)
-- );

PROMPT STUD_CRSE_YEAR
PROMPT ====================
ALTER TABLE STUD_CRSE_YEAR ADD (
 CONSTRAINT F1_STCY
 FOREIGN KEY (STUD_SESSION_ID)
 REFERENCES STUD_SESSION (STUD_SESSION_ID)
);

-- PROMPT STUD_CRSE_YEAR
-- PROMPT ====================
-- ALTER TABLE STUD_CRSE_YEAR ADD (
 -- CONSTRAINT F2_STCY
 -- FOREIGN KEY (CRSE_YEAR_ID)
 -- REFERENCES CRSE_YEAR (CRSE_YEAR_ID)
-- );

PROMPT STUD_CRSE_YEAR
PROMPT ====================
ALTER TABLE STUD_CRSE_YEAR ADD (
 CONSTRAINT F3_STCY
 FOREIGN KEY (STUDY_COUNTRY)
 REFERENCES COUNTRY (COUNTRY_CODE)
);

PROMPT STUD_CRSE_YEAR
PROMPT ====================
ALTER TABLE STUD_CRSE_YEAR ADD (
 CONSTRAINT F7_STCY
 FOREIGN KEY (DISABLEMENT_CODE)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT STUD_DEPENDANT
PROMPT ====================
ALTER TABLE STUD_DEPENDANT ADD (
 CONSTRAINT F1_STD
 FOREIGN KEY (STUD_SESSION_ID)
 REFERENCES STUD_SESSION (STUD_SESSION_ID)
);

PROMPT STUD_DEPENDANT
PROMPT ====================
ALTER TABLE STUD_DEPENDANT ADD (
 CONSTRAINT F2_STD
 FOREIGN KEY (RELATION_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT STUD_HOME_ADDR
PROMPT ====================
ALTER TABLE STUD_HOME_ADDR ADD (
 CONSTRAINT F1_STH
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT STUD_NOTES
PROMPT ====================
ALTER TABLE STUD_NOTES ADD (
 CONSTRAINT F1_STN
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F1_STS
 FOREIGN KEY (STUD_REF_NO)
 REFERENCES STUD (STUD_REF_NO)
 ON DELETE CASCADE
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F2_STS
 FOREIGN KEY (JA_CASE_ID)
 REFERENCES JA_CASE (JA_CASE_ID)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F3_STS
 FOREIGN KEY (BEN1_ID)
 REFERENCES BENEFACTOR (BEN_ID)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F4_STS
 FOREIGN KEY (BEN2_ID)
 REFERENCES BENEFACTOR (BEN_ID)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F5_STS
 FOREIGN KEY (BEN1_REL_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F6_STS
 FOREIGN KEY (BEN2_REL_ID)
 REFERENCES REFERENCE_DATA (ID)
);

PROMPT STUD_SESSION
PROMPT ====================
ALTER TABLE STUD_SESSION ADD (
 CONSTRAINT F9_STS
 FOREIGN KEY (REASON_NO_NINO)
 REFERENCES REFERENCE_DATA (ID)
);

-- PROMPT STUD_TRACK
-- PROMPT ====================
-- ALTER TABLE STUD_TRACK ADD (
 -- CONSTRAINT F1_STK
 -- FOREIGN KEY (STUD_REF_NO)
 -- REFERENCES STUD (STUD_REF_NO)
-- );

-- PROMPT STUD_TRACK
-- PROMPT ====================
-- ALTER TABLE STUD_TRACK ADD (
 -- CONSTRAINT F3_STK
 -- FOREIGN KEY (DEPT_CODE)
 -- REFERENCES DEPARTMENT (DEPT_CODE)
-- );

-- PROMPT STUD_TRACK
-- PROMPT ====================
-- ALTER TABLE STUD_TRACK ADD (
 -- CONSTRAINT F4_STK
 -- FOREIGN KEY (LOC_CODE)
 -- REFERENCES LOCATION (LOC_CODE)
-- );

-- PROMPT STUD_TRACK
-- PROMPT ====================
-- ALTER TABLE STUD_TRACK ADD (
 -- CONSTRAINT F5_STK
 -- FOREIGN KEY (FILE_STATUS_CODE)
 -- REFERENCES FILE_STATUS (FILE_STATUS_CODE)
-- );

