-- BUILD_REFERENTIAL_CONSTRAINTS.sql
-- Description: This script should be run at the end of any deployment to ensure that any referential constraints that 
--              may have been dropped inadvertantly are recreated. 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      26.11.10    A.Bowman (SAAS)         Initial Version.
-- 1.1      09.12.10    A.Bowman (SAAS)         Added F1_ICD
-- 1.2      02.03.11    A.Bowman (SAAS)         Added F1_PID
-- 1.3      10.06.11    A.Bowman (SAAS)         New version taken from DEV
-- 1.4      18.04.12    A.Bowman (SAAS)         Latest version taken from DEV
-- 1.5      13.07.12    A.Bowman (SAAS)         Updated to add missing constraints 
-- 
--
-- Configuration Management:
-- $HeadURL:  $
-- $Author: $
-- $Date:  $
-- $Revision: $

--EDM_AUD_STUD_FK
--EDM_EVENT_AA_EDM_EVENT_A_FK
--F_RD1
--F_RDM1
--F1_ADI
--F1_ATT_RECD
--F1_ATTD
--F1_ATTDM
--F1_AWA
--F1_AWI
--F1_BDE
--F1_BEI
--F1_COA
--F1_DSAA
--F1_DSACAT
--F1_DSAP
--F1_DSAPAY
--F1_EA
--F1_EC
--F1_EL
--F1_ICD
--F1_NSA
--F1_PAYRTN
--F1_PAYRTNUN
--F1_PFU
--F1_PID
--F1_PINST
--F1_PYE
--F1_SJ
--F1_SLCD
--F1_SP
--F1_ST
--F1_ST_LTR
--F1_STCD
--F1_STCY
--F1_STD
--F1_STHA
--F1_STN
--F1_STNS
--F1_STR
--F1_STS
--F1_STT
--F1_STTA
--F2_ADI
--F2_ATT_RECD
--F2_AWA
--F2_DSAA
--F2_DSAP
--F2_DSAPAY
--F2_NSA
--F2_PAYRTN
--F2_PINST
--F2_PYE
--F2_ST
--F2_STCY
--F2_STD
--F2_STN
--F2_STS
--F3_ATT_RECD
--F3_AWA
--F3_AWI
--F3_DSAA
--F3_DSAP
--F3_DSAPAY
--F3_PAYRTN
--F3_PINST
--F3_ST
--F3_STS
--F4_ATT_RECD
--F4_DSAA
--F4_DSAP
--F4_PINST
--F4_ST
--F4_STS
--F5_DSAP
--F5_PINST
--F6_DSAP
--
ALTER TABLE AWARD ADD (
  CONSTRAINT F1_AWA 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));

ALTER TABLE AWARD ADD (
  CONSTRAINT F2_AWA 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE AWARD ADD (
  CONSTRAINT F3_AWA 
 FOREIGN KEY (DSA_ALLOWANCE_ID) 
 REFERENCES DSA_ALLOWANCE (ID));


ALTER TABLE EMPLOYEE_ACTIVITY ADD (
  CONSTRAINT F1_EA 
 FOREIGN KEY (USERNAME) 
 REFERENCES EMPLOYEE (USERNAME));


ALTER TABLE EMPLOYEE_LOCKS ADD (
  CONSTRAINT F1_EL 
 FOREIGN KEY (USERNAME) 
 REFERENCES EMPLOYEE (USERNAME));


ALTER TABLE EMPLOYEE_CASES ADD (
  CONSTRAINT F1_EC 
 FOREIGN KEY (USERNAME) 
 REFERENCES EMPLOYEE (USERNAME));


ALTER TABLE BENEFACTOR_INCOME ADD (
  CONSTRAINT F1_BEI 
 FOREIGN KEY (BEN_ID) 
 REFERENCES BENEFACTOR (BEN_ID));


ALTER TABLE STUD ADD (
  CONSTRAINT F4_ST 
 FOREIGN KEY (DISABILITY_ID) 
 REFERENCES DISABILITY_TYPE (DISABILITY_TYPE_ID));

ALTER TABLE STUD ADD (
  CONSTRAINT F1_ST 
 FOREIGN KEY (BIRTH_COUNTRY_CODE) 
 REFERENCES COUNTRY (COUNTRY_CODE));

ALTER TABLE STUD ADD (
  CONSTRAINT F2_ST 
 FOREIGN KEY (NATION_COUNTRY_CODE) 
 REFERENCES COUNTRY (COUNTRY_CODE));

ALTER TABLE STUD ADD (
  CONSTRAINT F3_ST 
 FOREIGN KEY (RESIDENCE_COUNTRY_CODE) 
 REFERENCES COUNTRY (COUNTRY_CODE));


ALTER TABLE PAYEE_PAYMENT ADD (
  CONSTRAINT F1_PYE 
 FOREIGN KEY (PAYEE_ID) 
 REFERENCES PAYEE (PAYEE_ID));

ALTER TABLE PAYEE_PAYMENT ADD (
  CONSTRAINT F2_PYE 
 FOREIGN KEY (BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));


ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F1_PAYRTN 
 FOREIGN KEY (PAYMENT_INSTALMENT_ID) 
 REFERENCES PAYMENT_INSTALMENT (PAYMENT_INSTALMENT_ID));

ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F3_PAYRTN 
 FOREIGN KEY (RETURNS_BATCH_REF) 
 REFERENCES RETURN_BATCHES (RETURNS_BATCH_REF));

ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F2_PAYRTN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));


ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED ADD (
  CONSTRAINT F1_PAYRTNUN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));


ALTER TABLE STUD_CRSE_YEAR ADD (
  CONSTRAINT F2_STCY 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE STUD_CRSE_YEAR ADD (
  CONSTRAINT F1_STCY 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES STUD_SESSION (STUD_SESSION_ID));


ALTER TABLE SCOAP_JOURNAL_LINES ADD (
  CONSTRAINT F1_SJ 
 FOREIGN KEY (DPJ_BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));


ALTER TABLE EDM_EVENT_AUD_ACTION ADD (
  CONSTRAINT EDM_EVENT_AA_EDM_EVENT_A_FK 
 FOREIGN KEY (EVENT_AUD_ID) 
 REFERENCES EDM_EVENT_AUD (EVENT_AUD_ID));


ALTER TABLE SCOAP_PAYMENTS ADD (
  CONSTRAINT F1_SP 
 FOREIGN KEY (DPP_BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));


ALTER TABLE STUD_TERM_ADDR ADD (
  CONSTRAINT F1_STTA 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE STUD_HOME_ADDR ADD (
  CONSTRAINT F1_STHA 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE STUD_DEPENDANT ADD (
  CONSTRAINT F1_STD 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE STUD_DEPENDANT ADD (
  CONSTRAINT F2_STD 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE STUD_TRACK ADD (
  CONSTRAINT F1_STT 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE EDM_AUD ADD (
  CONSTRAINT EDM_AUD_STUD_FK 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO) DISABLE);


ALTER TABLE STUD_RATE ADD (
  CONSTRAINT F1_STR 
 FOREIGN KEY (STUD_AWARD_TYPE_ID) 
 REFERENCES STUD_AWARD_TYPE (STUD_AWARD_TYPE_ID));


ALTER TABLE STUD_NOMINEE ADD (
  CONSTRAINT F2_STN 
 FOREIGN KEY (NOMINEE_ID) 
 REFERENCES NOMINEE (NOMINEE_ID));

ALTER TABLE STUD_NOMINEE ADD (
  CONSTRAINT F1_STN 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE DSA_PAYMENT ADD (
  CONSTRAINT F1_DSAPAY 
 FOREIGN KEY (AWARD_INSTALMENT_ID) 
 REFERENCES AWARD_INSTALMENT (AWARD_INSTALMENT_ID));

ALTER TABLE DSA_PAYMENT ADD (
  CONSTRAINT F2_DSAPAY 
 FOREIGN KEY (DSA_ALLOWANCE_ID) 
 REFERENCES DSA_ALLOWANCE (ID));

ALTER TABLE DSA_PAYMENT ADD (
  CONSTRAINT F3_DSAPAY 
 FOREIGN KEY (DSA_PAYMENT_STATUS_ID) 
 REFERENCES DSA_PAYMENT_STATUS (DSA_PAYMENT_STATUS_ID));


ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F4_DSAP 
 FOREIGN KEY (DSA_REFERRAL_REASON_ID) 
 REFERENCES DSA_REFERRAL_REASON (DSA_REFERRAL_REASON_ID));

ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F5_DSAP 
 FOREIGN KEY (ASSESSMENT_CENTRE_ID) 
 REFERENCES DSA_ASSESSMENT_CENTRE (DSA_ASSESSMENT_CENTRE_ID));

ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F6_DSAP 
 FOREIGN KEY (DSA_REJECTION_REASON_ID) 
 REFERENCES DSA_REJECTION_REASON (DSA_REJECTION_REASON_ID));

ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F1_DSAP 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F2_DSAP 
 FOREIGN KEY (DISABILITY_TYPE_ID) 
 REFERENCES DISABILITY_TYPE (DISABILITY_TYPE_ID));

ALTER TABLE DSA_APPLICATION ADD (
  CONSTRAINT F3_DSAP 
 FOREIGN KEY (DSA_STUDENT_TYPE_ID) 
 REFERENCES DSA_STUDENT_TYPE (DSA_STUDENT_TYPE_ID));


ALTER TABLE DSA_ALLOWANCE ADD (
  CONSTRAINT F4_DSAA 
 FOREIGN KEY (DSA_CATEGORY_ID) 
 REFERENCES DSA_CATEGORY (DSA_CATEGORY_ID));

ALTER TABLE DSA_ALLOWANCE ADD (
  CONSTRAINT F1_DSAA 
 FOREIGN KEY (DSA_APPLICATION_ID) 
 REFERENCES DSA_APPLICATION (ID));

ALTER TABLE DSA_ALLOWANCE ADD (
  CONSTRAINT F2_DSAA 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE DSA_ALLOWANCE ADD (
  CONSTRAINT F3_DSAA 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));


ALTER TABLE STUD_SESSION ADD (
  CONSTRAINT F1_STS 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE STUD_SESSION ADD (
  CONSTRAINT F2_STS 
 FOREIGN KEY (JA_CASE_ID) 
 REFERENCES JA_CASE (JA_CASE_ID));

ALTER TABLE STUD_SESSION ADD (
  CONSTRAINT F3_STS 
 FOREIGN KEY (BEN1_ID) 
 REFERENCES BENEFACTOR (BEN_ID));

ALTER TABLE STUD_SESSION ADD (
  CONSTRAINT F4_STS 
 FOREIGN KEY (BEN2_ID) 
 REFERENCES BENEFACTOR (BEN_ID));


ALTER TABLE REFERENCE_TYPES ADD (
  CONSTRAINT F_RDM1 
 FOREIGN KEY (DOMAIN) 
 REFERENCES REFERENCE_DOMAINS (DOMAIN_NAME));


ALTER TABLE REFERENCE_DATA ADD (
  CONSTRAINT F_RD1 
 FOREIGN KEY (REF_TYPE_ID) 
 REFERENCES REFERENCE_TYPES (ID));


ALTER TABLE BENEFACTOR_DEPENDANT ADD (
  CONSTRAINT F1_BDE 
 FOREIGN KEY (BEN_ID) 
 REFERENCES BENEFACTOR (BEN_ID));


ALTER TABLE NMSB_SPEC_ARR ADD (
  CONSTRAINT F1_NSA 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE NMSB_SPEC_ARR ADD (
  CONSTRAINT F2_NSA 
 FOREIGN KEY (REASON_CODE) 
 REFERENCES NMSB_CONTINUATION_REASON (NMSB_CONT_ID));


ALTER TABLE PAYMENT_FILES_UNPROCESSED ADD (
  CONSTRAINT F1_PFU 
 FOREIGN KEY (TYPE_CODE) 
 REFERENCES PAYMENT_FILE_REF (TYPE_CODE));


ALTER TABLE AWARD_INSTALMENT ADD (
  CONSTRAINT F1_AWI 
 FOREIGN KEY (AWARD_ID) 
 REFERENCES AWARD (AWARD_ID));

ALTER TABLE AWARD_INSTALMENT ADD (
  CONSTRAINT F3_AWI 
 FOREIGN KEY (BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));


ALTER TABLE INST_CONT_EMAIL ADD (
  CONSTRAINT F1_ICD 
 FOREIGN KEY (INST_CODE) 
 REFERENCES INST_CONT_DETAILS (INST_CODE));


ALTER TABLE COMPLETE_TASK_DATA ADD (
  CONSTRAINT F1_PID 
 FOREIGN KEY (PROCESS_ID) 
 REFERENCES PROCESS_INSTANCE_DATA (PROCESS_ID));


ALTER TABLE STD_LETTERS ADD (
  CONSTRAINT F1_ST_LTR 
 FOREIGN KEY (CAT_CODE) 
 REFERENCES STD_LETTERS_CATEGORIES (CAT_CODE));


ALTER TABLE PAYMENT_INSTALMENT ADD (
  CONSTRAINT F4_PINST 
 FOREIGN KEY (PAYEE_PAYMENT_ID) 
 REFERENCES PAYEE_PAYMENT (PAYEE_PAYMENT_ID));

ALTER TABLE PAYMENT_INSTALMENT ADD (
  CONSTRAINT F1_PINST 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));

ALTER TABLE PAYMENT_INSTALMENT ADD (
  CONSTRAINT F2_PINST 
 FOREIGN KEY (AWARD_INSTALMENT_ID) 
 REFERENCES AWARD_INSTALMENT (AWARD_INSTALMENT_ID));

ALTER TABLE PAYMENT_INSTALMENT ADD (
  CONSTRAINT F3_PINST 
 FOREIGN KEY (BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));

ALTER TABLE PAYMENT_INSTALMENT ADD (
  CONSTRAINT F5_PINST 
 FOREIGN KEY (PAYEE_ID) 
 REFERENCES PAYEE (PAYEE_ID));


ALTER TABLE ADI_JOURNAL ADD (
  CONSTRAINT F1_ADI 
 FOREIGN KEY (BATCH_REF) 
 REFERENCES SCOAP_BATCHES (DPB_BATCH_REF));

ALTER TABLE ADI_JOURNAL ADD (
  CONSTRAINT F2_ADI 
 FOREIGN KEY (RETURNS_BATCH_REF) 
 REFERENCES RETURN_BATCHES (RETURNS_BATCH_REF));


ALTER TABLE STUD_NOTES ADD (
  CONSTRAINT F1_STNS 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE ATTENDANCE_DATA_RECEIVED ADD (
  CONSTRAINT F1_ATT_RECD 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));

ALTER TABLE ATTENDANCE_DATA_RECEIVED ADD (
  CONSTRAINT F2_ATT_RECD 
 FOREIGN KEY (STATUS) 
 REFERENCES ATTENDANCE_DATA_STATUS (STATUS_CODE));

ALTER TABLE ATTENDANCE_DATA_RECEIVED ADD (
  CONSTRAINT F3_ATT_RECD 
 FOREIGN KEY (REPEAT_YEAR_REASON) 
 REFERENCES REPEAT_YEAR_REASON_CODE (REASON_CODE));

ALTER TABLE ATTENDANCE_DATA_RECEIVED ADD (
  CONSTRAINT F4_ATT_RECD 
 FOREIGN KEY (LOA_REASON) 
 REFERENCES LOA_REASON_CODE (LOA_REASON_CODE));


ALTER TABLE ATTENDANCE_DATA_MESSAGE ADD (
  CONSTRAINT F1_ATTDM 
 FOREIGN KEY (ATTENDANCE_DATA_RECEIVED_ID) 
 REFERENCES ATTENDANCE_DATA_RECEIVED (ATTENDANCE_DATA_RECEIVED_ID));


ALTER TABLE ATTENDANCE_DATA ADD (
  CONSTRAINT F1_ATTD 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));


ALTER TABLE DSA_CATEGORY ADD (
  CONSTRAINT F1_DSACAT 
 FOREIGN KEY (TYPE_ID) 
 REFERENCES DSA_TYPE (DSA_TYPE_ID));


ALTER TABLE STUD_CONT_DETAILS ADD (
  CONSTRAINT F1_STCD 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));


ALTER TABLE SLC_DATA ADD (
  CONSTRAINT F1_SLCD 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));


ALTER TABLE CORRES_ATTACH ADD (
  CONSTRAINT F1_COA 
 FOREIGN KEY (CORRES_ID) 
 REFERENCES CORRES (CORRES_ID));














