-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/sgas/WEB_SYNONYMS.sql $
-- $Author: $
-- $Date: 2008-03-10 15:05:49 +0000 (Mon, 10 Mar 2008) $
-- $Revision: 365 $
--
--EXTERNAL SYNONYMS USING DB LINKS
DROP PUBLIC SYNONYM TERM_ADDR_CHANGE
/
CREATE PUBLIC SYNONYM TERM_ADDR_CHANGE FOR SGAS.TERM_ADDR_CHANGE@WEB
/

DROP PUBLIC SYNONYM BANK_CHANGE
/
CREATE PUBLIC SYNONYM BANK_CHANGE FOR SGAS.BANK_CHANGE@WEB
/

DROP PUBLIC SYNONYM TITLE_NAME_CHANGE
/
CREATE PUBLIC SYNONYM TITLE_NAME_CHANGE FOR SGAS.TITLE_NAME_CHANGE@WEB
/

DROP PUBLIC SYNONYM HOME_ADDR_CHANGE
/
CREATE PUBLIC SYNONYM HOME_ADDR_CHANGE FOR SGAS.HOME_ADDR_CHANGE@WEB
/

DROP PUBLIC SYNONYM LOAN_CONTACTS_CHANGE 
/
CREATE PUBLIC SYNONYM LOAN_CONTACTS_CHANGE FOR SGAS.LOAN_CONTACTS_CHANGE@WEB
/

DROP PUBLIC SYNONYM EMAIL_MPHONE_CHANGE
/
CREATE PUBLIC SYNONYM EMAIL_MPHONE_CHANGE FOR SGAS.EMAIL_MPHONE_CHANGE@WEB
/

DROP PUBLIC SYNONYM OTHER_CHANGE
/
CREATE PUBLIC SYNONYM OTHER_CHANGE FOR SGAS.OTHER_CHANGE@WEB
/