-- Reference data
-- Table: PROVIDER 
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
--          20.06.08    A Bowman (SAAS)         Initial Version.
--
-- Configuration Management:
-- $HeadURL: 
-- $Author: 
-- $Date: 
-- $Revision: 

INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'1', 'ABERDEEN COLLEGE', NULL, 'GALLOWGATE CENTRE', 'GALLOWGATE', 'ABERDEEN', NULL
, 'AB25 1BN', '01224 612330', '01224 612001', '800514', '00401158', 'MR RODDY SCOTT'
, NULL, NULL, 'GALLOWGATE CENTRE', 'GALLOWGATE', 'ABERDEEN', NULL, 'AB25 1BN', '01224 612122'
, NULL, 'R.SCOTT@ABCOL.AC.UK', 'MR RODDY SCOTT', NULL, NULL, 'GALLOWGATE CENTRE', 'GALLOWGATE'
, 'ABERDEEN', NULL, 'AB25 1BN', '01224 612122', NULL, 'R.SCOTT@ABCOL.AC.UK', 'N', 'N'
, '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM'));
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'2', 'ADAM SMITH COLLEGE FIFE', NULL, 'ST BRYCEDALE AVENUE', 'KIRKCALDY', NULL, NULL
, 'KY1 1EX', '01592 268 591', NULL, '801684', '06970225', 'MR JOHN THOMSON', 'FINANCE MANAGER'
, NULL, 'ST BRYCEDALE AVENUE', 'KIRKCALDY', NULL, NULL, 'KY1 1EX', '01592 223476'
, '01592 223404', 'JOHNTHOMSON@ADAMSMITH.AC.UK', 'MR JOHN THOMSON', 'FINANCE MANAGER'
, NULL, 'ST. BRYCEDALE AVENEUE', 'KIRKCALDY', NULL, NULL, 'KY1 1EX', '01592 223476'
, NULL, 'JOHNTHOMSON@ADAMSMITH.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM'));
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'3', 'ANGUS COLLEGE', NULL, 'KEPTIE ROAD', 'ARBROATH', NULL, NULL, 'DD11 3EA', '01241 432600'
, '01241 876169', '801235', '00109770', 'MRS MARLENE ANDERSON', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS MARLENE ANDERSON', NULL, NULL, 'KEPTIE ROAD'
, 'ARBROATH', NULL, NULL, 'DD11 3EA', '01241 432 699', NULL, 'MARLENE.ANDERSON@ANGUS.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM'));
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'4', 'ANNIESLAND COLLEGE', '19', 'HATFIELD DRIVE', 'GLASGOW', NULL, NULL, 'G12 0YE'
, '0141 357 3969', '0141 357 6557', '832133', '00103344', 'MR STEPHEN HUME', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR STEPHEN HUME', NULL, NULL
, 'HATFIELD DRIVE', 'GLASGOW', NULL, NULL, 'G12 0YE', '0141 357 6087', NULL, 'STEPHEN_HUME@ANNIESLAND.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'5', 'ARGYLL COLLEGE', NULL, 'WEST BAY', 'DUNOON', NULL, NULL, 'PA23 7HP', '01369 707 182'
, NULL, '801346', '00130524', 'MRS ELAINE MUNRO', NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, 'MRS ELAINE MUNRO', NULL, NULL, 'DUNBEG', 'OBAN', NULL, NULL
, 'PA37 1PZ', '01631 559505', NULL, 'ELAINE.MUNRO@ARGYLLCOLLEGE.AC.UK', 'N', 'N', '3'
, '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'6', 'AYR COLLEGE', NULL, 'DAM PARK', 'AYR', NULL, NULL, 'KA8 0EU', '01292 265184'
, '01292 263889', '826030', '80255336', 'MS MARY ROBERTSON', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MS MARY ROBERTSON', NULL, NULL, 'DAM PARK'
, 'AYR', NULL, NULL, 'KA8 0EU', '01292 293435', NULL, 'M.ROBERTSON@AYRCOLL.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'7', 'BANFF AND BUCHAN COLLEGE OF FURTHER EDUCATION', NULL, 'HENDERSON ROAD', 'FRASERBURGH'
, NULL, NULL, 'AB43 9GA', '01346 586100', '01346 515370', '302589', '00664159', 'MR JOHN ANDERSON'
, NULL, NULL, 'HENDERSON ROAD', 'FRASERBURGH', NULL, NULL, 'AB43 9GA', '01346 586174'
, NULL, 'ANDERSONJ@BANKFF-BUCHAN.AC.UK', 'MR JOHN ANDERSON', NULL, NULL, 'HENDERSON ROAD'
, 'FRASERBURGH', NULL, NULL, 'AB43 9GA', '01346 586174', NULL, 'ANDERSONJ@BANFF-BUCHAN.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'8', 'BARONY COLLEGE', NULL, 'PARKGATE', 'DUMFRIES', NULL, NULL, 'DG1 3NE', '01387 860251'
, '01387 860395', '826213', '70116729', 'MRS JUNE SCOTT', NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, 'MRS JUNE SCOTT', NULL, NULL, 'PARKGATE', 'DUMFRIES'
, NULL, NULL, 'DG1 3NE', '01387 860251', NULL, 'JSCOTT@BARONY.AC.UK', 'N', 'N', '2'
, '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'9', 'BORDERS COLLEGE', NULL, 'THORNIEDEAN HOUSE', 'MELROSE ROAD', 'GALASHIELS', NULL
, 'TD1 2AF', '08700 50 51 52', '01896 758179', '832019', '00116460', 'MS WEN YU TANG'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS WEN YU TANG', NULL
, NULL, 'THORNIEDEAN HOUSE', 'MELROSE ROAD', 'GALASHIELS', NULL, 'TD1 2AF', '01896 662 534'
, NULL, 'WTANG@BORDERSCOLLEGE.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'10', 'CARDONALD COLLEGE', '690', 'MOSSPARK DRIVE', 'GLASGOW', NULL, NULL, 'G52 3AY'
, '0141 272 3332', '0141 272 3444', '801426', '00119700', 'MR NORMAN RUNCIMAN', 'ASST FINANCE MANAGER'
, '690', 'MOSSPARK DRIVE', 'GLASGOW', NULL, NULL, 'G52 3AY', '0141 272 3111', '0141 272 3444'
, 'NRUNCIMAN@CARDONALD.AC.UK', 'MRS ELAINE RITCHIE', 'FINANCE OFFICER', '690', 'MOSSPARK DRIVE'
, 'GLASGOW', NULL, NULL, 'G52 3AY', '0141 272 3114', NULL, 'ERITCHIE@CARDONALD.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'11', 'CARNEGIE COLLEGE', NULL, 'HALBEATH', 'DUNFERMLINE', NULL, NULL, 'KY11 8DY'
, '01383 845 000', '01383 845 001', '800655', '00525952', 'MRS JILL GRAHAM', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS JILL GRAHAM', NULL, NULL
, 'HALBEATH', 'DUNFERMLINE', NULL, NULL, 'KY11 8DY', '01383 845 054', NULL, 'JGRAHAM@LAUDER.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'12', 'CENTRAL COLLEGE', '300', 'CATHEDRAL STREET', 'GLASGOW', NULL, NULL, 'G1 2TA'
, '0141 552 3941', '0141 552 7179', '801180', '00199126', 'MR ALEX STEWART', NULL
, '300', 'CATHEDRAL STREET', 'GLASGOW', NULL, NULL, 'G1 2TA', '0141 271 2126', NULL
, 'ALEX.STEWART@CENTRAL-GLASGOW.AC.UK', 'MR ALEX STEWART', NULL, '300', 'CATHEDRAL STREET'
, 'GLASGOW', NULL, NULL, 'G1 2TA', '0141 271 2126', NULL, 'ALEX.STEWART@CENTRAL-GLASGOW.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'13', 'CLYDEBANK COLLEGE', NULL, 'QUEEN''S QUAY', 'CLYDEBANK', NULL, NULL, 'G81 1BF'
, '0141 951 7416', '0141 751 7400', '203370', '30954020', 'MR ALAN RITCHIE', 'DIRECTOR OF FINANCE AND ESTATE'
, NULL, 'QUEEN''S QUAY', 'CLYDEBANK', NULL, NULL, 'G81 1BF', '0141 951 7416', '0141 951 7400'
, 'ALRITCHIE@CLYDEBANK.AC.UK', 'MR JAMES RENNIE', 'FINANCIAL CONTROLLER', NULL, 'QUEEN''S QUAY'
, 'CLYDEBANK', NULL, NULL, 'G81 1BF', '0141 951 7797', NULL, 'JRENNIE@CLYDEBANK.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'14', 'COATBRIDGE COLLEGE', NULL, 'KILDONAN STREET', 'COATBRIDGE', NULL, NULL, 'ML5 3LS'
, '01236 436 000', '01236 440 266', '826127', '00003018', 'MR DEREK BANKS', 'DIRECTOR OF FINANCE'
, NULL, 'KILDONAN STREET', 'COATBRIDGE', NULL, NULL, 'ML5 3LS', '01236 422 316', NULL
, 'DBANKS@COATBRIDGE.AC.UK', 'MR DEREK BANKS', 'DIRECTOR OF FINANCE', NULL, 'KILDONAN STREET'
, 'COATBRIDGE', NULL, NULL, 'ML5 3LS', '01236 422 316', NULL, 'DBANKS@COATBRIDGE.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'15', 'DUMFRIES & GALLOWAY COLLEGE', NULL, 'HERRIES AVENUE', 'HEATHHALL', 'DUMFRIES'
, NULL, 'DG1 3QZ', '01387 243818', '01387 250006', '801160', '00266880', 'MS KAREN HUNTER'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS KAREN HUNTER', NULL
, NULL, 'HERRIES AVENUE', 'HEATHHALL', 'DUMFRIES', NULL, 'DG1 3QZ', '01387 243891'
, NULL, 'HUNTERK@DUMGAL.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'16', 'DUNDEE COLLEGE', NULL, 'KINGSWAY CAMPUS', 'OLD GLAMIS ROAD', 'DUNDEE', NULL
, 'DD3 8LE', '01382 834834', '01382 838117', '831812', '00139440', 'MS LIANA BARTHOLOMEW'
, 'FINANCE TEAM LEADER', NULL, 'KINGSWAY CAMPUS', 'OLD GLAMIS ROAD', 'DUNDEE', NULL
, 'DD3 8LE', '01382 834834', '01382 858117', 'L.BARTHOLOMEW@DUNDEECOLL.AC.UK', 'MS LIANA BARTHOLOMEW'
, 'FINANCE TEAM LEADER', NULL, 'KINGSWAY CAMPUS', 'OLD GLAMIS ROAD', 'DUNDEE', NULL
, 'DD3 8LE', '01382 834834', NULL, 'L.BARTHOLOMEW@DUNDEECOLL.AC.UK', 'N', 'N', '2'
, '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'17', 'EDINBURGH''S TELFORD COLLEGE', '350', 'WEST GRANTON ROAD', 'EDINBURGH', NULL
, NULL, 'EH5 1QE', '0131 559 4000', '0131 559 4111', '831910', '00271551', 'MR KEITH PURNELL'
, 'FINANCE MANAGER', '350', 'WEST GRANTON ROAD', 'EDINBURGH', NULL, NULL, 'EH5 1QE'
, '0131 559 4022', '0131 559 4111', 'FINANCE@ED_COLL.AC.UK', 'MR KEITH PURNELL', 'FINANCE MANAGER'
, '350', 'WEST GRANTON ROAD', 'EDINBURGH', NULL, NULL, 'EH5 1QE', '0131 559 4022'
, NULL, 'FINANCE@ED-COLL_AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'18', 'ELMWOOD COLLEGE', NULL, 'CARSLOGIE ROAD', 'CUPAR', NULL, NULL, 'KY15 4JB', '01334 658 856'
, '01334 658 888', '831723', '00150643', 'MS VIVIEN NELSON', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MS VIVIEN NELSON', NULL, NULL, 'CARSLOGIE ROAD'
, 'CUPAR', NULL, NULL, 'KY15 4JB', '01334 658 808', NULL, 'VNELSON@ELMWOOD.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'19', 'FORTH VALLEY COLLEGE', NULL, 'STUDENT SERVICES CENTRE', 'GRANGEMOUTH ROAD'
, 'FALKIRK', NULL, 'FK2 9AD', '01324 403020', '01324 403222', '832032', '00788702'
, 'MRS JANET MCNEE', NULL, NULL, 'GRANGEMOUTH ROAD', 'FALKIRK', NULL, NULL, 'FK2 9AD'
, '01324 403011', NULL, 'JANET.MCNEE@FORTHVALLEY.AC.UK', 'MRS JANET MCNEE', NULL, NULL
, 'GRANGEMOUTH ROAD', 'FALKIRK', NULL, NULL, 'FK2 9AD', '01324  403011', NULL, 'JANET.MCNEE@FORTHVALLEY.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'20', 'GLASGOW COLLEGE OF NAUTICAL STUDIES', '21', 'THISTLE STREET', 'GLASGOW', NULL
, NULL, 'G5 9XB', '0141 565 2500', '0141 565 2599', '826413', '30266042', 'MS EILEEN MARSHALL'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS EILEEN MARSHALL'
, NULL, '21', 'THISTLE STREET', 'GLASGOW', NULL, NULL, 'G5 9XB', '0141 565 2565', NULL
, 'E.MARCHALL@GCNS.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'21', 'GLASGOW METROPOLITAN COLLEGE', '60', 'NORTH HANOVER STREET', 'GLASGOW', NULL
, NULL, 'G1 2BP', '0141 566 6222', '0141 566 6226', '826412', '10102903', 'MS LOUISE ANDERSON'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS LOUISE ANDERSON'
, NULL, NULL, 'GLASGOW METROPOLITAN COLLEGE', '60 NORTH HANOVER STREET', 'GLASGOW'
, NULL, 'G1 2BP', '0141 566 6222', NULL, 'LOUISE.ANDERSON@GLASGOWMET.AC.UK', 'N', 'N'
, '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'22', 'HIGHLAND THEOLOGICAL COLLEGE', '16', 'HIGH STREET', 'DINGWALL', NULL, NULL
, 'IV15 9HA', '01349 780000', '01349 780001', '800635', '00112023', 'MRS MARIE EWAN'
, 'FINANCE OFFICER', '16', 'HIGH STREET', 'DINGWALL', NULL, NULL, 'IV15 9HA', '01349 780204'
, '01349 780001', 'MARIE.EWAN@HTC.UHI.AC.UK', 'MRS MARIE EWAN', 'FINANCE OFFICER'
, '16', 'HIGH STREET', 'DINGWALL', NULL, NULL, 'IV15 9HA', '01349 780204', NULL, 'MARIE.EWAN@HTC.UHI.AC.UK'
, 'N', 'N', '3', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'23', 'INVERNESS COLLEGE', '3', 'LONGMAN ROAD', 'INVERNESS', NULL, NULL, 'IV1 1SA'
, '01463 273000', '01463 711977', '832310', '00180230', 'MRS MARY BUTLER', NULL, '3'
, 'LONGMAN ROAD', 'INVERNESS', NULL, NULL, 'IV1 1SA', '01463 273402', '01463 273012'
, 'MARY.BUTLER@INVERNESS.UHI.AC.UK', 'MRS FIONA MUSTARDE', NULL, '3', 'LONGMAN ROAD'
, 'INVERNESS', NULL, NULL, 'IV1 1SA', '01463 273260', NULL, 'FIONA.MUSTARDE@INVERNESS.UHI.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'24', 'JAMES WATT COLLEGE', NULL, 'FINNART STREET', 'GREENOCK', NULL, NULL, 'PA16 8HF'
, '01475 553014', '01475 554085', '800748', '00519673', 'MS VIVIENNE RUDDELL', 'PRINCIPAL ACCOUNTANT'
, NULL, 'FINNART STREET', 'GREENOCK', NULL, NULL, 'PA16 8HF', '01475 553014', '01475 554085'
, 'VRUDDELL@JAMESWATT.AC.UK', 'MS VIVIENNE RUDDELL', 'PRINCIPAL ACCOUNTANT', NULL
, 'FINNART STREET', 'GREENOCK', NULL, NULL, 'PA16 8HF', '01475 553014', NULL, 'VRUDDELL@JAMESWHATT.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'25', 'JEWEL AND ESK VALLEY COLLEGE', NULL, 'ESKBANK CENTRE', 'NEWBATTLE ROAD', 'ESKBANK'
, 'DALKEITH', 'EH22 3AE', '0845 850 0060', '0131 663 0271', '302581', '01037407', 'MR DAVID SWEENEY'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR DAVID SWEENEY', NULL
, NULL, 'ESKBANK CAMPUS', 'NEWBATTLE ROAD', 'DALKEITH', NULL, 'EH22 3AE', '0131 654 5330'
, NULL, 'DSWEENEY@JEVC.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'26', 'JOHN WHEATLEY COLLEGE', NULL, 'EAST END CAMPUS', '2 HASHELL ROAD', 'GLASGOW'
, NULL, 'G31 3SR', '0141 588 1571', '0141 588 1503', '826428', '60042308', 'MS YVONNE MCCAIG'
, NULL, NULL, 'EAST END CAMPUS', '2 HASHELL ROAD', 'GLASGOW', NULL, 'G31 3SR', '0141 588 1571'
, '0141 588 1503', 'YMCCAIG@JWHEATLEY.AC.UK', 'MS YVONNE MCCAIG', NULL, NULL, 'EAST END CAMPUS'
, '2 HASHELL ROAD', 'GLASGOW', NULL, 'G31 3SR', '0141 588 1571', NULL, 'YMCCAIG@JWHEATLEY.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'27', 'KILMARNOCK COLLEGE', NULL, 'HOLEHOUSE ROAD', 'KILMARNOCK', NULL, NULL, 'KA3 7AT'
, '0800 389 6817', '01563 538182', '800853', '06005432', 'MRS ELIZABETH WALKER', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS ELIZABETH WALKER', NULL
, NULL, 'HOLEHOUSE ROAD', 'KILMARNOCK', NULL, NULL, 'KA3 7AT', '0800 389 6817', NULL
, 'ENQUIRIES@KILMARNOCK.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'28', 'LANGSIDE COLLEGE', '50', 'PROSPECTHILL ROAD', 'GLASGOW', NULL, NULL, 'G42 9LB'
, '0141 636 6066', '0141 632 5252', '800717', '00500068', 'MR JOSEPH MCMAHON', 'FINANCE MANAGER'
, '50', 'PROSPECTHILL ROAD', 'GLASGOW', NULL, NULL, 'G42 9LB', '0141 272 3650', NULL
, 'JMCMAHON@LANGSIDE.AC.UK', 'MR JOSEPH MCMAHON', 'FINANCE MANAGER', '50', 'PROSPECTHILL ROAD'
, 'GLASGOW', NULL, NULL, 'G42 9LB', '0141 272 3650', NULL, 'JMCMAHON@LANGSIDE.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'29', 'LEWS CASTLE COLLEGE', NULL, 'LADY LEVER PARK', 'STORNOWAY', NULL, NULL, 'HS2 0XR'
, '01851 770000', '01851 770001', '832712', '00164770', 'MR IAIN MACMILLAN', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR IAIN MACMILLAN', NULL
, NULL, 'STORNOWAY', 'ISLE OF LEWIS', NULL, NULL, 'HS2 0XR', '01851 770 000', NULL
, 'IAIN.MACMILLAN@LEWS.UHI.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'30', 'MORAY COLLEGE', NULL, 'MORAY STREET', 'ELGIN', NULL, NULL, 'IV30 1JJ', '01343 576000'
, '01343 576001', '800666', '00156260', 'MR STUART CRUICKSHANK', NULL, NULL, 'MORAY STREET'
, 'ELGIN', NULL, NULL, 'IV30 1JJ', '01343 576418', NULL, 'STUART.CRUICKSHANK@MORAY.UHI.AC.UK'
, 'MR STUART CRUICKSHANK', NULL, NULL, 'MORAY STREET', 'ELGIN', NULL, NULL, 'IV30 1JJ'
, '01343 576418', NULL, 'STUART.CRUICKSHANK@MORAY.UHI.AC.UK', 'N', 'N', '2', '1', 'ILA500'
,  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'31', 'MOTHERWELL COLLEGE', NULL, 'DALZELL DRIVE', 'MOTHERWELL', NULL, NULL, 'ML1 2DD'
, '01698 232 425', '01698 232 527', '826626', '60390624', 'MR IAIN CLARK', 'FINANCIAL CONTROLLER'
, NULL, 'DALZELL DRIVE', 'MOTHERWELL', NULL, NULL, 'ML1 2DD', '01698 232323', NULL
, 'ICLARK@MOTHERWELL.CO.UK', 'MR IAIN CLARK', NULL, NULL, 'DALZELL DRIVE', 'MOTHERWELL'
, NULL, NULL, 'ML1 2DD', '01698 232323', NULL, 'ICLARK@MOTHERWELL.CO.UK', 'N', 'N'
, '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'32', 'NORTH GLASGOW COLLEGE', '110', 'FLEMINGTON STREET', 'SPRINGBURN', 'GLASGOW'
, NULL, 'G21 4BX', '0141 558 9001', '0141 558 9905', '826429', '50064238', 'MISS LESLEY RENSHAW'
, 'FINANCE ASSISTANT', '110', 'FLEMINGTON STREET', 'GLASGOW', NULL, NULL, 'G21 4BX'
, '0141 558 9001', NULL, 'LRENSHAW@NORTH-GLA.AC.UK', 'MISS LESLEY RENSHAW', 'FINANCE ASSISTANT'
, '110', 'FLEMINGTON ROAD', 'GLASGOW', NULL, NULL, 'G21 4BX', '0141 558 9001', NULL
, 'LRENSHAW@NORTH-GLA.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'33', 'NORTH HIGHLAND COLLEGE', NULL, 'ORMLIE ROAD', 'THURSO', NULL, NULL, 'KW14 7EE'
, '01847 889 000', '01847 889 001', '826816', '90540743', 'MRS MOIRA CONWAY', 'ACCOUNTS ASSISTANT'
, NULL, 'ORMLIE ROAD', 'THURSO', NULL, NULL, 'KW14 7EE', '01847 889 229', '01847 889 001'
, 'MOIRA.CONWAY@THURSO.UHI.AC.UK', 'MRS MOIRA CONWAY', 'ACCOUNTS ASSISTANT', NULL
, 'ORMLIE ROAD', 'THURSO', NULL, NULL, 'KW14 7EE', '01847 889229', NULL, 'MOIRA.CONWAY@THURSO.UHI.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'34', 'OATRIDGE COLLEGE', NULL, 'ECCLESMACHAN', 'BROXBURN', NULL, NULL, 'EH52 6NH'
, '01506 864800', '01506 853373', '832425', '00234792', 'MRS GILLIAN A HAMILTON', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS GILLIAN A HAMILTON', NULL
, NULL, 'ECCLESMACHAN', 'BROXBURN', NULL, NULL, 'EH52 6NH', '01506 864 800', NULL
, 'GHAMILTON@OATRIDGE.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'35', 'ORKNEY COLLEGE', NULL, 'EAST ROAD', 'KIRKWALL', NULL, NULL, 'KW15 1LX', '01856 569 000'
, '01856 569 001', '832407', '00233886', 'MR PETER KITNEY', NULL, NULL, 'EAST ROAD'
, 'KIRKWALL', NULL, NULL, 'KW15 1LX', '01856 569 000', NULL, NULL, 'MS CHRISTINE SCOTT'
, NULL, NULL, 'EAST ROAD', 'KIRKWALL', NULL, NULL, 'KW15 1LX', '01856 569 000', NULL
, 'CHRISTINE.SCOTT@ORKNEY.UHI.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'36', 'PERTH COLLEGE', NULL, 'CRIEFF ROAD', 'PERTH', NULL, NULL, 'PH1 2NX', '0845 270 1177'
, '01738 877001', '809128', '00710997', 'MR IAIN NEILSON', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MR IAIN NEILSON', NULL, NULL, 'CRIEFF ROAD'
, 'PERTH', NULL, NULL, 'PH1 2NX', '01738 877 233', NULL, 'IAIN.NEILSON@PERTH.UHI.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'37', 'REID KERR COLLEGE', NULL, 'RENFREW ROAD', 'PAISLEY', NULL, NULL, 'PA3 4DR'
, '0800 052 7343', '0141 581 2204', '809127', '00786356', 'MRS LAURA MCLEAN', NULL
, NULL, 'RENFREW ROAD', 'PAISLEY', NULL, NULL, 'PA3 4DR', '0141 581 2263', NULL, 'LAURA.MCLEAN@REIDKERR.AC.UK'
, 'MRS LAURA MCLEAN', NULL, NULL, 'RENFREW ROAD', 'PAISLEY', NULL, NULL, 'PA3 4DR'
, '0141 581 2263', NULL, 'LAURA.MCLEAN@REIDKERR.AC.UK', 'N', 'N', '2', '1', 'ILA500'
,  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'38', 'SABHAL MOR OSTAIG', NULL, 'TEANGUE', 'ISLE OF SKYE', NULL, NULL, 'IV44 8RQ'
, '01471 888000', '01471 888002', '800583', '00857661', 'MS MARGARET FOWLER', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS MARGARET FOWLER', NULL
, NULL, 'TEANGUE', 'ISLE OF SKYE', NULL, NULL, 'IV44 8RD', '01471 888 213', NULL, 'SM00MF@GROUPWISE.UHI.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'39', 'SHETLAND COLLEGE', NULL, 'GREMISTA', 'LERWICK', NULL, NULL, 'ZE1 0PX', '01595 771000'
, '01595 771001', '800882', '00729160', 'MS ELSE SMAASKJAER', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MS ELSE SMAASKJAER', NULL, NULL, 'GREMISTA'
, 'LERWICK', NULL, NULL, 'ZE1 0PX', '0159 577 1268', NULL, 'ELSE.SMAASKJAER@SHETLAND.UHI.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'40', 'SOUTH LANARKSHIRE COLLEGE', NULL, 'MAIN CENTRE', '85 HAMILTON ROAD', 'CAMBUSLANG'
, NULL, 'G72 7NY', '01355 270750', '01355 231044', '826118', '60172142', 'MR KEITH MCALLISTER'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR KEITH MCALLISTER'
, NULL, NULL, 'MAIN CENTRE', 'HAMILTON ROAD', 'CAMBUSLANG', 'GLASGOW', 'G72 7NY', '0141 641 6600'
, NULL, 'KEITH.MCALLISTER@SLC.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'41', 'STEVENSON COLLEGE EDINBURGH', NULL, 'BANKHEAD AVENUE', 'SIGHTHILL', 'EDINBURGH'
, NULL, 'EH11 4DE', '0131 535 4700', '0131 535 4708', '800227', '06002132', 'MS JAN BRECHIN'
, NULL, NULL, 'BANKHEAD AVENUE', 'SIGHTHILL', 'EDINBURGH', NULL, 'EH11 4DE', '0131 535 4660'
, NULL, 'JBRECHIN@STEVENSON.AC.UK', 'MS JAN BRECHIN', NULL, NULL, 'BANKHEAD AVENUE'
, 'EDINBURGH', NULL, NULL, 'EH11 4DE', '0131 535 4660', NULL, 'JBRECHIN@STEVENSON.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'42', 'STOW COLLEGE', '43', 'SHAMROCK STREET', 'GLASGOW', NULL, NULL, 'G4 9LD', '0141 332 1786'
, '0141 332 5207', '835200', '00149876', 'MR DAVID ALEXANDER', NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, 'MR DAVID ALEXANDER', NULL, '43', 'SHAMROCK STREET'
, 'GLASGOW', NULL, NULL, 'G4 9LD', '0141 332 1786', NULL, 'DALEXANDER@STOW.AC.UK'
, 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'43', 'WEST LOTHIAN COLLEGE', NULL, 'ALMONDVALE CRESCENT', 'LIVINGSTON', NULL, NULL
, 'EH54 7EP', '01506 418181', '01506 409980', '800880', '00897932', 'MR ANDREW PHILIP'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR ANDREW PHILIP', NULL
, NULL, 'ALMONDAVALE CRESCENT', 'LIVINGSTON', NULL, NULL, 'EH54 7EP', '01506 427532'
, NULL, 'APHILIP@WEST-LOTHIAN.AC.UK', 'N', 'N', '2', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'44', 'EDINBURGH COLLEGE OF ART', NULL, 'LAURISTON PLACE', 'EDINBURGH', NULL, NULL
, 'EH3 9DF', '0131 221 6027', '0131 221 6001', '801194', '00204068', 'MS ALISON HEGARTY'
, NULL, NULL, 'LAURISTON PLACE', 'EDINBURGH', NULL, NULL, 'EH3 9DF', '0131 221 6211'
, NULL, 'A.HEGARTY@ECA.AC.UK', 'MS ALISON HEGARTY', NULL, NULL, 'LAURISTON PLACE'
, 'EDINBURGH', NULL, NULL, 'EH3 9DF', '0131 221 6211', NULL, 'A.HEGARTY@ECA.AC.UK'
, 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'45', 'GLASGOW CALEDONIAN UNIVERSITY', NULL, 'COWCADDENS ROAD', 'GLASGOW', NULL, NULL
, 'G4 0BA', '0141 331 3818', '0141 331 3396', '835200', '00716754', 'MR ROBERT MCKAIN'
, 'HEAD OF ACCOUNTS RECEIVABLE', NULL, 'COWCADDENS ROAD', 'GLASGOW', NULL, NULL, 'G4 0BA'
, '0141 331 3818', '0141 331 3396', 'AR@GCAL.AC.UK', 'MR ROBERT MCKAIN', 'HEAD OF ACCOUNTS RECEIVABLE'
, NULL, 'COWCADDENS ROAD', 'GLASGOW', NULL, NULL, 'G4 0BA', '0141 331 3818', NULL
, 'AR@GCAL.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'46', 'HERIOT WATT UNIVERSITY', NULL, 'RICCARTON', 'EDINBURGH', NULL, NULL, 'EH14 4AS'
, '0131 449 5111', '0131 449 5153', '302581', '00353976', 'MR KEVIN MALLETT', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR KEVIN MALLETT', NULL, NULL
, 'RICCARTON', 'EDINBURGH', NULL, NULL, 'EH14 4AS', '0131 451 4001', NULL, 'K.MALLETT@HW.AC.UK'
, 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'47', 'NAPIER UNIVERSITY', NULL, 'CRAIGHOUSE CAMPUS', 'CRAIGHOUSE ROAD', 'EDINBURGH'
, NULL, 'EH10 5LG', '0500 35 35 70', '0131 455 6261', '831825', '00230250', 'MS DEIRDRE ROBERTSON'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS DEIRDRE ROBERTSON'
, NULL, NULL, 'EAST CRAIG', 'CRAIGHOUSE CAMPUS', 'EDINBURGH', NULL, 'EH10 5LG', '0131 455 6003'
, NULL, 'DC.ROBERTSON@NAPIER.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'48', 'QUEEN MARGARET UNIVERSITY', NULL, 'QUEEN MARGARET UNIVERSITY DRIVE', 'MUSSELBURGH'
, NULL, NULL, 'EH21 6UU', '0131 474 0000', '0131 474 0001', '835100', '00244979', 'MS KAREN INGLIS'
, 'FINANCE OFFICE MANAGER', NULL, 'QUEEN MARGARET DRIVE', 'MUSSELBURGH', NULL, NULL
, 'EH21 6UU', '0131 474 0000', '0131 474 0001', 'KINGLIS@QMU.AC.UK', 'MS KAREN INGLIS'
, 'FINANCE OFFICE MANAGER', NULL, 'QUEEN MARGARET UNIVERSITY DRIVE', 'MUSSELBURGH'
, NULL, NULL, 'EH21 6UU', '0131 474 0000', NULL, 'KINGLIS@QMU.AC.UK', 'N', 'N', '1'
, '1', 'ILA500',  TO_Date( '06/20/2008 09:28:49 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'49', 'ROBERT GORDON UNIVERSITY', NULL, 'SCHOOLHILL', 'ABERDEEN', NULL, NULL, 'AB10 1FR'
, '01224 262180', '01224 262038', '800514', '06003836', 'MR JOHN MIDDLETON', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR JOHN MIDDLETON', NULL
, NULL, 'STUDENT FINANCE - SCHOOLHILL', 'ABERDEEN', NULL, NULL, 'AB10 1FR', '1224262055'
, NULL, 'J.MIDDLETON@RGU.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'50', 'SCOTTISH AGRICULTURAL COLLEGE (SAC)', NULL, 'AYR CAMPUS', 'AUCHINCRUIVE', 'AYR'
, NULL, 'KA6 5HW', '0800 269453', NULL, '800224', '00336447', 'MR RICHARD FINLAYSON'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MR RICHARD FINLAYSON'
, NULL, NULL, 'WEST MAINS ROAD', 'EDINBURGH', NULL, NULL, 'EH9 3JE', '0131 535 4286'
, NULL, 'WWW.SAC.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'51', 'THE OPEN UNIVERSITY', '10', 'DRUMSHEGH GARDENS', 'EDINBURGH', NULL, NULL, 'EH3 7QJ'
, '0131 226 3851', '0131 220 6730', '601455', '01920294', 'DR SUSAN COOPER', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DR SUSAN COOPER', NULL, '10'
, 'DRUMSHEGH GARDENS', 'EDINBURGH', NULL, NULL, 'EH3 7QJ', '0131 226 3851', NULL, 'S.D.COOPER@OPEN.AC.UK'
, 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'52', 'UNIVERSITY OF ABERTAY DUNDEE', NULL, 'BELL STREET', 'DUNDEE', NULL, NULL, 'DD1 1HG'
, '01382 308000', '01382 308081', '807331', '00306492', 'MS CATRIONA BLAKE', NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS CATRIONA BLAKE', NULL
, NULL, 'KYDD BUILDING', '40 BELL STREET', 'DUNDEE', NULL, 'DD1 1HG', '01382 308023'
, NULL, 'C.BLAKE@ABERTAY.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'53', 'UNIVERSITY OF DUNDEE', NULL, 'NETHERGATE', 'DUNDEE', NULL, NULL, 'DD1 4HN'
, '01382 383000', NULL, '835000', '00279759', 'MS NORMA STEWART', NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MS NORMA STEWART', NULL, NULL, 'REGISTRY'
, '1 AIRLIE PLACE', 'DUNDEE', NULL, 'DD1 4HN', '01382 385392', NULL, 'N.STEWART@DUNDEE.AC.UK'
, 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'54', 'UNIVERSITY OF EDINBURGH', NULL, 'OLD COLLEGE', 'SOUTH BRIDGE', 'EDINBURGH'
, NULL, 'EH8 9YL', '0131 650 1000 ', '0131 650 2147', '800224', '00919680', 'MRS GERALDINE BEATTIE'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS GERALDINE BEATTIE'
, NULL, NULL, 'OLD COLLEGE', 'SOUTH BRIDGE', 'EDINBURGH', NULL, 'EH8 9YL', '0131 650 9184'
, NULL, 'GERALDINE.BEATTIE@ED.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'55', 'UNIVERSITY OF STIRLING', NULL, 'MAIN CAMPUS', 'STIRLING', NULL, NULL, 'FK9 4LA'
, '01786 473171', NULL, '809129', '00891500', 'MS CHRISTINE MACINNES', NULL, NULL
, 'MAIN CAMPUS', 'STIRLING', NULL, NULL, 'FK9 4LA', '01786 466198', NULL, 'CHRISTINE.MACINNES@STIR.AC.UK'
, 'MS CHRISTINE MACINNES', NULL, NULL, 'MAIN CAMPUS', 'STIRLING', NULL, NULL, 'FK9 4LA'
, '01786 466198', NULL, 'CHRISTINE.MACINNES@STIR.AC.UK', 'N', 'N', '1', '1', 'ILA500'
,  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO PROVIDER ( PROVIDER_ID, PROVIDER_NAME, PROVIDER_HOUSE_NO_OR_NAME, PROVIDER_ADDR_L1,
PROVIDER_ADDR_L2, PROVIDER_ADDR_L3, PROVIDER_ADDR_L4, PROVIDER_POST_CODE, PROVIDER_TEL_NO,
PROVIDER_FAX_NO, BANK_SORT_CODE, BANK_ACCOUNT_NO, MAIN_CONTACT_NAME, MAIN_CONTACT_POSITION,
MAIN_CONTACT_HOUSE_NO_OR_NAME, MAIN_CONTACT_ADDR_L1, MAIN_CONTACT_ADDR_L2, MAIN_CONTACT_ADDR_L3,
MAIN_CONTACT_ADDR_L4, MAIN_CONTACT_POST_CODE, MAIN_CONTACT_TEL_NO, MAIN_CONTACT_FAX_NO,
MAIN_CONTACT_EMAIL, FIN_CONTACT_NAME, FIN_CONTACT_POSITION, FIN_CONTACT_HOUSE_NO_OR_NAME,
FIN_CONTACT_ADDR_L1, FIN_CONTACT_ADDR_L2, FIN_CONTACT_ADDR_L3, FIN_CONTACT_ADDR_L4,
FIN_CONTACT_POST_CODE, FIN_CONTACT_TEL_NO, FIN_CONTACT_FAX_NO, FIN_CONTACT_EMAIL, SUSPEND_PAYMENTS,
SUSPEND_LETTERS, PROV_TYPE_ID, PROV_STATUS_ID, LAST_UPDATED_BY,
LAST_UPDATED_ON ) VALUES ( 
'56', 'UNIVERSITY OF THE WEST OF SCOTLAND', NULL, 'HIGH STREET', 'PAISLEY', NULL, NULL
, 'PA1 2BE', '0141 848 3000', '0141 849 4100', '809127', '00738290', 'MRS PAULA FRANCIS'
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MRS PAULA FRANCIS'
, NULL, NULL, NULL, 'HIGH STREET', 'PAISLEY', NULL, 'PA1 2BE', '0141 848 3721', NULL
, 'PAULA.FRANCIS@UWS.AC.UK', 'N', 'N', '1', '1', 'ILA500',  TO_Date( '06/20/2008 09:28:50 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
COMMIT;

 
