SELECT * FROM ZZ_MASK_COLUMN
WHERE ORDER_NUMBER > 77
ORDER BY ORDER_NUMBER;

SELECT *
FROM ZZ_MASK_COLUMN C
WHERE NOT EXISTS (SELECT 1
                  FROM ALL_TAB_COLS CO
                  WHERE CO.OWNER = 'SGAS'
                  AND CO.TABLE_NAME = C.TABLE_NAME
                  AND CO.COLUMN_NAME = C.COLUMN_NAME);
SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT * FROM ZZ_MASK_COLUMN
--  WHERE ORDER_NUMBER > 77
--  ORDER BY ORDER_NUMBER;
--

COMMIT;
