INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3', 'SAS3 (auto recognised)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS7', 'SAS7 (auto recognised)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'AB4_EDM_APP', 'AB4 (auto recognised)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SHORT_APP', 'Shortened Application', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'WEB_SHORT_APP', 'Web Shortened Application', 'E', 'Y', 'N', 'N', 'PDF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'GEN_CORR', 'General correspondence', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DSA_CORR', 'DSA correspondence', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DSA_APP', 'DSA form', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_DOC', 'Income documentation', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'CERT', 'Certificates', 'E', 'N', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'DUP_APP', 'Duplicate Application', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'FEE_LOAN_APP', 'Fee Loan Application', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OP_CORR', 'Overpayment Correspondence', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'TOP_UP_LOAN', 'Top Up Student Loan Application', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS'
,  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'TOP_UP_FEE_LOAN', 'Top Up Fee Loan', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OFFER', 'Offer letters', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'PT_MAN', 'Part Time (Manual)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3_MAN', 'SAS3 (Manual)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS7_MAN', 'SAS7 (Manual)', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'SAS3_APPEND', 'Appending SAS3 page', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'URGENT', 'Urgent Mail', 'E', 'Y', 'N', 'N', 'TIFF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'XML', 'XML File', 'X', NULL, NULL, NULL, NULL, 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'AWARD_REP', 'Award Report', 'O', NULL, NULL, NULL, 'PDF', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_EMAIL', 'Incoming E-mail', 'O', NULL, NULL, NULL, 'MSG', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_EMAIL', 'Outgoing E-mail', 'O', NULL, NULL, NULL, 'MSG', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_WORD', 'Incoming Document', 'O', NULL, NULL, NULL, 'DOC', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_WORD', 'Outgoing Document', 'O', NULL, NULL, NULL, 'DOC', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'INC_EXCEL', 'Incoming Excel', 'O', NULL, NULL, NULL, 'XLS', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO CONFIG_EDM ( DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED,
REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON ) VALUES ( 
'OUT_EXCEL', 'Outgoing Excel', 'O', NULL, NULL, NULL, 'XLS', 'SGAS',  TO_Date( '02/23/2008 04:16:03 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
commit;
 
