-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
-- 001      15/04/2010      A.Bowman (SAAS)                 Initial Version
--
-- Configuration Management:
-- $HeadURL: $
-- $Author: $
-- $Date:  $
-- $Revision: $

DROP TABLE EDM.EDM_COMPLETE$TEST_DATA CASCADE CONSTRAINTS PURGE;

CREATE TABLE EDM.EDM_COMPLETE$TEST_DATA
(
  OBJECT_ID        VARCHAR2(44 BYTE),
  RAW_DATA_ID      NUMBER(10),
  BATCH_TYPE_CODE  NUMBER(2),
  STUD_REF_NO      NUMBER(10),
  BATCH_ID         NUMBER(16),
  ENVELOPE_ID      NUMBER(4),
  SCAN_DATE        DATE,
  PROC_ERROR       VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  URGENT           VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  PROVIDER_ID      NUMBER(10),
  LEARNER_ID       VARCHAR2(10 BYTE),
  AUD_ACTION       VARCHAR2(30 BYTE),
  AUD_TIMESTAMP    DATE,
  AUD_USER         VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP PUBLIC SYNONYM EDM_COMPLETE_TEST;

CREATE PUBLIC SYNONYM EDM_COMPLETE_TEST FOR EDM.EDM_COMPLETE$TEST_DATA;


GRANT SELECT ON  EDM.EDM_COMPLETE$TEST_DATA TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  EDM.EDM_COMPLETE$TEST_DATA TO U207511;