-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/EDM_TEMP.sql $
-- $Author: $
-- $Date: 2010-01-19 09:45:47 +0000 (Tue, 19 Jan 2010) $
-- $Revision: 4600 $

DROP TABLE EDM.EDM_TEMP CASCADE CONSTRAINTS
/

--
-- EDM_TEMP  (Table) 
--
CREATE TABLE EDM.EDM_TEMP
(
  OBJECT_ID             VARCHAR2(44 BYTE),
  SESSION_CODE          NUMBER(4),
  DOCUMENT_TYPE_CODE    VARCHAR2(16 BYTE),
  DOCUMENT_NAME         VARCHAR2(40 BYTE),
  DOCUMENT_TYPE_COUNT   NUMBER(3),
  ATTACHMENT_TYPE_CODE  VARCHAR2(10 BYTE),
  RESCAN_REQUEST_ID     NUMBER(10)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- Administer grants
-- 
GRANT ALTER ON EDM.EDM_TEMP TO PUBLIC
/

GRANT DEBUG ON EDM.EDM_TEMP TO PUBLIC
/

GRANT QUERY REWRITE ON EDM.EDM_TEMP TO PUBLIC
/

GRANT ON COMMIT REFRESH ON EDM.EDM_TEMP TO PUBLIC
/

GRANT DELETE ON EDM.EDM_TEMP TO PUBLIC
/

GRANT UPDATE ON EDM.EDM_TEMP TO PUBLIC
/

GRANT SELECT ON EDM.EDM_TEMP TO PUBLIC
/

GRANT INSERT ON EDM.EDM_TEMP TO PUBLIC
/

GRANT INDEX ON EDM.EDM_TEMP TO PUBLIC
/

GRANT REFERENCES ON EDM.EDM_TEMP TO PUBLIC
/

-- 
-- Create public synonym: 
-- 
DROP PUBLIC SYNONYM EDM_TEMP
/

CREATE PUBLIC SYNONYM EDM_TEMP FOR EDM.EDM_TEMP
/
