-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
-- 001      15/04/2010      A.Bowman (SAAS)                 Added new columns provider_id, learner_id and triggers etc
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/EDM_COMPLETE.sql $
-- $Author: $
-- $Date: 2010-04-15 10:11:31 +0100 (Thu, 15 Apr 2010) $
-- $Revision: 5089 $

DROP TABLE EDM.EDM_COMPLETE CASCADE CONSTRAINTS PURGE;

CREATE TABLE EDM.EDM_COMPLETE
(
  OBJECT_ID        VARCHAR2(44 BYTE),
  RAW_DATA_ID      NUMBER(10),
  BATCH_TYPE_CODE  NUMBER(2),
  STUD_REF_NO      NUMBER(10),
  BATCH_ID         NUMBER(16),
  ENVELOPE_ID      NUMBER(4),
  SCAN_DATE        DATE,
  PROC_ERROR       VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  URGENT           VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  PROVIDER_ID      NUMBER(10),
  LEARNER_ID       VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          504K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER EDM.WMTbd2kszh AFTER INSERT ON EDM.EDM_COMPLETE FOR EACH ROW
BEGIN INSERT INTO WMBbd2kszh (OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT, wm_rowid) VALUES (:new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT, WMSbd2kszh.NEXTVAL); END;
/
SHOW ERRORS;



CREATE OR REPLACE TRIGGER EDM.EDM_COMPLETE$AUDIT_TRIG
 AFTER INSERT OR UPDATE ON EDM.EDM_COMPLETE FOR EACH ROW
DECLARE 
v_operation VARCHAR2(10) := NULL;
BEGIN
IF INSERTING THEN
   v_operation := 'INS';
ELSIF UPDATING THEN
   v_operation := 'UPD';
END IF;
IF INSERTING OR UPDATING THEN
  INSERT INTO EDM_COMPLETE$TEST_DATA (
    OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT, PROVIDER_ID, LEARNER_ID
    ,aud_action,aud_timestamp,aud_user)  
  VALUES (
    :new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT, :new.PROVIDER_ID, :new.LEARNER_ID
    ,v_operation,SYSDATE,USER);
END IF; 
END;
/
SHOW ERRORS;



CREATE OR REPLACE TRIGGER EDM.WMTbeii1ks AFTER INSERT ON EDM.EDM_COMPLETE FOR EACH ROW
BEGIN INSERT INTO WMBbeii1ks (OBJECT_ID, RAW_DATA_ID, BATCH_TYPE_CODE, STUD_REF_NO, PROVIDER_ID, LEARNER_ID, BATCH_ID, ENVELOPE_ID, SCAN_DATE, PROC_ERROR, URGENT, wm_rowid) VALUES (:new.OBJECT_ID, :new.RAW_DATA_ID, :new.BATCH_TYPE_CODE, :new.STUD_REF_NO, :new.PROVIDER_ID, :new.LEARNER_ID, :new.BATCH_ID, :new.ENVELOPE_ID, :new.SCAN_DATE, :new.PROC_ERROR, :new.URGENT, WMSbeii1ks.NEXTVAL); END;
/
SHOW ERRORS;



DROP PUBLIC SYNONYM EDM_COMPLETE;

CREATE PUBLIC SYNONYM EDM_COMPLETE FOR EDM.EDM_COMPLETE;


ALTER TABLE EDM.EDM_COMPLETE ADD (
  CONSTRAINT EDM_COMPLETE_CC02
 CHECK (urgent in ('Y', 'N')));

ALTER TABLE EDM.EDM_COMPLETE ADD (
  CONSTRAINT EDM_COMPLETE_CC01
 CHECK (proc_error in ('Y', 'N')));


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG ON  EDM.EDM_COMPLETE TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  EDM.EDM_COMPLETE TO U207511;
ALTER TABLE EDM.EDM_COMPLETE ADD (
  CONSTRAINT EDM_COMPLETE_CC01
 CHECK (proc_error in ('Y', 'N')))
/

ALTER TABLE EDM.EDM_COMPLETE ADD (
  CONSTRAINT EDM_COMPLETE_CC02
 CHECK (urgent in ('Y', 'N')))
/

--
-- Administer grants
-- 
GRANT DEBUG ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT QUERY REWRITE ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT ON COMMIT REFRESH ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT REFERENCES ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT UPDATE ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT SELECT ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT INSERT ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT INDEX ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT DELETE ON EDM.EDM_COMPLETE TO PUBLIC
/

GRANT ALTER ON EDM.EDM_COMPLETE TO PUBLIC
/

-- 
-- Create public synonym: 
-- 
DROP PUBLIC SYNONYM EDM_COMPLETE
/

CREATE PUBLIC SYNONYM EDM_COMPLETE FOR EDM.EDM_COMPLETE
/
