-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                  Desc.
--          08/01/2008      S Durkin (Sopra UK)     Initial Version
-- 001      11/02/2010      A.Bowman (SAAS)         Added data insert
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3:3690/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/EDM_BATCH_WF.sql $
-- $Author: $
-- $Date: 2012-02-09 13:13:45 +0000 (Thu, 09 Feb 2012) $
-- $Revision: 7681 $

ALTER TABLE EDM.EDM_BATCH_WF
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EDM.EDM_BATCH_WF CASCADE CONSTRAINTS
/

--
-- EDM_BATCH_WF  (Table) 
--
CREATE TABLE EDM.EDM_BATCH_WF
(
  BATCH_TYPE_CODE         NUMBER(2)             NOT NULL,
  BATCH_TYPE_DESCRIPTION  VARCHAR2(50 BYTE)     NOT NULL,
  WORK_ITEM_INDICATOR     VARCHAR2(1 BYTE),
  FIRST_SESSION           NUMBER(4),
  REPORTED_AS             VARCHAR2(1 BYTE),
  RAW_DATA_REQD           VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- EDM_BATCH_WF_PK  (Index) 
--
CREATE UNIQUE INDEX EDM_BATCH_WF_PK ON EDM.EDM_BATCH_WF
(BATCH_TYPE_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table EDM_BATCH_WF 
-- 
ALTER TABLE EDM.EDM_BATCH_WF ADD (
  CONSTRAINT EDM_BATCH_WF_CC01
 CHECK (raw_data_reqd  in ('Y','N')))
/

ALTER TABLE EDM.EDM_BATCH_WF ADD (
  CONSTRAINT EDM_BATCH_WF_UK01
 CHECK (work_item_indicator in ('E','O','L','D','I','B','S','G','R','U','V','T','F','H','P','W')))
/

ALTER TABLE EDM.EDM_BATCH_WF ADD (
  CONSTRAINT EDM_BATCH_WF_PK
 PRIMARY KEY
 (BATCH_TYPE_CODE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          500K
                NEXT             500K
                MINEXTENTS       1
                MAXEXTENTS       99
                PCTINCREASE      1
                FREELISTS        1
                FREELIST GROUPS  1
               ))
/


--
-- Administer grants
-- 
GRANT ALTER ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT DELETE ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT INDEX ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT INSERT ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT DEBUG ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT UPDATE ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT REFERENCES ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT ON COMMIT REFRESH ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT QUERY REWRITE ON EDM.EDM_BATCH_WF TO PUBLIC
/
GRANT SELECT ON EDM.EDM_BATCH_WF TO PUBLIC
/

-- 
-- Create public synonym: 
-- 
DROP PUBLIC SYNONYM EDM_BATCH_WF
/

CREATE PUBLIC SYNONYM EDM_BATCH_WF FOR EDM.EDM_BATCH_WF
/

---
--- Insert Data
---

INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
51, 'SAS3 2008/2009', 'E', 2008, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
52, 'SAS7 2008/2009', 'E', 2008, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
53, 'AB4 Travel Expenses Claim', 'B', 2008, 'C', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
54, 'Shortened Application', 'U', NULL, 'C', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
55, 'Scanned General Correspondence', 'S', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
56, 'DSA Application', 'D', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
57, 'DSA Correspondence', 'I', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
58, 'Overpayment Correspondence', 'V', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
59, 'Fee Loan Application', 'F', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
60, 'Top Up Student Loan Application', 'P', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
61, 'Manual Registration', 'O', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
70, 'StEPS ILA500 Learner Application', 'S', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
71, 'StEPS ILA500 Learner Correspondence', 'S', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
72, 'StEPS ILA500 Learning Provider Correspondence', 'S', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
64, 'NMSB1 2009/2010', 'E', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
62, 'Placement Expense Claims (AB24)', 'A', NULL, 'C', 'N'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
63, 'NMSB Shortened Application', 'U', NULL, 'C', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
31, 'SAS3_ONLINE', 'W', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
32, 'SAS7_ONLINE', 'W', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
33, 'NMSB_ONLINE', 'W', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
65, 'SAS3 2009/2010', 'E', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
66, 'SAS7 2009/2010', 'E', 2009, 'A', 'Y'); 
INSERT INTO EDM_BATCH_WF ( BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR,
FIRST_SESSION, REPORTED_AS, RAW_DATA_REQD ) VALUES ( 
67, 'NMSB1 2010/2011', 'E', 2010, 'A', 'Y');
INSERT INTO EDM.EDM_BATCH_WF values
(34,'CORRES_ONLINE','W',NULL,'C','N');
INSERT INTO EDM.EDM_BATCH_WF values
(35,'DSA_ONLINE','W',NULL,'C','N');
commit;
 
