DROP TABLE WEB_EDM_COMPLETE_HOLD CASCADE CONSTRAINTS;

CREATE TABLE WEB_EDM_COMPLETE_HOLD
(
  OBJECT_ID        VARCHAR2(44 BYTE),
  RAW_DATA_ID      NUMBER(10),
  BATCH_TYPE_CODE  NUMBER(2),
  STUD_REF_NO      NUMBER(10),
  BATCH_ID         NUMBER(16),
  ENVELOPE_ID      NUMBER(4),
  SCAN_DATE        DATE,
  PROC_ERROR       VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  URGENT           VARCHAR2(1 BYTE)             DEFAULT 'N'                   NOT NULL,
  PROVIDER_ID      NUMBER(10),
  LEARNER_ID       VARCHAR2(10 BYTE),
  AUD_TIMESTAMP    DATE DEFAULT Sysdate
)
TABLESPACE EDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



GRANT SELECT ON WEB_EDM_COMPLETE_HOLD TO PUBLIC;

