DROP TABLE EDM.WEB_EDM_TEMP_HOLD CASCADE CONSTRAINTS;

CREATE TABLE EDM.WEB_EDM_TEMP_HOLD
(
  OBJECT_ID             VARCHAR2(44 BYTE),
  SESSION_CODE          NUMBER(4),
  DOCUMENT_TYPE_CODE    VARCHAR2(16 BYTE),
  DOCUMENT_NAME         VARCHAR2(40 BYTE),
  DOCUMENT_TYPE_COUNT   NUMBER(3),
  ATTACHMENT_TYPE_CODE  VARCHAR2(10 BYTE),
  RESCAN_REQUEST_ID     NUMBER(10),
  AUD_TIMESTAMP         DATE DEFAULT Sysdate
)
TABLESPACE EDM_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

GRANT SELECT ON EDM.WEB_EDM_TEMP_HOLD TO PUBLIC;


