SET DEFINE OFF;

Insert into COUNTRY
   (COUNTRY_CODE, SHORT_NAME, CATEGORY, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, NEW_CATEGORY, LAST_UPDATED_BY, LAST_UPDATED_ON, 
    UK_COUNTRY, IS_ACTIVE)
 Values
   (970, NULL, NULL, 'STATELESS', 'STATELESS', 
    'N', 'N', NULL, 'SGAS', SYSDATE, 
    'N', 'N');

Insert into SGAS.NATIONALITY 
   (COUNTRY_CODE, NATIONALITY_NAME, NATIONALITY_REGION, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE)
 Values
   (970, 'STATELESS', 'ROW', 'SGAS', sysdate, 'Y');

COMMIT;