-- Adhoc to add foreign key references
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      28.04.2010  A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

ALTER TABLE SGAS.STUD_CRSE_YEAR ADD (
  CONSTRAINT F1_STCY 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.STUD_CRSE_YEAR ADD (
  CONSTRAINT F2_STCY 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_SESSION ADD (
  CONSTRAINT F1_STS 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_SESSION ADD (
  CONSTRAINT F2_STS 
 FOREIGN KEY (JA_CASE_ID) 
 REFERENCES SGAS.JA_CASE (JA_CASE_ID));

ALTER TABLE SGAS.STUD_SESSION ADD (
  CONSTRAINT F3_STS 
 FOREIGN KEY (BEN1_ID) 
 REFERENCES SGAS.BENEFACTOR (BEN_ID));

ALTER TABLE SGAS.STUD_SESSION ADD (
  CONSTRAINT F4_STS 
 FOREIGN KEY (BEN2_ID) 
 REFERENCES SGAS.BENEFACTOR (BEN_ID));

ALTER TABLE SGAS.STUD ADD (
  CONSTRAINT F1_ST
 FOREIGN KEY (BIRTH_COUNTRY_CODE) 
 REFERENCES SGAS.COUNTRY (COUNTRY_CODE));

ALTER TABLE SGAS.STUD ADD (
  CONSTRAINT F2_ST
 FOREIGN KEY (NATION_COUNTRY_CODE) 
 REFERENCES SGAS.COUNTRY (COUNTRY_CODE));

ALTER TABLE SGAS.STUD ADD (
  CONSTRAINT F3_ST
 FOREIGN KEY (RESIDENCE_COUNTRY_CODE) 
 REFERENCES SGAS.COUNTRY (COUNTRY_CODE));

ALTER TABLE SGAS.STUD_CONT_DETAILS ADD (
  CONSTRAINT F1_STCD
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_DEPENDANT ADD (
  CONSTRAINT F1_STD
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.STUD_DEPENDANT ADD (
  CONSTRAINT F2_STD
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_DEPENDANT ADD (
  CONSTRAINT F1_STD
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.STUD_HOME_ADDR ADD (
  CONSTRAINT F1_STHA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_TERM_ADDR ADD (
  CONSTRAINT F1_STTA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_NOMINEE ADD (
  CONSTRAINT F1_STN
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_NOMINEE ADD (
  CONSTRAINT F2_STN
 FOREIGN KEY (NOMINEE_ID) 
 REFERENCES SGAS.NOMINEE (NOMINEE_ID));

ALTER TABLE SGAS.STUD_NOTES ADD (
  CONSTRAINT F1_STNS
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_RATE ADD (
  CONSTRAINT F1_STR
 FOREIGN KEY (STUD_AWARD_TYPE_ID) 
 REFERENCES SGAS.STUD_AWARD_TYPE (STUD_AWARD_TYPE_ID));

ALTER TABLE SGAS.BENEFACTOR_DEPENDANT ADD (
  CONSTRAINT F1_BDE
 FOREIGN KEY (BEN_ID) 
 REFERENCES SGAS.BENEFACTOR (BEN_ID));

ALTER TABLE SGAS.BENEFACTOR_INCOME ADD (
  CONSTRAINT F1_BEI 
 FOREIGN KEY (BEN_ID) 
 REFERENCES SGAS.BENEFACTOR (BEN_ID));

ALTER TABLE SGAS.DSA_ALLOWANCE ADD (
  CONSTRAINT F1_DSAA 
 FOREIGN KEY (DSA_APPLICATION_ID) 
 REFERENCES SGAS.DSA_APPLICATION (ID));

ALTER TABLE SGAS.DSA_ALLOWANCE ADD (
  CONSTRAINT F2_DSAA 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.DSA_ALLOWANCE ADD (
  CONSTRAINT F3_DSAA 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES SGAS.STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));

ALTER TABLE SGAS.DSA_ALLOWANCE ADD (
  CONSTRAINT F4_DSAA 
 FOREIGN KEY (DSA_CATEGORY_ID) 
 REFERENCES SGAS.DSA_CATEGORY (DSA_CATEGORY_ID));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F1_DSAP 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F2_DSAP 
 FOREIGN KEY (DISABILITY_TYPE_ID) 
 REFERENCES SGAS.DISABILITY_TYPE (DISABILITY_TYPE_ID));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F3_DSAP 
 FOREIGN KEY (DSA_STUDENT_TYPE_ID) 
 REFERENCES SGAS.DSA_STUDENT_TYPE (DSA_STUDENT_TYPE_ID));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F4_DSAP 
 FOREIGN KEY (DSA_REFERRAL_REASON_ID) 
 REFERENCES SGAS.DSA_REFERRAL_REASON (DSA_REFERRAL_REASON_ID));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F5_DSAP 
 FOREIGN KEY (ASSESSMENT_CENTRE_ID) 
 REFERENCES SGAS.DSA_ASSESSMENT_CENTRE (DSA_ASSESSMENT_CENTRE_ID));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F6_DSAP 
 FOREIGN KEY (DSA_REJECTION_REASON_ID) 
 REFERENCES SGAS.DSA_REJECTION_REASON (DSA_REJECTION_REASON_ID));

ALTER TABLE SGAS.DSA_PAYMENT ADD (
  CONSTRAINT F1_DSAPAY 
 FOREIGN KEY (AWARD_INSTALMENT_ID) 
 REFERENCES SGAS.AWARD_INSTALMENT (AWARD_INSTALMENT_ID));

ALTER TABLE SGAS.DSA_PAYMENT ADD (
  CONSTRAINT F2_DSAPAY 
 FOREIGN KEY (DSA_ALLOWANCE_ID) 
 REFERENCES SGAS.DSA_ALLOWANCE (ID));

ALTER TABLE SGAS.DSA_PAYMENT ADD (
  CONSTRAINT F3_DSAPAY 
 FOREIGN KEY (DSA_PAYMENT_STATUS_ID) 
 REFERENCES SGAS.DSA_PAYMENT_STATUS (DSA_PAYMENT_STATUS_ID));

ALTER TABLE SGAS.STUD_TRACK ADD (
  CONSTRAINT F1_STT
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.AWARD ADD (
  CONSTRAINT F1_AWA
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES SGAS.STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));

ALTER TABLE SGAS.AWARD ADD (
  CONSTRAINT F2_AWA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.AWARD_INSTALMENT ADD (
  CONSTRAINT F1_AWI
 FOREIGN KEY (AWARD_ID) 
 REFERENCES SGAS.AWARD (AWARD_ID));

ALTER TABLE SGAS.NMSB_SPEC_ARR ADD (
  CONSTRAINT F1_NSA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.NMSB_SPEC_ARR ADD (
  CONSTRAINT F2_NSA
 FOREIGN KEY (REASON_CODE) 
 REFERENCES SGAS.NMSB_CONTINUATION_REASON (NMSB_CONT_ID));