-- Adhoc to add foreign key references
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      10.11.2010  A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

ALTER TABLE SGAS.STUD_CRSE_YEAR ADD (
  CONSTRAINT F2_STCY 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_CONT_DETAILS ADD (
  CONSTRAINT F1_STCD
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_DEPENDANT ADD (
  CONSTRAINT F2_STD
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_HOME_ADDR ADD (
  CONSTRAINT F1_STHA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_TERM_ADDR ADD (
  CONSTRAINT F1_STTA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F1_DSAP 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_TRACK ADD (
  CONSTRAINT F1_STT
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.AWARD ADD (
  CONSTRAINT F2_AWA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.NMSB_SPEC_ARR ADD (
  CONSTRAINT F1_NSA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_NOMINEE ADD (
  CONSTRAINT F2_STN
 FOREIGN KEY (NOMINEE_ID) 
 REFERENCES SGAS.NOMINEE (NOMINEE_ID));

ALTER TABLE SGAS.SCOAP_JOURNAL_LINES ADD (
  CONSTRAINT F1_SJ 
 FOREIGN KEY (DPJ_BATCH_REF) 
 REFERENCES SGAS.SCOAP_BATCHES (DPB_BATCH_REF));

ALTER TABLE SGAS.SCOAP_PAYMENTS ADD (
  CONSTRAINT F1_SP 
 FOREIGN KEY (DPP_BATCH_REF) 
 REFERENCES SGAS.SCOAP_BATCHES (DPB_BATCH_REF));



