-- Adhoc to add foreign key references
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      03.09.2010  A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

ALTER TABLE SGAS.DSA_APPLICATION ADD (
  CONSTRAINT F1_DSAP 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));
 
ALTER TABLE SGAS.NMSB_SPEC_ARR ADD (
  CONSTRAINT F1_NSA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));
 
ALTER TABLE SGAS.AWARD ADD (
  CONSTRAINT F2_AWA
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.DSA_ALLOWANCE ADD (
  CONSTRAINT F2_DSAA 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));