-- Adhoc to add foreign key references which appear to be missing from all environments
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      26.10.2010  A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

ALTER TABLE SGAS.STUD_CRSE_YEAR ADD (
  CONSTRAINT F1_STCY 
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.STUD_SESSION ADD (
  CONSTRAINT F1_STS 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_DEPENDANT ADD (
  CONSTRAINT F1_STD
 FOREIGN KEY (STUD_SESSION_ID) 
 REFERENCES SGAS.STUD_SESSION (STUD_SESSION_ID));

ALTER TABLE SGAS.STUD_NOMINEE ADD (
  CONSTRAINT F1_STN
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

ALTER TABLE SGAS.STUD_NOTES ADD (
  CONSTRAINT F1_STNS
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES SGAS.STUD (STUD_REF_NO));

