ALTER TABLE SGAS.STUD_CRSE_YEAR 
ADD student_status varchar2(3);

ALTER TABLE SGAS.STUD_CRSE_YEAR ADD (
  CONSTRAINT F3_STCY 
 FOREIGN KEY (STUDENT_STATUS) 
 REFERENCES SGAS.STUDENT_STATUS (LEGACY_CODE));