
TRUNCATE TABLE std_letters;
alter table std_letters DISABLE constraint F1_ST_LTR;

TRUNCATE TABLE std_letters_categories;

Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('BLA', 'Blank');
Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('DSA', 'Disabled Student Application');
Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('INT', 'Internal');
Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('CIBEN', 'CI Benefactor');
Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('BEN', 'Benefactor');
Insert into SGAS.STD_LETTERS_CATEGORIES
   (CAT_CODE, CAT_DESCRIPTION)
 Values
   ('OVRP', 'Over Payment');

alter table std_letters ENABLE constraint F1_ST_LTR;

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR01', 'REQ H/I FORM', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR01a', 'REQ H/I FORM (OVERSEAS)', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR02', 'REQ SINGLE PARENT EVIDENCE', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR03', 'REQ SINGLE PARENT EV - INCORRECT DOCS RECEIVED', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR04', 'REQ SINGLE PARENT EVIDENCE AND INCOME DOCS', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR05', 'REQ 17-18 INCOME DOCS', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR05a', 'REQ 17-18 INCOME DOCS (OVERSEAS)', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR06', 'REQ 17-18 INCOME DOCS - INCORRECT DOCS RECEIVED', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR07', 'REQ MAINTENANCE EVIDENCE', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR08', 'ESTRANGEMENT - REQ H/I FORM', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BENEFACTOR09', 'REQ PROOF OF LEGAL GUARDIANSHIP', 'BEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'BLANK', 'BLANK SHELL', 'BLA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR01', 'INCOME FOR TAX YR END 5/4/16 ALREADY DECLARED', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR01a', 'INC FOR TAX YR END 5/4/16 ALREADY DECLARED ABROAD', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR02', 'INCOME FOR TAX YR ENDING 5/4/16 NOT DECLARED', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR02a', 'INC FOR TAX YR ENDING 5/4/16 NOT DECLARED ABROAD', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR03', 'REFUSE - 15% DROP NOT EXPECTED', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR04', 'REFUSE - NO DROP IN INCOME BRACKET', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR05', 'REFUSE DUE REASON FOR DROP', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR06', 'CONFIRM CI ASSESSMENT MADE', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR07', '16/17 CI - REQ H/I FORM AND INCOME DOCS', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR07a', '16/17 CI - REQ H/I FORM AND INCOME DOCS (OVERSEAS)', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'CIBENEFACTOR08', '16/17 FINALISED - REVERT', 'CIBEN');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'DSALETTER01', 'CONFIRMATION OF PAYMENT OF DSA', 'DSA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'DSALETTER02', 'APPLICATION RETURNED - INCOMPLETE', 'DSA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'DSALETTER03', 'DSA BANK ACCOUNT', 'DSA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'DSALETTER04', 'O/P - NO RECEIPTS', 'DSA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'DSALETTER05', 'O/P - PARTIAL RECEIPTS', 'DSA');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'INT01', 'CURRENT INCOME CALCULATOR', 'INT');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'INT02', 'O/P ADJUSTMENT FORM', 'INT');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP01', 'WITHDRAWAL', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP02', 'W/D AFTER RECOVERY - ORIGINAL O/P DECREASED', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP03', 'W/D AFTER RECOVERY - ORIGINAL O/P INCREASED', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP04', 'NON-ATTENDANCE', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP05', 'NON-ATT AFTER RECOVERY - NO ADDITIONAL O/P', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP06', 'NON-ATT AFTER RECOVERY - ADDITIONAL O/P', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP07', 'NO LONGER ELIGIBLE AS NOW PART-TIME', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP08', 'NO LONGER ELIGIBLE DUE TO COURSE CHANGE', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP09', 'RWA, +1 ALREADY USED', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP10', 'FINALISATION - REQUEST REPAYMENT', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP11', '16-17 CURRENT INCOME - REVERT AND REQ REPAYMENT', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP12', 'DEPENDANT''S GRANT INCOME HIGHER THAN ESTIMATE', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP13', 'NMSB CHILDCARE GRANT', 'OVRP');

Insert into SGAS.STD_LETTERS (
 DOC_NAME, DOC_DESC, CAT_CODE)
Values (
 'OVRP14', 'RECOVER PART OF O/P FROM CURRENT SESSION', 'OVRP');

