
DROP SEQUENCE SGAS.SHORT_APP_SEQ;

CREATE SEQUENCE SGAS.SHORT_APP_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  ORDER;


DROP PUBLIC SYNONYM SHORT_APP_SEQ;

CREATE PUBLIC SYNONYM SHORT_APP_SEQ FOR SGAS.SHORT_APP_SEQ;

GRANT SELECT ON  SGAS.SHORT_APP_SEQ TO PUBLIC;

INSERT INTO CONFIG_DATA ( ITEM_NAME, CVAL, NVAL ) VALUES ( 
'SHORT_APP_DEST', '/projects/sgas/temp/short_app_files/', NULL); 
COMMIT;