CREATE INDEX SGAS.S1_PI ON SGAS.PAYMENT_INSTALMENT
(AWARD_INSTALMENT_ID)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;

CREATE INDEX SGAS.S8_AW ON SGAS.AWARD
(STUD_CRSE_YEAR_ID, AWARD_SRC)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;

