Insert into CONFIG_EDM
   (DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED, 
    REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('LPG_EVID_EMAIL', 'Lone Parent Evidence (email)', 'O', NULL, NULL, 
    NULL, 'MSG', 'SGAS', TO_DATE('04/08/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into CONFIG_EDM
   (DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED, 
    REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('LPG_EVID_SCAN', 'Lone Parent Evidence (scanned)', 'E', 'Y', 'Y', 
    'Y', 'TIFF', 'SGAS', TO_DATE('04/08/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));

Insert into CONFIG_EDM
   (DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED, 
    REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('LPG_EVID_WORD', 'Lone Parent Evidence (word doc)', 'O', NULL, NULL, 
    NULL, 'DOC', 'SGAS', TO_DATE('04/08/2013 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
