CREATE INDEX SGAS.S1_PI ON SGAS.PAYMENT_INSTALMENT
(AWARD_INSTALMENT_ID)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;

CREATE INDEX SGAS.S8_AW ON SGAS.AWARD
(STUD_CRSE_YEAR_ID, AWARD_SRC)
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL;

INSERT INTO marital_status
            (legacy_id, legacy_code, descript
            )
     VALUES (0, 'K', 'Civil Parntership'
            );
            
ALTER TABLE SGAS.STUD DROP CONSTRAINT ST_MARITAL_STATUS;            
            
ALTER TABLE SGAS.STUD ADD (
  CONSTRAINT ST_MARITAL_STATUS
 CHECK ( MARITAL_STATUS IN('S','M','D','P','W','E','K')));



