
UPDATE PAYEE_TYPE SET TYPE = 'S', DESCRIPTION = 'STUDENT' WHERE payee_type_id = 1;
UPDATE PAYEE_TYPE SET TYPE = 'N', DESCRIPTION = 'NOMINEE' WHERE payee_type_id = 2;
UPDATE PAYEE_TYPE SET TYPE = 'I', DESCRIPTION = 'INSTITUTION' WHERE payee_type_id = 3;

COMMIT;
