ALTER TABLE SGAS.SLC_DATA ADD (
  CONSTRAINT F1_SLCD 
 FOREIGN KEY (STUD_CRSE_YEAR_ID) 
 REFERENCES SGAS.STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID));
 
ALTER TABLE SGAS.STUD_CONT_DETAILS ADD (
  CONSTRAINT SCD_CONT_IND
 CHECK (CONTACT_IND IN (1, 2)));
 
ALTER TABLE SGAS.STUD_CONT_DETAILS ADD (
  CONSTRAINT STUD_CONT_DETAILS_PK
 PRIMARY KEY
 (STUD_REF_NO, CONTACT_IND)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));
               
CREATE BITMAP INDEX 
scd_bitmap_idx
ON STUD_CONT_DETAILS (CONTACT_IND);