Insert into SGAS.DSA_CATEGORY (CODE, DESCRIPTION, TYPE_ID, LAST_UPDATED_BY) Values ('310', 'Buddy', 3, 'SGAS');
Insert into SGAS.DSA_CATEGORY (CODE, DESCRIPTION, TYPE_ID, LAST_UPDATED_BY) Values ('311', 'Mentor', 3, 'SGAS');
Insert into SGAS.DSA_CATEGORY (CODE, DESCRIPTION, TYPE_ID, LAST_UPDATED_BY) Values ('312', 'IT Training', 3, 'SGAS');
COMMIT;