truncate table std_letters;
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD01', 'COMP  ABROAD- EXCHANGE', 'ABR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD02', 'COMP ABROAD-NON EXCHANGE', 'ABR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD03', 'VOL ABROAD- EXCHANGE', 'ABR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD04', 'VOL  ABROAD-NON EXCHANGE', 'ABR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD05', 'LANGUAGE ASSISTANT', 'ABR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP01', 'APP-RECEIVED AFTER CLOSING DATE', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP02', 'APP-MISSING EDUCATION/EMPLOYMENT DETAILS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP03', 'APP-INCOMPLETE INCOME- AB36 REQUIRED', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP03A', 'APP-INCOMPLETE INCOME-SEND AB36 (ABROAD)', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP03B', 'APP-INCOMPLETE - DETAILS FROM STUDENT FOR PARENT', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP04', 'APP-EVIDENCE THAT STUDENT HAS A PARTNER', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP05', 'APP-COURSE NOT VALID ', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP06', 'APP-REQ PROOF OF SEPARATION FROM STUDENT', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP07', 'APP-REQ PROOF OF SEPARATION FROM STUD FOR PARENT', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP08', 'APP-REQ PROOF OF SEPARATION FROM PARENT ETC', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP09', 'APP-NO RESIDENCE DETAILS-SEND FORM', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP10', 'APP-WAITING ON TERM DATES FROM THE SLC', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP11', 'APP-INVALID BANK DETAILS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP12', 'APP-WRONG SESSION APPLICATION', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP13', 'APP-SAS 7 INCORRECT-SAS 3 FORM ENCLOSED', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP14', 'APP-NO RESIDENCE OR EMP/EDUCATION DETAILS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP15', 'APP-NON INCOME-ASSESSED-SYSTEM RESTRICTED', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP16', 'APP-REQ FOR OFFER LETTER-DANCE AND DRAMA', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP17', 'APP-INCOMPLETE INCOME  PRV YRS INC', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP18', 'APP-INCOMPLETE INCOME  PRV YRS INC (ABROAD)', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP19', 'APP-WITHDRAWAL REQUEST INCOME DOCS TO FINALISE', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP20', 'APP-DROP IN INCOME REQ DOCS-NON INC ASS RESTRICT', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP21', 'APP-UPDATED BANK DETAILS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP22', 'APP-INCORRECT DOCS FOR FINALISING INCOME DETAILS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP22A', 'APP-INCORRECT DOCS FOR FINALISING DEDUCTIONS', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP23', 'APP-NOT APPLIED FOR FULL ENTITLEMENT', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP24', 'APP-REQ FOR DOCS TO BE TRANSLATED INTO ENGLISH', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP25', 'APP-GRO BIRTH CERTIFICATE REQUEST', 'APP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT01', 'ATTENDANCE DATA - REVOKE AWARD', 'ATT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT02', 'ATTENDANCE DATA - REVOKE AWARD O/P', 'ATT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('BLANK', 'BLANK SHELL', 'BLA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CARE01', 'SEND OUT CARE LEAVERS FORM', 'CAR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE01', 'COURSE NOT YET VALIDATED', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE02', 'PREVIOUS FUNDING AND QUALIFIED', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE03', '2ND DEGREE DENTISTRY', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE04', 'COURSE CHANGE', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE05', 'AHP SUPPORT FOR GRADUATES', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE06', 'AHP SUPPORT-COURSE CHANGE', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE07', 'REFUSAL-ACCELERATED LLB', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE08', 'ARCHITECTURE STUDENTS', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE09', '4 YR DEGREE STUDENTS CONVERTING TO 5 YR DEGREE', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE10', 'ALREADY HOLDS A HIGHER PG QUALIFICATION', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE11', 'HNC HEALTH CARE REFUSAL - APPLY TO SGHD FOR FEES', 'COUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC01', 'CI-SEND LETTER TO PARENT', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC02', 'CI-SEND LETTER TO PARENT (ABROAD)', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC03', 'CI-15% DROP NOT EXPECTED', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC04', 'CI- 15% BUT SAME INCOME BRACKET', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC05', 'CI-15% DROP EXPECTED-LETTER TO STUDENT', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC06', 'CI-15% DROP EXPECTED-LETTER TO PARENT', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC07', 'CI-REQ FOR ACTUAL INC- LETTER TO STUDENT 12-13', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC08', 'CI-REQ FOR ACTUAL INC-LETTER TO PARENT 12-13', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC09', 'CI-REQ  ACTUAL INC-LETTER TO PARENT (ABROAD) 12-13', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC10', 'CI-FINAL-REVERT BACK-LETTER TO STUDENT 12-13', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC11', 'CI- FINAL-REVERT BACK-LETTER TO PARENT 12-13', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC12', 'CI - CANT OFFER DUE TO REASON FOR DROP IN INCOME', 'CURIN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP01', 'DEPENDANTS'' GRANT-INCOME TOO HIGH', 'DEP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP02', 'DEPENDANTS'' GRANT-REQUEST EST OF INCOME', 'DEP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP03', 'ADVANCE OF LIVING COST GRANTS', 'DEP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP04', 'DEPENDANTS'' GRANT - FINALISE INCOME', 'DEP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA01', 'CONFIRMATION OF PAYMENT OF DSA', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA02', 'SAS3 NEEDED-NEW STUDENT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA03', 'SAS3 NEEDED-CONTINUING STUDENT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA04', 'SAS3 STILL TO BE PROCESSED', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA05', 'MORE INFORMATION REQUIRED', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA06', 'APPLICATION RETURNED-INCOMPLETE', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA07', 'APP RECEIVED TOO LATE', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA08', 'REPORT RECEIVED TOO LATE', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA09', 'TELL STUDENT ABOUT REFERRAL TO ACCESS CENTRE', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA10', 'PAYMENT FOR HELPERS', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA11', 'OP-TOTAL OF RECEIPTS LESS THAN PAYMENT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA12', 'REMINDER FOR RECEIPTS-21 DAY LETTER', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA13', 'DSA CLAIM ONLY', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA14', 'NEARING MAXIMUM OF NON-MEDICAL PERSONAL HELP', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA15', 'DSA RECEIPTS-SECOND REMINDER', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA16', 'DSA FORM REQUIRED', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA17', 'DSA RECEIPTS-FINAL REMINDER', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA18', 'DSA TRAVEL ELEMENT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA19', 'ACKNOWLEDGE RECEIPTS', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA20', 'DSA INVOICES ', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA21', 'DSA BANK ACCOUNT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA22', 'LATE REFERRAL FOR NEEDS ASSESSMENT', 'DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DTH01', 'DEATH OF STUDENT-CONFIRM NO MORE MONEY DUE', 'DTH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DTH02', 'DEATH OF STUDENT-MONEY DUE', 'DTH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DTH03', 'DEATH OF PARENT/PARTNER - ADVISE AWARD REASSESSED', 'DTH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU01', 'REFUSAL - EU NON GRADUATING', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU02', 'TUITION FEES-NURSING STUDENT', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU03', 'GRADUATING-EVIDENCE REQUEST', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU04', 'EU NATIONALS O/R IN REST OF UK STUDYING IN SCOT', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU05', 'REFUSAL-PREVIOUS QUALIFCATION', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU06', 'REQUEST PROOF OF ECTS CREDITS', 'EU');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT01', 'EXEMPT PAR CON-REFUSAL - AB36 REQUIRED', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT01A', 'EXEMPT PAR CON-REFUSAL-SEND AB36 (ABROAD)', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT02', 'EVIDENCE OF 3 YRS SELF SUPPORT OR AB36', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT02A', 'EVIDENCE OF 3 YRS SELF SUPPORT OR AB36 (ABROAD)', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT03', 'REQ DOCS FOR PROOF OF ESTRANGEMENT', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT04', 'PARENTS IN ON APP SO ESTRANGEMENT NOT GRANTED', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT05', 'REQ INC DETAILS FROM PARENTS ON BEHALF OF STUDENT', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT06', 'ADVISE STUDENT NO INC FROM PARENTS-OFFER MEETING', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT07', 'ESTRANGEMENT GRANTED', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT08', 'ESTRANGEMENT REFUSED AFTER DOCS RECEIVED', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT09', 'ESTRANGEMENT REFUSED AFTER MEETING', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT10', 'REQ PROOF OF ONGOING ESTRANGEMENT FOR NEW SESSION', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT11', 'STUD REQ FOR MEETING AFTER REFUSING ESTRANGEMENT', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT12', 'REQUEST PROOF OF LEGAL GUARDIANSHIP', 'EXE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN01', 'FORM NOT FILLED IN OR SIGNED', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN02', 'LOAN CONTACTS', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN03', 'LOAN REQUEST', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN04', 'CLMD NMT LOAN WANTS FULL LOAN-SEND AB36', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN04A', 'CLMD NMT LOAN WANTS FULL LOAN-SEND AB36 (ABROAD)', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN05', 'FEE LOAN/HEI BURSARY CONSENT-RUK G', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN06', 'FEE LOAN ADJUSTMENT FORM-SESSION 13-14', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN07', 'LOAN REQUEST AND SEND AB36', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN08', 'LOAN REQUEST AND SEND AB36 (ABROAD)', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN09', 'TOP UP LOAN FORM', 'LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG01', 'REQUEST BC', 'LP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG02', 'REQUEST BC AND SINGLE PARENT EVID', 'LP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG03', 'REQUEST SINGLE PARENT EVID', 'LP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR01', 'REQ EVID-NEW STUDENT', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR02', 'REQ EVID-CONT STUD-FIRST TIME APPLYING FOR MGR', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR03', 'REQ EVID-CONT STUD-ASS FEE ONLY-MGR LAST YR', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR04', 'REQ EVID-CONT STUD-REFUSED MGR LAST YR', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR05', 'ACCEPT-NEW STUD-DEPENDENT', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR06', 'ACCEPT-NEW STUD-INDEPENDENT', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR07', 'ACCEPT-CONT STUD-DEPENDENT', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR08', 'ACCEPT-CONT STUD-INDEPENDENT', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR09', 'REFUSE-NEW STUD', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR10', 'REFUSE-CONT STUD', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR11', 'REFUSE-NOT O/R IN SCOTLAND ON RELEVANT DATE', 'MGR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB01', 'NMSB-DEPENDANTS GRANT-INCOME TOO HIGH', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB02', 'NMSB-O/P OF AWARD DUE TO WITHDRAWAL', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB03', 'NMSB-APPLICATION RECEIVED TOO EARLY', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB04', 'NMSB-REQ SINGLE PARENT EVID', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB05', 'NMSB-CONTINUATION OF SUPPORT', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB06', 'NMSB-DEPS INCOME TOO HIGH-CHILDCARE ALLOW FORM', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB07', 'NMSB-CHILDCARE ALLOWANCE FORM', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB08', 'NMSB-ESTIMATE OF SPOUSE''S INCOME', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB09', 'NMSB OVERPAYMENT-APPLY FOR EXTENSION', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB10', 'NMSB OVERPAYMENT-EXCLUDE PAY DETAILS', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB11', 'NMSB OFFER LETTER', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB12', 'INCORRECT NMSB APPLICATION', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB13', 'NMSB-REQ SINGLE PARENT EVID  CHILDCARE FORM', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB14', 'NMSB-O/P DUE TO NON ATTENDANCE', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB15', 'NMSB-O/P DUE TO OUR ERROR', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB16', 'NMSB-SUSPENSION - WITHDRAW SUPPORT', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES01', 'REFUSAL-NON EEA NATIONAL', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES02', 'REFUSAL-UK NATIONAL', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES03', 'NON EEA NATIONAL-REQUEST EVIDENCE', 'NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OTHR01', 'BACS PAYMENT RETURNED ASK STUDENT WHY ', 'OTH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP01', 'O/P-DEPENDANTS GRANT ON FINALISATION', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP02', 'O/P-DUE TO OUR ERROR', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP03', 'O/P-DUE TO WITHDRAWAL', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP04', 'O/P-FINALISATION-RECOVER FROM NEXT SESSION', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP05', 'O/P-FINALISATION-ASK FOR REPAYMENT', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP06', 'U/P-DUE TO FINALISATION', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP07', 'O/P-PR YR FINALISATION-LIFT REST ON CURRENT YR', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP08', 'O/P WTC-RECOVER FROM NEXT SESSION', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP09', 'O/P WTC-ASK FOR REPAYMENT', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP10', 'O/P DUE TO NON ATTENDANCE ', 'OVRP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG01', 'PG-REFUSAL-ALREADY QUALIFIED', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG02', 'PG-REFUSAL END ON', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG03', 'PG-COURSE NOT FUNDED', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG04', 'PGCE-REFUSAL PREVIOUS ASSISTANCE', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG05', 'PG- APPROVED - FEE LOAN CONFIRMATION', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG06', 'PG -  FEE LOAN - MISSING NINO', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG07', 'PG-OUTSIDE SCOTLAND-CONSIDERING', 'PG');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('REPEAT01', 'REFUSAL-REPEAT -PLUS ONE ALREADY USED', 'REP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES01', 'REFUSAL-EU (NON UK) NATIONAL FULL SUPPORT', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES02', 'REFUSAL-APPLY TO LEA', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES03', 'REFUSAL-NON EEA NATIONAL', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES04', 'REFUSAL-UK NATIONAL', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES05', 'REFUSAL-UK R''TRS STUDY SCOT LAST HOME NOT SCOT', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES06', 'NON EEA NATIONAL-REQUEST EVIDENCE', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES07', 'SEND OUT AB10-S', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES08', 'AWARDED FUNDING BUT LLR RUNS OUT DURING THE COURSE', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES09', 'REQ EVID THEY HAVE APPLIED FOR EXT TO LLR OR ILR', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES10', 'RECEIPT OF UKBA ACKNOWLEDGE LETTER', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES11', 'RECEIPT OF UKBA APPEAL LETTER', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES12', 'LLR RUNS OUT BEFORE CRSE START REQ EVID OF EXT/ILR', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES13', 'REFUSAL - CHILD OF SWISS NATIONAL NOT OR IN SCOT', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES14', 'NEW RUK STUDENT WITH EU NAT ON RELEVANT DATE ', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES15', 'NEW RUK STUDENT WITH EU NAT AFTER RELEVANT DATE ', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES16', 'CONT RUK STUDENT WITH EU NAT AFTER RELEVANT DATE', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES17', 'REQUEST PASSPORT', 'RES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('TRAV01', 'TRAVEL - REQUEST FOR INCOME', 'TRAV');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('TRAV02', 'TRAVEL-REQUEST PROOF OF AIR FARES', 'TRAV');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('Z01', 'COURSE REFUSAL', 'Z0');
COMMIT;
