delete from std_letters
/
SET DEFINE OFF;
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP03', 'O/P-DEPENDANTS GRANT ON FINALISATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP04', 'O/P-DUE TO OUR ERROR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP05', 'O/P-DUE TO WITHDRAWAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP06', 'O/P-DUE TO WITHDRAWAL-SEND AB4');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP07', 'O/P-DUE TO WITHDRAWAL-REDUCE BY TRAVEL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP09', 'O/P-FINALISATION-RECOVER FROM NEXT SESSION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP09A', 'O/P-FINALISATION-ASK FOR REPAYMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP10', 'U/P-UNDERPAYMENT DUE TO FINALISATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP11', 'O/P-PR YR FINALISATION-LIFT RESTRICTION ON CUR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP12', 'CANCELLATION/AMENDMENT OF OVERPAYMENT (OP10)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP13', 'O/P WORKING TAX CREDIT-RECOVER FROM NEXT SESSION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP14', 'O/P WORKING TAX CREDIT-ASK FOR REPAYMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PAY01', 'MONTHLY PAYMENTS MAILSHOT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG01', 'PG-REFUSAL-ALREADY QUALIFIED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG02', 'PG-NOT NOMINATED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG03', 'PG-AWAITING NOMINATIONS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG04', 'PG-REFUSAL END ON');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG05', 'PG-REFUSAL NO BID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG06', 'PGCE-REFUSAL PREVIOUS ASSISTANCE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG08', 'PG-OUTSIDE SCOTLAND-APPROVED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG09', 'PG-OUTSIDE SCOTLAND-CONSIDERING');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('PG10', 'PG-REFUSAL MASTER COURSE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('REE01', 'SEARCH OF ENDOWMENTS REGISTER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('REPEAT01', 'REFUSAL-REPEAT YEAR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('REPEAT02', 'REPEAT YEAR GRANTED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('REPEAT03', 'REPEAT YEAR -EXPLANATION OF REFUSAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('REPEAT04', 'REPEAT APPROVAL-COPY TO INSTITUTION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES01', 'REFUSAL-EU (NON UK) NATIONAL FULL SUPPORT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES02', 'REFUSAL-APPLY TO LEA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES03', 'REFUSAL-NON UK/EEA NATIONAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES04', 'REFUSAL-UK NATIONAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES05', 'REFUSAL-UK RETURNERS STUDYING IN SCOTLAND');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES06', 'NON UK/EEA NATIONAL-REQUEST EVIDENCE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES07', 'SEND OUT AB10-S');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES08', 'AB10A-STUDENT TO FILL IN FOR UK NATIONAL ABROAD');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES09', 'AB10B-PARENTS TO FILL IN FOR UK NATIONAL ABROAD');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES10', 'AB10C-STUDENT TO FILL IN FOR UK NATIONAL BACK IN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES11', 'AB10D-PARENT TO FILL IN FOR UK NATIONAL BACK IN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES12', 'AB10E-FURTHER RESIDENCY INFO-STUDENT ONLY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES13', 'AB10F-FURTHER RESIDENCY INFO-PARENTS ONLY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('RES15', 'REFUSAL-ASYLUM SEEKERS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('STUDINC01', 'TICKED BENEFIT TYPE BUT NO EST OF INCOME GIVEN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('STUDINC02', 'EST OF INCOME SAME AS WTC STATEMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('STUDINC03', 'CHECK IF EST OF INCOME IS CORRECT FIGURE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV01', 'TRAVEL-REFUSE WALK DIST-6 JOURNEYS PAID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV02', 'TRAVEL-REQUEST FOR INCOME-SESSION 2009-2010');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV02A', 'TRAVEL-REQUEST FOR INCOME-SESSION 2008-2009');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV03', 'TRAVEL-CLAIM LESS THAN ELEMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV04', 'TRAVEL-EXPLANATION OF CALCULATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV05', 'TRAVEL-WALK DIST AND 6 JOURNEYS LESS THAN ELEMT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV06', 'TRAVEL-NOT SAAS FUNDED-REFER TO LEA ETC');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV07', 'TRAVEL-ADVANCE PAYMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV08', 'TRAVEL-CLAIM RECEIVED BUT NO SAS APPLICATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV09', 'TRAVEL-NON INC ASS SYS REST-REQUEST DOCS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV10', 'TRAVEL-REFUSE EU STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV11', 'TRAVEL-REFUSE NMSB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('TRAV12', 'TRAVEL-REQUEST PROOF OF AIR FARES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('WITH01', 'WITHDRAWAL-INFORM STUDENT NO O/P');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('Z01', 'COURSE REFUSAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('Z02', 'COURSE REFUSAL-EMA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD01', 'COMP FULL OR PART YEAR ABROAD-ERASMUS EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD02', 'COMP FULL OR PART YEAR ABROAD-NON ERASMUS EXCHNGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD03', 'COMP FULL YR ABROAD-NON EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD04', 'COMP PART YEAR ABROAD-NON EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD05', 'VOL FULL OR PART YEAR ABROAD-ERASMUS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD06', 'VOL FULL OR PART YEAR ABROAD-NON ERASMUS EXCHNGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD07', 'VOL FULL YEAR ABROAD-NON EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD08', 'VOL PART YEAR ABROAD-NON EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD09', 'EU COMP OR VOL YR ABROAD-NON EXCHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD10', 'LANGUAGE ASSISTANT-FULL YR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('ABROAD11', 'LANGUAGE ASSISTANT-PART YR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP01', 'APP-RECEIVEDAFTER CLOSING DATE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP02', 'APP-MISSING EDUCATION/EMPLOYMENT DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP03', 'APP-INCOMPLETE INCOME-SEND AB36');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP03A', 'APP-INCOMPLETE INCOME-SEND AB36 (PARENTS ABRD)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP04', 'EVIDENCE THAT STUDENT HAS A PARTNER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP05', 'APP-NO INSTITUTION /COURSE DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP06', 'APP-REQ PROOF OF SEPARATION FROM STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP06A', 'APP-REQ PROOF OF SEPARATION FROM STUD FOR PARENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP07', 'APP-REQ PROOF OF SEPARATION FROM PARENT ETC');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP08', 'APP-J/A-REQUEST PARENT(S) NI NUMBERS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP09', 'APP-NO RESIDENCE DETAILS-SEND FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP10', 'APP-PENDED-AWAITING INFORMATION FROM INST/SLC');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP11', 'APP-INVALID BANK DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP12', 'APP-WRONG SESSION APPLICATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP14', 'APP-SAS 7 INCORRECT-SAS 3 FORM ENCLOSED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP15', 'APP-NO RESIDENCE OR EMP/EDUCATION DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP16', 'APP-WRONG TRAVEL CLAIM FORM COMPLETED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP17', 'APP-NON INCOME-ASSESSED-SYSTEM RESTRICTED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP18', 'APP-REQ FOR OFFER LETTER-DANCE AND DRAMA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP19', 'APP-INCOME COMPLETE-REQ PREVIOUS YEARS INCOME');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP19A', 'APP-INCOMPLETE INCOME + REQ PRV YRS INC (ABROAD)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP20', 'WITHDRAWAL-REQUEST INCOME TO FINALISE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP21', 'DROP IN INC-REQ DOCS-RESTRICT TO NON-INC ONLY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP22', 'APP-UPDATED BANK DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP23', 'APP-INCORRECT DOCS FOR FINALISING INCOME DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('APP24', 'APP-PARENT ABROAD-REQ CORRECT FIN YR INCOME');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('BLANK', 'BLANK SHELL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE01', 'COURSE NOT YET VALIDATED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE02', 'HNC REFUSAL-SCOT F');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE03', 'HNC REFUSAL-RUK G');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE04', 'PREVIOUS FUNDING AND QUALIFIED-SCOT F');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE04A', 'PREVIOUS FUNDING AND QUALIFIED-RUK G');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE04B', 'SECOND DEGREE DENTISTRY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE05', 'FALSE START');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE06', 'COURSE CHANGE-SCOT F');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE06A', 'COURSE CHANGE-RUK G');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE07', 'COURSE CHANGE-SCOT D');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE08', 'COURSE CHANGE-RUK E');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE09', 'COURSE CHANGE-SCOT C');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE10', 'COURSE CHANGE-RUK B');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE10A', 'POST HND SUPPORT-SCOT F');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE11', 'POST HND SUPPORT-RUK G');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE11A', 'POST HND SUPPORT-SCOT D');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE12', 'POST HND SUPPORT-RUK E');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE13', 'POST HND SUPPORT-SCOT C');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE14', 'POST HND SUPPORT-RUK B');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE15', 'AHP SUPPORT FOR GRADUATES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE16', 'AHP SUPPORT-COURSE CHANGE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE17', 'AHP SUPPORT-POST HND');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE18', 'DIFFERENCE BETWEEN HIGHER AND STANDARD FEES');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE19', 'REFUSAL-ACCELERATED LLB');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('COURSE20', 'ARCHITECTURE STUDENTS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC01', 'CURRENT INCOME-SEND TO PARENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC01A', 'CI-SEND LETTER TO PARENT (ABROAD)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC01B', 'CI-SEND LETTER TO STUDENT FOR PARENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC01C', 'CI-SEND LETTER TO STUDENT FOR PARENT (ABROAD)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC02', 'CI-15% DROP NOT EXPECTED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC03', 'CI-15% DROP EXPECTED-LETTER TO STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC04', 'CI-15% DROP EXPECTED-LETTER TO PARENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC05', 'CI-REQUEST FOR ACTUAL INCOME- LETTER TO STUDEN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC06', 'CI-REQUEST FOR ACTUAL INCOME-LETTER TO PARENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC06A', 'CI-REQ FOR ACTUAL INC-LETTER TO PARENT (ABRD)');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC07', 'CI-FINALISATION-REVERT BACK-LETTER TOSTUDE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('CURINC08', 'CI- FINALISATION-REVERT BACK-LETTER TO PAREN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DEP01', 'DEPENDANTS- GRANT-INCOME TOO HIGH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DEP02', 'DEPENDANTS- GRANT-REQUEST EST OF INCOME');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DEP04', 'ADVANCE OF SUPPS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA01', 'CONFIRMATION OF PAYMENT OF DSA');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA02', 'SAS3 NEEDED-NEW STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA03', 'SAS3 NEEDED-CONTINUING STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA04', 'SAS3 STILL TO BE PROCESSED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA05', 'MORE INFORMATION REQUIRED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA06', 'APPLICATION RETURNED-INCOMPLETE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA07', 'APP RECEIVED TOO LATE-CONTINUING STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA08', 'APP RECEIVED TOO LATE-FINAL YEAR STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA09', 'REPORT RECEIVED TOO LATE-CONTINUING STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA10', 'REPORT RECEIVED TOO LATE-FINAL YEAR STUDENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA11', 'TELL STUDENT ABOUT REFERRAL TO ACCESS CENTRE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA12', 'PAYMENT FOR HELPERS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA13', 'OP-TOTAL OF RECEIPTS LESS THAN PAYMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA14', 'REMINDER FOR RECEIPTS-21 DAY LETTER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA15', 'DSA INVOICE ONLY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA16', 'NEARING MAX NMPH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA17', 'DSA RECEIPTS-2ND REMINDER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA18', 'DSA FORM REQUIRED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA19', 'DSA RECEIPTS-FINAL REMINDER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA20', 'DSA TRAVEL ELEMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DSA21', 'ACKNOWLEDGE RECEIPTS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DTH01', 'DEATH OF STUDENT-CONFIRM NO MORE MONEY DUE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('DTH02', 'DEATH OF STUDENT-MONEY DUE AND OFFER TRAVEL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EU01', 'REFUSAL -EU NON GRADUATING');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EU02', 'TUITION FEES-NURSING STUDENTS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EU03', 'GRADUATING-EVIDENCE REQUESTED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EXEMPT01', 'EXEMPT PAR CON-REFUSAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EXEMPT02', 'EVIDENCE OF 3 YEARS SELF SUPPORT OR AB36');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EXEMPT03', 'REQUEST PROOF OF ESTRANGEMENT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('EXEMPT04', 'REQUEST PROOF OF LEGAL GUARDIANSHIP');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT01', 'RECORD OF TELEPHONE CALL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT02', 'REQUEST B1 APPROVAL OF REPEAT ASSISTANCE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT03', 'BLANK FILE NOTE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT04', 'CURRENT INCOME CALCULATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT05', 'B1 REPEAT DECISION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('INT06', 'DSA NOMINEE FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN01', 'FORM NOT FILLED IN OR SIGNED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN02', 'LOAN CONTACTS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN03', 'LOAN REQUEST');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN05', 'CLAIMED NON INC ASS LOAN NOW WANTS FULL LOAN');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN06', 'FEE LOAN/HEI BURSARY CONSENT-RUK G');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN07', 'RUK E/RUK G SCHEME STATUS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN08', 'FEE LOAN ADJUSTMENT FORM-SESSION 08-09');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN09', 'FEE LOAN ADJUSTMENT FORM-SESSION 09-10');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN10', 'HEI BURSARY CONSENT-RUK G WEB APPS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN11', 'AB36 FINAL AND LOAN FORM TO STUDENTS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LOAN12', 'TOP UP LOAN FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPCG01', 'REFUSAL-NOT REGISTERED CHILDCARE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPCG02', 'ADDITIONAL CHILDCARE GRANT-SEND FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG01', 'REQUEST BC');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG02', 'REQ BC AND SEND LPCG FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG03', 'REQ BC AND SINGLE PARENT EVID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG04', 'REQ BC AND SINGLE PARENT EVID AND SEND LPCG FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG05', 'REQ SINGLE PARENT EVID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG06', 'REQ SINGLE PARENT EVID AND SEND LPCG FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG07', 'REQ WORKING TAX CREDIT ESTIMATE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('LPG08', 'REQ AWARD BREAKDOWN-WTC INCLUDED');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('MGR01', 'MIGRANT-NEW STUDENTS REQUEST EVIDENCE');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('MGR02', 'MIGRANT-CONT-REST FEES ONLY-REQUEST EVID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('MGR03', 'MIGRANT-CONT-PAID LIVING COSTS-REQUEST EVID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB01', 'NMSB-DEPENDANTS GRANT-INCOME TOO HIGH');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB02', 'NMSB-O/P OF AWARD DUE TO WITHDRAWAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB03', 'NMSB-APPLICATION RECEIVED TOO EARLY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB06', 'NMSB-REQ SINGLE PARENT EVID');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB08', 'NMSB-CONTINUATION OF SUPPORT');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB09', 'NMSB-DEPS INCOME TOO HIGH-CHILDCARE ALLOW FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB10', 'NMSB-CHILDCARE ALLOWANCE FORM');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB11', 'NMSB-ESTIMATE OF SPOUSE-S INCOME');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB12', 'NMSB OVERPAYMENT-APPLY FOR EXTENSION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB13', 'NMSB OVERPAYMENT-EXCLUDE PAY DETAILS');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB14', 'NMSB OFFER LETTER');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSB15', 'INCORRECT NMSB APPLICATION');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSBRES01', 'REFUSAL-NON UK/EEA NATIONAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('NMSBRES02', 'REFUSAL-UK NATIONAL');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OTHR02', 'CHEQUE RETURNED-ASK STUDENT WHY');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OTHR03', 'ASSESSED CONTRIBUTION-LETTER TO PARENT ETC');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP01', 'REFUND PREVIOUS O/P-NON INC ASS ONLY THIS YEAR');
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC)
 Values
   ('OVRP02', 'REQUEST FOR REFUND OF O/P DUE TO DISCONT. STUDIES');
COMMIT;
