ALTER TABLE SGAS.AWARD_INSTALMENT
drop CONSTRAINT AWI_RETURNED;


ALTER TABLE SGAS.AWARD_INSTALMENT ADD (
  CONSTRAINT F5_AWI
 FOREIGN KEY (RETURNED) 
 REFERENCES SGAS.PAYMENT_RETURN_STATUS (CODE));

