-- Drop no longer required AWARDS_RECALC table
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      21.05.2012    P.Hughes (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 


-----PRIOR TO RUNNING THIS SCRIPT
---PAYMENT_RETURNS_LOAD, PAYMENT_RETURNS, and PAYMENT_ERTURNS_UNIDENTIFIED data should all be backed up.


ALTER TABLE SGAS.PAYMENT_RETURN_ERRORS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE SGAS.PAYMENT_RETURN_ERRORS CASCADE CONSTRAINTS PURGE
/

--
-- PAYMENT_RETURN_ERRORS  (Table) 
--

CREATE TABLE SGAS.PAYMENT_RETURN_ERRORS
(
  PAY_ERR_ID              NUMBER(10) NOT NULL,
  RETURNS_BATCH_REF       VARCHAR2(7 BYTE),
  ERROR_TYPE              VARCHAR2(100 BYTE),
  ERROR_MODULE            VARCHAR2(100 BYTE),
  OPERATION               VARCHAR2(100 BYTE),
  ERROR_CODE              VARCHAR2(100 BYTE),
  ERROR_DATE              DATE,
  ERROR_MSG               VARCHAR2(1000 BYTE),
  PAYEE_PAYMENT_ID        NUMBER(10),
  STUD_REF_NO             NUMBER(10),
  LAST_UPDATED_BY         VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON         DATE               DEFAULT Sysdate NOT NULL
)

TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          100K
            NEXT             100K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURN_ERRORS IS 'table holds details of any payment return errors';


CREATE UNIQUE INDEX PAYMENT_RETURN_ERRORS_PK ON SGAS.PAYMENT_RETURN_ERRORS
(PAY_ERR_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYMENT_RETURN_ERRORS ADD (
  CONSTRAINT PAYMENT_RETURN_ERRORS_PK
 PRIMARY KEY
 (PAY_ERR_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));
               
--
-- Create public synonym
--
 
DROP PUBLIC SYNONYM PAYMENT_RETURN_ERRORS
/

CREATE PUBLIC SYNONYM PAYMENT_RETURN_ERRORS FOR SGAS.PAYMENT_RETURN_ERRORS
/

DROP SEQUENCE SGAS.PAY_RETURN_ERRORS_ID_SEQ
/
--
-- PAY_ERRORS_ID_seq  (Sequence) 
--
CREATE SEQUENCE SGAS.PAY_RETURN_ERRORS_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER SGAS.TRIG_PAY_RETURN_ERRORS_SEQ 
   BEFORE INSERT
   ON SGAS.PAYMENT_RETURN_ERRORS
   FOR EACH ROW
BEGIN
   SELECT PAY_RETURN_ERRORS_ID_SEQ.NEXTVAL
     INTO :NEW.PAY_ERR_ID
     FROM DUAL;
END;

ALTER TABLE SGAS.PAYMENT_RETURNS
 DROP PRIMARY KEY CASCADE;
DROP TABLE SGAS.PAYMENT_RETURNS CASCADE CONSTRAINTS PURGE;

CREATE TABLE SGAS.PAYMENT_RETURNS
(
  PAYMENT_RETURNS_ID       NUMBER(10),
  PAYMENT_INSTALMENT_ID    NUMBER(10),
  PAYMENT_RETURNS_LOAD_ID  NUMBER(10),
  PAYEE_PAYMENT_ID         NUMBER(10),
  RETURNS_BATCH_REF        VARCHAR2(7 BYTE),
  RETURNS_DATE             DATE,
  RETURNS_AMOUNT           NUMBER(9,2),
  RECEIPT_TYPE_ID          VARCHAR2(1 BYTE),
  RETURNS_STATUS           VARCHAR2(1 BYTE),
  PROCESS_DATE             DATE,
  ENTITY                   VARCHAR2(3 BYTE)     DEFAULT '600',
  COST_CENTRE              VARCHAR2(6 BYTE),
  ACCOUNT                  VARCHAR2(8 BYTE),
  PROGRAMME                VARCHAR2(3 BYTE),
  SUB_TYPE                 VARCHAR2(2 BYTE),
  PAYMENT_METHOD           VARCHAR2(1 BYTE),
  NOTES                    VARCHAR2(100 BYTE),
  STUD_AWARD_TYPE          VARCHAR2(20 BYTE),
  PAYEE_REF_ID             NUMBER(10),
  LAST_UPDATED_BY          VARCHAR2(15 BYTE)    DEFAULT User,
  LAST_UPDATED_ON          DATE                 DEFAULT Sysdate
)
TABLESPACE STEPS_DATA
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURNS IS 'table is used to hold details of returned payments';


CREATE UNIQUE INDEX SGAS.PAY_RTNS_PK ON SGAS.PAYMENT_RETURNS
(PAYMENT_RETURNS_ID)
LOGGING
TABLESPACE STEPS_DATA
NOPARALLEL;


DROP SEQUENCE SGAS.PAY_RTNS_ID_SEQ;

CREATE SEQUENCE SGAS.PAY_RTNS_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER SGAS.trig_pay_rtns_seq
   BEFORE INSERT
   ON SGAS.PAYMENT_RETURNS    FOR EACH ROW
BEGIN
   SELECT PAY_RTNS_ID_SEQ.NEXTVAL
     INTO :NEW.PAYMENT_RETURNS_ID
     FROM DUAL;
END;
/
SHOW ERRORS;



DROP PUBLIC SYNONYM PAYMENT_RETURNS;

CREATE PUBLIC SYNONYM PAYMENT_RETURNS FOR SGAS.PAYMENT_RETURNS;


ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT PAY_RTNS_PK
 PRIMARY KEY
 (PAYMENT_RETURNS_ID)
    USING INDEX 
    TABLESPACE STEPS_DATA);


ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F1_PAYRTN 
 FOREIGN KEY (PAYMENT_INSTALMENT_ID) 
 REFERENCES SGAS.PAYMENT_INSTALMENT (PAYMENT_INSTALMENT_ID));

ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F2_PAYRTN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES SGAS.PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));

ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT F3_PAYRTN 
 FOREIGN KEY (RETURNS_BATCH_REF) 
 REFERENCES SGAS.RETURN_BATCHES (RETURNS_BATCH_REF));
 
 DROP TABLE SGAS.PAYMENT_RETURNS_LOAD CASCADE CONSTRAINTS PURGE
/

--
-- PAYMENT_RETURNS_LOAD  (Table) 
--

CREATE TABLE SGAS.PAYMENT_RETURNS_LOAD
(
  PAYMENT_RETURNS_LOAD_ID        NUMBER(10) NOT NULL, 
  RETURNS_DATE                   DATE NOT NULL,
  RETURNS_AMOUNT                 NUMBER(9,2) NOT NULL,
  RECEIPT_TYPE_ID                VARCHAR2(1 BYTE) NOT NULL,
  RETURNS_STATUS                 VARCHAR2(1 BYTE) NOT NULL,
  PROCESS_DATE                   DATE NOT NULL,
  PAYEE_PAYMENT_ID               NUMBER(10),
  STUD_REF_NO                    NUMBER(10),
  NAME                           VARCHAR2(100),
  STUD_AWARD_TYPE		         VARCHAR2(20),
  OVERRIDE                       VARCHAR2(1) NOT NULL,
  LAST_UPDATED_BY                VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON                DATE               DEFAULT Sysdate NOT NULL  


)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3400K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURNS_LOAD IS 'table is used to hold details of the payment returns load';

CREATE UNIQUE INDEX PAYMENT_RTNS_LOAD_PK ON SGAS.PAYMENT_RETURNS_LOAD
(PAYMENT_RETURNS_LOAD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYMENT_RETURNS_LOAD ADD (
  CONSTRAINT PAYMENT_RETURNS_LOAD_PK
 PRIMARY KEY
 (PAYMENT_RETURNS_LOAD_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

-- 
-- Create public synonym 
-- 

DROP PUBLIC SYNONYM PAYMENT_RETURNS_LOAD
/
CREATE PUBLIC SYNONYM PAYMENT_RETURNS_LOAD FOR sgas.PAYMENT_RETURNS_LOAD
/
 
DROP SEQUENCE SGAS.PAYMENT_RETURNS_LOAD_ID_SEQ;              
               
CREATE SEQUENCE SGAS.PAYMENT_RETURNS_LOAD_ID_SEQ
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
/

CREATE OR REPLACE TRIGGER SGAS.TRIG_PAYMENT_RETURNS_LOAD_SEQ 
   BEFORE INSERT
   ON SGAS.PAYMENT_RETURNS_LOAD
   FOR EACH ROW
BEGIN
   SELECT PAYMENT_RETURNS_LOAD_ID_SEQ.NEXTVAL
     INTO :NEW.PAYMENT_RETURNS_LOAD_ID
     FROM DUAL;
END;

DROP TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED CASCADE CONSTRAINTS PURGE
/

--
-- PAYMENT_RETURNS_UNIDENTIFIED  (Table) 
--

CREATE TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED
(
  PAYMENT_RETURNS_LOAD_ID        NUMBER(10) NOT NULL, 
  RETURNS_DATE                   DATE NOT NULL,
  RETURNS_AMOUNT                 NUMBER(9,2) NOT NULL,
  RECEIPT_TYPE_ID                VARCHAR2(1 BYTE) NOT NULL,
  RETURNS_STATUS                 VARCHAR2(1 BYTE) NOT NULL,
  PROCESS_DATE                   DATE NOT NULL,
  PAYEE_PAYMENT_ID               NUMBER(10),
  STUD_REF_NO                    NUMBER(10),
  STUD_AWARD_TYPE		 VARCHAR2(20),
  NAME				 VARCHAR2(100),
  PROCESSED                      VARCHAR2(1 BYTE) NOT NULL,
  NOTES                          VARCHAR2(100),
  LAST_UPDATED_BY                VARCHAR2(15 BYTE)  DEFAULT User NOT NULL,
  LAST_UPDATED_ON                DATE               DEFAULT Sysdate NOT NULL  


)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3400K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED IS 'table is used to hold any unidentified returned payments';

CREATE UNIQUE INDEX PAYMENT_RTNS_UN_PK ON SGAS.PAYMENT_RETURNS_UNIDENTIFIED
(PAYMENT_RETURNS_LOAD_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED ADD (
  CONSTRAINT PAYMENT_RTNS_UN_PK
 PRIMARY KEY
 (PAYMENT_RETURNS_LOAD_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE SGAS.PAYMENT_RETURNS_UNIDENTIFIED ADD (
  CONSTRAINT F1_PAYRTNUN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES SGAS.PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));

-- 
-- Create public synonym 
-- 

DROP PUBLIC SYNONYM PAYMENT_RETURNS_UNIDENTIFIED
/
CREATE PUBLIC SYNONYM PAYMENT_RETURNS_UNIDENTIFIED FOR sgas.PAYMENT_RETURNS_UNIDENTIFIED
/





/*

TRUNCATE TABLE PAYMENT_RETURNS_LOAD;

TRUNCATE TABLE PAYMENT_RETURNS;

TRUNCATE TABLE PAYMENT_RETURNS_UNIDENTIFIED;


ALTER TABLE PAYMENT_RETURNS_LOAD
ADD STUD_AWARD_TYPE VARCHAR2(20);

ALTER TABLE PAYMENT_RETURNS_LOAD
ADD OVERRIDE VARCHAR2(1) NOT NULL;

ALTER TABLE PAYMENT_RETURNS_LOAD 
DROP COLUMN PAYEE_ID;




---REQUIRE HELP FOR THIS PART
ALTER TABLE PAYMENT_RETURNS_LOAD
DROP COLUMN IDENTIFIED_RETURN;

ALTER TABLE PAYMENT_RETURNS_LOAD
RENAME COLUMN PAYEE_REF_ID TO STUD_REF_NO;

ALTER TABLE PAYMENT_RETURNS_LOAD
RENAME COLUMN NOTES TO NAME;

ALTER TABLE PAYMENT_RETURNS
ADD STUD_AWARD_TYPE VARCHAR2(20);

ALTER TABLE PAYMENT_RETURNS
ADD STUD_REF_NO NUMBER(10);

ALTER TABLE PAYMENT_RETURNS
MODIFY PAYMENT_INSTALMENT_ID NUMBER(10) NULL;

ALTER TABLE PAYMENT_RETURNS
MODIFY PAYEE_PAYMENT_ID NUMBER(10) NULL;


ALTER TABLE PAYMENT_RETURNS    ---PRIMARY KEY
ADD PAYMENT_RETURNS_ID NUMBER NOT NULL;

ALTER TABLE PAYMENT_RETURNS
DROP CONSTRAINT PAYMENT_RETURNS_PK;



CREATE UNIQUE INDEX SGAS.PAY_RTNS_PK ON SGAS.PAYMENT_RETURNS
(PAYMENT_RETURNS_ID)
LOGGING
TABLESPACE STEPS_DATA
NOPARALLEL;


DROP SEQUENCE SGAS.PAY_RTNS_ID_SEQ;

CREATE SEQUENCE SGAS.PAY_RTNS_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE OR REPLACE TRIGGER SGAS.trig_pay_rtns_seq
   BEFORE INSERT
   ON SGAS.PAYMENT_RETURNS    FOR EACH ROW
BEGIN
   SELECT PAY_RTNS_ID_SEQ.NEXTVAL
     INTO :NEW.PAYMENT_RETURNS_ID
     FROM DUAL;
END;
/
SHOW ERRORS;

DROP PUBLIC SYNONYM PAYMENT_RETURNS;

CREATE PUBLIC SYNONYM PAYMENT_RETURNS FOR SGAS.PAYMENT_RETURNS;


ALTER TABLE SGAS.PAYMENT_RETURNS ADD (
  CONSTRAINT PAY_RTNS_PK
 PRIMARY KEY
 (PAYMENT_RETURNS_ID)
    USING INDEX 
    TABLESPACE STEPS_DATA);

ALTER TABLE PAYMENT_RETURN_ERRORS
RENAME COLUMN PAYEE_ID TO STUD_REF_NO;

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
DROP COLUMN PAYEE_REF_ID;

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
DROP COLUMN IDENTIFIED_RETURN;

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
DROP COLUMN PAYEE_ID;

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
ADD NAME VARCHAR2(100);

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
ADD STUD_REF_NO NUMBER(10);

ALTER TABLE PAYMENT_RETURNS_UNIDENTIFIED
ADD PROCESSED VARCHAR2(1) NOT NULL;
