CREATE INDEX sgas."S2_PI"
ON "SGAS"."PAYMENT_INSTALMENT" ( "STUD_REF_NO" )
LOGGING
TABLESPACE steps_index;

CREATE INDEX sgas."S4_STS"
ON "SGAS"."STUD_SESSION" ( "BEN2_ID" )
LOGGING
TABLESPACE steps_index;

CREATE INDEX SGAS."S3_PI"
ON "SGAS"."PAYMENT_INSTALMENT" ( "PAYEE_PAYMENT_ID" )
LOGGING
TABLESPACE STEPS_INDEX;

CREATE INDEX SGAS."S1_PP"
ON "SGAS"."PAYEE_PAYMENT" ( "PAYMENT_STATUS" )
LOGGING
TABLESPACE STEPS_INDEX;