----------------- SFD_2018 Defect 39 --------------------------------

ALTER TABLE PROCESS_INSTANCE_DATA MODIFY (STUD_REF_NO NUMBER(10));
ALTER TABLE  EDOC_ALL_TASK_LIST MODIFY (STUD_REF_NO NUMBER(10));
ALTER TABLE  COMPLETE_TASK_DATA MODIFY (STUD_REF_NO NUMBER(10));
ALTER TABLE  EDOC_ACTIVE_TASK_LIST MODIFY (STUD_REF_NO NUMBER(10));

COMMIT;