ALTER TABLE STUD_RATE ADD (
  CONSTRAINT F1_STR 
 FOREIGN KEY (STUD_AWARD_TYPE_ID) 
 REFERENCES STUD_AWARD_TYPE (STUD_AWARD_TYPE_ID));

ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F2_PAYRTN 
 FOREIGN KEY (PAYMENT_RETURNS_LOAD_ID) 
 REFERENCES PAYMENT_RETURNS_LOAD (PAYMENT_RETURNS_LOAD_ID));

ALTER TABLE PAYMENT_RETURNS ADD (
  CONSTRAINT F3_PAYRTN 
 FOREIGN KEY (RETURNS_BATCH_REF) 
 REFERENCES RETURN_BATCHES (RETURNS_BATCH_REF));

ALTER TABLE CORRES_ATTACH ADD (
  CONSTRAINT F1_COA 
 FOREIGN KEY (CORRES_ID) 
 REFERENCES CORRES (CORRES_ID));

Insert into CONFIG_DATA
   (ITEM_NAME, NVAL)
 Values
   ('STATUS_REPORT_CURRENT_YEAR', 2012);
   
COMMIT;