//THIS WILL CORRECT EXISTING AWARD_INSTALMENT RECORDS IN SIT WHERE THIS IS NULL, THE EXISTING CODE HAS BEEN CORRECTED SO THIS WILL ALWAYS BE //SET TO 'N' IN FUTURE - PH

UPDATE sgas.award_instalment
set recalc = 'N'
where recalc IS NULL