SET DEFINE OFF;

DROP TRIGGER SGAS.TRIG_ENQUIRY_OPTION_ID_SEQ;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Change of College/University or Course', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 1;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Cancel Submitted Application', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 2;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Amend Submitted Application', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 3;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Lone Parent Grant Query', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 4;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Bursary Query', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 5;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Care Experienced Accommodation Grant', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 6;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Disabled Students'' Allowance', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 7;

UPDATE SGAS.ENQUIRY_OPTION
SET DESCRIPTION = 'Online Services Query', LAST_UPDATED_ON = SYSDATE
WHERE ENQUIRY_OPTION_ID = 8;

Insert into SGAS.ENQUIRY_OPTION (ENQUIRY_OPTION_ID, DESCRIPTION, LAST_UPDATED_BY, LAST_UPDATED_ON, IS_ACTIVE)
Values (9, 'General Enquiry', 'SGAS', SYSDATE, 'Y');

COMMIT;

