CREATE TABLE CESB_FLAGS
(
STUD_REF_NO VARCHAR2(10) PRIMARY KEY, 
CARE_EXP_FOSTER VARCHAR2(1),
CARE_EXP_RES VARCHAR2(1),
CARE_EXP_KINSHIP_LA VARCHAR2(1),
CARE_EXP_KINSHIP_NO_LA VARCHAR2(1),
CARE_EXP_HOME VARCHAR(2),
CARE_EXP_OTHER VARCHAR2(1),
CARE_EXP_OTHER_DETAILS VARCHAR2(250),
CARE_EXP_START_AGE NUMBER(2),
CARE_EXP_END_AGE NUMBER(2),
LAST_UPDATED_BY VARCHAR2(15) 
);

COMMIT;

CREATE TABLE SGAS.CESB_Flags_AUD
(
  AUD_ID       NUMBER(10) PRIMARY KEY,
  AUD_DATE     DATE,
  COLUMN_NAME  VARCHAR2(32),
  TABLE_PKEY1  VARCHAR2(10),
  USERNAME     VARCHAR2(15),
  OLD          VARCHAR2(250),
  NEW          VARCHAR2(250),
  ACTION       VARCHAR2(1)
);

COMMIT;