WHENEVER SQLERROR CONTINUE
CREATE INDEX SGAS.ATT_DATA_SCY_IDX ON SGAS.ATTENDANCE_DATA
(STUD_CRSE_YEAR_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_ADR ON SGAS.ATTENDANCE_DATA_RECEIVED
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_AWI ON SGAS.AWARD_INSTALMENT
(AWARD_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S3_AWI ON SGAS.AWARD_INSTALMENT
(BATCH_REF)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.CTD_S1 ON SGAS.COMPLETE_TASK_DATA
(PROCESS_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_PP ON SGAS.PAYEE_PAYMENT
(PAYEE_ID, BATCH_REF)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.PI_BATCH_IDX ON SGAS.PAYMENT_INSTALMENT
(BATCH_REF)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_STS ON SGAS.STUD_SESSION
(BEN1_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
/
