WHENEVER SQLERROR CONTINUE
set serveroutput on size 1000000;
begin
DBMS_OUTPUT.PUT_LINE('Some of these indexes may ALREADY exist in some environments and show an "ORA-00955: name is already used by an existing object" error.  ');
DBMS_OUTPUT.PUT_LINE('This MAY not be a problem and should not stop the release. The log will need to be reviewed.');
end;
CREATE INDEX SGAS.S1_ADI ON SGAS.ADI_JOURNAL
(BATCH_REF)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_ATTDM ON SGAS.ATTENDANCE_DATA_MESSAGE
(ATTENDANCE_DATA_RECEIVED_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_AW ON SGAS.AWARD
(DSA_ALLOWANCE_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_DSAA ON SGAS.DSA_ALLOWANCE
(DSA_APPLICATION_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_DSAA ON SGAS.DSA_ALLOWANCE
(STUD_SESSION_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S3_DSAA ON SGAS.DSA_ALLOWANCE
(STUD_CRSE_YEAR_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_DSAP ON SGAS.DSA_APPLICATION
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_DSAPAY ON SGAS.DSA_PAYMENT
(AWARD_INSTALMENT_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_DSAPAY ON SGAS.DSA_PAYMENT
(DSA_ALLOWANCE_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_EC ON SGAS.EMPLOYEE_CASES
(USERNAME)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_NSA ON SGAS.NMSB_SPEC_ARR
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S4_PI ON SGAS.PAYMENT_INSTALMENT
(STUD_CRSE_YEAR_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S5_PI ON SGAS.PAYMENT_INSTALMENT
(PAYEE_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_PAY_RTNS ON SGAS.PAYMENT_RETURNS
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_PAY_RTNS ON SGAS.PAYMENT_RETURNS
(PAYEE_PAYMENT_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S3_PAY_RTNS ON SGAS.PAYMENT_RETURNS
(PAYMENT_INSTALMENT_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_SLCD ON SGAS.SLC_DATA
(STUD_CRSE_YEAR_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_STI ON SGAS.STUD_INCOME
(STUD_SESSION_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_STNO ON SGAS.STUD_NOMINEE
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_STNO ON SGAS.STUD_NOMINEE
(NOMINEE_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_AUST ON SGAS.AUTHENTICATE_STUD
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_AUST ON SGAS.AUTHENTICATE_STUD
(WEB_USER_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S2_CTD ON SGAS.COMPLETE_TASK_DATA
(STUD_REF_NO)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
CREATE INDEX SGAS.S1_SAS ON SGAS.STUD_AWARD_STATUS
(STUD_CRSE_YEAR_ID)
ONLINE
LOGGING
TABLESPACE STEPS_INDEX
NOPARALLEL
COMPUTE STATISTICS;
/
