Insert into CONFIG_EDM
   (DOCUMENT_TYPE_CODE, DOCUMENT_TYPE_NAME, TYPE, MULTIPAGE, RESCAN_ALLOWED, 
    REQ_ORIGINAL_ALLOWED, FILE_EXT, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('DSA_REM', 'DSA Reminder', 'O', NULL, NULL, 
    NULL, 'PDF', 'SGAS', TO_DATE(sysdate, 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
