---------------------Defects 5 --------------------------------------------------
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Husband, wife, civil partner or partner', IS_ACTIVE = 'Y', IS_ADULT = 'Y' WHERE SUPP_GRANT_RELATION_ID = 20; -- was 'SPOUSE'
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Child I act as a carer for', IS_ACTIVE = 'Y', IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 5; -- was 'BROTHER(CHILD)'
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Adult I act as a carer for', IS_ACTIVE = 'Y', IS_ADULT = 'Y' WHERE SUPP_GRANT_RELATION_ID = 10; -- was 'BROTHER(ADULT)'

UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 1;
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 2;
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 3;
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 4;

UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 6; -- SISTER
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 11; -- SISTER(ADULT)
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 12; -- FATHER
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 13; -- MOTHER
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 18; -- STEPFATHER
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 19; -- STEPMOTHER
UPDATE SGAS.SUPP_GRANT_RELATION SET IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 21; -- OTHER(ADULT)

DELETE FROM SGAS.SUPP_GRANT_RELATION WHERE SUPP_GRANT_RELATION_ID IN (25,26, 27);


-----------------------Defect 4 --------------------------------------------------
ALTER TABLE TITLE MODIFY (DESCRIPT VARCHAR2(50));
ALTER TABLE MARITAL_STATUS MODIFY (DESCRIPT VARCHAR2(50));
ALTER TABLE CONTACT_RELATIONSHIP MODIFY (DESCRIPT VARCHAR2(50));
ALTER TABLE BENEFACTOR_RELATION MODIFY (DESCRIPT VARCHAR2(50));
ALTER TABLE STUD_INCOME_TYPE MODIFY (DESCRIPTION VARCHAR2(100));
ALTER TABLE SUPP_GRANT_RELATION MODIFY (DESCRIPT VARCHAR2(50));
ALTER TABLE APPLICATION_STATUS_MESSAGE MODIFY (APPLICATION_STATUS VARCHAR2(50));

------------------------Defect 11 -----------------------------------------------------
UPDATE BENEFACTOR_RELATION SET LEGACY_ID = 30 WHERE BENEFACTOR_RELATION_ID = 7; -- LEGAL GUARDIAN
