----------------------- UPDATE STREAM TABLES WEB---------------------------------------

ALTER TABLE STUD ADD 
(
	RESIDENCY_CATEGORY 				VARCHAR2(8),
	PORTAL_USER_ID                  VARCHAR2(25)
);



ALTER TABLE STUD_CRSE_YEAR ADD 
(
	IS_INDEPENDENT 					VARCHAR2(1),
	INTERRUPTION_FROM_STUDY         VARCHAR2(1)
);


ALTER TABLE BENEFACTOR ADD 
(
	AB36 							VARCHAR2(1),
	CONSENT_TO_SHARE_STUDENT		VARCHAR2(1),
	ONLY_ONE_BEN					VARCHAR2(1),
	REASON_FOR_ONE_BEN_ID			NUMBER(10)
);


ALTER TABLE STUD_CONT_DETAILS ADD
(
	CONT_CONSENT					VARCHAR2(1)

); 

ALTER TABLE STUD_MESSAGE MODIFY (MESSAGE_TEXT VARCHAR2(1000));
ALTER TABLE STUD_MESSAGE ADD
(
	SUBJECT					        NUMBER(10)
);