-------------------------- STUD_AWARD_STATUS----------------------------------
CREATE TABLE STUD_AWARD_STATUS
(
  STUD_AWARD_STATUS_ID     NUMBER(10)           NOT NULL CONSTRAINT SAS_PK PRIMARY KEY,
  STUD_CRSE_YEAR_ID        NUMBER(9)            NOT NULL,
  AWARD_TYPE               VARCHAR2(50)         NOT NULL,
  AWARD_STATUS_MESSAGE_ID  NUMBER(2)            DEFAULT 2                     NOT NULL,
  CANCELLED_IND            VARCHAR2(1)          DEFAULT 'N'                   NOT NULL,
  LAST_UPDATED_BY          VARCHAR2(15)         DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON          DATE                 DEFAULT SYSDATE               NOT NULL
);

CREATE SEQUENCE SGAS.STUD_AWARD_STATUS_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

GRANT SELECT ON SGAS.STUD_AWARD_STATUS_ID_SEQ TO PUBLIC;


CREATE OR REPLACE TRIGGER SGAS.STUD_AWARD_STATUS_ID_SEQ
   BEFORE INSERT
   ON SGAS.STUD_AWARD_STATUS   FOR EACH ROW
BEGIN
   SELECT STUD_AWARD_STATUS_ID_SEQ.NEXTVAL
     INTO :NEW.STUD_AWARD_STATUS_ID
     FROM DUAL;
END;
/


ALTER TABLE SGAS.STUD_AWARD_STATUS ADD (
  FOREIGN KEY (STUD_CRSE_YEAR_ID) 
  REFERENCES SGAS.STUD_CRSE_YEAR (STUD_CRSE_YEAR_ID)
  ENABLE VALIDATE);