ALTER TABLE SGAS.SUPPLEMENTARY_STATUS
 DROP PRIMARY KEY CASCADE;

DROP TABLE SGAS.SUPPLEMENTARY_STATUS CASCADE CONSTRAINTS;

DROP TRIGGER SGAS.TRIG_STUD_STATUS_SEQ;

DROP SEQUENCE SUPP_STATUS_ID_SEQ;

------Columns should be deleted from both tables in STREAMS-------------------
ALTER TABLE SGAS.STUD_CRSE_YEAR@web DROP (SUPP_STATUS_ID, SUPP_LAST_UPDATE);
ALTER TABLE SGAS.STUD_CRSE_YEAR DROP (SUPP_STATUS_ID, SUPP_LAST_UPDATE);

DROP TRIGGER SCY_UPDATE_SUPP_LAST_UPDATE;

DROP TRIGGER SCY_UPDATE_SUPP_STATUS;

