CREATE OR REPLACE PACKAGE SGAS.PK_STEPS_STUD_ENQUIRY
IS
-- DESCRIPTION
-- ===========
-- Student Enquiry Data Transfer
   PROCEDURE transfer_stud_enquiries;
END PK_STEPS_STUD_ENQUIRY;
/


CREATE OR REPLACE PACKAGE BODY SGAS.PK_STEPS_STUD_ENQUIRY
IS
    PROCEDURE TRANSFER_STUD_ENQUIRIES 
        IS
        V_ERRM VARCHAR2(128);
        MAX_ID NUMBER;

        BEGIN
            SELECT MAX(ENQUIRY_ID) INTO MAX_ID FROM ENQUIRY_FORM@WEB; 
            INSERT INTO SGAS.STUD_ENQUIRY (ENQUIRY_ID, STUD_REF_NO, ENQUIRY_OPTION_ID, ENQUIRY_TEXT, ENQUIRY_DATE) SELECT * FROM ENQUIRY_FORM@WEB WHERE ENQUIRY_ID <= MAX_ID;
            DELETE ENQUIRY_FORM@WEB WHERE ENQUIRY_ID <= MAX_ID;
            COMMIT;
        EXCEPTION
        WHEN OTHERS
        THEN         
             BEGIN
                ROLLBACK;
                V_ERRM := SUBSTR(SQLERRM,1,128);
                INSERT INTO SGAS.STUD_ENQUIRY_TRANSFER_ERROR (ERROR_TEXT) VALUES (V_ERRM);
                COMMIT;
             END;
        END TRANSFER_STUD_ENQUIRIES;
END PK_STEPS_STUD_ENQUIRY;
/