DELETE FROM EDM.EDM_BATCH_WF WHERE BATCH_TYPE_CODE = 99;

INSERT INTO EDM.EDM_BATCH_WF (BATCH_TYPE_CODE, BATCH_TYPE_DESCRIPTION, WORK_ITEM_INDICATOR, REPORTED_AS, RAW_DATA_REQD) VALUES (99, 'Student Enquiry', 'S', 'C', 'N');

COMMIT;




