------------------- OLS 2016 EXISTING TABLE UPDATES ----------------------------------------
---DELETE _WEB TABLES FROM STEPS
BEGIN
  FOR c IN ( SELECT table_name FROM user_tables WHERE table_name LIKE '%_WEB' )
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name;
  END LOOP;
END;

-----------------CONFIG_DATA-----------------------------------------
ALTER TABLE CONFIG_DATA ADD
(
  DVAL               DATE
);

Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, DVAL)
 Values
   ('SESSION_START_DATE', TO_DATE('04/04/2016 00:00:00', 'DD/MM/YYYY HH24:MI:SS'));
Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, DVAL)
 Values
   ('SESSION_END_DATE', TO_DATE('31/03/2017 00:00:00', 'DD/MM/YYYY HH24:MI:SS'));
Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, NVAL)
 Values
   ('MAN_PW_EXPIRY_DAYS', 5);
Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, CVAL)
 Values
   ('AcademicYearStart', '01/08/2016');
Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, CVAL)
 Values
   ('AcademicYearEnd', '31/07/2017');
Insert into SGAS.CONFIG_DATA
   (ITEM_NAME, CVAL)
 Values 
   ('IS_FUNDING_CALC_ENABLED', 'Y');


----------TITLE----------------
ALTER TABLE SGAS.TITLE ADD
(
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

ALTER TABLE SGAS.TITLE ADD (
  CONSTRAINT T_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);
  
UPDATE SGAS.TITLE SET IS_ACTIVE = 'N' WHERE TITLE_ID IN ('6', '7');
ALTER TABLE TITLE MODIFY (DESCRIPT  VARCHAR2(50));

----------MARITAL STATUS---------------
ALTER TABLE SGAS.MARITAL_STATUS ADD
(
  IS_SINGLE           VARCHAR2(1) DEFAULT 'Y',
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

ALTER TABLE MARITAL_STATUS MODIFY (DESCRIPT  VARCHAR2(50));

ALTER TABLE SGAS.MARITAL_STATUS ADD (
  CONSTRAINT MR_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT MR_IS_SINGLE
  CHECK ( IS_SINGLE IN('Y','N') OR IS_SINGLE IS NULL)
  ENABLE VALIDATE,
  PRIMARY KEY (MARITAL_STATUS_ID));
  
UPDATE SGAS.MARITAL_STATUS SET IS_SINGLE = 'N' WHERE MARITAL_STATUS_ID IN ('2', '6', '7');


----------CONTACT_RELATIONSHIP---------------
ALTER TABLE SGAS.CONTACT_RELATIONSHIP ADD
(
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

ALTER TABLE CONTACT_RELATIONSHIP MODIFY (DESCRIPT  VARCHAR2(50));

ALTER TABLE SGAS.CONTACT_RELATIONSHIP ADD (
  CONSTRAINT CR_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Father' WHERE CONTACT_RELATIONSHIP_ID = 1;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Mother' WHERE CONTACT_RELATIONSHIP_ID = 2;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Parent' WHERE CONTACT_RELATIONSHIP_ID = 3;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Guardian' WHERE CONTACT_RELATIONSHIP_ID = 4;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Husband or Partner' WHERE CONTACT_RELATIONSHIP_ID = 5;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Wife or Partner' WHERE CONTACT_RELATIONSHIP_ID = 6;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Other' WHERE CONTACT_RELATIONSHIP_ID = 7;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Unknown' WHERE CONTACT_RELATIONSHIP_ID = 8;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Stepfather' WHERE CONTACT_RELATIONSHIP_ID = 9;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Stepmother' WHERE CONTACT_RELATIONSHIP_ID = 10;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Grandparent' WHERE CONTACT_RELATIONSHIP_ID = 11;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Brother' WHERE CONTACT_RELATIONSHIP_ID = 12;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Sister' WHERE CONTACT_RELATIONSHIP_ID = 13;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Uncle' WHERE CONTACT_RELATIONSHIP_ID = 14;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Aunt' WHERE CONTACT_RELATIONSHIP_ID = 15;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Son' WHERE CONTACT_RELATIONSHIP_ID = 16;
UPDATE SGAS.CONTACT_RELATIONSHIP SET DESCRIPT = 'Daughter' WHERE CONTACT_RELATIONSHIP_ID = 17;

UPDATE SGAS.CONTACT_RELATIONSHIP SET IS_ACTIVE = 'N' WHERE CONTACT_RELATIONSHIP_ID IN ('8');

----------SUPP_GRANT_RELATION----------------------
ALTER TABLE SGAS.SUPP_GRANT_RELATION ADD
(
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  IS_ADULT			  VARCHAR2(1) NULL
);

ALTER TABLE SUPP_GRANT_RELATION MODIFY (DESCRIPT  VARCHAR2(50));

ALTER TABLE SGAS.SUPP_GRANT_RELATION ADD (
  CONSTRAINT SG_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT SG_IS_ADULT
  CHECK ( IS_ADULT IN('Y','N') OR IS_ADULT IS NULL)
  ENABLE VALIDATE);

UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Son', IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 1;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Daughter', IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 2;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Stepson', IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 3;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Stepdaughter', IS_ADULT = 'N' WHERE SUPP_GRANT_RELATION_ID = 4;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Brother', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 5;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Sister', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 6;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Nephew (Child)', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 7;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Neice (Child)', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 8;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Other', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 9;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Brother (Adult)', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 10;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Sister (Adult)', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 11;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Father', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 12;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Mother', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 13;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Aunt', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 14;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Uncle', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 15;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Grandfather', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 16;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Grandmother', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 17;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Stepfather', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 18;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Stepmother', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 19;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Spouse', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 20;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Other (Adult)', IS_ACTIVE = 'N'  WHERE SUPP_GRANT_RELATION_ID = 21;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Neice (Adult)', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 22;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Nephew (Adult)', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 23;
UPDATE SGAS.SUPP_GRANT_RELATION SET DESCRIPT = 'Step Uncle', IS_ACTIVE = 'N' WHERE SUPP_GRANT_RELATION_ID = 24;

   
Insert into SGAS.SUPP_GRANT_RELATION
   (LEGACY_ID, LEGACY_CODE, DESCRIPT, IS_ACTIVE, IS_ADULT)
 Values
   (1, 'U', 'Husband, wife, civil partner or partner', 'Y', 'Y');

Insert into SGAS.SUPP_GRANT_RELATION
   (LEGACY_ID, LEGACY_CODE, DESCRIPT, IS_ACTIVE, IS_ADULT)
 Values
   (2, 'U', 'Adult I act as a carer for', 'Y', 'Y');

Insert into SGAS.SUPP_GRANT_RELATION
   (LEGACY_ID, LEGACY_CODE, DESCRIPT, IS_ACTIVE, IS_ADULT)
 Values
   (2, 'U', 'Child I act as a carer for', 'Y', 'N');
   

   ----------EU_PORTABILITY ~PK ADDED FOR MV ----------------------
ALTER TABLE SGAS.EU_PORTABILITY ADD (
  PRIMARY KEY (INST_CODE)
);

----------BENEFACTOR_RELATION-------------------
ALTER TABLE SGAS.BENEFACTOR_RELATION ADD
(
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

ALTER TABLE BENEFACTOR_RELATION MODIFY (DESCRIPT  VARCHAR2(50));

ALTER TABLE SGAS.BENEFACTOR_RELATION ADD (
  CONSTRAINT BR_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

UPDATE SGAS.BENEFACTOR_RELATION SET DESCRIPT = 'Father or Mother' WHERE BENEFACTOR_RELATION_ID = 1;
UPDATE SGAS.BENEFACTOR_RELATION SET DESCRIPT = 'Parent''s Partner' WHERE BENEFACTOR_RELATION_ID = 2;
UPDATE SGAS.BENEFACTOR_RELATION SET DESCRIPT = 'Step-Parent' WHERE BENEFACTOR_RELATION_ID = 3;
UPDATE SGAS.BENEFACTOR_RELATION SET DESCRIPT = 'Other' WHERE BENEFACTOR_RELATION_ID = 4;
UPDATE SGAS.BENEFACTOR_RELATION SET DESCRIPT = 'Husband, Wife or Partner' WHERE BENEFACTOR_RELATION_ID = 5;

INSERT INTO SGAS.BENEFACTOR_RELATION 
	(DESCRIPT, LEGACY_CODE, LEGACY_ID)
	VALUES('Legal Guardian', 'P', 33); 

----------STUD_INCOME_TYPE-----------------------
ALTER TABLE SGAS.STUD_INCOME_TYPE ADD
(
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);

ALTER TABLE STUD_INCOME_TYPE MODIFY (DESCRIPTION  VARCHAR2(100));

ALTER TABLE SGAS.STUD_INCOME_TYPE ADD (
  CONSTRAINT ST_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'None' WHERE INCOME_TYPE_ID = 0;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Benefits' WHERE INCOME_TYPE_ID = 1;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Working Tax Credits' WHERE INCOME_TYPE_ID = 2;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Trust Income' WHERE INCOME_TYPE_ID = 3;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Pension Income' WHERE INCOME_TYPE_ID = 4;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Property Income' WHERE INCOME_TYPE_ID = 5;
UPDATE SGAS.STUD_INCOME_TYPE SET DESCRIPTION = 'Other Income' WHERE INCOME_TYPE_ID = 6;


---------------------------------------------- NEW TABLES ------------------------------------

----------STUDENT_FAMILY_RELATIONSHIP--------------
CREATE TABLE SGAS.STUDENT_FAMILY_RELATIONSHIP
(
  STUDENT_FAMILY_RELATIONSHIP_ID      NUMBER(10)       	NOT NULL	CONSTRAINT SFR_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.STUDENT_FAMILY_RELATIONSHIP ADD (
  CONSTRAINT SF_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.STUDENT_FAMILY_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_STUDENT_FAMILY_SEQ
   BEFORE INSERT
   ON SGAS.STUDENT_FAMILY_RELATIONSHIP    FOR EACH ROW
BEGIN
   SELECT STUDENT_FAMILY_ID_SEQ.NEXTVAL
     INTO :NEW.STUDENT_FAMILY_RELATIONSHIP_ID
     FROM DUAL;
END;

Insert into SGAS.STUDENT_FAMILY_RELATIONSHIP
   (DESCRIPTION)
 Values
   ('Sibling');
Insert into SGAS.STUDENT_FAMILY_RELATIONSHIP
   (DESCRIPTION)
 Values
   ('Spouse or Partner');
Insert into SGAS.STUDENT_FAMILY_RELATIONSHIP
   (DESCRIPTION)
 Values
   ('Parent or Parent''s Partner');
Insert into SGAS.STUDENT_FAMILY_RELATIONSHIP
   (DESCRIPTION)
 Values
   ('Child or Step-Child');
Insert into SGAS.STUDENT_FAMILY_RELATIONSHIP
   (DESCRIPTION)
 Values
   ('Parent');


----------WHAT_DOING--------------------------------
CREATE TABLE SGAS.WHAT_DOING
(
  WHAT_DOING_ID       NUMBER(10)       	NOT NULL	CONSTRAINT WHD_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  ORGANISATION_REQ    VARCHAR2(1)				   DEFAULT 'Y'                   NOT NULL,
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.WHAT_DOING ADD (
  CONSTRAINT WD_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.WHAT_DOING_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_WHAT_DOING_ID_SEQ
   BEFORE INSERT
   ON SGAS.WHAT_DOING    FOR EACH ROW
BEGIN
   SELECT WHAT_DOING_ID_SEQ.NEXTVAL
     INTO :NEW.WHAT_DOING_ID
     FROM DUAL;
END;

Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('School', 'Y');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Home Education', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('College', 'Y');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('University', 'Y');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Employment', 'Y');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Unemployment', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Housewife/Househusband', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Incarcerated', 'Y');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Retired', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Travelling', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Carer', 'N');
Insert into SGAS.WHAT_DOING
   (DESCRIPTION, ORGANISATION_REQ)
 Values
   ('Financially Independent', 'N');

 
----------REASON_NO_BEN_INCOME----------------------
CREATE TABLE SGAS.REASON_NO_BEN_INCOME
(
  REASON_NO_BEN_INCOME_ID           NUMBER(10)       	NOT NULL	CONSTRAINT NOBEN_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(100),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.REASON_NO_BEN_INCOME ADD (
  CONSTRAINT RN_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.REASON_NO_BEN_INCOME_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_NO_BEN_INCOME_ID_SEQ
   BEFORE INSERT
   ON SGAS.REASON_NO_BEN_INCOME    FOR EACH ROW
BEGIN
   SELECT REASON_NO_BEN_INCOME_ID_SEQ.NEXTVAL
     INTO :NEW.REASON_NO_BEN_INCOME_ID
     FROM DUAL;
END;

Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Housewife/Househusband');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Unemployed - Not eligible for benefits');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Unemployed - Don''t receive benefits that we take into account');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Unemployed - Joint claim');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Retired - Not entitled to pension or benefits');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Self Employed - Made a loss');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Property or land income loss');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Full Time student in previous session');
Insert into SGAS.REASON_NO_BEN_INCOME
   (DESCRIPTION)
 Values
   ('Expected Dividends/Interest/Trust income not received');
  
----------REASON_FOR_ONE_BEN----------------------
CREATE TABLE SGAS.REASON_FOR_ONE_BEN
(
  REASON_FOR_ONE_BEN_ID           NUMBER(10)       	NOT NULL	CONSTRAINT ONE_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.REASON_FOR_ONE_BEN ADD (
  CONSTRAINT RF_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.REASON_FOR_ONE_BEN_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_REASON_FOR_ONE_BEN_ID_SEQ
   BEFORE INSERT
   ON SGAS.REASON_FOR_ONE_BEN    FOR EACH ROW
BEGIN
   SELECT REASON_FOR_ONE_BEN_ID_SEQ.NEXTVAL
     INTO :NEW.REASON_FOR_ONE_BEN_ID
     FROM DUAL;
END;

Insert into SGAS.REASON_FOR_ONE_BEN
   (DESCRIPTION)
 Values
   ('Single/Separated/Divorced');
Insert into SGAS.REASON_FOR_ONE_BEN
   (DESCRIPTION)
 Values
   ('Widowed');
Insert into SGAS.REASON_FOR_ONE_BEN
   (DESCRIPTION)
 Values
   ('In a relationship but living separately'); 
   
----------ENQUIRY_OPTION----------------------
CREATE TABLE SGAS.ENQUIRY_OPTION
(
  ENQUIRY_OPTION_ID           NUMBER(10)       	NOT NULL	CONSTRAINT ENQ_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.ENQUIRY_OPTION ADD (
  CONSTRAINT EO_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.ENQUIRY_OPTION_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_ENQUIRY_OPTION_ID_SEQ
   BEFORE INSERT
   ON SGAS.ENQUIRY_OPTION    FOR EACH ROW
BEGIN
   SELECT ENQUIRY_OPTION_ID_SEQ.NEXTVAL
     INTO :NEW.ENQUIRY_OPTION_ID
     FROM DUAL;
END;

Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Cancel/Amend Submitted Application');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Dependants Grant');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('DSA');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Migrant Worker');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Placement Expenses');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Study Abroad ');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Vacation Care Grant');
Insert into SGAS.ENQUIRY_OPTION
   (DESCRIPTION)
 Values
   ('Other');
   
----------ACCOUNT_LOCK_REASON----------------------
CREATE TABLE SGAS.ACCOUNT_LOCK_REASON
(
  ACCOUNT_LOCK_REASON_ID           NUMBER(10)       	NOT NULL	CONSTRAINT ALR_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.ACCOUNT_LOCK_REASON ADD (
  CONSTRAINT AL_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.ACCOUNT_LOCK_REASON_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.ACCOUNT_LOCK_REASON_SEQ
   BEFORE INSERT
   ON SGAS.ACCOUNT_LOCK_REASON    FOR EACH ROW
BEGIN
   SELECT ACCOUNT_LOCK_REASON_SEQ.NEXTVAL
     INTO :NEW.ACCOUNT_LOCK_REASON_ID
     FROM DUAL;
END;

Insert into SGAS.ACCOUNT_LOCK_REASON
   (DESCRIPTION)
 Values
   ('Duplicate account');
Insert into SGAS.ACCOUNT_LOCK_REASON
   (DESCRIPTION)
 Values
   ('Possible identity misuse');
Insert into SGAS.ACCOUNT_LOCK_REASON
   (DESCRIPTION)
 Values
   ('Possible malicious use');
Insert into SGAS.ACCOUNT_LOCK_REASON
   (DESCRIPTION)
 Values
   ('See Fraud');
   
   
   
----------ACCOUNT_UNLOCK_REASON----------------------
CREATE TABLE SGAS.ACCOUNT_UNLOCK_REASON
(
  ACCOUNT_UNLOCK_REASON_ID           NUMBER(10)       	NOT NULL	CONSTRAINT AUR_PK PRIMARY KEY,
  DESCRIPTION         VARCHAR2(50),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.ACCOUNT_UNLOCK_REASON ADD (
  CONSTRAINT AU_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.ACCOUNT_UNLOCK_REASON_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.ACCOUNT_UNLOCK_REASON_SEQ
   BEFORE INSERT
   ON SGAS.ACCOUNT_UNLOCK_REASON    FOR EACH ROW
BEGIN
   SELECT ACCOUNT_UNLOCK_REASON_SEQ.NEXTVAL
     INTO :NEW.ACCOUNT_UNLOCK_REASON_ID
     FROM DUAL;
END;

Insert into SGAS.ACCOUNT_UNLOCK_REASON
   (DESCRIPTION)
 Values
   ('Issue Resolved');

  
  ----------APPLICATION_STATUS_MESSAGE----------------------
CREATE TABLE SGAS.APPLICATION_STATUS_MESSAGE
(
  APPLICATION_STATUS_CODE                          VARCHAR2(1)       	NOT NULL	CONSTRAINT ASMS_PK PRIMARY KEY,
  APPLICATION_STATUS  VARCHAR2(50),
  DESCRIPTION         VARCHAR2(300),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.APPLICATION_STATUS_MESSAGE ADD (
  CONSTRAINT AM_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);


Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('N', 'New', 'We have received your application.');
Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('C', 'Assessed', 'We have assessed your application and you will be notified shortly.');
Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('T', 'Pending', 'Please check your Notifications for further information.');
Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('W', 'Withdrawn', 'Your college or university has told us you have withdrawn from your course. If you are still attending please contact them.');
Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('A', 'Non-Attendance', 'We have been notified you did not attend your course. If you are still attending please contact us on 0300 555 0505.');
Insert into SGAS.APPLICATION_STATUS_MESSAGE
   (APPLICATION_STATUS_CODE, APPLICATION_STATUS, DESCRIPTION)
 Values
   ('R', 'Rejected', 'Please check your Notifications for further information.');
 
 ----------AWARD_STATUS_MESSAGE----------------------
CREATE TABLE SGAS.AWARD_STATUS_MESSAGE
(
  AWARD_STATUS_MESSAGE_ID           NUMBER(10)       	NOT NULL	CONSTRAINT ASM_PK PRIMARY KEY,
  AWARD_STATUS        VARCHAR2(50),
  DESCRIPTION         VARCHAR2(300),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.AWARD_STATUS_MESSAGE ADD (
  CONSTRAINT AS_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.AWARD_STATUS_MESSAGE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.AWARD_STATUS_MESSAGE_SEQ
   BEFORE INSERT
   ON SGAS.AWARD_STATUS_MESSAGE    FOR EACH ROW
BEGIN
   SELECT AWARD_STATUS_MESSAGE_SEQ.NEXTVAL
     INTO :NEW.AWARD_STATUS_MESSAGE_ID
     FROM DUAL;
END;

Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Unclaimed', 'This award type has not been claimed for this application.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Claimed', 'You have claimed this award. We will notify you when we have assessed your entitlement.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Assessed', 'We have assessed your entitlement to this award and will confirm your entitlement in your award notice.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Assessed', 'We have assessed your entitlement to this award and have restricted this to a non-income assessed award.  We need further information to process your full entitlement. Please check your Notifications for further information.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Pending', 'We need more information to assess your entitlement to this award.  Please check your Notifications for further information.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Rejected', 'We have assessed your application and you are not entitled to this award.  We will contact you with the reasons for this decision.');
Insert into SGAS.AWARD_STATUS_MESSAGE
   (AWARD_STATUS, DESCRIPTION)
 Values
   ('Rejected', 'We have assessed your application and you are not entitled to this award.');
  
  
  
 ----------STUDENT_MESSAGE_SUBJECT----------------------
CREATE TABLE SGAS.STUDENT_MESSAGE_SUBJECT
(
  STUDENT_MESSAGE_SUBJECT_ID           NUMBER(10)       	NOT NULL	CONSTRAINT SMS_PK PRIMARY KEY,
  DISPLAY_ORDER       NUMBER(10)                   NOT NULL,
  DESCRIPTION         VARCHAR2(300),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SGAS.STUDENT_MESSAGE_SUBJECT ADD (
  CONSTRAINT SM_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);

CREATE SEQUENCE SGAS.STUDENT_MESSAGE_SUBJECT_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.STUDENT_MESSAGE_SUBJECT_SEQ
   BEFORE INSERT
   ON SGAS.STUDENT_MESSAGE_SUBJECT    FOR EACH ROW
BEGIN
   SELECT STUDENT_MESSAGE_SUBJECT_SEQ.NEXTVAL
     INTO :NEW.STUDENT_MESSAGE_SUBJECT_ID
     FROM DUAL;
END;

Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (1, 'Disabled Students'' Allowance');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (2, 'Household Income');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (3, 'Living Costs Grant');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (4, 'Nursing/Midwifery Course');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (5, 'Placements');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (6, 'Postgraduate Study');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (7, 'Previous Study');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (8, 'Residency');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (9, 'Student Loan');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (10, 'Studying Abroad');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (11, 'Tuition Fee Loan');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (12, 'Your SAAS Application');
Insert into SGAS.STUDENT_MESSAGE_SUBJECT
   (DISPLAY_ORDER, DESCRIPTION)
 Values
   (13, 'Reply to your Student Enquiry');  
  
----------NATIONALITY-----------------------------
CREATE TABLE SGAS.NATIONALITY
(
  NATIONALITY_ID      NUMBER(10)       	NOT NULL	CONSTRAINT NAT_PK PRIMARY KEY,
  COUNTRY_CODE        NUMBER(3),
  NATIONALITY_NAME    VARCHAR2(25),
  NATIONALITY_REGION  VARCHAR2(10),
  LAST_UPDATED_BY     VARCHAR2(15 BYTE)            DEFAULT USER                  NOT NULL,
  LAST_UPDATED_ON     DATE                         DEFAULT SYSDATE               NOT NULL,
  IS_ACTIVE           VARCHAR2(1)                  DEFAULT 'Y'                   NOT NULL
  
);
 
ALTER TABLE SGAS.NATIONALITY ADD (
  CONSTRAINT NA_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT NA_NATIONALITY_REGION
  CHECK ( NATIONALITY_REGION IN('UK','EU', 'ROW'))
  ENABLE VALIDATE,
  CONSTRAINT CODE_FK	
  FOREIGN KEY (COUNTRY_CODE)	
  REFERENCES SGAS.COUNTRY (COUNTRY_CODE)
  ENABLE VALIDATE
);

CREATE SEQUENCE SGAS.NATIONALITY_ID_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999
NOCACHE 
NOCYCLE 
NOORDER;

CREATE OR REPLACE TRIGGER SGAS.TRIG_NATIONALITY_SEQ
   BEFORE INSERT
   ON SGAS.NATIONALITY    FOR EACH ROW
BEGIN
   SELECT NATIONALITY_ID_SEQ.NEXTVAL
     INTO :NEW.NATIONALITY_ID
     FROM DUAL;
END;
 
   
   







   


 
 












