--- OLS 2016 UPDATES TO SGAS.COUNTRY-----------------------------------------------------------

ALTER TABLE SGAS.COUNTRY ADD
(
  UK_COUNTRY          VARCHAR2(1) DEFAULT 'N' NOT NULL,
  IS_ACTIVE           VARCHAR2(1) DEFAULT 'Y' NOT NULL
);


ALTER TABLE SGAS.COUNTRY ADD (
  CONSTRAINT CN_UK_COUNTRY
  CHECK ( UK_COUNTRY IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT CN_IS_ACTIVE
  CHECK ( IS_ACTIVE IN('Y','N'))
  ENABLE VALIDATE);
  
BEGIN
  
UPDATE SGAS.COUNTRY SET UK_COUNTRY = 'Y' WHERE COUNTRY_CODE = 1; -- ENGLAND
UPDATE SGAS.COUNTRY SET UK_COUNTRY = 'Y' WHERE COUNTRY_CODE = 4; -- IRELAND
UPDATE SGAS.COUNTRY SET UK_COUNTRY = 'Y' WHERE COUNTRY_CODE = 299; -- SCOTLAND
UPDATE SGAS.COUNTRY SET UK_COUNTRY = 'Y' WHERE COUNTRY_CODE = 579; -- WALES

---------------------Set to N where child record exists--------------------------------------
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 99; -- DUPLICATE NORTHER IRELAND
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 644; -- DENMARK 2002 
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 100; -- NORWAY 2000	
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 780; -- YUGOSLAVIA	
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 622; --'BURM'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 688; --'LEB'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 695; -- MALAGASY
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 697; -- MALAYAN
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 712; -- NEW GUINEA
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 735; -- ST HELENA
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 922; -- ST VINCENT
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 772; -- USSR/CIS
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 775; -- NORTH VIETNAM REPLACED BY VIETNAM
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 777; -- WEST INDIES
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 601; -- YEMENI PDR
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 633; -- ZAIRE
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 9; --'CAROLINA'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 427; --'ILEA'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 624; --'KAMP'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 687; --'LAO PDR'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 689; --'LEE ISL'
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 742; -- SARAWAKI
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 797; -- SIKKIMI
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 771; -- USA
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE = 741; -- WEST SAMOA


UPDATE SGAS.COUNTRY SET LONG_NAME = 'UNITED STATES OF AMERICA' WHERE COUNTRY_CODE = 2; 
UPDATE SGAS.COUNTRY SET LONG_NAME = 'NORTHERN IRELAND' WHERE COUNTRY_CODE = 4; 
UPDATE SGAS.COUNTRY SET LONG_NAME = 'VIRGIN ISLANDS (AMERICAN)' WHERE COUNTRY_CODE = 800; 
UPDATE SGAS.COUNTRY SET LONG_NAME = 'ANTIGUA AND BARBUDA' WHERE COUNTRY_CODE = 607;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'AZERBAIJAN' WHERE COUNTRY_CODE = 837;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'BRITISH ANTARCTIC TERRITORY' WHERE COUNTRY_CODE = 801;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'BURKINA FASO' WHERE COUNTRY_CODE = 769;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'CHINA' WHERE COUNTRY_CODE = 631;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'CONGO' WHERE COUNTRY_CODE = 634;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'ERITREA' WHERE COUNTRY_CODE = 851;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'GREENLAND' WHERE COUNTRY_CODE = 828;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'NORTH KOREA' WHERE COUNTRY_CODE = 685;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'SOUTH KOREA' WHERE COUNTRY_CODE = 684;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'MALDIVES' WHERE COUNTRY_CODE = 793;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'PAPUA NEW GUINEAN' WHERE COUNTRY_CODE = 723;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'EAST TIMOR' WHERE COUNTRY_CODE = 786;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'SABA' WHERE COUNTRY_CODE = 739;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'SOMALIA' WHERE COUNTRY_CODE = 748;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'ST HELENA, ASCENSION AND TRISTAN DA CUNHA' WHERE COUNTRY_CODE = 735;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'VIETNAM' WHERE COUNTRY_CODE = 774;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'SURINAME' WHERE COUNTRY_CODE = 753;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'SYRIA' WHERE COUNTRY_CODE = 757;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'TURKMEN' WHERE COUNTRY_CODE = 844;
UPDATE SGAS.COUNTRY SET LONG_NAME = 'YEMEN' WHERE COUNTRY_CODE = 779;

UPDATE SGAS.COUNTRY SET SHORT_NAME = 'SAMO' WHERE COUNTRY_CODE = 796;
UPDATE SGAS.COUNTRY SET SHORT_NAME = 'VIET' WHERE COUNTRY_CODE = 774;
UPDATE SGAS.COUNTRY SET SHORT_NAME = 'SYR' WHERE COUNTRY_CODE = 757;
UPDATE SGAS.COUNTRY SET SHORT_NAME = 'YEM' WHERE COUNTRY_CODE = 779;
UPDATE SGAS.COUNTRY SET SHORT_NAME = 'GREE' WHERE COUNTRY_CODE = 828;


UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'BHUTANESE' WHERE COUNTRY_CODE = 616;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'BOSNIAN/HERZOGOVIAN' WHERE COUNTRY_CODE = 848;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'BRUNEIAN' WHERE COUNTRY_CODE = 620;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'BURKINABE' WHERE COUNTRY_CODE = 769;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'CENTRAL AFRICAN' WHERE COUNTRY_CODE = 627;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'CAMEROONIAN' WHERE COUNTRY_CODE = 625;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'CAPE VERDEAN' WHERE COUNTRY_CODE = 788;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'CAYMANIAN' WHERE COUNTRY_CODE = 789;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'CHADIAN' WHERE COUNTRY_CODE = 629;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'DJIBOUTIAN' WHERE COUNTRY_CODE = 749;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'GABONESE' WHERE COUNTRY_CODE = 654;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'EQUATOGUINEAN' WHERE COUNTRY_CODE = 790;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'GREENLANDER' WHERE COUNTRY_CODE = 828;

UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'HONG KONGER' WHERE COUNTRY_CODE = 669;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'MALDIVE' WHERE COUNTRY_CODE = 793;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'MALIAN' WHERE COUNTRY_CODE = 699;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'MOZAMBICAN' WHERE COUNTRY_CODE = 707;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'NEPALESE' WHERE COUNTRY_CODE = 709;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'NIGERIEN' WHERE COUNTRY_CODE = 716;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'PAPUA NEW GUINEAN' WHERE COUNTRY_CODE = 723;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'DUTCH' WHERE COUNTRY_CODE = 739;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SAMOA' WHERE COUNTRY_CODE = 796;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SAMMARINESE' WHERE COUNTRY_CODE = 826;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SIERRA LEONEAN' WHERE COUNTRY_CODE = 745;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SINGAPOREAN' WHERE COUNTRY_CODE = 746;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SOLOMAN ISLANDER' WHERE COUNTRY_CODE = 747;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'VIETNAMESE' WHERE COUNTRY_CODE = 774;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'SURINAME' WHERE COUNTRY_CODE = 753;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'TOGOLESE' WHERE COUNTRY_CODE = 762;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'TURKMENISTAN' WHERE COUNTRY_CODE = 844;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'TUVULAN' WHERE COUNTRY_CODE = 647;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'EMIRATI' WHERE COUNTRY_CODE = 764;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'UZBEKISTANI' WHERE COUNTRY_CODE = 846;
UPDATE SGAS.COUNTRY SET NATIONALITY_NAME = 'VANUATUAN' WHERE COUNTRY_CODE = 713;




Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (11, 'AMS', 'AMERICAN SAMOAN', 'AMERICAN SAMOA', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (12, 'ANT', 'ANTARCTICAN', 'ANTARCTICA', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (13, 'CAMB', 'CAMBODIAN', 'CAMBODIA', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (14, 'CHR', 'CHRISTMAS ISLAND', 'CHRISTMAS ISLAND', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (15, 'COCOS', 'COCOS (KEELING) ISLANDS', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (16, 'COO', 'COOK ISLANDS', 'COOK ISLANDS', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (17, 'EAS', 'TIMORESE', 'EAST TIMOR', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (18, 'GAZ', 'GAZA', 'GAZA', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (19, 'GUAD', 'FRENCH', 'GUADELOUPE', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (20, 'LAO', 'LAOTIAN', 'LAOS', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (21, 'LIBY', 'LIBYAN', 'LIBYA', 
    'N', 'N', 'SGAS');

	Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (22, 'MAC', 'MACANESE', 'MACAO', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (23, 'MADA', 'MADAGASY', 'MADAGASCAR', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (24, 'MAR', 'MARSHALLESE', 'MARSHALL ISLANDS', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (25, 'MART', 'FRENCH', 'MARTINIQUE', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (26, 'MICR', 'MICRONESIA', 'MICRONESIA (FEDERATED STATES OF)', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (27, 'PAL', 'PALAU', 'PALAU', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (28, 'PALE', 'PALESTINIAN', 'PALESTINE', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (29, 'REU', 'REUNION', 'REUNION ISLAND', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (30, 'SAINT', 'FRENCH', 'SAINT BARTHELEMY', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (31, 'SAIN', 'KITTIAN NEVISIAN', 'SAINT KITTS AND NEVIS', 
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (32, 'ARUB', 'ARUBAN', 'ARUBA', 
    'N', 'N', 'SGAS');
	
Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (33, 'FAR', 'FAROESE', 'FAROE ISLANDS',
    'N', 'N', 'SGAS');
	
Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY)
 Values
   (34, 'NIU', 'NIUEANS', 'NIUE',
    'N', 'N', 'SGAS');

Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY, UK_COUNTRY)
 Values
   (35, 'CHAN', 'BRITISH', 'CHANNEL ISLANDS',
    'N', 'Y', 'SGAS', 'Y');
	
Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY, UK_COUNTRY)
 Values
   (36, 'ISLE', 'BRITISH', 'ISLE OF MAN',
    'N', 'N', 'SGAS', 'Y');
	
Insert into SGAS.COUNTRY
   (COUNTRY_CODE, SHORT_NAME, NATIONALITY_NAME, LONG_NAME, 
    SKELETON, EUROPEAN_COMMUNITY, LAST_UPDATED_BY, UK_COUNTRY)
 Values
   (37, 'LIE', 'LIECHTENSTEINER', 'LIECHTENSTEIN ',
    'N', 'Y', 'SGAS', 'N');


COMMIT;
END;
