SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  select DISTINCT(nationality_name), COUNTRY_CODE, NATIONALITY_REGION from country WHERE IS_ACTIVE = 'Y' order by nationality_name asc;
--
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AFGHAN', 602, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ALBANIAN', 603, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ALGERIAN', 604, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AMERICAN (USA)', 2, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AMERICAN (VIRGIN ISLANDS)', 800, 'ROW');

Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AMERICAN SAMOAN', 11, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ANDORRAN', 605, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ANGOLAN', 606, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ANGUILLAN', 824, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ANTARCTICAN', 12, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ANTIGUAN', 607, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ARGENTINIAN', 608, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ARMENIAN', 836, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ARUBAN', 32, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AUSTRALIAN', 609, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AUSTRIAN', 610, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('AZERBAIJANI', 837, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BAHAMIAN', 611, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BAHRANIAN', 612, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BANGLADESHI', 787, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BARBADIAN', 613, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BELARUSSIAN', 838, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BELGIAN', 614, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BELIZE', 668, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BENIN', 640, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BERMUDAN', 615, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BHUTANESE', 616, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BOLIVIAN', 617, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BOSNIAN/HERZOGOVIAN', 848, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BOTSWANIAN', 618, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRAZILIAN', 619, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (UK)', 10, 'UK');

--MAKE INACTIVE SO LAST LINE OF SQL WORKS ------------------------
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION, IS_ACTIVE)
 Values
   ('BRITISH (N IRELAND)', 99, 'UK', 'N');

   
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (FALKLAND ISLES)', 649, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (GIBRALTER)', 659, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (CHANNEL ISLES)', 35, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (ISLE OF MAN)', 36, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (VIRGIN ISLES)', 776, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRITISH (ANTARTIC TER)', 801, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BRUNEIAN', 620, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BULGARIAN', 621, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BURKINABE', 769, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('BURUNDI', 623, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CAMBODIAN', 13, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CAMEROONIAN', 625, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CANADIAN', 626, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CAPE VERDEAN', 788, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CAYMANIAN', 789, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CENTRAL AFRICAN', 627, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CHADIAN', 629, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CHILIAN', 630, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CHINESE', 631, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CHRISTMAS ISLAND', 14, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('COCOS', 15, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('COLOMBIAN', 632, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('COMOROS', 804, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CONGOLESE', 634, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('COOK ISLANDS', 16, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('COSTA RICAN', 635, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CROATIAN', 834, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CUBAN', 636, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CYPRIOT', 638, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('CZECH', 849, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DANISH', 641, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DJIBOUTIAN', 749, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DOMINICAN (DOMINICA)', 642, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DOMINICAN (DOM REPUBLIC)', 643, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DUTCH (NETHERLANDS)', 710, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DUTCH (SABA)', 739, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('DUTCH (ANTILLES)', 637, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ECUADORIAN', 645, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('EGYPTIAN', 900, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('EL SALVADORIAN', 646, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('EMIRATI', 764, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ENGLISH', 1, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('EQUATOGUINEAN', 790, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ERITREAN', 851, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ESTONIAN', 831, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ETHIOPIAN', 648, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FAROESE', 33, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FIJIAN', 650, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FILIPINO', 726, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FINNISH', 651, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (SAINT BARTHELEMY)', 30, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (GUYANA)', 791, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (WEST INDIES)', 792, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (O/SEAS TERR)', 822, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (GUADELOUPE)', 19, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (FRANCE)', 653, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('FRENCH (MARTINIQUE)', 25, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GABONESE', 654, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GAMBIAN', 655, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GAZA', 18, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GEORGIAN', 847, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GERMAN', 656, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GHANAIAN', 658, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GREEK', 661, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GREENLANDER', 828, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GRENADAN', 662, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GUATAMALIAN', 663, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GUINEA BISSAUN', 802, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GUINEAN', 664, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('GUYANAN', 665, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('HAITIAN', 666, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('HONDURAN', 667, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('HONG KONGER', 669, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('HUNGARIAN', 670, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ICELANDIC', 671, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('INDIAN', 672, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('INDONESIAN', 673, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('IRANIAN', 674, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('IRAQI', 675, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('IRISH (REPUBLIC)', 676, 'EU');

--- MAKE INACTIVE SO LAST LINE OF SQL WORKS----------------
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION, IS_ACTIVE)
 Values
   ('IRISH', 4, 'UK', 'N');
   

Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ISRAELI', 677, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ITALIAN', 678, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('IVORY COAST', 679, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('JAMAICAN', 680, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('JAPANESE', 681, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('JORDANIAN', 682, 'ROW');

Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KAZAKH', 839, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KENYAN', 683, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KIRIBATI', 660, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KITTIAN NEVISIAN', 31, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SOUTH KOREAN', 684, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NORTH KOREAN', 685, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KOSOVAN', 523, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KUWAITI', 686, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('KYRGYZSTANI', 840, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LAOTIAN', 20, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LATVIAN', 832, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LESOTHAN', 690, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LIBERIAN', 691, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LIBYAN', 21, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LIECHTENSTEINER', 37, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LITHUANIAN', 833, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('LUXEMBOURG', 693, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MACANESE', 22, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MACAO', 694, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MACEDONIAN', 524, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MADAGASY', 23, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MALAWIAN', 696, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MALAYSIAN', 698, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MALDIVE', 793, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MALIAN', 699, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MALTESE', 700, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MARSHALLESE', 24, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MAURITANIAN', 701, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MAURITIAN', 702, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MAYOTTIAN', 821, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MEXICAN', 703, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MICRONESIA', 26, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MOLDOVAN', 841, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MONACAN', 825, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MONGOLIAN', 704, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MONTENEGRIN', 528, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MONTSERRAT', 705, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MOROCCAN', 706, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('MOZAMBICAN', 707, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NAMIBIAN', 798, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NAURAN', 805, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NEPALESE', 709, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NEW CALEDONIAN', 711, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NEW ZEALAND', 714, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NICARAGUAN', 715, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NIGERIAN', 717, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NIGERIEN', 716, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NIUEANS', 34, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NORWEGIAN', 718, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('NOT KNOWN', 782, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('OMANI', 708, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PAKISTANI', 721, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PALAU', 27, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PALESTINIAN', 28, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PANAMANIAN', 722, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PAPUA NEW GUINEAN', 723, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PARAGUAYAN', 724, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PERUVIAN', 725, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('POLISH', 727, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PORTUGUESE', 728, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PORTUGUESE TIMOR', 786, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PORTUGUESE WEST AFRICAN', 794, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('PUERTO RICAN', 730, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('QATARI', 731, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('REUNION', 29, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ROMANIAN', 733, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('RUSSIAN', 842, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('RWANDAN', 734, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SAMMARINESE', 826, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SAMOA', 796, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SAO TOME & PRINCIPE', 803, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SAUDI', 743, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SCILLIAN', 420, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SCOTTISH', 299, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SENEGALI', 785, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SERBIAN', 526, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SEYCHELLOIS', 744, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SIERRA LEONEAN', 745, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SINGAPOREAN', 746, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SLOVAKIAN', 850, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SLOVENIAN', 835, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SOLOMAN ISLANDER', 747, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SOMALI', 748, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SOUTH AFRICAN', 750, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SPANISH', 751, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SRI LANKAN', 628, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ST LUCIAN', 737, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SUDANESE (SUDAN)', 752, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SUDANESE (SOUTH SUDAN)', 527, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SURINAME', 753, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SWAZI', 754, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SWEDISH', 755, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SWISS', 756, 'EU');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('SYRIAN', 757, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TAIWANESE', 652, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TAJIK', 843, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TANZANIAN', 759, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('THAI', 760, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TIBETAN', 761, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TIMORESE', 17, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TOGOLESE', 762, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TONGAN', 784, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TRINIDAD & TOBAGAN', 763, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TUNISIAN', 765, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TURKA & CAICOS ISLANDS', 799, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TURKISH', 766, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TURKMENISTAN', 844, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('TUVULAN', 647, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('UAR', 768, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('UGANDAN', 767, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('UKRANIAN', 845, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('URUGUYAN', 770, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('UZBEKISTANI', 846, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('VANUATUAN', 713, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('VENEZUELAN', 773, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('VIETNAMESE', 774, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('WELSH', 579, 'UK');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('YEMENI', 779, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ZAMBIAN', 781, 'ROW');
Insert into SGAS.NATIONALITY
   (NATIONALITY_NAME, COUNTRY_CODE, NATIONALITY_REGION)
 Values
   ('ZIMBABWEAN', 732, 'ROW');

COMMIT;

------------------------------- SET EVERYTHING ELSE IN COUNTRY TO INACTIVE -----------------------------
UPDATE SGAS.COUNTRY SET IS_ACTIVE = 'N' WHERE COUNTRY_CODE NOT IN (SELECT COUNTRY_CODE FROM NATIONALITY);