----------------------- UPDATE STREAM TABLES WEB---------------------------------------

ALTER TABLE STUD ADD 
(
	RESIDENCY_CATEGORY 				VARCHAR2(8),
	PORTAL_USER_ID                  VARCHAR2(25)
);

ALTER TABLE STUD_SESSION ADD 
(
	BEN1_AB36 				VARCHAR2(1),
	BEN2_AB36               VARCHAR2(1),
	CONSTRAINT STUD1_AB36
    CHECK ( BEN1_AB36 IN('Y','N'))
    ENABLE VALIDATE,
	CONSTRAINT STUD2_AB36
    CHECK ( BEN2_AB36 IN('Y','N'))
    ENABLE VALIDATE
);

ALTER TABLE STUD_CRSE_YEAR ADD 
(
	IS_INDEPENDENT 					VARCHAR2(1),
	INTERRUPTION_FROM_STUDY         VARCHAR2(1)
);


ALTER TABLE BENEFACTOR ADD 
(
	AB36 							VARCHAR2(1),
	CONSENT_TO_SHARE_STUDENT		VARCHAR2(1),
	ONLY_ONE_BEN					VARCHAR2(1),
	REASON_FOR_ONE_BEN_ID			NUMBER(10)
);

ALTER TABLE BENEFACTOR ADD (
  CONSTRAINT BEN_AB36
  CHECK ( AB36 IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT BEN_CTSS
  CHECK ( CONSENT_TO_SHARE_STUDENT IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT BEN_OOB
  CHECK ( ONLY_ONE_BEN IN('Y','N'))
  ENABLE VALIDATE,
  CONSTRAINT RES_ONE_BEN_FK	
  FOREIGN KEY (REASON_FOR_ONE_BEN_ID)	
  REFERENCES REASON_FOR_ONE_BEN (REASON_FOR_ONE_BEN_ID)
  ENABLE VALIDATE
);

ALTER TABLE STUD_CONT_DETAILS ADD
(
	CONT_CONSENT					VARCHAR2(1)

); 

ALTER TABLE STUD_MESSAGE MODIFY (MESSAGE_TEXT VARCHAR2(1000));

ALTER TABLE STUD_MESSAGE ADD
(
	SUBJECT					        NUMBER(10)
); 

UPDATE STUD_MESSAGE SET SUBJECT = 12;
ALTER TABLE STUD_MESSAGE MODIFY (SUBJECT NOT NULL);

ALTER TABLE STUD_MESSAGE ADD 
(
  CONSTRAINT SM_SUB_FK	
  FOREIGN KEY (SUBJECT)	
  REFERENCES SGAS.STUDENT_MESSAGE_SUBJECT(STUDENT_MESSAGE_SUBJECT_ID) 
  ENABLE VALIDATE
);