-- Adhoc to add foreign key references
--
-- MODIFICATION HISTORY:
-- Ref      Date        Author                  Desc.
-- 1.0      10.11.2010  A.Bowman (SAAS)         Initial Version.
-- 
--
-- Configuration Management:
-- $HeadURL: $ 
-- $Author: $
-- $Date: $
-- $Revision: $ 

ALTER TABLE SGAS.PAYMENT_INSTALMENT ADD (
  CONSTRAINT F2_PINST 
 FOREIGN KEY (AWARD_INSTALMENT_ID) 
 REFERENCES SGAS.AWARD_INSTALMENT (AWARD_INSTALMENT_ID));

ALTER TABLE SGAS.PAYMENT_INSTALMENT ADD (
  CONSTRAINT F4_PINST 
 FOREIGN KEY (PAYEE_PAYMENT_ID) 
 REFERENCES SGAS.PAYEE_PAYMENT (PAYEE_PAYMENT_ID));

ALTER TABLE SGAS.PAYMENT_INSTALMENT ADD (
  CONSTRAINT F5_PINST 
 FOREIGN KEY (PAYEE_ID) 
 REFERENCES SGAS.PAYEE (PAYEE_ID));

ALTER TABLE SGAS.PAYEE_PAYMENT ADD (
  CONSTRAINT F1_PYE 
 FOREIGN KEY (PAYEE_ID) 
 REFERENCES SGAS.PAYEE (PAYEE_ID));

ALTER TABLE SGAS.STUD_RATE ADD (
  CONSTRAINT F1_STR
 FOREIGN KEY (STUD_AWARD_TYPE_ID) 
 REFERENCES SGAS.STUD_AWARD_TYPE (STUD_AWARD_TYPE_ID));

ALTER TABLE COMPLETED_TEC ADD (
  CONSTRAINT CTEC_FK3 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO));
 
 
ALTER TABLE SGAS.EDM_AUD ADD (
  CONSTRAINT EDM_AUD_STUD_FK 
 FOREIGN KEY (STUD_REF_NO) 
 REFERENCES STUD (STUD_REF_NO) DISABLE);
 
ALTER TABLE SGAS.REFERENCE_TYPES ADD (
  CONSTRAINT F_RDM1 
 FOREIGN KEY (DOMAIN) 
 REFERENCES REFERENCE_DOMAINS (DOMAIN_NAME));

commit;