/* Formatted on 2012/09/27 15:31 (Formatter Plus v4.8.8) */
COMMENT ON TABLE adjust IS 'Records overpayments (adjustments and repayments) relating to institutions and students';
COMMENT ON TABLE applic_reg IS 'A record of documents sent in by the student';
COMMENT ON TABLE authenticate_stud IS 'This table contains authenticated student details';
COMMENT ON TABLE award IS 'The award information for a particular student';
COMMENT ON TABLE award_instalment IS 'The instalments to be paid to the student, nominee or institution';
COMMENT ON TABLE bank_change_exc IS 'Table holding a list of exceptions thrown during the steps_bank_change web job';
COMMENT ON TABLE ben_income_status IS 'The different statuses a benefactor may have';
COMMENT ON TABLE ben_income_type IS 'Table containing the different income types a benefactor may have';
COMMENT ON TABLE benefactor IS 'A students benefactor may be required to support the student, usually the students parents';
COMMENT ON TABLE benefactor_dependant IS 'The details of a benefactors dependant, eg child';
COMMENT ON TABLE benefactor_income IS 'The benefactors income record. e.g Fathers income';
COMMENT ON TABLE benefactor_relation IS 'Table containing the different relationship types a benefactor may have with a student';
COMMENT ON TABLE complete_task_data IS 'Table containing details of processed tasks performed through the Student Task workflow';
COMMENT ON TABLE complete_web_applications IS 'Table used to hold data transferred from the Web service prior to the application being created on StEPS';
COMMENT ON TABLE completed_shwap IS 'Holds student information for short web applications';
--COMMENT ON TABLE    completed_tec    IS    'Table used to hold data transferred from the Web service prior to the Travel award being created on StEPS award tables';
COMMENT ON TABLE config_data IS 'This internal processing table will be used to store both numeric and character based configuration data';
COMMENT ON TABLE config_edm IS 'This table holds details of EDM document types and is used to populate an dropdown at completion stage and dropdowns for recategorisation and attaching new documents within StEPS';
COMMENT ON TABLE contact_relationship IS 'Table containing the different relationship types a loan contact may have with a student';
COMMENT ON TABLE corres IS 'Written correspondence details held by the agency';
COMMENT ON TABLE corres_attach IS 'Contains Ad-Hoc outgoing correspondence as OLE objects';
COMMENT ON TABLE country IS 'Country details';
COMMENT ON TABLE dearing_status IS 'Table containnig all the Dearing statuses';
COMMENT ON TABLE dsa_application IS 'Table containnig DSA applications for a student';
COMMENT ON TABLE dsa_assessment_centre IS 'Table containing details about DSA Assessment Centres';
COMMENT ON TABLE dsa_category IS 'Table containing the different categories a DSA allowance may be classed as';
COMMENT ON TABLE dsa_payment IS 'Table containing details about DSA payments made to a student';
COMMENT ON TABLE dsa_student_type IS 'Table containing the different student types that a DSA application was processed under';
COMMENT ON TABLE dup_bank_reason IS 'Reasons a student may have duplicate bank details to another student';
COMMENT ON TABLE edm_app_labels IS 'Table to hold details of all EDM batches and whether B and W labels have been printed for the batch';
COMMENT ON TABLE edm_aud IS 'Table holding auditing of data changes on the SAS3 application form in Correction and Completion';
COMMENT ON TABLE edm_event_aud IS 'Parent table to EDM_EVENT_AUD_ACTION holding scanning, correction and completion event data';
COMMENT ON TABLE edm_event_aud_action IS 'Child table to EDM_EVENT_AUD holding scanning, correction and completion event data';
COMMENT ON TABLE edm_images IS 'This table holds details of images and XML data files held on the EDM server';
COMMENT ON TABLE email_mphone_change_exc IS 'Table holding a list of exceptions thrown during the steps_mail_change web job';
COMMENT ON TABLE employee IS 'Table containing all staff details who have interacted with StEPS';
COMMENT ON TABLE employee_activity IS 'Table containing processing stats of staff';
COMMENT ON TABLE employee_cases IS 'Table containing the last ten cases a staff member has had locked';
COMMENT ON TABLE employee_locks IS 'Table containing the current locks a staff member may have from updating cases';
COMMENT ON TABLE home_addr_change_exc IS 'Table holding a list of exceptions thrown during the steps_home_change web job';
COMMENT ON TABLE ja_case IS 'The overall details of a joint application case are held in this table';
COMMENT ON TABLE label_print IS 'A table used for Labelling/Filing';
COMMENT ON TABLE loan_contacts_change_exc IS 'Table holding a list of exceptions thrown during the steps_loan_change web job';
COMMENT ON TABLE location IS 'A table used for Labelling/Filing';
COMMENT ON TABLE other_change_exc IS 'Table holding a list of exceptions thrown during the steps_other_change web job';
COMMENT ON TABLE pt_stud_dependant IS 'A part time student dependants details';
COMMENT ON TABLE scoap_batches IS 'Contains an entry for each payment batch';
COMMENT ON TABLE scoap_payments IS 'Contains the payment entries relating to batches of payments';
COMMENT ON TABLE slc_batches IS 'A table used for SLC file production';
COMMENT ON TABLE slc_data IS 'A table used for SLC file production';
COMMENT ON TABLE slc_errors IS 'A table used for SLC file error production';
COMMENT ON TABLE std_letters IS 'Descriptions and filenames of documents used for standard letters';
COMMENT ON TABLE std_letters_categories IS 'Categories of shell letters that they are grouped under';
COMMENT ON TABLE stud IS 'The student details which usually remain unchanged from year to year';
COMMENT ON TABLE stud_app_prog IS 'Table used to hold details of student application status for telephony enquiries';
COMMENT ON TABLE stud_cont_details IS 'A table used for holding student contact details';
COMMENT ON TABLE stud_crse_year IS 'The combination of a student and their course of study for a specific academic session and course year';
COMMENT ON TABLE stud_dependant IS 'Details of any of the students dependants';
COMMENT ON TABLE stud_home_addr IS 'The current and previous addresses of a student';
COMMENT ON TABLE stud_rate IS 'The data and rates associated with a particular award type paid to a student';
COMMENT ON TABLE stud_session IS 'Holds details related to a student for a particular session';
COMMENT ON TABLE stud_term_addr IS 'The address of a student during term time';
COMMENT ON TABLE stud_track IS 'A table used for Labelling/Filing';
COMMENT ON TABLE stud_trav_prog IS 'Table used to hold details of student application status for telephony enquiries';
COMMENT ON TABLE telephony_mis IS 'Table used to hold MIS details of telephony enquiries';
COMMENT ON TABLE term_addr_change_exc IS 'Table holding a list of exceptions thrown during the steps_term_change web job';
COMMENT ON TABLE title_name_change_exc IS 'Table holding a list of exceptions thrown during the steps_name_change web job';

COMMENT ON TABLE adi_journal IS 'Holds adi payment record for a batch, equivalent database record of one line from an ADI file';
COMMENT ON TABLE attendance_data IS 'This table will be used by SAAS to store information on whether enrolment and ongoing attendance information has been requested for each STUD_CRSE_YEAR record';
COMMENT ON TABLE attendance_data_message IS 'This table is used to store the messages generated when an ATTENDANCE_DATA record fails a validation check';
COMMENT ON TABLE attendance_data_received IS 'This table holds details of all return file records received from Institutions';
COMMENT ON TABLE attendance_data_status IS 'This table is used to store the status codes which will be populated by Institutions in the Attendance Data files';
COMMENT ON TABLE audit_staging IS 'This table that contains all the audited information from the SGAS schema, within the SGAS schema, before it is moved to the AUDIT schema';
COMMENT ON TABLE audit_staging_failed IS 'This table contains failure messages for records that could not be inserted into AUDIT.FACT_AUD';
COMMENT ON TABLE award_letter_errors IS 'This table holds error information gathered during the execution of Award Letters, this data will assist the BSU identify which letters have failed';
COMMENT ON TABLE batch_recalc IS 'This table holds stud_crse_year records that will be picked up for batch recalculation';
COMMENT ON TABLE case_status IS 'This is a reference data table holding all the possible statuses of an application';
COMMENT ON TABLE corres_attach IS 'This table contains Ad-Hoc outgoing correspondence as OLE objects';
COMMENT ON TABLE crse_term_change IS 'This table holds details of courses with updated terms';
COMMENT ON TABLE debt_status IS 'This is a reference data table holding all the possible statuses of debt in the SGAS Schema';
COMMENT ON TABLE disability_type IS 'This is a reference data table holding all the different types of disability in the SGAS Schema';
COMMENT ON TABLE dla_request IS 'This table holds details of duplicate award notice requests which are transferred from the web database';
COMMENT ON TABLE document_type IS 'This table holds details of the different document types used in the SGAS Schema';
COMMENT ON TABLE ed8_run_log IS 'THis table holds detailed information in respective of the running of any ED8 job';
COMMENT ON TABLE employment_status IS 'This is a reference data table holding all the possible statuses of employment in the SGAS Schema';
COMMENT ON TABLE fee_loan_type IS 'This is a reference data table holding all the different types of fee loan in the SGAS Schema';
COMMENT ON TABLE fee_payment_date IS 'This table holds a list of fee payment dates';
COMMENT ON TABLE fee_status_rep_hist IS 'This table holds historic fee status report data';
COMMENT ON TABLE finance_reversal_journal IS 'This table holds a record of journal lines to be reversed in the UI';
COMMENT ON TABLE inst_cont_details IS 'This table holds contact details for institutions';
COMMENT ON TABLE inst_cont_email IS 'This table holds EMAIL details for institutions';
COMMENT ON TABLE inst_location IS 'This table holds the location of each institution';
COMMENT ON TABLE inst_term_change IS 'This table holds details of institutions with updated terms';
COMMENT ON TABLE loan_status IS 'This is a reference data table holding all the possible statuses of loan in the SGAS Schema';
COMMENT ON TABLE loa_reason_code IS 'This table is used to store the leave of absence reason codes which will be populated by Institutions in the Attendance Data files';
COMMENT ON TABLE marital_status IS 'This is a reference data table holding all the possible statuses of marriage in the SGAS Schema';
COMMENT ON TABLE nmsb_continuation_reason IS 'This table is a reference data table holding all NMSB Continuation reasons in the SGAS Schema';
COMMENT ON TABLE nmsb_spec_arr IS 'This table holds all NMSB special arrangement details';
COMMENT ON TABLE nominee IS 'This table holds all the details of nominees in the SGAS Schema';
COMMENT ON TABLE non_award_payment_date IS 'This table holdS a list of non payment dates for Awards';
COMMENT ON TABLE no_nino_reason IS 'This table is a reference data table holding all the reasons for a student not having a ni number';
COMMENT ON TABLE other_loan_type IS 'This is a reference data table holding all the different types of other loan types in the SGAS Schema';
COMMENT ON TABLE password_letter_request IS 'This table holds details of password letter requests from the web';
COMMENT ON TABLE password_letter_request_temp IS 'This is a temp table that is used to hold details of password letter requests from the web';