--  J Wynne 02/05/2014
--  Shell letter changes for change of session 2014
--  This updates the table STD_LETTERS which StEPS gets the shell letter index from

--  Delete unwanted letters
DELETE FROM STD_LETTERS
WHERE DOC_NAME = 'FEX1';

DELETE FROM STD_LETTERS
WHERE DOC_NAME = 'FEX2';

DELETE FROM STD_LETTERS
WHERE DOC_NAME = 'FEX3';

COMMIT;

-- Insert into STD_LETTERS new shell letters 2014
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP27', 'APP-FINALISE PROVISIONAL AWARD FOR 2014-2015', 'APP');

COMMIT;
     
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('INT01', 'CURRENT INCOME CALCULATOR', 'INT');   

COMMIT;

Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('INT02', 'O/P ADJUSTMENT FORM', 'INT');

COMMIT;
    
Insert into STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES02A', 'REFUSAL-UK NATIONAL-WERE ABROAD BUT BACK IN UK', 'NMSB');  

COMMIT;


-- Update existing letters with new descriptions 

UPDATE STD_LETTERS
SET DOC_DESC = 'REFUSAL-ACCELERATED LLB'
WHERE DOC_NAME = 'COURSE06';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'ARCHITECTURE STUDENTS'
WHERE DOC_NAME = 'COURSE07';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = '4 YR DEGREE STUDENTS CONVERTING to 5 YR DEGREE'
WHERE DOC_NAME = 'COURSE08';   

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'ALREADY HOLDS A HIGHER PG QUALIFICATION'
WHERE DOC_NAME = 'COURSE09'; 

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'HNC HEALTH CARE REFUSAL - APPLY TO SGHD FOR FEES'
WHERE DOC_NAME = 'COURSE10';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CWG ATHELETES - CONFORMATION OF SUPPORT'
WHERE DOC_NAME = 'COURSE11';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'EVIDENCE OF NO EXIT AWARD'
WHERE DOC_NAME = 'COURSE12';   

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CI-REQ FOR ACTUAL INC- LETTER TO STUDENT 13-14'
WHERE DOC_NAME = 'CURINC07';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CI-REQ FOR ACTUAL INC-LETTER TO PARENT 13-14'
WHERE DOC_NAME = 'CURINC08';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CI-REQ  ACTUAL INC-LETTER TO PARENT (ABROAD) 13-14'
WHERE DOC_NAME = 'CURINC09';   

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CI-FINAL-REVERT BACK-LETTER TO STUDENT 13-14'
WHERE DOC_NAME = 'CURINC10';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'CI- FINAL-REVERT BACK-LETTER TO PARENT 13-14'
WHERE DOC_NAME = 'CURINC11';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'DSA BANK ACCOUNT'
WHERE DOC_NAME = 'DSA20';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'LATE REFERRAL FOR NEEDS ASSESSMENT'
WHERE DOC_NAME = 'DSA21';   

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'STUDYING ONE YEAR OF THEIR COURSE IN SCOTLAND'
WHERE DOC_NAME = 'EU03';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'HONOURS YEAR - REQUEST NUMBER OF ECTS CREDITS'
WHERE DOC_NAME = 'EU05';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'LOAN REQUEST AND AB36 REQUIRED'
WHERE DOC_NAME = 'LOAN07';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'NMSB-REQ SINGLE PARENT EVID ''&'' SEND CHILDCARE FOR'
WHERE DOC_NAME = 'NMSB13';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'LOAN REQUEST AND AB36 REQUIRED'
WHERE DOC_NAME = 'LOAN07';

UPDATE STD_LETTERS
SET DOC_DESC = 'REFUSAL-UK NATIONAL-WERE ABROAD BUT BACK IN UK'
WHERE DOC_NAME = 'NMSBRES02a';


UPDATE STD_LETTERS
SET DOC_DESC = 'REFUSAL-APPLY TO SFE/SFW/SFNI'
WHERE DOC_NAME = 'RES02';

UPDATE STD_LETTERS
SET DOC_DESC = 'REFUSAL-UK NATIONAL-LIVING ABROAD'
WHERE DOC_NAME = 'RES04';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'EU NATIONAL LIVING IN EEA/SWITZ-LAST HOME NOT SCOT'
WHERE DOC_NAME = 'RES05';

UPDATE STD_LETTERS
SET DOC_DESC = 'SEND OUT AB10''S IF RES01-RE04c DON’T APPLY'
WHERE DOC_NAME = 'RES07';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'NEW EU NATIONAL LIVING IN RUK ELIGIBLE FOR EU FEES'
WHERE DOC_NAME = 'RES14';

COMMIT;

UPDATE STD_LETTERS
SET DOC_DESC = 'NEW EU NATIONAL LIVING IN RUK NOT EU ON RD'
WHERE DOC_NAME = 'RES15';



COMMIT;         