DROP SEQUENCE SGAS.SLC_FILE_SEQ_NUM;

CREATE SEQUENCE SGAS.SLC_FILE_SEQ_NUM
  START WITH 1
  MAXVALUE 9999999
  MINVALUE 1
  CYCLE
  NOCACHE
  NOORDER;


DROP PUBLIC SYNONYM SLC_FILE_SEQ_NUM;

CREATE OR REPLACE PUBLIC SYNONYM SLC_FILE_SEQ_NUM FOR SGAS.SLC_FILE_SEQ_NUM;