--THIS IS USED IN ORDER TO UPDATE OLD SIT DATA
--THE FLOW-SERVICES HAVE BEEN UPDATED SO THAT RESID_PAR_CONT = 0 (NOT NULL)
--THIS SQL BASICALLY UPDATES OLD EXISTING CASES SO THAT THEY AWARD NOTIFICATION LETTERS WILL STILL BE PRODUCED

UPDATE SGAS.STUD_CRSE_YEAR
SET RESID_STUD_CONT = 0
WHERE RESID_STUD_CONT IS NULL;