INSERT INTO STUD_AWARD_TYPE(STUD_AWARD_TYPE.STUD_AWARD_TYPE , LOAN_NON_LOAN_FEE, SCHEME, AWARD_TYPE_DESCRIPT, SHOW_ON_AN_PAYMENTS, COST_CENTRE, PROGRAMME, 
                            ACCOUNT_NAME, ENTITY, SAAS_MAKE_PAYMENT, COMMENTS, STUD_AWARD_TYPE.TYPE ) 
            VALUES('CESB', 'non-Loan' , 'UG', 'CARE EXPERIENCED STUDENT BURSARY', 'Y', '213260', 'ECC' , '60155753', '600', 'Y', '', 'CESB');
COMMIT;
