ALTER TABLE care_experienced_apps_report 

ADD(CARE_EXP_FOSTER         VARCHAR2(1 BYTE),
  CARE_EXP_RES            VARCHAR2(1 BYTE),
  CARE_EXP_KINSHIP_LA     VARCHAR2(1 BYTE),
  CARE_EXP_KINSHIP_NO_LA  VARCHAR2(1 BYTE),
  CARE_EXP_HOME           VARCHAR2(2 BYTE),
  CARE_EXP_OTHER          VARCHAR2(1 BYTE),
  CARE_EXP_OTHER_DETAILS  VARCHAR2(250 BYTE),
  CESB_EVI_RECVD          VARCHAR2(1 BYTE)
  );
  
  COMMIT; 