--ADHOC SCRIPT TO UPDATE SYSTEM USER TO HAVE 0% QA 
Insert into SGAS.STEPS_QA_DATA
   (USERNAME, QA_TYPE, QA_LEVEL, NO_PROCESSED, NO_QA, NO_FAIL_QA, LAST_UPDATED_BY, LAST_UPDATED_ON)
 Values
   ('SYSTEM', 'U', 0, 0, 0, 0, 'SGAS', TO_DATE('08/26/2009 10:07:14', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;




