SET DEFINE OFF;

UPDATE CONFIG_DATA SET CVAL = 'docx' where ITEM_NAME = 'SHELL_FILETYPE';

TRUNCATE TABLE STD_LETTERS;

Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD01', 'COMP  ABROAD- EXCHANGE', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD02', 'COMP  ABROAD- EXCHANGE - RUK', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD03', 'COMP ABROAD-NON EXCHANGE', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD04', 'VOL ABROAD- EXCHANGE', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD05', 'VOL ABROAD-NON EXCHANGE', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD06', 'LANGUAGE ASSISTANT', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD07', 'EU PORTABILITY', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD08', 'CONFIRM PAYMENT - REQ NEW FORM AND RECEIPTS', 'ABR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ABROAD09', 'CONFIRM PAYMENT - REQ RECEIPTS ONLY', 'ABR');      
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP01', 'BENEFACTORS UNKNOWN - NEED H/I FORM', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP01a', 'BENEFACTORS UNKNOWN - NEED H/I FORM (ABROAD)', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP02', 'REQ H/I FORM FROM BENEFACTOR', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP02a', 'REG H/I FORM FROM BENEFACTOR (ABROAD)', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP03', 'REQ H/I FORM FROM SINGLE BENEFACTOR EV FROM PARENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP04', 'REQ CONFIRMATION OF OTHER INCOME - TO BENEFACTOR', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP05', 'REQ MAINTENANCE EVIDENCE - TO BENEFACTOR', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP06', 'STUDENT INCOME ONLY - INCORRECT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP07', 'REQ SINGLE PARENT EV FOR PARENT - FROM PARENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP08', 'REQ SINGLE BENEFIT EV AND INC DOCS FROM PARENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP09', 'INCORRECT DOCS FOR SINGLE PARENT EV', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP10', 'REQ SINGLE PARENT EV FOR PARENT - TO STUDENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP11', 'CASEWORKER RESTRICT - INFORM STUDENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP12', 'REQ 16-17 DOCS FROM BENEFACTOR', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP13', 'INCORRECT DOCS FOR FINALISING 16-17 TO BENEFACTOR', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP14', 'WITHDRAWL NEED INC DOCS - INFORM STUDENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP15', 'SYSTEM RESTRICT - INFORM STUDENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP16', 'SYSTEM RESTRICT - REQ PREV SESSION DOCS', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP17', 'SYSTEM RESTRICT - REQ H/I FORM AND PREV DOCS', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP17a', 'SYS RESTRICT - REQ H/I FORM AND PREV DOCS (ABROAD)', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP18', 'MISSING EDUCATION EMPLOYMENT DETAILS', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP19', 'NO RESIDENCE DETAILS - SEND FORM', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP20', 'NO RESIDENCE OR EDU/EMP DETAILS - SEND DETAILS', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP21', 'REQ EVIDENCE - STUDENT HAS PARTNER', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP22', 'REQ SEPARATION EV FOR STUDENT', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP23', 'INVALID BANK DETAILS', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP24', 'NEED DOCS TRANSLATED INTO ENGLISH', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP25', 'UG APP INCORRECT-COMPLETE PG APP', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP26', 'WRONG SESSION APPLICATION', 'APP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('APP27', 'APP RECEIVED AFTER CLOSING DATE', 'APP');         
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT01', 'WITHDRAWAL - No OVERPAYMENT', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT02', 'OVERPAYMENT DUE TO WITHDRAWAL', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT03', 'NON ATTENDANCE - NO OVERPAYMENT', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT04', 'NON ATTENDANCE - OVERPAYMENT', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT05', 'REGISTERED WITH ATTENDANCE - NO OVERPAYMENT', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT06', 'RWA - OVERPAYMENT - RECOVER NEXT SESSION', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT07', 'RWA - USING THE +1', 'ATT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('ATT08', 'MLOA - INFORM STUDENT', 'ATT');         
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('BLANK', 'BLANK SHELL', 'BLA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CARE01', 'REQ PROOF STUDENT IS CARE LEAVER', 'CAR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CARE02', 'SEND CARE LEAVERS GRANT FORM', 'CAR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CARE03', 'REFUSAL - NOT ELIGIBLE FOR CARE LEAVERS GRANT', 'CAR');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE01', 'REFUSE - COURSE NOT ELIGIBLE FOR FUNDING', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE02', 'REFUSE - ALREADY QUALIFIED AND FUNDED', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE03', 'PGDE REFUSAL - PREV FUNDING AND NO PRIORITY', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE04', 'REFUSAL - ACCELERATED LLB', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE05', 'PREV FUNDING - CAN ONLY FUND PART OF COURSE', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE06', 'AHP SUPPORT - COURSE CHANGE', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE07', 'AHP SUPPORT FOR GRADUATES', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE08', 'RUK - CAPITATION FEES', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE09', 'EVIDENCE OF NO EXIT QUALIFICATION', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE10', 'HNC HEALTH CARE REFUSAL - APPLY TO SGHD', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE11', '2ND DEGREE DENTISTRY', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE12', 'ARCHITECTURE - REFUSE YR2 PLACEMENT', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE13', 'CHANGE TO 5YR DEGREE AFTER OR DURING YR4', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE14', 'CHANGE SEP-JUN TO JAN-DEC COURSE IN SAME SESSION', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE15', 'BURSARY DEDUCTIONS WITH OP', 'COUR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('COURSE16', 'COURSE CHANGE - BURSARY EXPLANATIONS', 'COUR');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC01', 'PREV TAX YEAR INC ON APP - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC01a', 'PREV TAX YEAR INC ON APP - TO BENEFACTOR ABROAD', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC02', 'PREV TAX YEAR INCOME NOT ON APP - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC02a', 'PREV TAX YEAR INCOME NOT ON APP - TO BEN ABROAD', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC03', 'REF-15% DROP NOT EXPECTED - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC04', 'REF - NO DROP IN INCOME BRACKET - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC05', 'REF DUE REASON FOR DROP - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC06', 'REFUSE REASSESSMENT - TO STUDENT', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC07', 'CONFIRM CI ASSESSMENT MADE - TO STUDENT', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC08', 'CONFIRM CI ASSESSMENT MADE - TO BENEFACTOR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC09', '15-16 CI - REQ ACTUAL INCOME - TO STUDENT', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC10', '15-16 CI - INCOME ON 16-17 APP - REQ INC DOCS', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC10a', '15-16 CI - INCOME ON 16-17 APP - REQ INC DOCS ABR', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC11', '15-16 CI - NO INC ON 16-17 APP - REQ INCOME', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC11a', '15-16 CI - NO INC ON 16-17 APP - REQ INCOME ABROAD', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC12', '15-16 CI - REVERT AND RECOVER OP - TO STUDENT', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC13', '15-16 CI - REVERT AND REQ OP RECOVERY - TO STUDENT', 'CURIN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('CURINC14', 'FINAL - REVERT - TO BENEFACTOR', 'CURIN');               
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP01', 'DEPENDANTS'' GRANT REFUSAL-INCOME TOO HIGH', 'DEP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP02', 'DEPENDANTS'' GRANT-REFUSAL - DEP IS STUDENT', 'DEP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP03', 'DEPENDANTS'' DG - REQUEST ESTIMATE OF INCOME', 'DEP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DEP04', 'DEPENDANTS'' DG - REQ ACTUAL INCOME FOR 15-16', 'DEP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA01', 'CONFIRMATION OF PAYMENT OF DSA', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA02', 'SAS3 NEEDED-NEW STUDENT', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA03', 'SAS3 NEEDED-CONTINUING STUDENT', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA04', 'SAS3 STILL TO BE PROCESSED', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA05', 'MORE INFORMATION REQUIRED', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA06', 'APPLICATION RETURNED-INCOMPLETE', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA07', 'APP RECEIVED TOO LATE', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA08', 'REPORT RECEIVED TOO LATE', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA09', 'TELL STUDENT ABOUT REFERRAL TO ASSESSMENT CENTRE', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA10', 'PAYMENT FOR HELPERS', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA11', 'OP-TOTAL OF RECEIPTS LESS THAN PAYMENT', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA12', 'REMINDER FOR RECEIPTS-21 DAY LETTER', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA13', 'DSA CLAIM ONLY', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA14', 'NEARING MAXIMUM OF NON-MEDICAL PERSONAL HELP', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA15', 'DSA RECEIPTS-SECOND REMINDER', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA16', 'DSA RECEIPTS-FINAL REMINDER', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA17', 'DSA FORM REQUIRED', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA18', 'ACKNOWLEDGE RECEIPTS', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA19', 'DSA INVOICES', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA20', 'DSA BANK ACCOUNT', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DSA21', 'LATE REFERRAL FOR NEEDS ASSESSMENT', 'DSA');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('DTH01', 'ACKNOWLEDGE DEATH OF STUDENT', 'DTH');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU01', 'STUDYING ONE YEAR OF THEIR COURSE IN SCOTLAND', 'EU');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU02', 'REJECT - FUNDED AND QUALIFIED AT SAME LEVEL', 'EU');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU03', 'UNCLEAR IF UG OR PG GAINED - REQ EVIDENCE', 'EU');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EU04', 'HONS YEAR ONLY - REQ EV OF 240 CREDITS OR LESS', 'EU');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT01', 'STUDENT DECLARED PARENTS ON APP BUT INDEPENDENT', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT02', 'DO NOT MEET IND CRITERIA - REQ HI FORM', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT02a', 'DO NOT MEET IND CRITERIA - REQ HI FORM ABROAD', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT03', 'REQ EVIDENCE OF ESTRANGEMENT', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT04', 'REFUSE ESTRANGEMENT - PARENT IS LOAN CONTACT', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT05', 'ESTRANGEMENT - REQ HI FORM FROM PARENTS', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT06', 'REF ESTRANGEMENT - NO HI FORM - OFFER MEETING', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT07', 'ESTRANGEMENT APPROVED', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT08', 'REFUSE - EVIDENCE SHOWS NOT ESTRANGED - REQ HI', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT09', 'ESTRANGEMENT REFUSED AFTER MEETING', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT10', 'REQ PROOF OF ONGOING ESTRANGEMENT FOR NEW SESSION', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('EXEMPT11', 'REQ PROOF OF LEGAL GUARDIANSHIP FROM BENEFACTORS', 'EXE');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('INT01', 'CURRENT INCOME CALCULATOR', 'INT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('INT02', 'O/P ADJUSTMENT FORM', 'INT');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN01', 'FORM NOT FILLED IN CORRECTLY OR SIGNED', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN02', 'MISSING LOAN CONTACT - REQ NEW CONTACT', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN03', 'FEE LOAN/RUK G HEI CONSENT', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN04', 'FEE LOAN ADJUSTMENT FORM-SESSION 15-16', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN05', 'TOP UP LOAN FORM', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN06', 'ZERO LOAN REQ ON APP', 'LOAN');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LOAN07', 'NO LOAN - AGE TOO HIGH', 'LOAN');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG01', 'REQ CHILD BC AND LONE PARENT EVIDENCE', 'LP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG02', 'REQ LONE PARENT EVIDENCE ONLY', 'LP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('LPG03', 'REFUSE - INCOME TOO HIGH ''&'' REQ LP EVIDENCE', 'LP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR01', 'MIGRANT WORKER - REQUEST EVIDENCE', 'MGR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR02', 'FAMILY MEMBER OF MIGRANT WORKER - REQ EVID', 'MGR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR03', 'REFUSE - NOT O/R IN SCO ON RELEVANT DATE', 'MGR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR04', 'REFUSE AS CANNOT REGARD AS WORKER', 'MGR');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('MGR05', 'REFUSE AS NO LINK WITH EMPLOYMENT', 'MGR');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB01', 'NMSB-DEPENDANTS GRANT-INCOME TOO HIGH', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB02', 'NMSB-O/P OF AWARD DUE TO WITHDRAWAL', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB03', 'NMSB-REQ BIRTH CERT AND SINGLE PARENT EVID', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB04', 'NMSB-REQ FURTHER SINGLE PARENT EVID', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB05', 'NMSB-CONTINUATION OF SUPPORT', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB06', 'NMSB-DEPS INCOME TOO HIGH-CHILDCARE ALLOW FORM', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB07', 'NMSB-CHILDCARE ALLOWANCE FORM', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB08', 'NMSB-ESTIMATE OF SPOUSE''S INCOME', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB09', 'NMSB-O/P RECOVER FROM CURRENT SESSION', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB10', 'NMSB - APPLY FOR AN EXTENSION ', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB11', 'INCORRECT NMSB APPLICATION', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB12', 'NMSB-REQ SINGLE PARENT EVID & SEND CHILDCARE FORM', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB13', 'NMSB-O/P DUE TO NON ATTENDANCE', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB14', 'NMSB-O/P OF CHILDCARE GRANT', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB15', 'NMSB - REFUSAL - EU STUDENTS', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB16', 'NMSB - RECOMMENCEMENT EVIDENCE', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB17', 'NMSB - RECOMMENCEMENT APPLY FOR SUPPORT', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB18', 'NMSB - CONTINUATION OF SUPPORT', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSB19', 'NMSB - PLACEMENT REFUSAL', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES01', 'REFUSAL-NON EEA NATIONAL', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES02', 'REFUSAL-UK NATIONAL-LIVING ABROAD', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES02a', 'REFUSAL-UK NATIONAL-WERE ABROAD BUT BACK IN UK', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('NMSBRES03', 'NON EEA NATIONAL-REQUEST EVIDENCE', 'NMSB');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OTHR01', 'BACS PAYMENT RETURNED ASK STUDENT WHY', 'OTH');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP01', 'O/P-DEPENDANTS GRANT INCOME MORE THAN ESTIMATE', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP02', 'O/P-DUE TO OUR ERROR', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP03', 'O/P-DUE FINALISATION - RECOVER NEXT SESSION', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP04', 'O/P-FINALISATION-ASK FOR REPAYMENT', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP05', 'O/P DUE PREV YR FINAL - REASSESS CURRENT SESS', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP06', 'O/P - RECOVER PREV O/P IN FULL FROM CURRENT SESS', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('OVRP07', 'O/P-RECOVER PART OF O/P FROM CURRENT SESSION', 'OVRP');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG01', 'PG-REFUSAL-ALREADY QUALIFIED', 'PG');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG02', 'PG-REFUSAL END ON', 'PG');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG03', 'PG-COURSE NOT FUNDED', 'PG');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG04', 'PG-OUTSIDE SCOTLAND-CONSIDERING', 'PG');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG05', 'PG -  FEE LOAN - MISSING NINO', 'PG');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PG06', 'SAS7 INCORRECT - ADVISED TO COMPLETE SAS3 ONLINE', 'PG');   
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PLAC01', 'PAID PLACEMENT', 'PLAC');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('PLAC02', 'UNPAID PLACEMENT', 'PLAC');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES01', 'NON EEA NATIONAL - REQ EVIDENCE', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES02', 'LTR ENDS BEFORE COURSE STARTS - REQ EV ILR/EXT', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES03', 'AWARDED FUNDING BUT LTR RUNS OUT DURING COURSE', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES04', 'REQ EV OF APP FOR EXTENSION FOR ILR/LTR', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES05', 'ACK PROOF OF APP FOR EXTENSION OF ILR/LTR', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES06', 'ACK PROOF OF APPEAL FOR EXT OF ILR/LTR', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES07', 'REFUSAL - NON EEA NATIONAL', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES08', 'EU NAT LIVING IN RUK - REQUEST PASSPORT', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES09', 'EU NATIONAL OUTSIDE UK OR BIDAR - REQ PASSPORT', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES10', 'NEW EU NATIONAL LIVING IN RUK - FEES ONLY', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES11', 'REFUSE - EU NAT LIVING IN RUK - NOT ON RD ', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES12', 'REF FULL FUNDING FOR EU (NON UK) NATIONAL', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES13', 'UK NAT LIVE ABROAD - SEND RESIDENCE FORMS', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES14', 'UK NATIONAL-BACK FROM ABROAD-SEND RESIDENCE FORM', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES15', 'EU NATIONAL-LIVING ABROAD-SEND RESIDENCE FORM', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES16', 'EU NATIONAL-BACK FROM ABROAD-SEND RESIDENCE FORM', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES17', 'SEND OUT AB10S IF RES13-RES16 DON’T APPLY', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES18', 'DUAL UK/EU - REQ EVID OF UTILISED RIGHT OF RESD', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES19', 'REFUSE DUAL UK/EU-NOT UTILISED RIGHT OF RESIDENCE', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES20', 'UK NATIONAL LIVING IN EEA/SWITZ-LAST HOME NOT SCOT', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES21', 'REFUSAL - RESIDENT IN RUK, APPLY TO SFE/SFW/SFNI', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('RES22', 'REFUSAL - CHILD OF SWISS NATIONAL NOT O/R IN SCOT', 'RES');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('TRAV01', 'TRAVEL - REQUEST FOR INCOME', 'TRAV');
Insert into SGAS.STD_LETTERS
   (DOC_NAME, DOC_DESC, CAT_CODE)
 Values
   ('TRAV02', 'TRAVEL - UG NOT ELIGIBLE FOR TRAVEL EXPENSES', 'TRAV');

COMMIT;