CREATE OR REPLACE VIEW SGAS.DE_PM_PAYMENTS
(DPP_BATCH_REF, DPP_SEQUENCE_NO, DPP_OUR_REF1, DPP_OUR_REF2, DPP_OUR_REF3, 
 DPP_SOURCE_REF, DPP_PAYEE, DPP_PAYEE_ADDRESS1, DPP_PAYEE_ADDRESS2, DPP_PAYEE_ADDRESS3, 
 DPP_PAYEE_POSTCODE, DPP_PAYEE_BANK_ACCOUNT, DPP_BANK_SORT_CODE, DPP_BANK_ACCOUNT_TYPE, DPP_BUILD_SOC_ROLL_NO, 
 DPP_PAYMENT_AMOUNT, DPP_PAYMENT_METHOD, DPP_PAY_SUB_TYPE, DPP_PAYMENT_DATE, DPP_REFER_TO_OR_ENCLOSURE, 
 DPP_REMITTER_ADDRESS_CODE, DPP_RADV_ADDRESSEE, DPP_RADV_ADDRESS1, DPP_RADV_ADDRESS2, DPP_RADV_ADDRESS3, 
 DPP_RADV_ADDRESS4, DPP_RADV_POSTCODE, DPP_BANK_ID, DPP_REMITTANCE_TEXT_01, DPP_REMITTANCE_TEXT_02, 
 DPP_REMITTANCE_TEXT_03, DPP_REMITTANCE_TEXT_04, DPP_REMITTANCE_TEXT_05, DPP_REMITTANCE_TEXT_06, DPP_REMITTANCE_TEXT_07, 
 DPP_REMITTANCE_TEXT_08, DPP_REMITTANCE_TEXT_09, DPP_REMITTANCE_TEXT_10, DPP_REMITTANCE_TEXT_11, DPP_REMITTANCE_TEXT_12, 
 DPP_REMITTANCE_TEXT_13, DPP_REMITTANCE_TEXT_14, DPP_REMITTANCE_TEXT_15, DPP_REMITTANCE_TEXT_16, DPP_REMITTANCE_TEXT_17, 
 DPP_REMITTANCE_TEXT_18, DPP_REMITTANCE_TEXT_19, DPP_REMITTANCE_TEXT_20, DPP_PAYMENT_ID, DPP_PO_NUM, 
 DPP_REISSUE, DPP_RETURNED, DPP_CURRENCY, DPP_OUR_REF4)
AS 
SELECT "DPP_BATCH_REF","DPP_SEQUENCE_NO","DPP_OUR_REF1","DPP_OUR_REF2","DPP_OUR_REF3","DPP_SOURCE_REF","DPP_PAYEE","DPP_PAYEE_ADDRESS1","DPP_PAYEE_ADDRESS2","DPP_PAYEE_ADDRESS3","DPP_PAYEE_POSTCODE","DPP_PAYEE_BANK_ACCOUNT","DPP_PAYEE_BANK_SORT_CODE","DPP_BANK_ACCOUNT_TYPE","DPP_BUILD_SOC_ROLL_NO","DPP_PAYMENT_AMOUNT","DPP_PAYMENT_METHOD","DPP_PAY_SUB_TYPE","DPP_PAYMENT_DATE","DPP_REFER_TO_OR_ENCLOSURE","DPP_REMITTER_ADDRESS_CODE","DPP_RADV_ADDRESSEE","DPP_RADV_ADDRESS1","DPP_RADV_ADDRESS2","DPP_RADV_ADDRESS3","DPP_RADV_ADDRESS4","DPP_RADV_POSTCODE","DPP_BANK_ID","DPP_REMITTANCE_TEXT_01","DPP_REMITTANCE_TEXT_02","DPP_REMITTANCE_TEXT_03","DPP_REMITTANCE_TEXT_04","DPP_REMITTANCE_TEXT_05","DPP_REMITTANCE_TEXT_06","DPP_REMITTANCE_TEXT_07","DPP_REMITTANCE_TEXT_08","DPP_REMITTANCE_TEXT_09","DPP_REMITTANCE_TEXT_10","DPP_REMITTANCE_TEXT_11","DPP_REMITTANCE_TEXT_12","DPP_REMITTANCE_TEXT_13","DPP_REMITTANCE_TEXT_14","DPP_REMITTANCE_TEXT_15","DPP_REMITTANCE_TEXT_16","DPP_REMITTANCE_TEXT_17","DPP_REMITTANCE_TEXT_18","DPP_REMITTANCE_TEXT_19","DPP_REMITTANCE_TEXT_20","DPP_PAYMENT_ID","DPP_PO_NUM","DPP_REISSUE","DPP_RETURNED","DPP_CURRENCY","DPP_OUR_REF4" FROM SCOAP_PAYMENTS
WHERE dpp_batch_ref IN
(SELECT dpb_batch_ref FROM SCOAP_BATCHES
 WHERE dpb_batch_creation_date > (SYSDATE - 1)
 and dpb_payment_type = 'C')
UNION
SELECT "DPP_BATCH_REF","DPP_SEQUENCE_NO","DPP_OUR_REF1","DPP_OUR_REF2","DPP_OUR_REF3","DPP_SOURCE_REF","DPP_PAYEE","DPP_PAYEE_ADDRESS1","DPP_PAYEE_ADDRESS2","DPP_PAYEE_ADDRESS3","DPP_PAYEE_POSTCODE","DPP_PAYEE_BANK_ACCOUNT","DPP_PAYEE_BANK_SORT_CODE","DPP_BANK_ACCOUNT_TYPE","DPP_BUILD_SOC_ROLL_NO","DPP_PAYMENT_AMOUNT","DPP_PAYMENT_METHOD","DPP_PAY_SUB_TYPE","DPP_PAYMENT_DATE","DPP_REFER_TO_OR_ENCLOSURE","DPP_REMITTER_ADDRESS_CODE","DPP_RADV_ADDRESSEE","DPP_RADV_ADDRESS1","DPP_RADV_ADDRESS2","DPP_RADV_ADDRESS3","DPP_RADV_ADDRESS4","DPP_RADV_POSTCODE","DPP_BANK_ID","DPP_REMITTANCE_TEXT_01","DPP_REMITTANCE_TEXT_02","DPP_REMITTANCE_TEXT_03","DPP_REMITTANCE_TEXT_04","DPP_REMITTANCE_TEXT_05","DPP_REMITTANCE_TEXT_06","DPP_REMITTANCE_TEXT_07","DPP_REMITTANCE_TEXT_08","DPP_REMITTANCE_TEXT_09","DPP_REMITTANCE_TEXT_10","DPP_REMITTANCE_TEXT_11","DPP_REMITTANCE_TEXT_12","DPP_REMITTANCE_TEXT_13","DPP_REMITTANCE_TEXT_14","DPP_REMITTANCE_TEXT_15","DPP_REMITTANCE_TEXT_16","DPP_REMITTANCE_TEXT_17","DPP_REMITTANCE_TEXT_18","DPP_REMITTANCE_TEXT_19","DPP_REMITTANCE_TEXT_20","DPP_PAYMENT_ID","DPP_PO_NUM","DPP_REISSUE","DPP_RETURNED","DPP_CURRENCY","DPP_OUR_REF4" FROM SCOAP_PAYMENTS@STEPSSIT.WORLD
WHERE dpp_batch_ref IN
(SELECT dpb_batch_ref FROM SCOAP_BATCHES@STEPSSIT.WORLD
 WHERE dpb_batch_creation_date > (SYSDATE - 1)
 and dpb_payment_type = 'C');



CREATE PUBLIC SYNONYM DE_PM_PAYMENTS FOR SGAS.DE_PM_PAYMENTS
/


GRANT SELECT ON  SGAS.DE_PM_PAYMENTS TO SCOAP_QUERY
/