CREATE TABLE SGAS.INSTITUTE_TYPES
(
  ID           NUMBER(10),
  DESCRIPTION  VARCHAR2(50 BYTE)
 );
 
 
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(1,'HIGHER EDUCATION INSTITUTION');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(2,'COLLEGE OF FURTHER EDUCATION');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(3,'COLLEGE OF NURSE AND MIDWIFERY');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(4,'THEOLOGICAL COLLEGE');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(5,'NHS COLLEGE');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(6,'ADULT EDUCATION COLLEGE');
 INSERT INTO SGAS.INSTITUTE_TYPES VALUES(7,'OTHER INSTITUTION');
 commit;