/* Formatted on 14/11/2018 14:16:54 (QP5 v5.215.12089.38647) */
CREATE TABLE SGAS.COURSE_SUBJECT_CATEGORY
(
   ID            NUMBER (10),
   DESCRIPTION   VARCHAR2 (50 BYTE)
);

 SET DEFINE OFF;

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (101, 'ENGLISH');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (102, 'HISTORY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (103, 'LAW');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (104, 'PHILOSOPHY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (105, 'LITERATURE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (106, 'LINGUISTICS');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (107, 'FILM AND THEATRE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (108, 'ART HISTORY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (109, 'ARCHAEOLOGY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (110, 'CLASSICS');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (111, 'THEOLOGY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (112, 'MUSIC');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (113, 'PUBLISHING STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (114, 'FRENCH');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (115, 'GERMAN');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (116, 'ITALIAN');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (117, 'HISPANIC STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (118, 'JAPANESE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (119, 'EUROPEAN STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (120, 'ART AND DESIGN');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (121, 'CELTIC/IRISH');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (122, 'RUSSIAN');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (123, 'SCOTTISH STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (124, 'HUMAN RIGHTS');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (125, 'ORIENTAL STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (126, 'ARCHITECTURE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (127, 'SLAVONIC');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (128, 'SPANISH');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (129, 'AGRICULTURE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (130, 'ALLIED TO MEDICINE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (131, 'ARCHITECTURE,BUILDING AND PLANNING');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (132, 'BIOLOGICAL SCIENCES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (133, 'BUSINESS AND ADMINISTRATIVE STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (134, 'CATERING');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (135, 'COMBINED OR GENERAL');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (136, 'CREATIVE ARTS');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (137, 'DENTISTRY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (138, 'EDUCATION');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (139, 'ENGINEERING AND TECHNOLOGY');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (140, 'HUMANITIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (141, 'LANGUAGES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (142, 'LEISURE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (143, 'MASS COMMUNICATIONS AND DOCUMENTATION');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (144, 'MATHEMATICAL SCIENCES AND INFORMATICS');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (145, 'MEDICINE');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (146, 'PHYSICAL SCIENCES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (147, 'SOCIAL STUDIES');

INSERT INTO COURSE_SUBJECT_CATEGORY (ID, DESCRIPT)
     VALUES (148, 'OTHER');

COMMIT;