ALTER TABLE CAMPUS ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CAMPUS ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE CRSE ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CRSE ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE CRSE_TERM ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CRSE_TERM ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE CRSE_SESSION ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CRSE_SESSION ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE CRSE_YEAR ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CRSE_YEAR ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE INST ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE INST ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE INST_TERM ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE INST_TERM ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

ALTER TABLE CAMPUS ADD LAST_UPDATED_BY VARCHAR2(15 BYTE) DEFAULT 'UNKNOWN' NOT NULL;
ALTER TABLE CAMPUS ADD LAST_UPDATED_ON DATE DEFAULT SYSDATE NOT NULL;

COMMIT;

