-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/BATCH_STATS.sql $
-- $Author: $
-- $Date: 2010-01-19 09:45:47 +0000 (Tue, 19 Jan 2010) $
-- $Revision: 4600 $

DROP TABLE EDM.BATCH_STATS CASCADE CONSTRAINTS
/

--
-- BATCH_STATS  (Table) 
--
CREATE TABLE EDM.BATCH_STATS
(
  BATCH_NAME                   VARCHAR2(50 BYTE),
  BATCH_DOCS                   NUMBER           DEFAULT 0,
  PROCESS_NAME                 VARCHAR2(50 BYTE),
  EXPORT_DATETIME              DATE,
  EXPORT_CHARACTERS            NUMBER           DEFAULT 0,
  RECOGNITION_DATETIME         DATE,
  RECOGNITION_TIMETAKEN        NUMBER           DEFAULT 0,
  RECOGNITION_MACHINENAME      VARCHAR2(50 BYTE),
  RECOGNITION_FIELDS_ACCEPTED  NUMBER           DEFAULT 0,
  RECOGNITION_FIELDS_REJECTED  NUMBER           DEFAULT 0,
  RECOGNITION_CHARS_ACCEPTED   NUMBER           DEFAULT 0,
  RECOGNITION_CHARS_REJECTED   NUMBER           DEFAULT 0,
  CORRECTION_USERNAME          VARCHAR2(50 BYTE),
  CORRECTION_DATETIME          DATE,
  CORRECTION_KDS               NUMBER           DEFAULT 0,
  COMPLETION_USERNAME          VARCHAR2(50 BYTE),
  COMPLETION_DATETIME          DATE,
  COMPLETION_TIMETAKEN         NUMBER           DEFAULT 0,
  COMPLETION_NPAUSES           NUMBER           DEFAULT 0,
  COMPLETION_PAUSETIME         NUMBER           DEFAULT 0,
  COMPLETION_KDS               NUMBER           DEFAULT 0,
  COMPLETION_KDS_DATAENTRY     NUMBER           DEFAULT 0,
  COMPLETION_KDS_FUNCTION      NUMBER           DEFAULT 0,
  COMPLETION_KDS_BACKSPACE     NUMBER           DEFAULT 0,
  COMPLETION_KDS_PRINTABLE     NUMBER           DEFAULT 0,
  COMPLETION_KDS_HOUR          NUMBER           DEFAULT 0,
  VERIFICATION_USERNAME        VARCHAR2(50 BYTE),
  VERIFICATION_DATETIME        DATE,
  VERIFICATION_TIMETAKEN       NUMBER           DEFAULT 0,
  VERIFICATION_NPAUSES         NUMBER           DEFAULT 0,
  VERIFICATION_PAUSETIME       NUMBER           DEFAULT 0,
  VERIFICATION_ERRORCHARS      NUMBER           DEFAULT 0,
  VERIFICATION_KDS             NUMBER           DEFAULT 0,
  VERIFICATION_KDS_DATAENTRY   NUMBER           DEFAULT 0,
  VERIFICATION_KDS_FUNCTION    NUMBER           DEFAULT 0,
  VERIFICATION_KDS_BACKSPACE   NUMBER           DEFAULT 0,
  VERIFICATION_KDS_PRINTABLE   NUMBER           DEFAULT 0,
  VERIFICATION_KDS_HOUR        NUMBER           DEFAULT 0,
  ADDR_KDS_TOTAL               NUMBER           DEFAULT 0,
  ADDR_KDS_SAVED               NUMBER           DEFAULT 0,
  ADDR_AUTO_PROC               NUMBER           DEFAULT 0,
  ADDR_MANUALLY_CHANGED        NUMBER           DEFAULT 0,
  COMPLETION_F1                NUMBER(3),
  RESCAN_FROM_COMPLETION       VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             524K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

--
-- Administer grants
-- 
GRANT ALTER ON EDM.BATCH_STATS TO PUBLIC
/

GRANT DELETE ON EDM.BATCH_STATS TO PUBLIC
/

GRANT INDEX ON EDM.BATCH_STATS TO PUBLIC
/

GRANT INSERT ON EDM.BATCH_STATS TO PUBLIC
/

GRANT SELECT ON EDM.BATCH_STATS TO PUBLIC
/

GRANT UPDATE ON EDM.BATCH_STATS TO PUBLIC
/

GRANT REFERENCES ON EDM.BATCH_STATS TO PUBLIC
/

GRANT DEBUG ON EDM.BATCH_STATS TO PUBLIC
/

GRANT QUERY REWRITE ON EDM.BATCH_STATS TO PUBLIC
/

GRANT ON COMMIT REFRESH ON EDM.BATCH_STATS TO PUBLIC
/

-- 
-- Create public synonym: 
-- 
DROP PUBLIC SYNONYM BATCH_STATS
/

CREATE PUBLIC SYNONYM BATCH_STATS FOR EDM.BATCH_STATS
/
