

CREATE TABLE EDM.RAW_DATA_DEP
(
  OBJECT_ID                  VARCHAR2(44 BYTE)  NOT NULL,
  STUD_REF_NO                NUMBER(10),
  STUD_DEP_ID                NUMBER(10),
  FORENAMES                  VARCHAR2(25 BYTE),
  SURNAME                    VARCHAR2(25 BYTE),
  DOB                        VARCHAR2(10 BYTE),
  DEPENDANT_RELATIONSHIP_ID  NUMBER(4),
  TOTAL_INCOME               NUMBER(9,2),
  EMAIL_ADDR                 VARCHAR2(80 BYTE),
  POST_CODE                  VARCHAR2(8 BYTE),
  HOUSE_NO_NAME              VARCHAR2(32 BYTE),
  ADDR_L1                    VARCHAR2(65 BYTE),
  ADDR_L2                    VARCHAR2(65 BYTE),
  ADDR_L3                    VARCHAR2(65 BYTE),
  ADDR_L4                    VARCHAR2(65 BYTE),
  LPG                        VARCHAR2(1 BYTE)
)
TABLESPACE EDM_DATA
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX EDM.RAW_DATA_DEP_PK ON EDM.RAW_DATA_DEP
(STUD_DEP_ID)
LOGGING
TABLESPACE EDM_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE EDM.RAW_DATA_DEP ADD (
  CONSTRAINT RAW_DATA_DEP_PK
  PRIMARY KEY
  (STUD_DEP_ID)
  USING INDEX EDM.RAW_DATA_DEP_PK
  ENABLE VALIDATE);
  
  GRANT DELETE, INSERT, SELECT, UPDATE ON EDM.RAW_DATA_DEP TO SGAS;
