-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/EDM_ERROR_LOG.sql $
-- $Author: $
-- $Date: 2010-01-19 09:45:47 +0000 (Tue, 19 Jan 2010) $
-- $Revision: 4600 $

DROP TABLE EDM.EDM_ERROR_LOG CASCADE CONSTRAINTS
/

--
-- EDM_ERROR_LOG  (Table) 
--
CREATE TABLE EDM.EDM_ERROR_LOG
(
  OBJECT_ID    VARCHAR2(44 BYTE),
  STUD_REF_NO  NUMBER(10),
  ERROR_TEXT   VARCHAR2(1000 BYTE)              NOT NULL,
  ERROR_DATE   DATE                             NOT NULL
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/



--
-- Administer grants
-- 
GRANT DELETE ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT ALTER ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT INDEX ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT INSERT ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT SELECT ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT UPDATE ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT REFERENCES ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT ON COMMIT REFRESH ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT QUERY REWRITE ON EDM.EDM_ERROR_LOG TO PUBLIC
/

GRANT DEBUG ON EDM.EDM_ERROR_LOG TO PUBLIC
/