-- Create table script.
--
-- MODIFICATION HISTORY
-- Ref.     Date            Author                          Desc.
--          08/01/2008  S Durkin (Sopra UK)     Initial Version
--
-- Configuration Management:
-- $HeadURL: svn://192.168.186.3/projects/sgas/tradev/svnRepositories/steps/trunk/Database/steps/edm/tables/PICK_LIST.sql $
-- $Author: $
-- $Date: 2010-01-19 09:45:47 +0000 (Tue, 19 Jan 2010) $
-- $Revision: 4600 $

ALTER TABLE EDM.PICK_LIST
 DROP PRIMARY KEY CASCADE
/
DROP TABLE EDM.PICK_LIST CASCADE CONSTRAINTS
/

--
-- PICK_LIST  (Table) 
--
CREATE TABLE EDM.PICK_LIST
(
  PICK_LIST_ID         NUMBER(10)               NOT NULL,
  PICK_STATUS          VARCHAR2(25 BYTE)        DEFAULT 'ACTION REQUIRED',
  PICK_TYPE_CODE       VARCHAR2(10 BYTE),
  PICKLIST_REPORT_ID   VARCHAR2(100 BYTE),
  WORKSTATION_ID       NUMBER(10),
  BATCH_ID             NUMBER(16),
  ENVELOPE_ID          NUMBER(4),
  DOCUMENT_TYPE_CODE   VARCHAR2(16 BYTE),
  DOCUMENT_TYPE_COUNT  NUMBER(3),
  CHANGED_BY_USER      VARCHAR2(25 BYTE),
  CHANGE_ACTION        VARCHAR2(100 BYTE),
  CHANGE_DATETIME      DATE,
  CW_REQ               VARCHAR2(25 BYTE),
  CW_REQ_DATE          DATE,
  DATE_REPORT_PRINTED  DATE,
  DELETED_DATE         DATE,
  STUD_REF_NO          NUMBER(10),
  SLC_REFERENCE_NO     VARCHAR2(10 BYTE),
  STUD_SURNAME         VARCHAR2(25 BYTE),
  POST_CODE            VARCHAR2(8 BYTE),
  ADDR_L1              VARCHAR2(65 BYTE),
  INST_NAME            VARCHAR2(50 BYTE),
  COURSE_NAME          VARCHAR2(50 BYTE),
  ERROR_TEXT           VARCHAR2(1000 BYTE),
  RESCAN_REQUEST_ID    NUMBER(10)
)
TABLESPACE USERS
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          32M
            NEXT             14K
            MINEXTENTS       1
            MAXEXTENTS       999
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- PICK_LIST_PK  (Index) 
--
CREATE UNIQUE INDEX PICK_LIST_PK ON EDM.PICK_LIST
(PICK_LIST_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          500K
            NEXT             500K
            MINEXTENTS       1
            MAXEXTENTS       99
            PCTINCREASE      1
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table PICK_LIST 
-- 
ALTER TABLE EDM.PICK_LIST ADD (
  CONSTRAINT PICK_LIST_PK
 PRIMARY KEY
 (PICK_LIST_ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          500K
                NEXT             500K
                MINEXTENTS       1
                MAXEXTENTS       99
                PCTINCREASE      1
                FREELISTS        1
                FREELIST GROUPS  1
               ))
/


--
-- Administer grants
-- 
GRANT ALTER ON EDM.PICK_LIST TO PUBLIC
/

GRANT DELETE ON EDM.PICK_LIST TO PUBLIC
/

GRANT INDEX ON EDM.PICK_LIST TO PUBLIC
/

GRANT INSERT ON EDM.PICK_LIST TO PUBLIC
/

GRANT DEBUG ON EDM.PICK_LIST TO PUBLIC
/

GRANT UPDATE ON EDM.PICK_LIST TO PUBLIC
/

GRANT REFERENCES ON EDM.PICK_LIST TO PUBLIC
/

GRANT ON COMMIT REFRESH ON EDM.PICK_LIST TO PUBLIC
/

GRANT QUERY REWRITE ON EDM.PICK_LIST TO PUBLIC
/

GRANT SELECT ON EDM.PICK_LIST TO PUBLIC
/
