--DROP MATERIALIZED VIEW SGAS.DSA_APP_STATUS;
CREATE MATERIALIZED VIEW SGAS.DSA_APP_STATUS (DSA_APP_STATUS_ID,DSA_APP_STATUS,IS_ACTIVE,LAST_UPDATED_ON,LAST_UPDATED_BY)
TABLESPACE SAAS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE SAAS_DATA
            PCTFREE    10
            INITRANS   2
            MAXTRANS   255
            STORAGE    (
                        PCTINCREASE      0
                        BUFFER_POOL      DEFAULT
                        FLASH_CACHE      DEFAULT
                        CELL_FLASH_CACHE DEFAULT
                       )
REFRESH COMPLETE ON DEMAND
START WITH TO_DATE(SYSDATE,'dd-mon-yyyy')
WITH PRIMARY KEY
AS 
SELECT DSA_APP_STATUS_ID,
       DSA_APP_STATUS,
       IS_ACTIVE,
       LAST_UPDATED_ON,
       LAST_UPDATED_BY
  FROM DSA_APP_STATUS@steps.world;

COMMENT ON MATERIALIZED VIEW SGAS.DSA_APP_STATUS IS 'snapshot table for snapshot SGAS.DSA_APP_STATUS';
