--DROP MATERIALIZED VIEW SGAS.INST_GROUPING;
CREATE MATERIALIZED VIEW SGAS.INST_GROUPING (INST_CODE,PARENT_INST_CODE,PARENT_INST_DISPLAY_NAME)
TABLESPACE SAAS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE SAAS_DATA
            PCTFREE    10
            INITRANS   2
            MAXTRANS   255
            STORAGE    (
                        PCTINCREASE      0
                        BUFFER_POOL      DEFAULT
                        FLASH_CACHE      DEFAULT
                        CELL_FLASH_CACHE DEFAULT
                       )
REFRESH COMPLETE ON DEMAND
START WITH TO_DATE(SYSDATE,'dd-mon-yyyy')
WITH PRIMARY KEY
AS 
SELECT INST_CODE, PARENT_INST_CODE, PARENT_INST_DISPLAY_NAME
  FROM INST_GROUPING@STEPS.WORLD;


COMMENT ON MATERIALIZED VIEW SGAS.INST_GROUPING IS 'snapshot table for snapshot SGAS.INST_GROUPING';
